mindsdb/mindsdb

- mindsdb/libs/controllers/mindsdb_controller.py
Fix #21 issues. This PR adds validation for predict value. If predict value is missing or it's empty string ValidationError will be raised.
> Check for valid predict value

- mindsdb/proxies/mysql/data_types/mysql_packets/eof_packet.py
- mindsdb/proxies/mysql/data_types/mysql_packets/err_packet.py
- mindsdb/proxies/mysql/data_types/mysql_packets/handshake_packet.py
- mindsdb/proxies/mysql/data_types/mysql_packets/handshake_response_packet.py
- mindsdb/proxies/mysql/data_types/mysql_packets/ok_packet.py
- mindsdb/proxies/mysql/data_types/mysql_packets/switch_auth_packet.py
_Undefined names_ have the potential to raise __NameError__ at runtime.  Could not discover where in this repo __MAX_LENGTH__ is defined .  The undefined names in __mysql_scramble.py__ occur because the Python porting best practice [use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection) was not followed.  Wildcard (*) imports are probably masking other _undefined names_.
[flake8](http://flake8.pycqa.org) testing of https://github.com/mindsdb/mindsdb on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./mindsdb/libs/ml_models/pytorch/encoders/rnn/decoder_rnn.py:10:76: F821 undefined name 'MAX_LENGTH'
def __init__(self, hidden_size, output_size, …
```
> Undefined names: Add missing imports

- mindsdb/external_libs/mysql_scramble.py
_Undefined names_ have the potential to raise __NameError__ at runtime.  Could not discover where in this repo __MAX_LENGTH__ is defined .  Follows the Python porting best practice [use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).
[flake8](http://flake8.pycqa.org) testing of https://github.com/mindsdb/mindsdb on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./mindsdb/libs/ml_models/pytorch/encoders/rnn/decoder_rnn.py:10:76: F821 undefined name 'MAX_LENGTH'
def __init__(self, hidden_size, output_size, dropout_p=0.1, max_length=MAX_LENGTH):
^
./mindsdb/external_libs/mysql_scramble.py:39:18: F821 undefined name 'xrange'
range_type = …
```
> Fix undefined names in mysql_scramble.py

- mindsdb/libs/phases/stats_generator/stats_generator.py
The data type for a column remained `None` if a specific column had only null (empty) values.
This caused issues later on the chain.
A better fix might be to:
a) Crash if a column has only null values
b) Ignore the column
c) Deal with data type `None` in the `norm` function or later down the chain
For now, this is a very easy way to fixes #64
And it shouldn't affect behavior in any way.
> current data type default to TEXT in order to avoid null data types

- integration_testing/run_a_file.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
Fixes #84 by defaulting to the `TEXT` data type if any of the values are Text in a column that's predominantly numerical.
Also fixes the way some of the score in the stats generator are computed, since some of the scores didn't behave well when given `None` values, so we have to use them on the cleaned up column data rather than the raw column data.
> Titanic fix

- .gitmodules
- docs/Config.md
- integration_testing/data_generators.py
- integration_testing/run_tests.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/data_entities/persistent_model_metadata.py
- mindsdb/libs/data_types/mindsdb_logger.py
- mindsdb/libs/data_types/transaction_output_data.py
- mindsdb/libs/data_types/transaction_output_row.py
- mindsdb/libs/phases/data_extractor/data_extractor.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
* Ludwig now properly handles timeseries where oreder_by is provided (group by is still ignored). The types date str, datetime str, int and flot are support for the timeseries column[s].
* Improved the checks done during the integration tests
* Fixed minor issues that had some of the integration tests failing and removed some weird ascii chars (will figure out what issues they cause later, it's rather weird).
* Prettified the logging for the integration testing
* Removed the correlation score, for now, because it seemed to me it was taking too long to compute (by commenting it out)
* Few other minor cleanups (e.g. adding path argument to ludwig) in order to start preparing v.1.0 for merge into master.
> Timeseries support with ludwig + other stuff

- .travis.yml
This PR removes Python 3.5 from Travis CI
> Remove 3.5 Python version from Travis

- integration_testing/data_generators.py
- integration_testing/run_tests.py
- mindsdb/libs/constants/mindsdb.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
I forgot to make an issue for this, but it's been a change we needed for along time, so, I coded it today.
Essentially if a column has a lot of repeat values the stats generator will determine it's type as categorical. This is checked on the whole dataset, rather than only on the sample.
The formula at the moment is somewhat randomly chosen as:
`(len(all_distinct_vals) < len(all_values)/200) or ( (len(all_distinct_vals) < 120) and (len(all_distinct_vals) < len(all_values)/6) )`
Feel free to ask for other magic numbers if you wish
This happens regardless of the previously determined type of the column.
I've also changed a bit of the code around how categorical values are treated further down the line and added a new data generator to be able to generate numerical values within a very small …
> Categorical improvements

- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/helpers/general_helpers.py
- test.log
This *should* resolve #155 .
It's not the prettiest solution, but, for the moment, it's the most non-invasive way I've found of doing it that should work on all platforms. There's some weirdness around ludwig logging that I don't quite understand which gets in the way of a more "standard" fix.
The lines related to disabling TF logging could be removed and it would work as intended on all platforms (I think). But, ideally, once a few ludwig changes are made, we can actually keep only the TF related lines and remove the stderr and stdout supression (which isn't exactly a "best practice"), so I'll keep that code in for now.
> Silence ludwig output

- integration_testing/run_tests.py
- integration_testing/run_travis_tests.py
- mindsdb/libs/controllers/predictor.py
Finished the two functions for the mindsdb server:
`get_model_data(model_name)` which returns a json to be used by the frontend for plots
and
`get_models()` to be used by the mindsdb server to get a list of all the modules
Loads of the data is incomplete because... well, we don't generate said data yet, I'll make some issues around that.
Hopefully the schema is ok, some things may have to change because I might have missed something, but overall it seems fine. Will start integrating this with the server tomorrow.
Oh, I think we might also want to close  (#154) for now, since the difference between what the server expects and the actual light metadata were so big we had to write the adapter.
It might be nice to get a separate schema for the light metadata in the future, but for now there's …
> Lmd adaptor

- integration_testing/run_travis_tests.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
* Sourcing training stats (accuracy) from ludwig
* Allow models to be trained further by adding the `rebuild_model=False` argument to the `learn` method of the Preidctor
Initially the intention was to switch to using ludwig's `online_train`, but it's apparently garbage in many ways (see comments in the ludwig code and issue https://github.com/uber/ludwig/issues/295), so for now we stuck with `train`.
sadly enough, this means we can't really control how long training takes or the number of epochs or gather our own information about the model whilst it's being trained :(
> Ludwig online train

- docs/website/docs/ColumnMetrics.md
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
* Added a `description` and `warning` for each of the scores computed by the stats generator. The description is a simplified description of what the score is, the warning is a string representing the warning we logged to the user regarding the score or `None` if we considered the value of the score to be low enough to warrant no notice.
* These 2 new fields are now being written into the object associated with each of the scores in the adapted light metadata.
* Added documentation (based on the internal google doc) for each of the scores inside the website docs directory. This Resolves #111 .
Note: The scores are called "metrics" in the adapted metadata if they are used to compute a derived score and are found under the object named after said derived score inside the `model_columns_map` …
> Stats generator review and improvements

- docs/examples/basic/predict.py
- docs/examples/basic/test.py
- docs/examples/nlp/predict.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/phases/data_extractor/data_extractor.py
- requirements-win.txt
- requirements.txt
* Changed the code examples in the docs to work with the new mindsdb.
* Added a missing dependency which was stopping us from correctly using xlsx files
* Changed some code around the `Transaction` (namely the heavy and light medal metadata loading) to fix a broader bug that was causing the `when` argument to behave incorrectly.
This resolves #167
> Updated examples & fixed a couple of bugs

- mindsdb/libs/controllers/predictor.py
Modified the names of the params in `export` and `load` to make it obvious the whole of mindsdb storage is being exported rather than a particular model.
If you think they should instead export a single model, or if you think we should have separate functions for exporting single models, please comment here and I'll go ahead and implement them, they shouldn't be terribly difficult to add.
Note that, at the moment, `load` overrides the previous storage of mindsdb, I'm not sure if this is an issue or not. What should the behavior be there ?
Once this PR is merged (probably after some comments and me fixing stuff) we can safely Close #57
> export_and_load_2

- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/helpers/general_helpers.py
- mindsdb/libs/model_examination/column_evaluator.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
This PR currently adds stats for each sub-bucket of a column if that column is very important and/or unimportant as determined by the `ColumnEvaluator`.
Currently the `StatsGenerator` uses the validation dataset (which is the one used to determine importance by the `ColumnEvaluator` in order to generate the metrics.
Warnings are given much like in the normal stats generator for sub buckets with a low quality score.
Added the column importance score and the column stats for columns with a very low score to the adapted metadata.
This Resolves #163 .
> Generic stats generation

- mindsdb/libs/controllers/transaction.py
* Save light and heavy metadata more frequently
* Moved the loading and saving of metadata (both light and heavy) to separate functions as part of transactions (should possibly be made part of predictor.py instead or made into generic helpers, but, later, faster this way now)
> Save more frequently

- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/model_examination/column_evaluator.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- tmp.py
Added a `force_vectors` category to the adapted metadata, which shows the normal distribution of predictions on the validation data, as well as the prediction distribution (histogram) for when a certain column is missing.
The computation for this is done inside the `ColumnEvaluator` using the stats generator to generate the histogram for each of the situations.
Resolves #121
> Force vectors

- mindsdb/libs/helpers/general_helpers.py
Simple try catch wouldn't do... but checking if the method is contained within the entitiy (os or sys.stdout) seems to cause a crash which doesn't cause the notebook to exit... kinda weird, but, I'll take what I can get, this should fix the issues specific to running on jupyter notebook.
> fixed jupyter notebook crashes due to dup2 and fileno

- README.md
This PR adds a fix for the broken link inside the README that redirects to the docs site.
> Fix broken link to redirect to docs site

- integration_testing/run_tests.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
* Added a `use_gpu` argument to the interface of predict and train. In some situation (e.g. timeseries) gpu usage is still unreliable, so for now it's a good compromise to just add a flag to disable it... since debugging the issues is environment specific (depends on the local version of cudnn and underlying libs)
* Added a fix for #222  by properly updating the timeseries columns when we have a DATE type column that gets split into year/month/day for the ludwigy backend
* Added better handling for multiple order_by columns in the ludwig backend
* Added a potential fix for #212 by switching to a different date parsing module that should be less OS dependent and comfortable with more formats. Though, I can't replicate said issue locally, so no idea if the issue is resolves.
This should …
> Timeseries fixes, use gpu interface

- mindsdb/libs/data_sources/file_ds.py
Use requests instead of urllib3. Using requests library the issues with SSL certification is fixed. #227
> Use requests instead of urlib3 

- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
Fixed a few bugs in the stats generator (or possible causes for confusion).
The main one being that date and timestamp types were not being analyzer correctly once the type was determine (due to incorrect iteration through a column in the data frame using `enumerate`)
> Better date types handling

- docs/website/docs/DataSources.md
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/data_sources/file_ds.py
- mindsdb/libs/data_types/data_source.py
- mindsdb/libs/helpers/general_helpers.py
- mindsdb/libs/helpers/probabilistic_validator.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- requirements.txt
* The probabilistic validator now registers one observation on the true validation dataset for every observation on the validation set with a column nulled out. 
This is done in order not to bias the probabilistic validator on datasets with a lot of columns, when the weighting of the very-relevant observations on the true validation data will be diminished to much by feeding in a lot of ignored-column data. 
I'm not fully sure as to why this works, it has to do with the internals of how the Complement naive bayes gets fit, but in practice it seems to yield good results.
* Removed column renaming from the mindsdb file data source logic, thus fixing a bug where the `when` wasn't working with columns that had special characters in them. 
Also fixed a bug where the prediction was returned in …
> Column naming + probabilistic validator changes

- mindsdb/__about__.py
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/phases/data_transformer/data_transformer.py
- mindsdb/libs/phases/model_analyzer/helpers/column_evaluator.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- requirements.txt
- tests/integration_tests/generated_data_tests.py
* Fixed the way timeseries data was adapted for lightwood... it was completely **** before, no idea how it even passed the tests
* Handling `nan` float values by simply setting them to `0`
* Fixes around how we standardize date and datetime/timestamp types for lightwood
* No longer ignoring order by columns in the model analysis
> Various fixes centered mostly around timeseries

- mindsdb/__about__.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/data_types/probability_evaluation.py
- mindsdb/libs/helpers/probabilistic_validator.py
Added the `always_use_model_prediction` parameters to the `unstable_parameters_dict`, and added `unstable_parameters_dict` to the list of argument `predict` can take.
This is in order to side-step models where the bayesian model is not giving us decent results.
This is a temporary fix until we find better bayesian models.
> Added always_use_model_prediction to unstable parameters dict

- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/phases/data_transformer/data_transformer.py
- requirements.txt
* Added final interface for target category balancing (making all target categories equally important in the accuracy evaluation regardless of the number of occurrences in the training dataset)
* Added final interface for assigning a custom weight to the target category
* Optimized target category balancing for lightwood, where we can use a weighted loss function for training instead of duplicating rows (row duplication is still done for the validation dataset)
> Target category balancing

- docs/website/website/core/Footer.js
Getting started link in footer is redirecting to an invalid url and git displays `404 page not found`. After this PR it is redirecting to the valid getting started page
> fix getting started link throwing 404

- .travis.yml
Somehow choco was installing 3.8 version and Travis build was failing.
> Add python version to choco

- mindsdb/__about__.py
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/helpers/probabilistic_validator.py
- mindsdb/libs/phases/data_transformer/data_transformer.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
- requirements.txt
1. Added two parameters to the unstable parameters list:
* `force_categorical_encoding` -- A list of columns which to forcefully treat as categorical, no matter what the stats generator determines to be the actual type
* `force_disable_cache`  --  Forcefully disable the caching of values when using the lightwood backend, to deal with large datasets
2. The `ignore_columns` argument was currently not working, fixed it's functionality by temporarily pigybacking on the `malformed_columns` functionality. We might wish to separate this in the future, as to no extract these columns to being with.... buuuuut, this was a quicker fix, less prone to bug and it works.
> Large dataset fixes

- mindsdb/__about__.py
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/constants/mindsdb.py
- mindsdb/libs/data_types/transaction_data.py
- mindsdb/libs/phases/data_extractor/data_extractor.py
- mindsdb/libs/phases/data_transformer/data_transformer.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
- test.py
- tests/accuracy_benchmarking/compare.py
* Data shuffling during extraction now uses a seed (total length of the data) to obtain more consistency between mindsdb training runs
* Got rid of the indexes external to the data frame from everywhere *but* the data extractor where I still keep them because I want to re-work that more thoroughly and it's tied in with re-factoring how time-series work and for now I don't want to break it... for now it works, and the external-index based logic is de-coupled from where where else:
1. Got rid of external index usage in ludwig backend
2. Got rid of external index usage in data transformer
3. Got rid of external indexes in the `TransactionData` object
* Decoupled Stats generator from needing a train/test/validation split, now it just relies on whatever dataframe gets past to it. This will …
> Improve extractor

- mindsdb/libs/data_sources/file_ds.py
problem :
the file_ds.py was not able to find the type of file
given to it due to first_few_lines giving \r\n
so it was not able to find what type of delimiter is used and throws an
error.
Solution :
to fix this an if statement is added to check if line is \r\n or
\n then it will continue else it will append that line in
first_few_lines.
closes #316
> Add an error check for \r\n and \n type of strings

- mindsdb/__about__.py
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/phases/data_transformer/data_transformer.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
Added a way for the stats generator to detect "foreign keys" (e.g. account ids, location ids, usernames... etc). This is not perfect but testing on a few datasets gave in promising results.
There an option in the unstable parameter dictionary `handle_foreign_keys` and then set to `True` mindsdb will act upon these, for now it only does so by removing them from training.
Dropped the cap on the dimension of categorical columns, since now the autoencoder in lightwood should deal with that and ludwig didn't have much of a problem with it, as far as I can remember.
> Foreign key

- mindsdb/__about__.py
- mindsdb/libs/backends/ludwig.py
fixes #345 
No longer pass empty data-frames to ludwig when training with multiple dataframes, increased the limit before which we split a dataframe to speed-up training with large datasets.
> Ludwig data split

- mindsdb/__about__.py
- mindsdb/libs/controllers/predictor.py
- tests/ci_tests/tests.py
Model importing now works, in that it correctly modifies the lightwood and ludwig model pathing, it also supports importing multiple models from the same zip file, which is appropriate since we support exporting all the models at once in a single zip file.
This resolves #364
> Import model fix

- .travis.yml
Solves #352.
Travis build was not failing as there was no option set in the `script` tag of travis.yml for taking actions if it fails. At present `script` tag is only executing tests script and as those scripts are running so there are no issues found and build will pass.
As per present scenerio the build will fail only if the scripts are not excuted such as the file which was executed using those scripts was not present there.
I guess adding `set -e` option will cause it to fail if there occurs an error in the script.
This was the only solution that came to my mind. We can use `pytest` or other tests rather than just running scripts manually if we want Travis to catch it automatically. For the present code, I think this should work.
> Travis Build not failing for script failure

- .travis.yml
- mindsdb/__about__.py
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/helpers/general_helpers.py
- mindsdb/libs/helpers/probabilistic_validator.py
- mindsdb/libs/phases/model_analyzer/helpers/column_evaluator.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
- mindsdb/libs/phases/model_interface/model_interface.py
- tests/accuracy_benchmarking/benchmark.py
- tests/ci_tests/fast_test.py
- tests/ci_tests/full_test.py
- tests/ci_tests/tests.py
- tests/functional_testing/custom_model.py
* Made `model_name` default to the name of the current model in a bunch of the Predictor's auxiliary functions (e.g. `export_model`)
* Confusion matrix is now properly generated even when the model give us null predictions (Fixes #366 )
* Grouping by a numerical column when the backend is set to lightwood now works (Fixes #365)
> Fix a bunch of issues

- .travis.yml
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/helpers/parser.py
- mindsdb/libs/helpers/probabilistic_validator.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
- mindsdb/scraps.py
https://travis-ci.org/mindsdb/mindsdb/jobs/653113896#L1020
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and …
> Travis CI: Find Python syntax errors and undefined names

- mindsdb/__about__.py
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/helpers/general_helpers.py
- mindsdb/libs/phases/data_extractor/data_extractor.py
- mindsdb/libs/phases/data_transformer/data_transformer.py
- mindsdb/libs/phases/model_analyzer/helpers/column_evaluator.py
- mindsdb/libs/phases/stats_generator/scores.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
- tests/ci_tests/tests.py
- tests/integration_tests/data_generators.py
Pushing the various fixes I work on today here.
* Resolves #390 
* Fixed a bug reported by Max and seen previously where `when_data` datasources could not have missing input columns, even though we supported this with `when` (just assuming the missing inputs have value `None`). This same behavior is now supported for `when_data` (note: this is the method used to pass larger structures such as files and data-frames to `predict`)
* Mindsdb contained a bunch of @TODOs most of them outdated and/or incorrect (by this point) removed he incorrect/now-irrelevant ones, did the small changes required by a few others. A few are still left, but those are useful to keep in there, not important enough to be issues, but important enough to have an easy way of greping for them.
* Stats generator now runs …
> Various Fixes for issues that accumulated 

- mindsdb/__about__.py
- mindsdb/libs/backends/lightwood.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/data_types/transaction_output_row.py
Various changes to source confidence from lightwood without normalization and rely on that confidence more when available.
Source predictions and numerical ranges directly from lightwood, bypassing the bayesian model (maybe revert back ? maybe make the current flag for this work again or add a new one ?).
Fixed model deletion.
> Confidence changes

- docs/website/website/siteConfig.js
Apparently this config needed to be changed in order to re-route with the new subdomain 
docs.mindsdb.com
> changed url to point to docs.mindsdb.com

- mindsdb/libs/backends/ludwig.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/data_sources/file_ds.py
- mindsdb/libs/helpers/debugging.py
- mindsdb/libs/helpers/general_helpers.py
- mindsdb/libs/helpers/text_helpers.py
- mindsdb/libs/phases/data_splitter/data_splitter.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
- mindsdb/scraps.py
- tests/ci_tests/tests.py
- tests/integration_tests/data_generators.py
`mindsdb/scraps/getColPermutations()`'s name says **permutations** while in docstring it says **combinations**, so I made two functions both for combinations and permutations that work according to their description.
**PEP-8:**
_Object type comparisons should always use isinstance() instead of comparing types directly._
_Use `.startswith()` and `.endswith()` instead of string slicing to check for prefixes or suffixes._
> Cleanup and getColPermutations logic fix

- mindsdb/__about__.py
- mindsdb/libs/phases/data_splitter/data_splitter.py
- mindsdb/libs/phases/model_interface/model_interface.py
Drops the target columns if they are null, this is done as part of a newly added cleanup in the `DataSplitter`, I realized some cleanup/transformations ought to be done before that point and some after, will maybe split the DataTrasnformer into two modules to do this in the future, no need to bother for now.
Also version bump that should deploy changes from the previous PR, also small logging fix in the `ModelInterface`
> Drop null targets

- mindsdb/__about__.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/helpers/probabilistic_validator.py
- mindsdb/libs/phases/model_analyzer/model_analyzer.py
* Calculating numerical accuracy in the `ProbabilisticValidator` based on whether or not the real values falls within the predicted range.
* Making the "will fall in the numerical range" the target of the Bayesian model used for confidence determination in the `ProbabilisticValidator` for numerical targets.
* Getting a sample of max 400 predicted-ranges + real-values from the validation datasets, this sample can be used to plot the accuracy graph for numerical values instead of the confusion matrix.
> Numerical accuracy changes

- mindsdb/__about__.py
- mindsdb/libs/phases/stats_generator/data_preparation.py
This PR fixes the `AttributeError: 'int' object has no attribute 'isspace'` bug. Sometimes the column in `clean_init_and_date_data` method is of type int so the isspace can throw error, as in [this example](https://community.mindsdb.com/t/pandas-dataframe/92/2).
> Cast column as string in case of different type

- mindsdb/__about__.py
- mindsdb/libs/data_sources/clickhouse_ds.py
When creating ClickHouse DS from query ended with semicolon is error raised with unclear message.
> Clickhouse datasource: fixed query endings with semicolon

- mindsdb/__about__.py
- mindsdb/libs/constants/mindsdb.py
- mindsdb/libs/controllers/predictor.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/data_types/data_source.py
- mindsdb/libs/phases/data_extractor/data_extractor.py
- mindsdb/libs/phases/stats_generator/stats_generator.py
- tests/ci_tests/tests.py
- tests/functional_testing/data_source_setting.py
* Added a method to the `DataSource` superclass that all datasource inherit to allow for manual setting of the data subtypes of a certain column. We only allow subtype setting (instead of typesetting or the ability to set either/or type and subtype) because:
a) We'd have to change the `StatsGenerator` quite a lot to find a subtype under specific type constraints and this proved too difficult
b) Setting the subtype also dictates the data type, so setting a subtype is enough to set both
c) I don't see many cases in which a user would want and know what type to set for his data better than mindsdb but not what subtype.
* Made mindsdb able to use said types and subtypes, when specified, instead of those inferred by the `StatsGenerator` (the type inference step is skipped for columns where the …
> Manual (Sub)type setting

- mindsdb/__about__.py
- mindsdb/libs/data_sources/file_ds.py
It used to cause `reference before assignment error` on the variable `header`. Now it is an explicit `raise ValueError` . Also I changed variable name from `format` to `fmt`, because `format` is a built-in function name.
> Explicit exception when file type is unsupported

- mindsdb/__about__.py
- mindsdb/libs/data_types/transaction_data.py
- mindsdb/libs/phases/data_analyzer/data_analyzer.py
- mindsdb/libs/phases/type_deductor/type_deductor.py
- tests/unit_tests/libs/phases/data_analyzer/test_data_analyzer.py
Resolves #487 
As @George3d6 suggested, sampling is done once in `TypeDeductor` and stored in `transaction.input_data`
> Sample once

- mindsdb/__about__.py
- mindsdb/libs/controllers/transaction.py
- mindsdb/libs/data_types/transaction_output_row.py
- mindsdb/libs/helpers/explain_prediction.py
- tests/ci_tests/tests.py
- tests/unit_tests/libs/controllers/test_predictor.py
Makes it harder to be confused by the old explainer, see:
https://github.com/mindsdb/mindsdb/issues/510
> Add warnings that TransactionOutputRow.explain() is deprecated

- distributions/windows/install.py
- mindsdb/interfaces/datastore/datastore.py
- mindsdb/utilities/fs.py
Resolves #523 
The server will not run on windows because of scipy DLL loading error (scipy 1.5.0). To solve this we should either change mindsdb requirements (until the dll issue is fixed by scipy) or install scipy==1.4.1 only for windows, in this installer.
> simplify installer, add windows-specific paths for mindsdb data

- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This PR adds missing GitHub community standards as code of conduct, contribution guide. I think we have moved them to mindsdb_native so they were missing for this repo.
> Add gh standards

- mindsdb/interfaces/native/mindsdb.py
This PR change uses a new import_model method from functional instead of load fixes Scout upload issue.
> Use import_model instead of load

- mindsdb/api/http/namespaces/config.py
- tests/integration_tests/api/test_http.py
* Changed the `/modification` endpoint to just be a `POST` call on the normal `/integrations/<name>` endpoint
* Refreshing database integrations when one is added or modified
* Added endpoint to list the name of all integrations.
* Modified tests to account for this.
> added a few suggestions from Max and modified tests

- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- mindsdb/integrations/clickhouse/clickhouse.py
- mindsdb/integrations/mariadb/mariadb.py
- mindsdb/interfaces/datastore/datastore.py
close #593 
this fix allow use via sql-interface predictors with names contains 'minus' and 'space' signs (and probably other else supported by current database)
> table name escaping

- mindsdb/__main__.py
- mindsdb/utilities/config.py
- mindsdb/utilities/wizards.py
- tests/integration_tests/api/test_http.py
- tests/integration_tests/flows/common.py
- tests/integration_tests/flows/config/config.json
Close #603 
Before version 1.99.5 config has not contains 'type' key for integrations, so anyone who used mindsb before this version and update after will have error at start. This 'fix' add 'migration' for old config to fix current error and make easier to bring changes in config structure.
> Validity check and migrations for Config

- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
Small enhancement: if someone starts mindsb module with --config arg, then he need somehow create ssl-cert before and specify path to it in config. This PR add opportunity remove this key from config, or set it to empty string. In this case temp cert will be created at start.
> make cert if it not specified in config

- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
That tiny fix for issue https://github.com/mindsdb/mindsdb/issues/591
When model field has 'timestamp' type, when it will be converted to string timestamp
> fix timestamp transformation

- mindsdb/api/http/namespaces/config.py
- mindsdb/api/http/namespaces/datasource.py
- mindsdb/interfaces/datastore/datastore.py
- mindsdb/utilities/config.py
- tests/integration_tests/api/test_http.py
1. Added `/config/all_integrations` endpoint that lists all integrations with the full data associated with all of them in a dict keyed on the integration ids
2. Added `/integrations/<name>/check` (where `<name>` is the integration's id) that allows you to check whether an integration is functional (i.e. if mindsdb can connect to the database)
3. Added the ability to add database integration based datasource to the `/datasources/<name> -- PUT` endpoiont:
Simply call the endpoint and replace `<name>` with the name of our datasource then give two parameters in the json post body:
`query` - the sql query to get the actual data
`integration_id` - the id of the database integration
4. To see what database integration a given datasource comes from, simply check the `source_type` parameter of …
> Db improvements

- .github/workflows/cla.yml
This PR automates the CLA signing using Github Actions. The CLA files are referenced in mindsdb_native since it is the same agreement.
> Add CLA assistant

- mindsdb/utilities/config.py
If user specified password in config as int, it followed to errors when connect to DB. Now all passwords will reading as strings, empty or  = null will read as empty string.
> Read passwords from config as strings

- mindsdb/api/http/namespaces/datasource.py
- requirements_test.txt
Reason: when user push on 'data quality' in gui, it call `/ds_name/analyze` route. This query will be active untill analysis finished. It can take much time for big datasets, query can fail by timeout. As resolve i done this:
1. when first time called `/ds_name/analyze`, analysis starts and returned to user {status: 'analyzing'}
2. {status: 'analyzing'} will be returned each time while analysis not finished
3. then if finished, returned analysis data
> Datasource analysis in separate thread

- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
- mindsdb/integrations/clickhouse/clickhouse.py
- mindsdb/interfaces/datastore/datastore.py
Fixes #609
1. Datasource dir will be removed if error raised.
2. If trained columns not in datasource columns list, error for user will be raised
3. fixed 'use db' query
4. changed clickhouse array type to text, because CH cant get array from mysql.
> Deleting datastore dir on learing error

- mindsdb/__init__.py
- mindsdb/__main__.py
- mindsdb/utilities/functions.py
Fixes #649
In some cases, if user provide in `--config` arg `storage_path` different from `storage_path` in default config, it  may occur bug with different paths in mindsdb and mindsb_native.
> Fix different storage paths in mindsdb and mindsb_native

- .github/workflows/cla.yml
- README.md
The old collab example was using version 1.4 of mindsdb and was outdated and users got errors as #659. In the new example, we are using mindsdb_native.
> Update colab example

- mindsdb/api/http/start.py
This handler will catch all not-http related errors and return it to user as {message: error} with 500 code.
Example of output if typo in table name when datasource creation:
```
{
"message": "Exception: Code: 60, e.displayText() = DB::Exception: Table test.home_rental1s doesn't exist. (version 20.6.4.44 (official build))\n"
}
```
> Routes exception handler

- mindsdb/utilities/wizards.py
Errors can raise If server and client machines have different time. That will fix it.
> Change ssl cert start date

- mindsdb/api/http/initialize.py
- mindsdb/utilities/ps.py
After initializing the application, the function of opening the browser with the main link is launched in a separate thread.
This function scans the availability of the api-http port of the service and the browser opens only after the service is started.
If an error occurs while scanning the port or when opening the browser, then nothing happens, an error log is displayed.
mindsdb
> open browser with index.html when http-api started

- distributions/docker/Dockerfile
Fixes #772
- Updated the dockerfile `CMD` instruction to start the server
mindsdb
> change docker cmd to start mindsdb server

- distributions/docker/build-docker.sh
Fixes #
Added correct URL in build-docker.sh so proper Dockerfile can be pulled.
- Changed this line:
```
curl https://raw.githubusercontent.com/mindsdb/mindsdb/master/distributions/docker/Dockerfile > Dockerfile
```
To this line:
```
curl https://raw.githubusercontent.com/mindsdb/mindsdb/staging/distributions/docker/Dockerfile > Dockerfile
```
Issue #777 
mindsdb
> Added correct URL to build-docker.sh

- INTEGRATION.md
- mindsdb/api/http/namespaces/datasource.py
- mindsdb/api/http/namespaces/predictor.py
- mindsdb/api/mongo/op_msg_responders/insert.py
- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
- mindsdb/interfaces/datastore/datastore.py
* When creating  a datasource we are now taking into account the `database` parameter in the integration config if it exists, the database which we authenticate against, for postgres, mysql, mariadb and mssql
* Supporting an extra parameter called `database` in datasource creation requests, which indicates that we should authenticate against + get data from another database than the "default" one in the integration config.
* Added docs to help the frontend team
* Simplified datasource creation logic
> Better data sourcing

- distributions/windows/install.py
- Don't close terminal at exit
- Inform user about shortcut on desktop after successfull installation
> message after successfull installation (windows installer)

- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
I think it should be by set by default. I looked in 'waitress' sources, they set this option without any conditions. And i dont see any real situation where we need it switched off.
> Set allow_reuse_address by default for mysql api

- .gitignore
- mindsdb/api/http/initialize.py
- mindsdb/api/http/start.py
Fix to static file path to be `''` instead of `'/'`. Apparently `'/'` sometimes doesn't work (https://github.com/pallets/flask/issues/3134)... though flask says it should. Maybe it's only an issue with some versions or environments, but if I encountered it chances are other people might, so we might as well use `''` if there is not harm @StpMax , thoughts ?
Also added a few files to the `.gitignore` with this ocassion.
> Static file fix(?)

- mindsdb/api/mongo/op_msg_responders/find.py
- mindsdb/api/mongo/op_msg_responders/list_databases.py
- mindsdb/integrations/base/integration.py
- mindsdb/integrations/clickhouse/clickhouse.py
- mindsdb/integrations/mariadb/mariadb.py
- mindsdb/integrations/mssql/mssql.py
- mindsdb/integrations/mysql/mysql.py
- mindsdb/integrations/postgres/postgres.py
- mindsdb/utilities/config.py
Should work by setting config['api']['mysql']['database'].
Checks:
For mongo db name defined by config['api']['mongodb']['database']
> Configurable mindsdb sql database name

- mindsdb/utilities/wizards.py
Fixes #851 
mindsdb
added optional boolean parameter argument for  make_executable() function and added the relevant shell code for checking truth value of update parameter and then running "py -m pip install mindsdb --upgrade " code
> optional boolean arguement added for executable function

- mindsdb/__main__.py
Fixes #823 
- Previously, there was a bug that when interrupting the main process by ctrl-c, all other processes should have stopped too. 
But sometimes that didn't happen in some cases.
- In order to solve this issue , this PR is an improvement to the existing code that adds `try - except` to  `close_api_gracefully` 
function so that the graceful exit can take place.
Changes can be found [here](https://github.com/yash2189/mindsdb/blob/fix%23823/mindsdb/__main__.py)
mindsdb
> fixed address already in use when running mindsdb

- mindsdb/api/http/namespaces/datasource.py
Removed the caching refresh limit of 10 seconds for data analysis, due to datasource versioning we can just cache this forever.
> Caching data analysis forever

- .github/workflows/mindsdb.yml
- mindsdb/api/mysql/mysql_proxy/classes/server_capabilities.py
- mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/handshake_packet.py
- mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/handshake_response_packet.py
- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
- mindsdb/integrations/postgres/postgres.py
- mindsdb/utilities/config.py
- mindsdb/utilities/functions.py
- requirements_test.txt
- tests/README.md
- tests/docker/cli.sh
- tests/docker/docker-compose-mongo.yml
- tests/docker/docker-compose.yml
- tests/docker/mongodb/glue/Dockerfile
- tests/docker/mongodb/glue/data/entrypoint.sh
- tests/docker/mongodb/glue/data/init_config_rs.js
- tests/docker/mongodb/glue/data/init_db_rs.js
- tests/docker/mongodb/glue/data/init_mongos.js
- tests/docker/mongodb/mongos/mongos-dockerfile
- tests/integration_tests/api/test_http.py
- tests/integration_tests/flows/common.py
- tests/integration_tests/flows/config/config.json
- tests/integration_tests/flows/test_clickhouse.py
- tests/integration_tests/flows/test_custom_model.py
- tests/integration_tests/flows/test_mariadb.py
- tests/integration_tests/flows/test_mongo.py
- tests/integration_tests/flows/test_mssql.py
- tests/integration_tests/flows/test_mysql.py
- tests/integration_tests/flows/test_postgres.py
Integration tests can be run in two modes, defined by env variable USE_EXTERNAL_DB_SERVER:
1. if USE_EXTERNAL_DB_SERVER="0", than on run test will be runned docker container with target databasde.
2. if USE_EXTERNAL_DB_SERVER="1", then ssh-tunnels to test database server will be up. For that should exists:  
* `.mindsdb_credentials.json` file in home dir.
* `~/.ssh/db_machine` with key for db machine.
> Tests using remote databases

- mindsdb/api/http/namespaces/predictor.py
- mindsdb/interfaces/datastore/sqlite_helpers.py
- mindsdb/interfaces/native/mindsdb.py
- mindsdb/utilities/functions.py
Fixes #928
Reason of error - is no 'type' for column, specified in 'ignore_columns' on model training.
It can be fixed by adding `if len(data_analysis[column]) == 0` to each place, where used `data_analysis`, or by changing `data_analysis` view when we get data from mindsdb_native. Here is second way.
> Changes in model view

- .github/workflows/mindsdb.yml
Fixes #804 
Release image (which created in a `deploy` step) needs to contain MindsDB version installed from PyPi repository (not from local source files) In this case we ensure that release image and PyPi have same version.
> Install mindsdb from pypi in deploy step

- mindsdb/api/http/namespaces/util.py
- mindsdb/interfaces/native/mindsdb.py
- mindsdb/interfaces/native/predictor_process.py
- tests/docker/postgres/Dockerfile
- tests/integration_tests/api/test_http.py
- tests/integration_tests/flows/config/config.json
Resolves #941 
The endpoint ended up being `/api/util/report_uuid`
Example of what it returns: `{"report_uuid": "820e08b3-dafb-42f6-bfcd-bc51a6dee472"}`
The impl was a bit more complicated and will fail until the changes in https://github.com/mindsdb/mindsdb_native/pull/303 are merged
> Report UUID endpoint

- mindsdb/api/http/initialize.py
- mindsdb/api/http/start.py
- tests/integration_tests/api/test_http.py
1. for any route, except starts from `api/` or `static/`, will be returned file from `static` folder (if exists), or `index.html`
2. decreased cache timeout to 60 seconds (by default 12 hours).
> Changes in static routing

- mindsdb/utilities/config.py
Fixes #946 
Issue happens in case then relative path to config.json located in a custom directory provided.
> 946: Fix 'storage' folder path definition

- distributions/docker/Dockerfile
- mindsdb/utilities/config.py
- mindsdb/utilities/wizards.py
After renaming 'enabled' to 'publish' in config['integrations'] an error may appear, because in user config integrations still have 'enabled' keys. That migration will change it.
> Migration for config 1.3 -> 1.4

- tests/integration_tests/flows/test_mysql.py
At this moment we get 'timeout error' during mysql test. That because predicts in tests train without time limit. Since https://github.com/mindsdb/mindsdb_native/issues/291 is closed, we can return limit for train.
> fix timeout issue

- mindsdb/utilities/fs.py
Fixes #986 
Issue has detailed description. No sense to duplicate it here
```
(mindsdb_venv) ~/repos/MindsDB/mindsdb itsyplen$ python -m mindsdb
Athena Datasource is not available by default. If you wish to use it, please install mindsdb_native[extra_data_sources]
SnowflakeDS Datasource is not available by default. If you wish to use it, please install mindsdb_native[snowflake]
Google Cloud Storage Datasource is not available by default. If you wish to use it, please install mindsdb_native[extra_data_sources]
Configuration file:
/Users/itsyplen/.local/etc/mindsdb/config.json
Storage path:
/Users/itsyplen/.local/var/lib/mindsdb
```
> Issue986: specify home dir properly

- distributions/windows/build_installers.py
Closes https://github.com/mindsdb/mindsdb/issues/964
Use `--uac-admin` flag when building windows installers with pyinstaller so the executable is run as admin when double-clicked
> run as admin by default

- .github/workflows/mindsdb.yml
- .github/workflows/release.yml
a bug in the winshell module:
https://stackoverflow.com/a/45929866/8841831
so pywin32 has to be installed for winshell to work (otherwise there is a `ModuleNotFoundError` when importing winshell)
> install pywin32 before winshell to build windows installer

- mindsdb/api/mongo/classes/__init__.py
- mindsdb/api/mongo/classes/responder.py
- mindsdb/api/mongo/classes/scram.py
- mindsdb/api/mongo/classes/session.py
- mindsdb/api/mongo/op_msg_responders/__init__.py
- mindsdb/api/mongo/op_msg_responders/add_shard.py
- mindsdb/api/mongo/op_msg_responders/aggregate.py
- mindsdb/api/mongo/op_msg_responders/buildinfo.py
- mindsdb/api/mongo/op_msg_responders/coll_stats.py
- mindsdb/api/mongo/op_msg_responders/connection_status.py
- mindsdb/api/mongo/op_msg_responders/count.py
- mindsdb/api/mongo/op_msg_responders/db_stats.py
- mindsdb/api/mongo/op_msg_responders/delete.py
- mindsdb/api/mongo/op_msg_responders/find.py
- mindsdb/api/mongo/op_msg_responders/get_cmd_line_opts.py
- mindsdb/api/mongo/op_msg_responders/host_info.py
- mindsdb/api/mongo/op_msg_responders/insert.py
- mindsdb/api/mongo/op_msg_responders/is_master.py
- mindsdb/api/mongo/op_msg_responders/is_master_lower.py
- mindsdb/api/mongo/op_msg_responders/list_collections.py
- mindsdb/api/mongo/op_msg_responders/list_databases.py
- mindsdb/api/mongo/op_msg_responders/list_indexes.py
- mindsdb/api/mongo/op_msg_responders/sasl_continue.py
- mindsdb/api/mongo/op_msg_responders/sasl_start.py
- mindsdb/api/mongo/op_msg_responders/update_range_deletions.py
- mindsdb/api/mongo/op_msg_responders/whatsmyuri.py
- mindsdb/api/mongo/op_query_responders/is_master.py
- mindsdb/api/mongo/server.py
This is base implementation of 'SCRAM-SHA-1' auth in MongoDB. That ahould allow connect to mindsdb 'mongo api' using name/password:
`mongo --port 47337 -u "user" -p "password" --authenticationDatabase "admin"`
To do it, first need to add 'user' and 'password' fields in `config['api']['mongodb']`. If any of this fields is empty, then is no possible to connect as above.
Connection without user/password still allowed (even if 'user' and 'password' in config).
Added ssl socket wrapp dor mongo api. Now possible connect with and without ssl:
`mongo --port 47337`
`mongo --port 47337 --ssl --sslAllowInvalidCertificates`
`sslAllowInvalidCertificates` need because mongodb dont allow self signed certs.
Added processing of packages to mongo api (need for work thorough Compass):
```
connection_status …
```
> username/password auth for MongoDB api

- mindsdb/interfaces/database/database.py
Fixes #1007
- **What**
- When predictor is creating and any integration with third-party database is already exists, mindsdb creates a table object in each existing integration for new predictor
- When predictor is deleting, mindsdb removes all tables related to this predictor in each integration
- If integration created with invalid credentials or connection couldn't be estalished, user receives 500 error on deleting predictor event and backend also raises exception on create/delete predictor in this case (see details in original issue)
- **How**
- check connection before each register/unregister predictor action
> Error while delete predictor from not valid integration

- mindsdb/api/http/namespaces/predictor.py
- mindsdb/interfaces/custom/custom_models.py
Fixes #994
**What**:
- `predict_datasource` endpoint send to native Predictor dict with pickle DataSource info which doesn't support my native Predictor
**How**
- Sending particular DataSource instance instead for data about this one
> Receive DataSource instance to Predictor instead of object_info dict

- mindsdb/api/http/namespaces/datasource.py
- tests/integration_tests/api/test_http.py
Fixes #945
**What**
- Error(namely error loop) happened while user try to create datasource form non existing integration (see details into related issue).
- Root cause of it - native receives original data dictionary as File DataSource info
**How**
- By checking that provided integration exists in API endpoint
mindsdb
> Error to create datasource from fake integration

- tests/integration_tests/flows/common.py
**why**
Sometimes error appears on test start: `mysql cant connect to 127.0.0.1 bla bla bla`. The reason is unsuccessful port forwarding before. My guess, that can happens if someone other used same port before and dont close forwarding properly (if, for example, exception raised during test). 
**how**
1. closing all current port-forwarding on test start (need comment this if several tests will be ran in same time)
2. trying open port forwarding in cycle, untill success (no more 10 times)
> improve port forwarding closing

- mindsdb/interfaces/native/mindsdb.py
**why**
if predictor trained with ignore_column, then that columns will be in `data_analysis['columns']`, but will be missed in `data_analysis` and data_analysis['columns_to_ignore']. That follow to error on mindsdb start up.
**how**
add check
> fix ignored column in data analisys

- mindsdb/__main__.py
- mindsdb/api/http/initialize.py
- mindsdb/api/http/namespaces/util.py
- mindsdb/api/http/start.py
- mindsdb/utilities/telemetry.py
**why**
At this moment to disable telemetry need do two things: enter konami code at frontend and set env variable at backend. That can be simplified
**how**
At http api start we can inject to index.html code to disable telemetry, if it disabled for backend. 
Additionally, at backend start will be console output if telemetry is disabled
> Disable frontend telemetry

- mindsdb/integrations/mongodb/mongodb.py
**why**
Checking connection to data lake always failed. That, probably, because connection to data lake should be with `tls=true`.
**how**
if `mongo.net` in connection sting, then we set that option. Also, for `mongo.net` set `tlsCAFile=certifi.where()` since Alejo cant connect without it.
> Fix for checking connection to atlas data lake

- mindsdb/api/mongo/responders/find.py
**why**
to allow use 'dot' notation in mongo `find`: db.predictor.find({'a.b': 1})
**how**
added additional check for field exists
> Allow dot in mongo find

- mindsdb/api/mongo/responders/find.py
**why**
if user execute `.find` with list as argument, then fields will be missed in result
**how**
added keys from each element of `find` argument to result list.
> Better mongo fields list

- mindsdb/api/http/initialize.py
- mindsdb/api/http/start.py
**why**
It was no possible listen connections from any address and serv GUI at Windows.
**how**
Added check for host is equal to empty string or `0.0.0.0`. In that case connections from any address will be listen and GUI will be open at `127.0.0.1`.
> Allow listen any http addres

- mindsdb/__main__.py
- mindsdb/api/http/initialize.py
- mindsdb/api/http/start.py
- mindsdb/utilities/functions.py
Studio  takes a long time to download and run, this is not necessary when launching certain instance
Added a ` --no_studio` flag, when specified Studio will not be downloaded or launched
> no_studio flag

- mindsdb/__main__.py
- mindsdb/api/http/initialize.py
- mindsdb/api/http/namespaces/predictor.py
- mindsdb/api/http/start.py
- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
- mindsdb/interfaces/custom/custom_models.py
- mindsdb/interfaces/native/learn_process.py
- mindsdb/interfaces/native/native.py
- mindsdb/utilities/functions.py
In order to move to an ID-based schema we need to start  linking stuff by id.
In order to move to a model where predictors are linked with datasources we need to, well, link them
Pass datasource id to all calls to `.learn()` in order to provide the predictor with the id of the datasource it's usign.
In the future we can make the predictor get the datasource based on this ID, but not a priority.
> Datasource id for predictors

- mindsdb/__main__.py
- mindsdb/interfaces/native/learn_process.py
- mindsdb/utilities/config.py
- mindsdb/utilities/ps.py
Fixes #1058 
- ```close_api_gracefully only closes the API, but not any ongoing learn processes, which are left orphaned and consuming loads of memory.```
- Each learning process when start working stories its own pid as empty file in `storage_dir/in_learning` directory and will delete it at the end if no interruption happens
- `close_api_gracefully` read list of files in `storage_dir/in_learning` and sends SIGTERM to each of this process.
mindsdb
> close learn process gracefully

- mindsdb/api/http/namespaces/config.py
- mindsdb/integrations/__init__.py
- mindsdb/integrations/base/integration.py
- mindsdb/integrations/clickhouse/clickhouse.py
- mindsdb/integrations/mariadb/mariadb.py
- mindsdb/integrations/mongodb/mongodb.py
- mindsdb/integrations/mssql/mssql.py
- mindsdb/integrations/mysql/mysql.py
- mindsdb/integrations/postgres/postgres.py
Fixes #1082
**What:**
- right now it is possible to check connection for `real` integrations that is why check connection (put /integration request with {test: true}) fails
**How**:
- Provide connection checker for each integration type as a mixin to decouple strong conjunction between Integration abstraction and particular call to different database types
> 'check connection' not worked for existing connection

- requirements.txt
Fixes #1120 
Fix typo for installing TLS optional requirement with Pymongo
> Pymongo requriements

- mindsdb/interfaces/datastore/datastore.py
Fixes 
`pymongo.errors.WriteError: local variable 'ds' referenced before assignment, full error: {'index': 0, 'code': 0, 'errmsg': "local variable 'ds' referenced before assignment"}` during creating predictor in mindsdb cloud via mongo api
> error in creating mongo datasource

- mindsdb/api/mongo/responders/insert.py
- mindsdb/interfaces/native/native.py
Fixes:
```
raise exception
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: UPDATE predictor SET updated_at=%(updated_at)s, data=%(data)s, to_predict=%(to_predict)s, version=%(version)s, datasource_id=%(datasource_id)s WHERE predictor.id = %(predictor_id)s]
[parameters: {'updated_at': datetime.datetime(2021, 3, 3, 13, 1, 9, 991338), 'data': '{"name": "mongo_pred1", "status": "training"}', 'to_predict': 'passenger_count', 'version': '2.34.0', 'datasource_id': {}, 'predictor_id': 1}] …
```
> provide correct datasource id while train model via mongo API

- mindsdb/api/mysql/mysql_proxy/data_types/mysql_datum.py
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
- mindsdb/integrations/mariadb/mariadb.py
- mindsdb/integrations/mysql/mysql.py
**why**
fix for #1127
**how**
1. issue could have been caused if datasource table had not same charset as default in database.
2. in our implementation of mysql protocol we calc length of text fields as count of characters, which was wrong, it should be length of bytes represented of string.
> Fix for non latin characters in mysql/mariadb

- mindsdb/api/http/namespaces/datasource.py
- mindsdb/api/http/start.py
- mindsdb/interfaces/datastore/datastore.py
**why**
1. to add more errors logging on ds creation fails
2. i think it will be good to remove DS if it is broken, instead ignore it
3. there was possible get 'broken' ds if something happen in `def save_datasource` (even with `sesson.delete(ds_record)` in exception handler, because by default autocommit is false).
**how**
> Delete broken datasources + loggin errors

- mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py
**why**
looker try select additional fields from information_schema.columns, which we not provide before
**how**
add that fields to list
> fix select columns list

- mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
**why**
some queries come with leading comment string:
```
--comment
select * from a
```
**how**
remove comment by pyparsing
> Filter comments from sql

- mindsdb/api/http/namespaces/config.py
- mindsdb/api/mongo/classes/responder.py
- mindsdb/interfaces/database/database.py
**why**
When creating an integration, function 'register predictors' is calling for each integration, which is not necessary.
**how**
> call 'register_predictor' only for creating integration

- mindsdb/api/http/namespaces/config.py
Fixes #
```
http API: started on 47334
http exception: local variable 'cloud' referenced before assignment
[2021-03-15 15:47:32,235] ERROR in app: Exception on /api/config/vars [GET]
Traceback (most recent call last):
File "/home/itsyplen/repos/work/MindsDB/mindsdb_env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/itsyplen/repos/work/MindsDB/mindsdb_env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/itsyplen/repos/work/MindsDB/mindsdb_env/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
resp = resource(*args, **kwargs)
File "/home/itsyplen/repos/work/MindsDB/mindsdb_env/lib/python3.8/site-packages/fl …
```
> local variable 'cloud' referenced before assignment

- mindsdb/interfaces/model/learn_process.py
- mindsdb/interfaces/model/model_controller.py
**why**
two small fixes:
1. http call to list predictors can return predictor with `'predict': None` right after learn start, which is the cause of error on frontend
2. add error processing on predictor learn fail
**how**
> Fix for issues if predictor learn fail

- mindsdb/__init__.py
- mindsdb/utilities/log.py
**why**
to close #1181 
**how**
This are not good fix for issue, but should be enough for now:
1. increase sqlite access timeout  from default 5 to 30 seconds. Now multiple models can be train simultaneously without errors.
2. I dont found why ray send each second log line from `mindsdb_native` as empty string with 'error' level, so i added filter to DBHandler where all empty lines will be filtered. That should decrease db write access twice as much.
> fix saving logs to db

- .github/workflows/mindsdb.yml
This PR adds workflow for deploying amis to aws. To preview the whole flow visit https://github.com/mindsdb/mindsdb_gateway/tree/staging/deployments. 
>Note Before merging add    `ACCESS_KEY`,  `AWS_ACCESS_KEY` and   `AWS_SECRET_KEY` to repo secrets.
> Add GitHub Action for publishing AMIs

- mindsdb/utilities/log.py
This PR fixes the issue for `AttributeError: 'LogRecord' object has no attribute 'message'`. This was happening when starting the Mongo API. Firstly I thought some other error happens and we are not able to catch it because of this issue but, after fixing this mongo was successfully started.
> Add records to avoid, undefined error[Fix mongo api start]

- mindsdb/api/mongo/responders/__init__.py
- mindsdb/api/mongo/responders/buildinfo.py
- mindsdb/api/mongo/responders/end_sessions.py
- mindsdb/api/mongo/responders/get_free_monitoring_status.py
**why**
Latest mongo shell sends `getFreeMonitoringStatus` at start of connection and `endSessions` at the end. All works, but user see error message in console, and client reconnect, which make debugging much harder.
**how**
> processing for 2 new mongo packages

- mindsdb/integrations/clickhouse/clickhouse.py
- mindsdb/integrations/mariadb/mariadb.py
- mindsdb/integrations/mssql/mssql.py
- mindsdb/integrations/mysql/mysql.py
- mindsdb/integrations/postgres/postgres.py
- mindsdb/interfaces/storage/db.py
**why**
1. At this moment is not possible to remove DS which was used for predictor training, if as storage database use not sqlite.
2. one of users get error on creation predictors table in db, there is no way to determine why. Add `log.error()` for that cases.
**how**
remove db constrain
> Remove constrain on ds table

- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
**why**
`xmlrpc` can not transfer `dict_values`, so predictions can fail
> Fix rpc predictions

- mindsdb/api/http/namespaces/stream.py
- mindsdb/integrations/kafka/kafkadb.py
- mindsdb/integrations/redis/redisdb.py
- mindsdb/interfaces/storage/db.py
- mindsdb/streams/base/base_stream.py
- mindsdb/streams/kafka/kafka_stream.py
- mindsdb/streams/redis/redis_stream.py
Fixed #1171
How (this is the last part of implementation):
by providing ts_setting like (`order_by`, `group_by`, `window_size` and prediction `target`) in creating Stream API request (for Kafka and Redis):
```
import requests
stream_info = {"predictor": "covid_ts",
"stream_in": "covid_in",
"stream_out": "covid_out",
"integration_name": "kafka_test",
"type": "timeseries",
"ts_params": {"target": "adult_icu_bed_utilization",
"order_by": "time",
"group_by": "state",
"window_size": 10},
}
url = "http://127.0.0.1:47334/api/streams/kafka_stream_http_api"
res = requests.put(url, json={'params': stream_info})
print(res.status_code, res.text)
```
> Provide TS settings

- mindsdb/interfaces/model/model_controller.py
if `predicotr.data` is None and `new_model_data` is None too, then was error on accessing to `model` var
> fix get_models for currupted predictors

- .github/workflows/matrix_includes.json
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
- mindsdb/interfaces/model/model_controller.py
- mindsdb/utilities/log.py
Mindsdb won't return any rows if the `data` resulting from the `select` function in the datanode has the values for the received columns changed. (when using from within clickhouse)
E.g. if we get ` WHERE A=1 AND B='2'` but then try to return the data dict:
`{'A': None, 'B': '2', 'to_pred': 13242}`, then we will see `0` rows being returned to clickhouse.
The original values that the prediction is generated from being made "null" was happening inside the native `predict` call and is an unknown bug, but in case this happens in the future it might make sense to implement a "fix" for it mindsdb side, which this PR does. I assume this might have to do with clickhouse doing the `WHERE` filtering on their side too, but am unsure.
Also:
* Fixed `get_model` to work before `name` gets set as a …
> Timeseries fix + various

- .github/workflows/mindsdb.yml
- mindsdb/__init__.py
- mindsdb/__main__.py
- mindsdb/api/mongo/responders/insert.py
- mindsdb/interfaces/model/model_controller.py
- mindsdb/interfaces/model/model_interface.py
- mindsdb/utilities/functions.py
- mindsdb/utilities/os_specific.py
Currently we use ray always if it installed. This PR make that optional. So we avoid possible errors if user already use ray, and make local testing much easier.
Use or not ray checked by:
1. env variable USE_RAY
2. arg --ray (which is more priority)
By default ray is not used
> Optional ray usage

- mindsdb/api/http/namespaces/datasource.py
- mindsdb/api/mongo/responders/find.py
- mindsdb/api/mongo/responders/insert.py
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
- mindsdb/interfaces/datastore/datastore.py
**why**
to fix https://github.com/mindsdb/mindsdb/issues/1204
In some cases we need raise error if name of creating datasource is exists (e.g. creating datasource through http api), in some other cases we need create ds name on fly (e.g. creating temp ds for 'range' query).
**how**
> Better manage ds names on creation

- mindsdb/api/http/namespaces/datasource.py
- mindsdb/interfaces/datastore/datastore.py
- mindsdb/interfaces/storage/fs.py
**why**
to fix https://github.com/mindsdb/mindsdb_gui_web/issues/787
**how**
mindsdb instance can have not ds file if use s3 as storage. Need upload it first.
> Fix downloading ds from s3

- mindsdb/api/http/namespaces/datasource.py
- mindsdb/api/http/namespaces/entitites/predictor_status.py
- mindsdb/interfaces/datastore/datastore.py
- mindsdb/interfaces/model/model_controller.py
- mindsdb/utilities/config.py
Fixes #1280
Perform simple checking before delete a datasource.
By setting `force_datasource_removing` to True in config any datasource would be deleted despite on any linked models.
> Don't allow deleting datasources if they are linked to a predictor

- mindsdb/__main__.py
- mindsdb/integrations/clickhouse/clickhouse.py
- mindsdb/integrations/mariadb/mariadb.py
- mindsdb/integrations/mysql/mysql.py
- mindsdb/integrations/postgres/postgres.py
Fixes #1198
change `CREATE TABLE...` to `CREATE TABLE IF NOT EXISTS....` for all predictor tables in all integrations
> Error register predictors for integrations with same DB

- mindsdb/streams/kafka/kafka_stream.py
- mindsdb/streams/redis/redis_stream.py
make `group by` optional for TS streams
> Allow empty group_by in TS streams

- mindsdb/api/http/namespaces/predictor.py
currently `/predict` request with when_data in `timeseries` (list) format ends with error:
`'No data provided for the predictions', 400`
Need to fix it. 
There is more sanity fix:
1. get model info
2. check is it timeseries or not
3. Allow/decline list format according to previous item
but it is too expensive for us, I think
@StpMax Please suggest
> Allow to send data in timeseries format to 'predict' endpoint

- mindsdb/streams/redis/redis_stream.py
I'm getting an error while creating mindsdb stream via Redis:
```XADD control * action create name covid_stream predictor covid stream_in covid_in stream_out covid_out stream_anomaly covid_anomaly```
```
2021-08-05 08:26:27,787 - ERROR - for dct in self._control_stream.read():
2021-08-05 08:26:27,799 - ERROR -   File "/home/itsyplen/repos/work/MindsDB/mindsdb/mindsdb/streams/redis/redis_stream.py", line 14, in read
2021-08-05 08:26:27,812 - ERROR - yield json.loads(when_data[b''])
2021-08-05 08:26:27,826 - ERROR - KeyError
2021-08-05 08:26:27,838 - ERROR - : 
2021-08-05 08:26:27,853 - ERROR - b''
```
Redis stream must handle bytes and dicts properly
> Back compatibility for creating stream through redis API

- tests/integration_tests/flows/test_kafka.py
- tests/integration_tests/flows/test_redis.py
Fixes #1388
- Use local import only after calling `run_environment`
- uncomment subset of tests
- added test for ts prediction with empty `group_by`
mindsdb
> Streaming tests pathing issue

- docs/mindsdb-docs/docs/deployment/linux.md
- docs/mindsdb-docs/docs/deployment/source.md
- docs/mindsdb-docs/docs/deployment/windows.md
Fixes #1487 1487
- Updated all references to 3.6.x to 3.7.x within the /docs/deployment folder. (Found references that hadn't been updated in source.md and linux.md in addition to the referenced windows.md in the issue.)
mindsdb
> Remove 3.6.x from docs

- docs/mindsdb-docs/docs/sql/tutorials/mindsdb-superset-snowflake.md
Fixes #1729
- Fix PREDICTOR query by removing TRAIN keyword:
mindsdb
> Fix CREATE PREDICTOR Query in tutorials

- docker/build.py
- docker/dockerfile_beta.template
- docker/dockerfile_release.template
This is a small change for container creation in Docker. **build.py** will create the following types of containers:
* Release: Statically created image to retain all transitive dependencies at the time of creation. MindsDB will not attempt to update on every startup. The PyTorch and MindsDB image is anchored to a specific version on build.
* Beta: Identical to the old image: PyTorch(latest), MindsDB(latest), Base image upgraded. MindsDB always tries to upgrade at startup.
The change has been small so as not to break previous usage. There is a lot of room for improvement in this process.
> A dirty little change to keep release versions pinned

- docs/mindsdb-docs/docs/deployment/docker.md
Fixes #
Currently the default docker for mac allocates 2GB of memory which is insufficient to run the mindsdb docker container. The process would fail with a cryptic "KILLED" message.
To rectify this, Docker for Mac users should bump their allocated memory to at least 4GB. 
This PR adds a note to users to do so before installation
mindsdb
> docs(docker): add instructions for docker for mac

- .gitignore
Fixed issue #1731.
This commit is to add VS Code statements in the .gitignore file because
many developers currently use the IDE VS Code (https://code.visualstudio.com/)
Signed-off-by: Geunsik Lim <leemgs@gmail.com>
> Added VScode case in .gitignore

- docs/mindsdb-docs/docs/databases/MariaDB.md
The database name may not be the default `mindsdb` (and the parameter seems supported).
> For completeness sake add database parameter

- mindsdb/utilities/functions.py
`import  mindsdb` for MindsDB 2.57.0 is broken in Google Colab.
```
usage: ipykernel_launcher.py [-h] [--api API] [--config CONFIG] [--verbose]
[--no_studio] [-v] [--ray]
ipykernel_launcher.py: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-86875774-eea9-43df-8fac-d91f2925addb.json
An exception has occurred, use %tb to see the full traceback.
SystemExit: 2
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```
`get_ipython().__class__.__name__` returns just `Shell` there.
This check should cover more possible notebooks.
Fixes #659
Fixes #922
Ordinary `ipython` in terminal.
```
In [2]: get_ipython().config
Out[2]: {}
``` …
> Unbreak `import mindsdb`on Google Colab

- mindsdb/interfaces/model/model_controller.py
- mindsdb/interfaces/model/model_interface.py
Fixes 
`rename` endpoint returns next error:
```
"'ModelInterface' object has no attribute 'rename_model'"
```
Fix it by implementing this method
> Fix 'rename predictor' endpoint

- docs/mindsdb-docs/mkdocs.yml
Fixes #1783
- Renamed AI-powered forecasts in Apache Superset and Snowflake to AI powered forecasts with MindsDB in [mkdocs.yml](https://github.com/mindsdb/mindsdb/blob/staging/docs/mindsdb-docs/mkdocs.yml#L89)
> Changed long tutorial name

- mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
Fixes #1754
- update the [file](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py). A backslash is added before the backquote to identify the backquote
> New PR -Error when integration name contains space

- mindsdb/integrations/__init__.py
- mindsdb/integrations/trinodb/trinodb.py
- mindsdb/interfaces/datastore/datastore.py
- requirements.txt
This PR adds TrinoDB as a supported datasource and upgrades the version of datasources to the latest. 
:information_source: Merge this after https://github.com/mindsdb/datasources/pull/59 PR, so mindsdb can install latest daasources from pypi :information_source: .
> Add trinods

- .github/workflows/mindsdb.yml
- .github/workflows/release.yml
This PR moves the docker deploy step to releases workflow so it runs after the create_version_file for prod.
> Move docker deploy to releases

- docker/build.py
Fixes #1876.
This will tag each image as mindsdb:latest and mindsdb:version and push to Dockerhub
> Tag containers and push

- mindsdb/api/mongo/responders/find.py
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
- mindsdb/interfaces/model/model_controller.py
Confidence bounds will *not* be presented to the user at all when they are missing from the model's predictions (rather than being replaced by `None`)
> Make confidence bound optional

- docs/mindsdb-docs/docs/deployment/docker.md
Added MySQL port to the docker run command and wrote a note to hint about any other DB ports. 
Added MySQL port to the tutorial as it shows in the next step to connect to the MySQL and it this step doesn't give any hint of opening the MySQL port. 
This is related to the issue https://github.com/mindsdb/mindsdb/issues/1947
mindsdb
> Added the mysql port to docker run command

- mindsdb/interfaces/model/model_controller.py
I was not able to JOIN an MLflow BYOM predictor, had a BAD REQUEST that indicated wrong payload formatting?
So, this PR slightly changes the payload to use pandas directly and to specify the content-type as `'application/json; format=pandas-records'`, which seems to do the trick.
> Fix: mlflow integration JOIN support

- helm/README.md
- helm/mindsdb/.helmignore
- helm/mindsdb/Chart.yaml
- helm/mindsdb/templates/NOTES.txt
- helm/mindsdb/templates/_helpers.tpl
- helm/mindsdb/templates/deployment.yaml
- helm/mindsdb/templates/hpa.yaml
- helm/mindsdb/templates/http-service.yaml
- helm/mindsdb/templates/ingress.yaml
- helm/mindsdb/templates/mongodb-service.yaml
- helm/mindsdb/templates/mysql-service.yaml
- helm/mindsdb/templates/serviceaccount.yaml
- helm/mindsdb/templates/tests/test-connection.yaml
- helm/mindsdb/values.yaml
Fixes #2053 
- added the helm chart for `mindsdb`
- helm chart consists of 1 `Deployment`, 3 `Services` and 1 `Ingress`
- exposes 3 services, by default, can be enabled or disabled
> added helm chart

- mindsdb/api/http/namespaces/sql.py
for listing the tree of databases on mindsdb, specially for the GUI
Endpoint 
/list_databases
returns an object equivalent to: 
`SHOW DATABASES` + `SHOW TABLES FROM {_each_database_}'`
In an object form as: 
```{
"data": [
{
"name": "information_schema",
"tables": []
},
{
"name": "mindsdb",
"tables": [
[
"predictors"
],
[
"commands"
],
[
"databases"
]
]
},
{
"name": "files",
"tables": []
},
{
"name": "views",
"tables": []
},
{
"name": "example_db",
"tables": []
}
],
"type": "ok"
}```
mindsdb
> created list_databases endpoint 

- mindsdb/api/http/namespaces/predictor.py
- mindsdb/interfaces/model/model_controller.py
- tests/integration_tests/flows/test_http.py
- Fix test to be consistent with SDK usage
- Support predictor renaming based on `name` arg pased via API endpoint
- Fix wrong key retrieval inside `import`
> Fixes to import/export predictor

- mindsdb/interfaces/database/database.py
Fixed "registered" and "unregistered" were spelled incorrectly in 3 error messages.
They seem to be correct everywhere else.
> Corrected "registered" spelling in error messages

- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
Fix typo in error message.
Old: Only one field can be in 'OPRDER BY'
New: Only one field can be in 'ORDER BY'
> Fix typo in error: Only one field can be in 'ORDER BY'

- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
This trivial change makes the engine name lovercase before passing it to `answer_create_datasource()`. So a statement like this now works (at least in my tests):
```
CREATE DATABASE ... WITH ENGINE='MariaDB' ...
```
> Make CREATE DATABASE ENGINE case-insensitive

- helm/README.md
Fixes #
- Helm Readme typo: seperate -> separate
mindsdb
> docs(helm readme): fix typo seperate -> separate

- docs/mindsdb-docs/docs/sql/create/predictor.md
Fixed typo in the sql create predictor documentation [here](https://github.com/mindsdb/mindsdb/blob/staging/docs/mindsdb-docs/docs/sql/create/predictor.md)
Details:
- Corrected `traning` to `training`
> Fixed typo for SQL SELECT syntax description

- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
To enable live anomaly detection from queries that filter to the most recent known data point (i.e. `WHERE T = LATEST`).
* Rename `__mdb_make_predictions` to `__mdb_forecast_offset`. For more details, see [here](https://github.com/mindsdb/lightwood/pull/894).
* Set appropriate offset in the respective column, and pass modified DF to lightwood as before.
NOTE: will only pass once # is merged into lightwood staging
NOTE: the new changes in lightwood mean that now `WHERE T = LATEST - K` would also be possible, but this is not implemented in this PR because it's likely not a useful behavior.
> Handle T = Latest syntax for TS predictors

- docs/mindsdb-docs/docs/sql/tutorials/bodyfat.md
This PR replaces the incorrect paths for images for the above-said tutorial.
Fixes #2292 
-` /sql` was added to the path of the images so that they load correctly on the web page
> Issue 2292 : Updating correct image paths for Determining Body Fat Percentage Tutorial

- docker/README.md
Otherwise `docker build` caches last run and doesn't check URL for newest release version.
> docker: Add `--no-cache` to force `pip install`

- mindsdb/integrations/libs/base_handler.py
Fixes minor typo (`INTSERT` => `INSERT`)
> Fix minor typo (`INTSERT` => `INSERT`)

- docs/mindsdb-docs/docs/sql/tutorials/byom.md
- mindsdb/__main__.py
- mindsdb/api/mongo/responders/list_collections.py
- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/join_utils.py
- mindsdb/interfaces/model/model_controller.py
- tests/integration_tests/flows/test_http.py
- tests/prediction_latency_test/README.md
There are small typos in:
- docs/mindsdb-docs/docs/sql/tutorials/byom.md
- mindsdb/__main__.py
- mindsdb/api/mongo/responders/list_collections.py
- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/join_utils.py
- mindsdb/interfaces/model/model_controller.py
- tests/integration_tests/flows/test_http.py
- tests/prediction_latency_test/README.md
Fixes:
- Should read `compatibility` rather than `compatibiltiy`.
- Should read `somewhere` rather than `somethere`.
- Should read `retrieval` rather than `retrival`.
- Should read `handler` rather than `hanlder`.
- Should read `deprecated` rather than `deprected`.
- Should read `database` rather than `databaes`.
- Should read `accessible` rather than `accesible`.
Semi-automated pull request generated by …
> docs: Fix a few typos

- docker/release
Removed from default `requirements.txt` here https://github.com/mindsdb/lightwood/pull/897/files
> docker: `prophet` is no longer a part of the image

- mindsdb/integrations/handlers/cockroach_handler/README.md
- mindsdb/integrations/handlers/cockroach_handler/__about__.py
- mindsdb/integrations/handlers/cockroach_handler/__init__.py
- mindsdb/integrations/handlers/cockroach_handler/cockroach_handler.py
- mindsdb/integrations/handlers/cockroach_handler/requirements.txt
- mindsdb/integrations/handlers/cockroach_handler/tests/test_cockroachdb_handler.py
This PR adds a new handler for connecting to CockroachDB that as an initial handler extends the PostgreSQL one since CockroachDB is wire-compatible with PostgreSQL.
> Add CockroachDB handler

- requirements.txt
This PR adds cliclhouse-driver in the main requirements #2569 . For now, by default install dependencies for : 
- MySQL, MariaDB, SingleStore (mysql client)
- PostgreSQL,CockroachDB, CKAN, Questdb (psycopg)
- ClickHouse(clickhouse-driver)
> Add CH driver to requirements

- README.md
- docker/README.md
- docs/mindsdb-docs/docs/sql/tutorials/bitcoin-forecasting.md
- docs/mindsdb-docs/docs/sql/tutorials/crop-prediction.md
- docs/mindsdb-docs/docs/sql/tutorials/heart-disease.md
- docs/mindsdb-docs/docs/sql/tutorials/mindsdb-superset-snowflake.md
- docs/mindsdb-docs/docs/sql/tutorials/mushrooms.md
Fixes #
fix broken links for Docker, PyPI and mindsdb-cloud in the following pages -
README files
and
https://docs.mindsdb.com/sql/tutorials/bitcoin-forecasting/
https://docs.mindsdb.com/sql/tutorials/crop-prediction/
https://docs.mindsdb.com/sql/tutorials/heart-disease/
https://docs.mindsdb.com/sql/tutorials/mushrooms/
https://docs.mindsdb.com/sql/tutorials/mindsdb-superset-snowflake/
> fix broken links  in mindsdb-docs 

- mindsdb/api/mongo/README.md
- mindsdb/api/mongo/responders/find.py
- mindsdb/api/mongo/server.py
- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py
- mindsdb/integrations/handlers/mongodb_handler/utils/mongodb_parser.py
- mindsdb/integrations/handlers/mongodb_handler/utils/mongodb_render.py
- requirements.txt
- tests/unit/test_mongodb_server.py
Changes:
1. Added key for input modifiers of data from mongo:
```
db.sales_model.find(
{
"collection": "mongo_int.house_sales", 
"query":  { 
"$where": "this.sale_date > latest and this.type = 'house'" 
},
'modifiers': [
{'$unwind': '$hist_data'},
{'$project': {'sale_price': '$hist_data.sale_price', 'saledate': '$hist_data.saledate', 'type': 1}}
]
},
```
2. Return human readable error message
3. fix: "SHOW tables FROM mindsdb" reads list tables from other integrations
> Mongodb handler: unnesting keys in collections

- docs/mindsdb-docs/docs/setup/self-hosted/docker.md
Fixes #2665
- This PR refactors the JSON block in the Docker Docs page to improve the readability for users by splitting the JSON parameters into multiple lines.
> Refactored the JSON block parameters to multiple lines

- mindsdb/integrations/handlers/scylla_handler/README.md
- mindsdb/integrations/handlers/scylla_handler/scylla_handler.py
This PR 
* Fixes #2677 when using secure connect bundle to connect
* Adds default protocol version if not provided
* Makes keystore as optional parameter. Users can switch between keystores using [datasource].[keystore] query.
> Fix Scylla bundle error

- mindsdb/api/mongo/responders/buildinfo.py
Fix: 'predictor' collection does not open in compass  1.32.6
> Fix for compass 1.32.6

- mindsdb/integrations/handlers/scylla_handler/scylla_handler.py
Remove table name from targets otherwise select with targets doesn't work
select  organization_uuid  from astra.table_orgs_predict;
#2700
> Astra fix: remove table name from targets

- mindsdb/integrations/handlers/cassandra_handler/__init__.py
- mindsdb/integrations/handlers/couchbase_handler/__init__.py
- mindsdb/integrations/handlers/datastax_handler/__init__.py
- mindsdb/integrations/handlers/datastax_handler/datastax_handler.py
- mindsdb/integrations/handlers/db2_handler/__init__.py
- mindsdb/integrations/handlers/scylla_handler/__init__.py
Enables creating astra handler using url for secure bundle
` "secure_connect_bundle": {"url":  '...'}`
It's enabled by exposing connection_args property of handler
The same change done in handlers:
- scylla
- db2
- couchbase
- cassandra
> Expose connection_args of handlers

- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
- mindsdb/integrations/handlers/ludwig_handler/ludwig_handler.py
- mindsdb/integrations/handlers/mlflow_handler/mlflow_handler/mlflow_handler.py
- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
- mindsdb/integrations/libs/base_handler.py
For API consistency, this PR removes the old experimental `select_into()` method and its usage within `PredictiveHandler.select_into()`.
> Handlers - Remove select_into()

- docs/mindsdb-docs/docs/sql/create/databases.md
- mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
- mindsdb/integrations/handlers/trino_handler/trino_handler.py
Fixes #
- add http_scheme and basic auth (password) to trino handler/integration
- fix engine name in the document
sample config with http_scheme and basic auth
```
CREATE DATABASE trino_datasource
WITH ENGINE='trino',
PARAMETERS={
"user": "trino_user",
"http_scheme": "https",
"port": 443,
"password": "trino_password",
"host": "trino_host",
"catalog": "trino_catalog",
"schema": "trino_schema"
};
```
> Trino ldap

- docs/mindsdb-docs/docs/connect/dbeaver.md
- docs/mindsdb-docs/docs/connect/dbt.md
- docs/mindsdb-docs/docs/connect/mysql-client.md
- docs/mindsdb-docs/docs/connect/sql-alchemy.md
- docs/mindsdb-docs/docs/index.md
Fixes #
- Changed `cloud-mysql.mindsdb.com` to `cloud.mindsdb.com` following error from a GUI client: Dbeaver ( `unable to read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.`)
-  I noticed the `Mindsdb Cloud Username` is the same as the `email address` so I pointed that out with a comment. 
- Then, adding a note on the behaviour of Sqlalchemy `create_engine` to the documentation
> Changed `cloud-mysql.mindsdb.com` to `cloud.mindsdb.com`

- docs/mindsdb-docs/docs/connect/mysql-client.md
Fixes #2972
-Changing MindsDB hostname values from cloud-mysql.mindsdb.com to cloud.mindsdb.com
mindsdb
> Changing MindsDB hostname values

- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- tests/unit/executor_test_base.py
- tests/unit/test_executor.py
Fix of bug:
- If datasource is file with column contents number (year)
- And created predictor by this column
- Using of predictor caused and error:
'>' not supported between instances of 'numpy.ndarray'
mindsdb
> TS filter: accept float in order field

- mindsdb/interfaces/database/integrations.py
- tests/integration_tests/flows/test_mysql_api.py
- tests/unit/test_executor.py
Unable to drop if:
- is system database ('files', 'views', 'lightwood') 
- linked predictors exist
#2930
> Drop database fix

- docs/mindsdb-docs/docs/sql/create/view.md
Fixes #2948
-Remove AS {name} from all the CREATE PREDICTOR commands
mindsdb
> Remove AS {name} from all the CREATE PREDICTOR commands

- docs/mindsdb-docs/docs/contribute/integrations.md
While working on a new database handler, came across a minor typo in the docs for building integrations. Minor change.
- fixed a minor typo in docs
mindsdb
> minor: fix typo in docs/contribute/integrations

- docs/mindsdb-docs/docs/sql/tutorials/process-quality.md
Remove "AS quality" from Process Quality Tutorial
Fixes #3080
-Remove AS {name} from Process Quality Tutorial
mindsdb
> Remove AS {name} from Process Quality Tutorial

- docs/mindsdb-docs/docs/tutorials.md
Adding "MindsDB: Your introduction to creating machine learning predictive models." to list of centralized community tutorials
Fixes #3095
-Referencing community tutorial from chandrevdw31
mindsdb
> Referencing community tutorial from chandrevdw31

- mindsdb/integrations/handlers/hana_handler/hana_handler.py
`HANAHDBCLIDialect` already includes a method for getting columns from a table, this could be a cleaner way.
> [minor] Use SAP HANA Dialect Implementation for `get_columns()`

- README.md
- mindsdb/integrations/handlers/hana_handler/README.md
- mindsdb/integrations/handlers/hana_handler/hana_handler.py
- mindsdb/integrations/handlers/hana_handler/requirements.txt
- mindsdb/integrations/handlers/hana_handler/tests/test_hana_handler.py
- Adds SAP HANA handler documentation and features it on the main README
- Fixes the test config and requirement version pins for reproducibility (invalid package versions added earlier inadvertently)
> [docs] Add SAP HANA Handler Documentation

- mindsdb/__main__.py
- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
Fixes #3297
- As mentioned in the issue, the ` select_data_query` field is of Ordered Dict type.
- lightwood handler fails to insert *Predictor record* as `fetch_data_query` field expects string instead of dict. Refer here for[DB column data type](https://github.com/mindsdb/mindsdb/blob/2dcf36340fb4791ebfd1417db5f5819744fa828b/mindsdb/interfaces/storage/db.py#L93) and [query that's sent as Ordered dict instead of string](https://github.com/mindsdb/mindsdb/blob/2dcf36340fb4791ebfd1417db5f5819744fa828b/mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py#L292)
- The fix converts the dict datatype to string
> Fixes MongoAPI for adding predictor

- docker/docker-compose.yml
- mindsdb/__main__.py
- mindsdb/migrations/migrate.py
Fixes [50](https://github.com/mindsdb/mindsdb_private/issues/50)
- Migration runs in a separate container
- This behavior managed by specifying/non-specifying SEPARATE_MIGRATIONS env variable
- mindsdb container and migration container use same MINDSDB_STORAGE_DIR (which is mindsdb_repo_root_dir/var by default)
> docker-compose: run migrations in a separate container

- .flake8
- .pre-commit-config.yaml
- requirements-dev.txt
Fixes #3300
- Added flake8 config, pre-commit config
- Added black, isort, flake8, and other checkers which will automatically scan and fix issued in code being committed/pushed to the repository. 
- This will only run on files being changed on someone's local environment
- Devs can by pass it with flag `--no-verify` in their commit. To enforce compliance we will have to run these same checks in a PR code integration pipeline.
- What are mindsdb repo norms? We will have to codify those in these configs
- How do we want to deal with old files and code and configs breaking these norms? 
mindsdb
> Setup pre-commit hooks. Fixes #3300

- docs/mindsdb-docs/docs/getting-started.md
This seems related to #2595 and #2608 although those have been long-since closed.
- While I was setting up a new machine, I noticed that the Docker and Pip links were broken in getting-started, but not in quickstart. Did a quick search to see if there was any issues or PRs related, but couldn't find any, so here's a quick PR to fix those links. :)
- docs/mindsdb-docs/docs/getting-started.md contained an old link for Docker that appears to no longer exist (/deployment/docker), and the link for Pypi was missing the leading forward slash resulting in a 404 from the docs attempting a relative path instead of absolute.
mindsdb
> Fixed broken links for Docker and Pip in getting-started.

- mindsdb/integrations/handlers/cockroach_handler/tests/test_cockroachdb_handler.py
- mindsdb/integrations/handlers/db2_handler/tests/test_db2_handler.py
- mindsdb/integrations/handlers/firebird_handler/tests/test_firebird_handler.py
- mindsdb/integrations/handlers/informix_handler/tests/test_informix_handler.py
- mindsdb/integrations/handlers/matrixone_handler/tests/test_matrixone_handler.py
- mindsdb/integrations/handlers/mlflow_handler/tests/test_mlflow_handler.py
- mindsdb/integrations/handlers/monetdb_handler/tests/test_monetdb_handler.py
- mindsdb/integrations/handlers/mssql_handler/tests/test_mssql_handler.py
- mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
- mindsdb/integrations/handlers/questdb_handler/tests/test_questdb_handler.py
- mindsdb/integrations/handlers/singlestore_handler/tests/test_singlestore_handler.py
- mindsdb/integrations/handlers/supabase_handler/tests/test_supabase_handler.py
- mindsdb/integrations/handlers/trino_handler/tests/test_trino_handler.py
- mindsdb/integrations/handlers/vertica_handler/tests/test_vertica_handler.py
- mindsdb/integrations/handlers/yugabyte_handler/tests/test_yugabyte_handler.py
Fixes #
This constitute a clean up of the unit tests written for the database handlers. This involves fixing wrong import paths, and missing dictionary keys (most of the test didn't include the `connection_data` key even though it was written in the handler!).
> Cleaned up handler tests

- docker/mindsdb.Dockerfile
- docker/release
- mindsdb/integrations/handlers/snowflake_handler/requirements.txt
Fix error:
ImportError: cannot import name '_rfc_1738_quote' from 'sqlalchemy.engine.url'
If snowflake version is 1.4.2 and sqlalchemy version is 1.4.42
> Up snowflake version to 1.4.3

- README.md
Fixes # 3848 
Issue Link: https://github.com/mindsdb/mindsdb/issues/3848
-  At readme File, In support Section
highlighted link was redirecting to https://github.com/mindsdb/mindsdb/issues link.
It should be redirecting to following link: https://github.com/mindsdb/mindsdb/issues/new/choose
So I have updated it.
mindsdb
> Update issue link in README

- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- tests/unit/test_executor.py
If TS predictor was created without group_by and prediction is using LATEST it returns error:
`error in apply predictor step: 'NoneType' object is not iterable`
> Fix latest without group

- mindsdb/interfaces/database/integrations.py
- mindsdb/interfaces/storage/db.py
Changed check for deleting of predictor: 
- predictor is deleted when deleted_at!=null
> Fix: unable to drop database linked to predictor

- mindsdb/integrations/handlers/file_handler/file_handler.py
The file handler was sampling (128*1024) bytes and using that data to identify the csv dialect. 
For the spam dataset that was not enough. changed to (256 * 1024)  and that solved the issue. 
*(provide a reason in case of NO, see PR guidelines topic)*
PR guidelines still in progress. 
*(link to the appropriate ticket if documentation have to be changed, but it couldn’t be done in this PR by some reason)*
It doesn't need to update any docs. 
*(link to the appropriate ticket if tests have to be changed, but it couldn’t be done in this PR by some reason)*
It doesn't 
*(link to the appropriate ticket if tests have to be created, but it couldn’t be done in this PR by some reason)*
Potentially we could add the SPAM dataset to a test. 
Yes. 
*(in case then big feature have been decomposed to …
> Added more bytes to sample read to identify csv dialect

- .github/workflows/mindsdb.yml
- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/project_datanode.py
- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
- mindsdb/integrations/libs/ml_exec_base.py
- requirements.txt
- tests/unit/test_predictor_params.py
New syntax:
- select * from predictor1 where a=1 using b=2
- select * from table join predictor1 where a=1 using b=2 
Access to params in ML handler:
```
def predict(self, df, args=None):
print(args['predict_params'])
```
#4016
> Pass parameters to predictor at prediction stage

- docs-v2/mint.json
- Adds MindsDB's GTM ID to `mint.json` to enable GTM in Mintlify Docs.
- Mintlify will automatically add the GTM script with the tag ID on all the pages after this is merged in.
mindsdb
> Enable Google Tag Manager

- docs/mint.json
Uses Slack invite permalink instead of the invitation itself.
Also deleted GA tracking code that was accidentally included.
mindsdb
> Use redirect Slack invitation

- tests/unit/executor_test_base.py
Changed multiproccession to multithreading for unit tests for executor. 
It helps to do mocking in data hanlder that are using in subprocess (for example extracting data for training)
> Mock multiprocessing to multithreading

- docs/setup/self-hosted/pip/macos.mdx
Add macOS installation docs for `libomp` as a required library for LightGBM
Fixes #https://github.com/mindsdb/mindsdb/issues/3965
> Libomp in macOS docs

- mindsdb/interfaces/storage/db.py
- mindsdb/migrations/versions/2022-10-14_43c52d23845a_projects.py
- mindsdb/migrations/versions/2022-12-26_459218b0844c_fix_unique_constraint.py
We had doubled db constraints names 'unique_integration_name_company_id': in `project` and `integration` tables. 
Constraint renamed in old migration. Added new migration to rename constraint in existing databases (with try/catch for who install mindsdb from scratch)
> fix unique constraint

- mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
Bugfix: createing hf translation model trows error "Not expected parameters: lang_input"
[#4187](https://github.com/mindsdb/mindsdb/issues/4187)
- [X ] 🐛 Bug fix (non-breaking change which fixes an issue)
> Bugfix: create hf translation model 

- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py
Enables support for overriding automatically inferred data types when using the Lightwood handler.
If the user provides:
```sql
CREATE ...
USING 
dtype_dict = {
'col1': 'type',
...
};
```
The handler will extract this mapping and use it to build a modified problem definition, which will trigger the default encoder belonging to each new `dtype` (note: manually specifying encoders is out of scope for this PR and will be added at a later date).
> [ENH] Override dtypes - LW handler

- tests/README.md
Reformatting tests/README.md file. The reason for this was the current version has points 1.2, 1.3, and 1.4 on the single line. 
**Fixes** #4305 
- [X ] 📄 This change requires a documentation update
Reformatting the md file
- [ X] My code follows the style guidelines(PEP 8) of MindsDB.
- [ X] I have updated the documentation, or created issues to update them.
> updated tests/readme formatting as 1.2,1.3,1.4 were on single line

- docs/mint.json
A previous documentation update was not able to deploy because the `mint.json` was not valid. This PR fixes the invalid properties so deployments will continue to work
Fix the `auth.method` and removed `colors` that have been deprecated
> [Docs] Update to valid mint.json

- docs/data-integrations/all-data-integrations.mdx
Removed the service_name from the docs as the parameter is not allowed by oracle.
**Fixes** #(4327)
Deleted the document and thus it changes
> Worked on #4327 as it was instructed by the maintainer

- mindsdb/integrations/libs/ml_exec_base.py
Adding # noqa to docstring at top of ml_exec_base.py
Linter will ignore docstring
> Ignore docstring in ml_exec_base.py with noqa

- mindsdb/api/mysql/mysql_proxy/controllers/session_controller.py
- mindsdb/api/mysql/mysql_proxy/executor/executor.py
- mindsdb/api/mysql/mysql_proxy/executor/executor_client.py
Since there is another logic to save context (current database in particular) in REST API comparing with MySQL API, microservice mode couldn't do it.
> Microservice mode: save context in REST API

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
This PR extends the support for most (but not all) OpenAI text completion parameters.
Already supported params:
- max_tokens
- temperature
Introduced in this PR:
- top_p
- n
- stop
- presence_penalty
- frequency_penalty
- best_of
- logit_bias
- user
For example:
```sql
SELECT input, completion
FROM mindsdb.openai_test
WHERE input = 'Write an essay on your favourite subject'
USING
max_tokens=200,
stop=["debate"];  -- this stops the completion as soon as "debate" is generated
```
Refactored some bits of logic in the handler, particularly the _submit_completion function but also the compilation of all api_args has been slightly redesigned for cleaner code.
> [ENH] Support for additional OpenAI completion endpoint params

- mindsdb/__main__.py
- mindsdb/integrations/handlers/openai_handler/helpers.py
This PR accounts for when the API key has no token credit left, yielding an informative message when calling an OpenAI model.
Also, added a try-except clause for setting `torch.mp` to `spawn` in the `__main__` process (which is helpful when debugging if this option has already been set).
Small change in the exponential backoff decorator to check for `insufficient_quota` in the provided error.
> [fix] raise Error if OpenAI API key has exceeded current quota

- mindsdb/integrations/handlers/aurora_handler/__about__.py
- mindsdb/integrations/handlers/aurora_handler/__init__.py
- mindsdb/integrations/handlers/aurora_handler/aurora_handler.py
- mindsdb/integrations/handlers/aurora_handler/requirements.txt
- mindsdb/integrations/handlers/aurora_handler/tests/test_aurora_handler.py
I have implemented the new integration for Amazon Aurora. I have not been able to perform any testing as I don't really have access to an AWS account.
Amazon Aurora comes in two flavors: a MySQL compatible version and a PostgreSQL compatible version. This integration makes use of the relevant handlers that have already been implemented for these RDBMSs.
It uses `boto3` to identify which database engine that the database cluster is running and then instantiates the relevant handler. For this purpose, users will be required to pass in their AWS access key and secret access key. However, this can be simplified by getting the users to pass in the name of the database engine as a parameter. 
@ZoranPandovski What are your thoughts on this?
I am somewhat confident that this integration will …
> Amazon Aurora Integration

- mindsdb/interfaces/jobs/jobs_controller.py
- mindsdb/interfaces/storage/db.py
- mindsdb/migrations/versions/2023-02-02_b6d0a47294ac_jobs.py
Fix: jobs executor not using project and execute every query in mindsdb project
> Jobs manage: fix working with projects

- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py
Enables problem definition overriding for lightwood handler.
Can now do something like:
```sql
CREATE MODEL 
mindsdb.home_rentals_model
FROM example_db
(SELECT * FROM demo_data.home_rentals)
PREDICT rental_price
USING
problem_definition={'use_default_analysis': False};
```
> [fix] override problem definition in lightwood handler

- docs/connect/sql-alchemy.mdx
Adds community tutorial links to the Using MindsDB via SQL API -> Connect to MindsDB -> Other SQL Clients -> SQL Alchemy page.
**Fixes** #(4481)
Add community tutorial links to the Using MindsDB via SQL API -> Connect to MindsDB -> Other SQL Clients -> SQL Alchemy page.
> add tutorial links #4481

- docs/using-mongo-api/regression.mdx
This PR adds a community tutorial link to the Mongo API regression page.
**Fixes** #(issue) #4564
To implement this feature, I added the community tutorial link to the appropriate location in the Mongo API regression page (regression.mdx).
I have read the CLA Document and I hereby sign the CLA.
> [Docs] Add community tutorial link to Mongo API regression page (#4564)

- mindsdb/integrations/handlers/duckdb_handler/duckdb_handler.py
Added missing renderer instance variable in the DuckDB handler.
**Fixes** #4609
- `SqlalchemyRender('postgres')` added as the renderer.
> Add missing renderer instance variable

- mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
In last pandas (1.5.3) there may appear recursion error https://github.com/pandas-dev/pandas/pull/45749
The error should be fixed in pandas long time ago, but looks like appear again
> fix for recursion in pandas

- mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
At the start of model training we need to check if user already has model in 'training' status. We need to prevent user from starting training too frequently 
> fix filter for starting model training

- docs/mint.json
- docs/sql/tutorials/regression-community.mdx
Created a doc page to contain the community tutorial links (Tutorials -> Regression -> Tutorials by Our Community)
**Fixes** #4729
This feature was implemented by following instructions outlined in https://github.com/mindsdb/mindsdb/issues/4729
> [Docs] doc page for community tutorial links

- mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
This PR adds schema as an optional parameter to the psql connection. If the `schema` is provided, it will be used as a default alongside `public`. If not, only the public is used by default.
**Fixes** #4659
> Add schema as a param to Postgres connection

- docs/data-integrations/amazon-redshift.mdx
Fixes parsing error present on the Amazon Redshift documentation page.
**Fixes** #4761 
Removed the `<br>` tag that was causing the parsing issue.
> Fix parsing error on amazon redshift docs page

- mindsdb/integrations/handlers/cloud_spanner_handler/README.md
This PR updates the Readme page of the Cloud Spanner Handler.
**Fixes** #4724 
This will add a new `NOTE` section at the end of the Readme page of Cloud Spanner Handler containing a list of all the unsupported PostgreSQL features.
> Updated Readme with the unsupported PostrgreSQL features

- docs/mint.json
Mintlify is renaming the mint.json `openApi` property to `openapi`. This PR ensures your OpenApi file will continue updating after we deprecate the old syntax.
> Rename openApi to openapi in mint.json

- mindsdb/integrations/handlers/d0lt_handler/requirements.txt
The `d0lt` handler has been implemented by inheriting from the the `matrixone` handler. The only dependency for the `matrixone` handler is the `pymysql` package,
As the `d0lt` implementation is inheriting from this handler, the only dependency for it should also be `pymysql`, however, the previous dependency listed for it was `mysql-connector-python`.
This has been fixed by adding the correct dependency and the logs stating that the handler cannot be used (https://github.com/mindsdb/mindsdb/issues/4548) are no longer visible,
> Fixed Dependencies for the d0lt Handler

- mindsdb/integrations/handlers/trino_handler/requirements.txt
The `pyhive` package which is used in the implementation of the `trino` handler was not included in the `requirements.txt` file. As a result, the trino handler was unusable. This has been fixed.
> Fixed Dependencies for the trino Handler

- mindsdb/integrations/handlers/aurora_handler/requirements.txt
- mindsdb/integrations/handlers/cloud_sql_handler/requirements.txt
- mindsdb/integrations/handlers/cockroach_handler/requirements.txt
- mindsdb/integrations/handlers/mysql_handler/requirements.txt
- mindsdb/integrations/handlers/opengauss_handler/requirements.txt
- mindsdb/integrations/handlers/orioledb_handler/requirements.txt
- mindsdb/integrations/handlers/postgres_handler/requirements.txt
- mindsdb/integrations/handlers/questdb_handler/requirements.txt
- mindsdb/integrations/handlers/supabase_handler/requirements.txt
- mindsdb/integrations/handlers/timescaledb_handler/requirements.txt
The following dependency requirements have been resolved below,
- The `docker` dependency has been removed from the MySQL as it has not been used anywhere. The same requirement has been removed from two other handlers that use this handler: Amazon Aurora and Google Cloud SQL
- The `psycopg[binary]` dependency in the Postgres handler and all other handlers that inherit from it has been updated as the version specified does not seem to exist as mentioned here: https://github.com/mindsdb/mindsdb/issues/4555. I have tested out the Postgres handler with the new version of the dependency by spinning up a Docker container and it seems to be working fine.
> Fixed Dependencies in MySQL and Postgres Handlers

- mindsdb/integrations/handlers/file_handler/file_handler.py
- requirements.txt
This PR resolves #4747 by adding the missing dependency installed in the old version by mindsdb_datasources. Also, the 
type guessing for xlsx, xsl files was not working as expected, and sometimes the file type was guessed as CSV so the data wasn't displayed correctly
**Fixes** #4747, #4912
>NOTE: We should simplify the guessing type and re use the py magic for all file types.
Install missing openpyxl library and use pythohn-magic for file guessing type.
> Simplify file name detection

- docs/nlp/question-answering-inside-mysql-with-openai.mdx
Changed the values of `title` and `sidebarTitle` to read as follows:
`title: Question Answering with MindsDB and OpenAI using SQL 
sidebarTitle: Question Answering using SQL
`
**Fixes** #5006
> [Docs] Updated title of the MySQL Question Answering tutorial

- mindsdb/api/http/namespaces/tab.py
- tests/integration_tests/flows/test_http.py
#1169
**Fixes** #1169
Current version of `tabs` api ignore `company_id` parameter. This PR fixes it.
> [Bug]1169: Improve tab storage

- docker/mindsdb.Dockerfile
This PR resolves the error with the Docker image about missing libmagic dependency
**Fixes** #5072 
> Install missing dependency

- mindsdb/integrations/handlers/twitter_handler/twitter_handler.py
This PR adds:
1. a check to the twitter connection args, raising an explicit error when inserts are tried with a read-only connection.
2. a simple mechanism to pick initialization arguments from the environment variables if they're left unspecified.
> Twitter integration small fixes

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
This PR adds support for the image endpoint that OpenAI offers in their API. This grants access to the DALL-E family of models.
Refactored the handler so that a first check is performed at prediction time: either an image endpoint request, or a text (normal or chat) completion. Added new methods to generate the `Image.create` call.
> [feat] OpenAI image endpoint

- docs/sql/feature-eng.mdx
- Fix table formatting in feature-eng.mdx tabs by adding table structure instead of using markdown table
**Fixes** #(4130)
The table tags are rendered directly instead of converting the markdown table.
> fix: Table formatting in feature-eng.mdx (#4130)

- docs/mint.json
Add the singlestore.mdx file to docs navigation.
This allows navigation to that page inside the documentation.
**Fixes** #5315 
The "data-integrations/singlestore" page was included in the `docs/mint.json` file.
> Add singlestore.mdx file to docs navigation

- docs/data-integrations/DynamoDB.mdx
The DynamoDB.mdx file had a small error that caused a parsing error. The issue consisted of a `<br>` not being closed correctly. 
**Fixes** #5385 
The `<br>` was  changed to `<br/>` which now allows the page to be rendered correctly.
> solved 5385-parsing error in the docs

- docs/setup/self-hosted/pip/windows.mdx
This step resolves the encoding error on Windows systems with default encoding standards other than UTF-8.
Added a step in the Windows installation guide to solve a Windows system's common encoding issue.
**Fixes** #5478 
Added a step for users to enable the beta feature of windows, which allows the system to use the UTF-8 encoding standard.
> Added a step in Windows installation guide

- docs/setup/self-hosted/pip/linux.mdx
- docs/setup/self-hosted/pip/macos.mdx
- docs/setup/self-hosted/pip/source.mdx
- docs/setup/self-hosted/pip/windows.mdx
Added instructions of how to run `mongodb` API in the docs in setup via `pip`
Fixes #5544
> docs: added instructions to start mongodb api

- mindsdb/integrations/handlers/neuralforecast_handler/README.md
- mindsdb/integrations/handlers/neuralforecast_handler/neuralforecast_handler.py
- mindsdb/integrations/utilities/time_series_utils.py
- tests/unit/ml_handlers/test_neuralforecast.py
Implement hierarchical reconciliation for Nixtla's Neuralforecast handler.
We added hierarchical reconciliation using a similar method to the Statsforecast handler.
Also added a new unit test and updated the describe method.
```
CREATE MODEL 
mindsdb.nf_hier
FROM example_db
(SELECT * FROM demo_data.house_sales)
PREDICT ma
ORDER BY saledate
GROUP BY type, bedrooms
-- as the target is quarterly, we will look back two years to forecast the next one
WINDOW 8
HORIZON 4
USING engine='neuralforecast', train_time=0.01, hierarchy=['type', 'bedrooms']
;
```
```
SELECT m.saledate as date, m.ma as forecast
FROM mindsdb.nf_hier as m 
JOIN example_db.demo_data.house_sales as t
WHERE t.saledate > LATEST and t.type='house' and t.bedrooms=4
LIMIT 4;
```
```DESCRIBE mindsdb.nf_hier.model;```
> Hierarchical forecast v2 - integration with Neuralforecast handler

- docs/mint.json
Mintlify recently changed its configuration schema for feedback buttons. The new configuration hides it by default but enables it using
```json
"feedback": {
"suggestEdit": true,
"raiseIssue": true
}
```
Updates the documentation configuration to use the proper schema
> [Docs] Update feedback buttons configuration

- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
- mindsdb/interfaces/storage/fs.py
1. Lightwood may always pull/copy a model even though it may already exists. Can be improved by checking if already exists before copying.
2. Lightwood may repeatedly load the same predictor. Can be improved by caching. 
We are currently using these changes in our production servers. It has cut down predictor times from ~4 seconds down to ~0.03 seconds on the model load and prediction. A massive improvement.
1. Add caching when lightwood grabs the predictor.
2. Perform a rough file size check before attempting to copy
> Cache - Lightwood

- mindsdb/api/http/start.py
- mindsdb/api/mongo/start.py
- mindsdb/api/mysql/start.py
- mindsdb/utilities/functions.py
Add loading of parsers at start of api. Therefore parser won't be loading on first query. That saves about 3s for first query processing.
Added loading of parsers to start of api
> Init lexer parsers on start

- mindsdb/integrations/handlers/github_handler/README.md
- mindsdb/integrations/handlers/github_handler/github_tables.py
Added issue INSERT support to the github_handler #5357.
> Added issue INSERT support to the github_handler

- mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py
Pandas sometimes calls monthly frequency "MS" (month start). 
This was omitted in the first implementation, so it assumed season length of 1 rather than 12 for MS data.
Added row for the new frequency.
> StatsForecast - minor frequency patch

- mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
Adding an optional Postgres connection parameter sslmode to toggle disable/enable encryption. 
Fixing misspellings.
Local Postgres instances are often configured without encryption (e.g. official Postgres docker instances).
Mindsdb only supports encrypted connections to Postgres because of psycopg default.
As a result of psycopg default, Mindsdb fails to connect to a local docker Postgres instance.
Add an optional sslmode connection parameter that can be set to 'disable' for unencrypted Postgres connections.
> Adding an optional Postgres connection parameter sslmode

- mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
- requirements.txt
Changes:
- is not possible to use:
```
create database aa.bb
```
- if you need to create database with '.' in name need to use '`' symbol:
```
create database `aa.bb`
-- for drop:
drop database `aa.bb`
```
Fix #5616
> Fix: only 1 part in create database command

- docs/data-integrations/timescaledb.mdx
Added a semicolon ; at the end of the SELECT query in  <code>docs/data-integrations/timescaledb.mdx</code>
fixes #5802
> added semicolon

- mindsdb/api/mongo/README.md
- mindsdb/api/mongo/responders/delete.py
- mindsdb/api/mongo/responders/find.py
- mindsdb/api/mongo/responders/insert.py
- tests/unit/test_mongodb_server.py
**Create**
`CREATE ml_engine ...` alternative in mongo:
```
db.ml_engines.insertOne({'name': "openai_2", "handler": "openai", "params": {"api_key": "qqq"}})
```
**List**
`SHOW ml_engines` alternative in mongo:
```
db.ml_engines.find()
```
**Delete**
`DROP ml_engine ...` alternative in mongo:
```
db.ml_engines.deleteOne({"name": "openai_2"})
```
resolves #5778
> ML ENGINES in mongo

- docs/setup/self-hosted/docker.mdx
I've simply made one addition to the Docker self-hosting tutorial to mention Docker's `detach` flag. I noticed it when I self-hosted it on AWS and I thought it might be a handy addition.
My writing may not be as documentation-friendly, so I'm open to any language-related changes if required :)
> Updated Docker Self-host Tutorial docker.mdx

- mindsdb/integrations/handlers/byom_handler/README.md
- mindsdb/integrations/handlers/byom_handler/byom_handler.py
- mindsdb/integrations/handlers/byom_handler/proc_wrapper.py
Using:
1. Add args argument to train and predict methods:
```
class CustomPredictor():
def train(self, df, target_col, args=None):
...
def predict(self, df, args=None):
...
```
2. Passing args to model training
``` 
create predictor pred 
from files (select * from byom)
predict Time
using engine='uploaded_model',
param1=1, param2='2'
```
3. Passing args at predict
```
select * from files.byom t 
join pred3 p
using param1=1, param2='2'
```
fixes #5747
> Use args for BYOM

- mindsdb/integrations/handlers/monetdb_handler/monetdb_handler.py
- Change the monetdb_handler.py file
- Closes #5979
- Monetdb handler is comparing the list of result rows with a number which gives an error.
**Fixes** #5979 
- To resolve this, I changed the comparison to the length of result rows with numbers.
> Fix the monetdb handler

- .github/workflows/matrix_includes.json
- setup.py
Now we are having errors in CI because:
- Lightwood 23.5.1.0 requires torch >=2.0.0
- torch 2.0.0 doesn't support python 3.7
Changes in this PR:
- removing python 3.7 support by mindsdb package
- removing python 3.7 in CI workflow
- adding python 3.9 in CI workflow
> Drop 3.7 python support

- mindsdb/integrations/handlers/clickhouse_handler/__about__.py
- mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py
- mindsdb/integrations/handlers/clickhouse_handler/requirements.txt
There was an issue with connecting to Clickhouse.
Set `protocol`  by default to `clickhouse`, any other protocols may be set via `protocol` field in connection params.
> Fix issue with Clickhouse handler

- docs/setup/self-hosted/pip/linux.mdx
This PR updates the python version in `docs/setup/self-hosted/pip/linux.mdx` (A guide for setting mindsdb on Linux locally) to min python `3.8.0`.
For more details regarding the issue, you can visit the following link: `Github Issue` https://github.com/mindsdb/mindsdb/issues/6138
> docs: update python version in docs/setup/self-hosted/pip/linux.mdx

- docs/connect/metabase.mdx
Correct port value in metabase
**Fixes** #6186
> [Docs] Correct port value in metabase #6186 -> Fixed

- docs/data-integrations/ckan.mdx
Solves #6272  required changes made.
Added the `<Tip>
If you installed MindsDB locally via pip, you need to install all handler dependencies manually. To do so, go to the handler's folder (mindsdb/integrations/handlers/ckan_handler) and run this command: `pip install -r requirements.txt`.
</Tip>` in the `ckan.mdx` file at the specified place.
#6272 
Documentation
- [] I have commented my code, particularly in hard-to-understand areas.
> Solves #6272 Updated instructions for ckan.mdx

- docs/connect/mongo-shell.mdx
Updated the Docs to set the proper port number for mongo-shell.
**Fixes** #6297 
Changed to port value to 3306 in mongo-shell documentation
> Correct port value in mongo-shell documentation

- docs/mint.json
these apps (reddit, plaid, google calendar, confluence) were released on April 28th, and on that day I created doc pages to link them in the changelog blog post.
since these are not tested (and reddit does not work in cloud), I remove them from docs navigation for now.
**Fixes** #-
> removed not tested apps from docs navigation

- mindsdb/interfaces/database/projects.py
Change: 
Add model columns to output even if we joining empty dataframe with model
This change is fixing this query:
```
SELECT
sentiment as text
FROM (
SELECT * FROM ( SELECT * FROM mysql_demo_db.amazon_reviews limit 0)
JOIN sentiment_classifier_gpt3
LIMIT 1
);
```
At the moment it is working with error if  limit 0 and without error if  limit 1
> Add target column to output even if dtype_dict is empty

- docs/sql/tutorials/eeg-forecasting.mdx
changed /sql/create/predictor to /sql/create/model in docs\sql\tutorials\eeg-forecasting.mdx
**Fixes** #6454 
📄 This change requires a documentation update
Replaced  /sql/create/predictor to /sql/create/model in a link in docs\sql\tutorials\eeg-forecasting.mdx
My code follows the style guidelines(PEP 8) of MindsDB.
I have commented my code, particularly in hard-to-understand areas.
I have updated the documentation, or created issues to update them.
> Fixed issue #6454

- mindsdb/README.md
Fixed Link in mindsdb\README.md file.
Fixes https://github.com/mindsdb/mindsdb/issues/6457
Fixed link /sql/create/predictor/ and replace it with https://docs.mindsdb.com/sql/create/model
> Update link in mindsdb\README.md

- docs/custom-model/openai.mdx
changed /sql/create/predictor to /sql/create/model in docs/custom-model/openai.mdx
**Fixes** [issue](https://github.com/mindsdb/mindsdb/issues/6356)
- 📄 This change requires a documentation update
Replaced /sql/create/predictor to /sql/create/model in docs/custom-model/openai.mdx and fixed the broken link
- My code follows the style guidelines(PEP 8) of MindsDB.
- I have commented my code, particularly in hard-to-understand areas.
- I have updated the documentation, or created issues to update them.
> fixed broken link in docs/custom-model/openai.mdx

- mindsdb/integrations/handlers/shopify_handler/README.md
Quick fix to the `CREATE DATABASE` statement in the Shopify integration's README.
> Updated the Shopify Integration's README

- mindsdb/integrations/handlers/stripe_handler/README.md
Quick fix to the advanced `SELECT` statement in the Stripe integration's README.
> Updated the Stripe Integration's README 

- mindsdb/integrations/handlers/cohere_handler/cohere_handler.py
- mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
- mindsdb/integrations/handlers/llama_index_handler/llama_index_handler.py
- mindsdb/integrations/handlers/openai_handler/openai_handler.py
- mindsdb/integrations/handlers/writer_handler/writer_handler.py
- mindsdb/integrations/libs/base.py
- mindsdb/integrations/libs/ml_exec_base.py
Fixes an unlogged issue that affects generative handlers like Writer, LlamaIndex, etc.
Add flags to generative handlers, and use this in the check that would previously raise an exception if the target column was not found in the input dataset.
> [fix] skip target check in data for genAI handlers

- mindsdb/integrations/handlers/github_handler/README.md
Fixed the `CREATE DATABASE` statement in the GitHub handler's README by removing an extra comma and made a couple of small grammatical changes.
> Fixed Incorrect Syntax in GitHub README

- README.md
Fixed the img source link for supported python version
Before:
After:
> Fix img source link for supported python version

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
The PR adds a explicit check to abort finetuning runs if the base model is not in the list of finetune-compatible models.
**Fixes** #4734.
> [fix] OpenAI - Add check for supported finetune models

- docs/sql/data-insights.mdx
Removes link to feedback form section in docs/sql/data-insights.mdx
**Fixes** #6659 
Deleted designated section from markdown file.
> Removed link to feedback form section

- docs/data-integrations/sap-hana.mdx
Updated instructions for `docs/data-integrations/sap-hana.mdx`
**Fixes** #6706 
Added `<Tip>
If you installed MindsDB locally via pip, you need to install all handler dependencies manually. To do so, go to the handler's folder (mindsdb/integrations/handlers/hana_handler) and run this command: `pip install -r requirements.txt`.
</Tip>` to the end of the Implementation chapter.
> Changes regarding issue #6706

- mindsdb/interfaces/storage/fs.py
Don't try to import fcntl on windows
> Don't import fcntl on windows

- docs/data-integrations/oceanbase.mdx
Update instructions for OceanBase  file
**FIxes**  Issue #6696
Added additional content under implementations chapter of OceanBase file
Solution is adding-: 
If you installed MindsDB locally via pip, you need to install all handler dependencies manually. To do so, go to the handler's folder (mindsdb/integrations/handlers/oceanbase_handler) and run this command: `pip install -r requirements.txt` 
So that all dependencies are installed
> Updated instructions for OceanBase

- mindsdb/migrations/versions/2023-06-27_607709e1615b_update_project_names.py
Fixes #6554
Created migration to update 'project' and 'integration' tables names: replace '.' to '_'
> Remove '.' from project and integrations names

- docs/data-integrations/mysql.mdx
I added this message to the end of the implementation chapter: " If you installed MindsDB locally via pip, you need to install all handler dependencies manually. To do so, go to the handler's folder (mindsdb/integrations/handlers/mysql_handler) and run this command: `pip install -r requirements.txt`."
- [ ✓] 🐛 Bug fix (non-breaking change which fixes an issue)
Update instructions for MySQL Document #6695
- [ ✓] I have updated the documentation.
> Added tip message to MySQL.mdx file #6695

- docs/data-integrations/monetdb.mdx
Added a tip to manually install dependencies for MonetDB in the case where MindsDB was installed locally via pip.
**Fixes** #6693 
Added more documentation using html in the `docs/data-integrations/monetdb.mdx` file
> Add tip for MonetDB dependencies

- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
This PR enables usage of lightwood embedding modes. Example:
```
CREATE MODEL 
mindsdb.home_rentals_model
FROM example_db
(SELECT * FROM demo_data.home_rentals)
PREDICT rental_price
USING
problem_definition.embedding_only = True;  -- this will set `return_embedding` as `True` by default when predicting, and skip some phases in the learning pipeline
SELECT rental_price, 
FROM home_rentals_model
WHERE sqft = 823
AND location='good'
AND neighborhood='downtown'
AND days_on_market=10
USING
return_embedding = True;  -- this forces an embedding as output
```
> support embedding mode for lightwood models

- mindsdb/integrations/libs/learn_process.py
Mark predictor as 'error' if can't get training data
Close #6832
> mark predictor as 'error' if cant get training data

- mindsdb/integrations/handlers/frappe_handler/frappe_client.py
Now in case of error frappe_client shows only 'Expectation Failed'
After update content of error message should be visible
> Show error message from frappe api

- docker/build.py
Possible fix of:
`ApplyLayer exit status 1 stdout:  stderr: write /opt/conda/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so: no space left on device`
> Fix docker image error:

- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
- mindsdb/integrations/handlers/singlestore_handler/singlestore_handler.py
This PR adds an additional `conn_attrs` key to the MySQL config required for providing a partner name for the SingleStore integration.
> Singlestore conn attr

- mindsdb/integrations/handlers/oracle_handler/README.md
- mindsdb/integrations/handlers/oracle_handler/oracle_handler.py
Changes:
- added disable_oob param (disable out-of-band breaks)
- added auth_mode param (connect with database privilege)
- fixed get_tables methdo 
#6746
> Fix oracle: connection with sys should be sysdba or sysoper

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
- tests/unit/ml_handlers/test_openai.py
When creating the openAI handler, we validate the arguments provided by a user against a known list of arguments.
We throw an error an unexpected argument was found.
This solution is a bit hacky, in the sense we need to keep maintaining and updating the right argument list on the handler level. I am proposing a [design doc](https://docs.google.com/document/d/1mE64JEXmn0Kz60c0_qVAWhjvNKCpiNvg5wVLxHPoKjY/edit?usp=sharing) to ask handler developers to self declare and document
the argument specifications in the handler implementation.
**Fixes** #6845
Error message if wrong arguments are provided:
We maintain a list of known arguments that can be accepted.
Anything beyond this list will be regarded as invalid. The handler throws an error when …
> Unknown argument validation + fix openai handler test

- docker/release
In order to use  `Shopify` integration, the dependency was not mentioned in the `release` file. So, it was breaking while using Docker environment
**Fixes** #6913 
Added the dependency in the `release` file for docker env
> [Bug, Docker] Shopify bug fixed

- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- mindsdb/interfaces/database/views.py
#6507
Don't rise exception if table has more than 2 parts and try to send select as is in integration
> Don't rise exception if table has more than 2 parts

- docker/mindsdb.Dockerfile
- mindsdb/api/http/namespaces/tab.py
- mindsdb/interfaces/storage/fs.py
On at least some systems, LOCK_EX can only be used if the file descriptor refers to a file opened for writing. Previously we opened files for read.
> Fix for files locking

- mindsdb/__main__.py
- mindsdb/interfaces/database/integrations.py
- do not show at start list of handlers that cannot be imported
- improve error message if handler cannot be imported
- delete ability to create integration via config file
**Fixes**
[Fix 6208](https://github.com/mindsdb/mindsdb/issues/6208)
> Better error message if handler cannot be used

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
This is a cherry picked version of #6819.
It only contains the part related to supporting embedding mode in openAI handler.
No modifications on top.
Full credits to @ea-rus 
Usage
```sql
CREATE MODEL openai_emb
PREDICT embedding
USING
engine = 'openai',
mode='embedding',
model_name='text-embedding-ada-002', -- name of embedding model
question_column='summary';  -- input column name
select * from ourdb.ourtable
join  openai_emb;
```
---
I used the following commands to get this PR
```bash
git fetch origin/mongo-embeddings
git check out origin/mongo-embeddings
git diff staging -- mindsdb/integrations/handlers/openai_handler/ > embedding.diff
git check out staging
git check out -b feature/openai-embedding
git apply embedding.diff
```
(Please delete options that are not …
> OpenAI embedding mode

- mindsdb/integrations/handlers/ignite_handler/ignite_handler.py
This PR ensures that the port value, retrieved from connection configurations, is properly converted to an integer before attempting the connection. Additionally, a ValueError is raised if the provided port number is not a valid integer.
> Fix Database Connection Issue With Ignite by Ensuring Port is an Integer

- docker/release
This PR adds a missing dependency in the Docker image for the Apache Ignite integration.
**Fixes** https://github.com/mindsdb/mindsdb/issues/7064
> Add Ignite dependencies to Docker

- mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py
For example, this command:
```sql
FINETUNE model
FROM mindsdb (
SELECT * FROM data
)
USING
trainer_args = {"max_steps": 10};
```
Will pass to the `.partial_fit()` method the following `args` variable:
```python
args = {
<any other training-time key-value pairs here>
...
'trainer_args': {"max_steps": 10}  # will override any pair provided above under the same key
}
```
> [fix] correct passing of finetuning args in lightwood

- mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py
Fixed: this query rose exception because output dataframe is empty and doesn't content error column
```
select * from web ( https://docs.mindsdb.com, limit=0)
```
> WEB handler: no error if result is empty

- mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py
- mindsdb/integrations/utilities/time_series_utils.py
Updated statsforecast handler to accept dataframes without grouping column. Grouping column is added inside of handler.
Usage:
Fix #6948
Because [NFLX.xls](https://github.com/mindsdb/mindsdb/files/12171104/NFLX.xls) dataset doesn't contain group values need to create model without 'group by' clause:
```sql
CREATE MODEL 
netflix_stock 
FROM files (select * from nflx)
PREDICT High 
ORDER BY Date 
HORIZON 30 
USING ENGINE = 'statsforecast';
```
Usage of model:
```sql
SELECT *
FROM mindsdb.netflix_stock as m
JOIN files.nflx as t
WHERE t.date > LATEST
```
> Statsforecast: allow to create model without group column

- docs/sql/tutorials/house-sales-statsforecast.mdx
This PR fixes the bug related to the target variable forecasted by StatsForecast in https://docs.mindsdb.com/sql/tutorials/house-sales-statsforecast. 
Here's the screenshot of the error:
> fix: house sales statsforecast tutorial

- docker/release
- requirements/requirements.txt
This PR adds duckdb as a dependency required for google sheet integration to Docker. Note, soon we should migrate this handler and avoid loading the sheet to duckdb, but for now it is required.
> Add duckdb to Docker 

- docs/setup/self-hosted/pip/source.mdx
The self-hosted restriction suggests using SSH keys to clone the mindsdb repo (`git clone git@github.com:mindsdb/mindsdb.git`). In some cases, this could be restrictive for some users. See #7142. 
Suggesting installing using https.
> fix: add installing option without ssh

- docker/release
This PR adds the Binance conector as a dependency for Binance integration to Docker image.
#7153  #7153
> Add binance-connector to Docker

- mindsdb/integrations/handlers/binance_handler/binance_handler.py
Round timestamps in `binance` handler. It allows to not convert timestamp to int in query.
> Round timestamps in `binance` handler

- mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
- mindsdb/interfaces/database/integrations.py
The following query will fail when creating an ML_engine with empty arguments
```
CREATE ML_ENGINE test_lw
FROM lightwood;
```
This is a bug brought by  #7087
> Defensive coding for None connection_args

- mindsdb/integrations/handlers/autokeras_handler/requirements.txt
`sklearn` is deprecated, `scikit-learn` must be used instead
**Fixes**
related to https://github.com/mindsdb/mindsdb/issues/6899
> Fix deprecated requirement `sklearn`

- mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
fixed langchain parameter name
- using `prompt_template` locally works fine - but the model's answer is null
- using `prompt` on cloud works fine (after deploying this fix, use `prompt_template` on cloud as well)
> fixed langchain parameter name

- mindsdb/api/http/namespaces/config.py
- mindsdb/integrations/handlers/gmail_handler/gmail_handler.py
Because different instances has different secret keys we need to get secret key from gateway server in special header
It this header doesn't exist: then it is local version and simple key is used
Related to https://github.com/mindsdb/mindsdb_gateway/pull/629
> Gmail auth: get secret key from gateway

- mindsdb/api/postgres/postgres_proxy/postgres_proxy.py
This PR reads the host and port from the default or extend config when starting the PostgreSQL API.
**Fixes** Reported issue on Slack
> Add an option to extend the default host, port

- docs/integrations/data-integrations/mysql.mdx
- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
If MySQL integration port is not specifiedm use 3306.
**Fixes** #7230
> Mysql port default

- mindsdb/integrations/handlers/aurora_handler/aurora_handler.py
Aurora integration, connection arguments: remove hint to use 127.0.0.1 instead of localhost.
Aurora can't run on localhost.
**Fixes** 
> Aurora: Remove the note to use 127.0.0.1 instead of localhost

- mindsdb/__main__.py
This change is required for the jobs microservice [here](https://github.com/mindsdb/INTERNAL-mindsdb-build-deploy-to-kubernetes/pull/13)
This allows supplying an empty api list with `--api=`, which will then only run the jobs and tasks services (depending on the user's config).
> Allow providing an empty API list arg

- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
Previously `get_tables()` run `SHOW TABLE` against MySQL. With this change, it now runs a `SELECT` against `information_schema.TABLES`. It returns the same columns as the PostgreSQL integration and it has an `ORDER BY`.
This change guarantees that `SHOW TABLES` (when run in a MySQL integration) shows the tables in an alphabetical order.
Including more columns means that we also allows MindsDB to distinguish tables from views. Not sure if this information is currently used.
**Fixes** #7232
> MySQL: remove show tables

- mindsdb/integrations/handlers/palm_handler/__about__.py
- mindsdb/integrations/handlers/palm_handler/__init__.py
- mindsdb/integrations/handlers/palm_handler/palm_handler.py
- mindsdb/integrations/handlers/palm_handler/requirements.txt
- mindsdb/integrations/handlers/palm_handler/setup.py
- mindsdb/utilities/hooks/__init__.py
Created a basic handler for [PaLM API](https://developers.generativeai.google/api/python/google/generativeai) Integration into mindsdb.
It has the following set of features:
- Generate Completion with a prompt
- Generate Response with a given Prompt Template
- Generate Embeddings for a given piece of text
**Fixes** #7319 
I want to get feedback on the proposed way of this integration. I have used references from the OpenAI handler for this to get started. I am open to any suggestions or improvements you might have. Please let me know about the required changes and improvements.
Thank you. :pray:
> PaLM 2 API Integration

- mindsdb/integrations/handlers/gmail_handler/gmail_handler.py
- mindsdb/integrations/handlers/gmail_handler/utils.py
- mindsdb/integrations/handlers/google_calendar_handler/__init__.py
- mindsdb/integrations/handlers/google_calendar_handler/google_calendar_handler.py
Enables google calendar handler to work on cloud:
- uses auto flow from gmail handler
- file should be uploaded from 'add datasource' form 
Fixes: #6607 
Linked to https://github.com/mindsdb/mindsdb-frontend/pull/1724
1. Getting client secret file:
- Go to [google console](https://console.cloud.google.com/)
- Create new project
- Go to Google [Calendar API](https://console.cloud.google.com/apis/library/calendar-json.googleapis.com) and enable it
- Go to credentials page.
- Create OAuth credentials with type 'Web application' and setup it.
- Download and save client_secret.json
2. Add database in web mindsdb web editor
- select add -> new datasource
- select 'google calendar'
- upload client_secret.json, test connection and save
Please include a summary of the change and the issue it …
> Google calendar integration 

- mindsdb/integrations/handlers/cassandra_handler/cassandra_handler.py
Fixed Cassandra handler parameters:
- secure_connect_bundle replaced to STR (was PATH), because cassandra handler doesn't expect PATH
Creation cassandra handler via form returns error:
> Fix Cassandra handler: secure_connect_bundle is path

- docker/release
This PR adds the dependencies required to run the Microsoft Teams handler in MindsDB Docker image.
> Added the Microsoft Teams Handler Dependencies to the Docker Image

- mindsdb/integrations/handlers/s3_handler/s3_handler.py
This PR adds a call to extract the metadata of the object the user is trying to connect to, in the `check_connection()` method. This handles the situation where the credentials are incorrect as well as the situation where the bucket or the object itself does not exist.
https://github.com/mindsdb/mindsdb/issues/7434
When the credentials are incorrect,
When the bucket does not exist,
When the object does not exist,
> [PR] Validate AWS S3 Credentials at CREATE DATABASE Step

- mindsdb/integrations/handlers/web_handler/README.md
- mindsdb/integrations/handlers/web_handler/web_handler.py
- requirements/requirements.txt
Changes:
- limit is required now
- negative limit is the same as 0 
- limit is total count of rows on output (not depended on count of input urls) 
- updated mindsdb_sql dependency (to accept negative limit)
Fixes: #7118
> Fix: LIMIT -1 in Web Crawler

- mindsdb/__about__.py
- mindsdb/api/postgres/postgres_proxy/postgres_proxy.py
v23.9.3.1 hotfix
This Hotfix enables Postgres API to handle more than 1 connection
> v23.9.3.1 - Hotfix for Postgres API Connections

- mindsdb/integrations/handlers/redshift_handler/redshift_handler.py
add labels on redshift handlers
[Bug]: no labels on Amazon Redshift connection #7455
Fixes #7455
1. open GUI
2. add redshift handler. 
3. check redshift handlers
- [ x   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.
> add redshift handlers

- mindsdb/integrations/handlers/shopify_handler/README.md
- mindsdb/integrations/handlers/shopify_handler/shopify_handler.py
- mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
This PR introduces the `LocationTable` to the Shopify integration in MindsDB, enabling users to query location data directly from their Shopify stores.
Fixes #7512 (assuming this is the issue number for the Location Table Implementation)
1. Setup the Shopify integration by providing the required `shop_url` and `access_token`.
2. Query the location data using: 
```sql
SELECT id, name, address
FROM shopify_datasource.locations
ORDER BY id
LIMIT 5
```
3. Verify that the data fetched matches the locations in the Shopify store.
> Shopify location table

- mindsdb/integrations/handlers/chromadb_handler/README.md
`"chroma_api_impl": "rest",` is no longer a valid connection parameter while connecting to chromadb. Hence, removed the parameter from readme file.
Fixes #7531 
> Update chromadb doc

- mindsdb/interfaces/storage/fs.py
do not use `fcntl` at not posix os
Fixes #7668
> fix: do not use `fcntl` at not posix os

- mindsdb/integrations/handlers/couchbase_handler/couchbase_handler.py
This PR fixes the Couchbase connection error that occurs when attempting to connect to the cloud offering, i.e Couchbase Capella.
https://github.com/mindsdb/mindsdb/issues/7391
Given below are the results of the manual tests that were run,
**Couchbase Capella:**
**Couchbase Local:**
> Couchbase Connection Error Fix

- mindsdb/integrations/handlers/byom_handler/byom_handler.py
In last numpy versions there was an error:
```
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
> Fix: `object` instead of `np.object`

- mindsdb/integrations/handlers/ignite_handler/README.md
I made a small change to the example CREATE DATABASE statement given in the README for the Apache Ignite handler by removing an incorrect parameter.
> Fixed the Example CREATE DATABASE Statement in Apache Ignite README

- mindsdb/integrations/handlers/hackernews_handler/README.md
- mindsdb/integrations/handlers/hackernews_handler/hn_handler.py
- mindsdb/integrations/handlers/hackernews_handler/hn_table.py
Implemented the Hacker News GET `/showstories.json` endpoint ([show-hn-stories](https://hackernews.api-docs.io/v0/live-data/show-hn-stories))
Created separate table (`showstories`) for storing the data from GET `/showstories.json` endpoint. Also added the sample query in the Hacker News handler readme.
Fixes #7737 
1. Create database using following command:
`CREATE DATABASE my_hackernews WITH ENGINE = 'hackernews'`
2. Test the implemented endpoint data:
`SELECT * FROM my_hackernews.showstories LIMIT 5;`
> Add showstories endpoint

- tests/handler_tests/test_pinecone_handler.py
Fixes a minor code formatting error introduced in a previous merge (`F841 local variable 'num_record' is assigned to but never used` to be specific) that is causing CI to halt.
> Minor lint fix

- mindsdb/utilities/ml_task_queue/consumer.py
Count of parallel tasks reduced from 1 per 2 CPU cores to 1 per 8 CPU cores
> Reduce count of parallel tasks if use redis queue

- mindsdb/integrations/handlers/shopify_handler/README.md
- mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
Added the implementation to delete customers by interacting with Shopify API
Fixes #7762 
-  Go to mindsdb online editor
- Execute the query "DELETE FROM shopify_datasource.customers WHERE first_name = 'some_first_name';"
- The query will get executed without any ImplementationError.
- Verify that the item has been deleted by checking the items returned by the query "SELECT * from shopify_datasource ; "
https://github.com/mindsdb/mindsdb/assets/70593335/34af8060-dd74-4d88-b47a-e933f7ce612a
> [Shopify] Add Delete Customers implementation for Shopify

- docker/docker-compose-ci.yml
- mindsdb/integrations/handlers/binance_handler/README.md
- mindsdb/integrations/handlers/clickhouse_handler/README.md
- mindsdb/integrations/handlers/couchbase_handler/README.md
- mindsdb/integrations/handlers/crate_handler/README.md
- mindsdb/integrations/handlers/d0lt_handler/README.md
- mindsdb/integrations/handlers/google_calendar_handler/README.md
- mindsdb/integrations/handlers/hive_handler/README.md
- mindsdb/integrations/handlers/hsqldb_handler/README.md
- mindsdb/integrations/handlers/influxdb_handler/README.md
- mindsdb/integrations/handlers/jira_handler/README.md
- mindsdb/integrations/handlers/matrixone_handler/README.md
- mindsdb/integrations/handlers/milvus_handler/README.md
- mindsdb/integrations/handlers/mysql_handler/Manual_QA.md
- mindsdb/integrations/handlers/neuralforecast_handler/README.md
- mindsdb/integrations/handlers/newsapi_handler/README.md
- mindsdb/integrations/handlers/nuo_jdbc_handler/README.md
- mindsdb/integrations/handlers/pinot_handler/README.md
- mindsdb/integrations/handlers/reddit_handler/README.md
- mindsdb/integrations/handlers/rocket_chat_handler/README.md
- mindsdb/integrations/handlers/vertica_handler/README.md
- mindsdb/integrations/handlers/youtube_handler/README.md
This PR fix the typo that was seen in files of mindsdb folder
```pseudo
doen > does
succesful > succesfull
DATABSE > DATABASE
ommited > omitted
asscociated > associated
acces > access
entires > entries
```
> Chore: Typo fixed in multiple files of mindsdb folder

- docker/release
This PR adds the dependencies for the PGVector handler to Docker image.
Partially fixes https://github.com/mindsdb/mindsdb/issues/7926
> Added Dependencies for PGVector to Docker

- mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
- mindsdb/integrations/handlers/chromadb_handler/requirements.txt
This PR adds the `pysqlite3-binary` for the Chroma because it is currently not working in MindsDB Cloud. This is the error that has been encountered,
`Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.`
Because the version of the `sqlite3` module is tied to the Python version, I thought this would be the best way to go about it. This works locally after some initial testing, but the problem exists in Cloud.
Fixes https://github.com/mindsdb/mindsdb/issues/7949
> Added the pysqlite3-binary Dependency for Chroma

- docker/release
This PR adds the dependencies for the Anthropic handler to Docker image.
Fixes https://github.com/mindsdb/mindsdb/issues/7928
> Added Dependencies for Anthropic to Docker

- docker/release
This PR bumps the version of the couchbase package in Cloud. The latest version of this package is required for the new implementation of the Couchbase integration.
Fixes https://github.com/mindsdb/mindsdb/issues/8020
> Bumped the Couchbase Package Version for the Docker Image

- docs/integrations/app-integrations/newsapi.mdx
- mindsdb/integrations/handlers/newsapi_handler/README.md
- mindsdb/integrations/handlers/newsapi_handler/newsapi_handler.py
This PR adds a few changes to the NewsAPI handler:
1. Check if there is data. If not, return an empty DF instead of throwing a mapping error
2. Fix the sorting issue by correctly parsing the ORDER BY value
3. Check if the API call is successful
4. Set default page API value if the page value is missing
Fixes #7899 , #7897
The unit tests for this handler will be added in separate PR.
To ensure the changes are working as expected, run the following queries:
```sql
SELECT *
FROM newsAPI.article
WHERE query = 'mindsdb';
```
And:
```
SELECT *
FROM newsAPI.article
WHERE query = 'Python'
AND sources="bbc-news"
AND publishedAt >= "2021-03-23" AND  publishedAt <= "2023-04-23"
LIMIT 4;
```
> Newsapi Integration Bugs

- mindsdb/integrations/handlers/npm_handler/requirements.txt
My guess is that `requests` not being installed is the issue. Could not reproduce the bug on development setup. Maybe someone from MindsDB core team can confirm.
Fixes #7995
> Add requirements.txt to npm

- mindsdb/integrations/handlers/dockerhub_handler/dockerhub_tables.py
- mindsdb/integrations/handlers/dockerhub_handler/requirements.txt
This PR handles the error for when both the namespace and repository columns are not part of the `SELECT` query for the Docker Hub `repo_images_summary` table.
Fixes https://github.com/mindsdb/mindsdb/issues/8049
> Updated Mandatory Parameters for Docker Hub repo_images_summary Table

- .github/workflows/mindsdb.yml
This PR moves the ML tests to a new step and runs them only for mindsdb team members. 
Note this check works only from the accounts that have '@mindsdb'
Fixes failing PRs from community members
> Add new step for running the ML tests if the user is part of mindsdb org

- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- mindsdb/api/mysql/mysql_proxy/utilities/sql.py
By default `duckdb`  get only 1000 rows if need do type infer. That may be not sufficient for some cases.
> DataFrame query with increasing butch size for type infer 

- mindsdb/integrations/handlers/youtube_handler/requirements.txt
- mindsdb/integrations/handlers/youtube_handler/youtube_handler.py
- mindsdb/integrations/handlers/youtube_handler/youtube_tables.py
Implemented the option to retrieve video transcripts in JSON format with the YouTube handler with the select query
~~~~sql
SELECT * FROM mindsdb_youtube.comments
WHERE video_id = "raWFGQ20OfA";
~~~~
Fixes #7891
> feat(youtube_handler): implement youtube transcripts retrieval in video table

- mindsdb/integrations/handlers/mongodb_handler/mongodb_handler.py
remove server selection timeout override in mongodb handler. 
[default is best/safe at 30000ms](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.serverSelectionTimeoutMS) and can be configured in connection string if needing to override
set serverSelectionTimeoutMS to 0 in connection string and observe failure
set serverSelectionTimeoutMS to 30000 in connection string and observe success
don't set serverSelectionTimeoutMS in connection string and observe success for connections above the previous 5000ms
> remove server selection timeout override for mongodbhandler

- docs/openapi.yml
Fixing typo on OpenAPI docs description.
> Fix typo OpenAPI

- mindsdb/api/mysql/mysql_proxy/utilities/sql.py
- mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
Some postgres types cast to pandas 'object' by default. This may cause error in further processing in `duckdb`: it try infer pandas 'object' columns types using butch selection from df.  In most cases it works fine, but in some rare cases type may be inferred wrong.
> Cast `postgres` types to pandas compatible

- mindsdb/interfaces/query_context/context_controller.py
- mindsdb/interfaces/query_context/last_query.py
- tests/unit/test_project_structure.py
Getting last value for query should keep other query conditons
```sql
select * from a=1 and b>last
``` 
will use this query (with a=1 filter)
```sql
select b where a=1 and b is not null order by b desc limit 1
```
> LAST: Use all conditions to get last value

- mindsdb/integrations/handlers/npm_handler/api.py
Fix fetching non-existent columns for the handler. New default value is now an empty `dict` instead of an empty string
> NPM Handler: Fix fetching non-existent column

- docker/release
This PR adds the dependencies for the ChromaDB handler to Docker image.
Fixes https://github.com/mindsdb/mindsdb/issues/8267
> Added Dependencies for ChromaDB to Docker

- requirements/requirements.txt
This PR updates to the latest version of MindsDB SQL to solve the import chatbots error
> Update mindsdb_sql version

- tests/unit/ml_handlers/base_ml_test.py
- tests/unit/ml_handlers/test_anthropic.py
This PR adds the unit tests for the Anthropic integration. It also adds `BaseMLTest` and `BaseMLAPITest` classes, which contains some of the common functionality used throughout the tests for ML Engines (and API-based ML engines).
Fixes https://github.com/mindsdb/mindsdb/issues/8261
Test report (summary),
One unit test is failing due to a limitation in the handler; unknown model arguments are not handled.
> Added the Unit Tests for the Anthropic Integration

- mindsdb/integrations/handlers/email_handler/email_helpers.py
This PR updates the Email integration to allow selecting emails within the last 24 hours.
Fixes https://github.com/mindsdb/mindsdb/issues/8282
Now, the integration emails within the last 24 hours as well,
> Fix for Selecting Emails Within the Last 24 Hrs

- Makefile
update Makefile to shortcut handler requirements install
**Shortcuts:**
Install mindsdb locally, dev requirements and install pre-commit hooks:
`make install_mindsdb` 
Run precommit on local staged changes:
`make precommit`
Install requirements for a specific handler:
`make install_handler  HANDLER_NAME=writer`
run mindsdb locally with python:
`make run_mindsdb`
> add short cut for installing handler requirements

- mindsdb/integrations/handlers/openai_handler/constants.py
- mindsdb/integrations/handlers/openai_handler/openai_handler.py
This PR adds support for DallE 3.
The `model_name` should now be passed when setting `mode=image`. Otherwise, `dall-e-2` will be used by default.
Example:
```sql
CREATE MODEL mindsdb.dalle
PREDICT img_url
USING
engine = 'openai',
mode = 'image',
model_name = 'dall-e-3',
prompt_template = 'Make a photorealistic image. Here is the description: {{description}}, 4k, digital painting';
DESCRIBE mindsdb.dalle;
SELECT description, img_url
FROM mindsdb.dalle
WHERE 
description = 'a house by the lakeside';
```
> [ENH] OpenAI: add support for dall-e-3

- mindsdb/interfaces/query_context/context_controller.py
If result dataframe from data (or api) handler contents different types in the same column as in example, or contents null values with string values:
```
df= pd.DataFrame([[1],['0'] ])
df= pd.DataFrame([[None],['0'] ])
```
finding the current last value lead to error:
```
TypeError: '>=' not supported between instances of 'str' and 'float'
```
This pr fixes it.
> Fix Last keyword: expect different types in same dataframe column

- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
This PR fixes a broken type hint that had been used for the `_translate_conditions()` method of the PGVector integration. A few other cosmetic changes such as removing unnecessary imports, adding type hints for other methods etc. have been made.
Fixes https://github.com/mindsdb/mindsdb/issues/8325
> Fix for Broken PGVector Type Hint

- mindsdb/integrations/handlers/mongodb_handler/mongodb_handler.py
If we create mongo connection from Add -> New datasource menu database name is not passed to backend. 
This fix gets database name from connection if it is not specified in connection_args
https://www.loom.com/share/481b27c931064679968dbba80233b7df
> Creating mongo connection via form fix

- mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
- mindsdb/integrations/handlers/gmail_handler/gmail_handler.py
- mindsdb/integrations/libs/response.py
Fixes for add gmail db via sql:
- added code param
- copy storage from test database to real
Fixes #8097
1. Run this command with credentials_file 
```sql 
CREATE DATABASE gm
WITH ENGINE = 'gmail',
parameters = {
"credentials_file": "/tmp/client_secret_gmail.json"
}; 
```
2. It will return url to authorize. Go there
3. After authorization it should show page with code variable
4. Add code to query and run it again
```sql
CREATE DATABASE gm
WITH ENGINE = 'gmail',
parameters = {
"credentials_file": "/tmp/client_secret_gmail.json",
"code": "<put code here>"
}; 
```
5. Check database table:
```sql
select * from gm.emails limit 10;
```
> Create gmail db via sql

- mindsdb/integrations/handlers/byom_handler/byom_handler.py
Set correct BYOM mode it `type` initially was in connection arguments
> [fix] Wrong BYOM mode if `type` was in connection arguments

- mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
- requirements/requirements.txt
1. Accept row_dict param in ApplyPredictorStep
Depends on https://github.com/mindsdb/mindsdb_sql/pull/327
Example of supported query:
```sql
SELECT location
FROM (
select location, neighborhood 
from example_db.demo_data.home_rentals as t LIMIT 10
) as t
JOIN mindsdb.home_rentals_model as m
where m.days_on_market= 1
;
```
2. Support subselect for row_dict param in ApplyPredictorStep
Example query
```sql
SELECT m2.*
FROM example_db.demo_data.home_rentals as t 
JOIN mindsdb.home_rentals_model as m
JOIN mindsdb.home_rentals_model as m2
where  m2.days_on_market=(select days_on_market from example_db.demo_data.home_rentals limit 1)
LIMIT 10
```
3. Support 'model join model'
Example query
```sql
SELECT m2.*
FROM example_db.demo_data.home_rentals as t 
JOIN mindsdb.home_rentals_model as m
JOIN …
```
> Accept model filters in query

- mindsdb/integrations/libs/vectordatabase_handler.py
- mindsdb/interfaces/knowledge_base/controller.py
When inserting values into a knowledge base (e.g. [this demo](https://pastebin.com/gTCypTW9)), it currently fails with a `"None of [Index([('i', 'd'), ('i', 'd')], dtype='object')] are in the [index]"` error due to how we are inserting. Additionally, the way we fill in missing IDs when the ID column is present causes errors as well.
This PR fixes both of those issues.
> Fix Knowledge Base Insert

- docs/setup/self-hosted/pip/macos.mdx
- docs/setup/self-hosted/pip/source.mdx
Users have issues installing handlers on macOS because by default it uses zsh which can't handle the pip syntax for extras.
Putting the package name in quotes fixes the issue
> Minor docs update for ZSH

- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
- tests/handler_tests/test_mysql_handler.py
This changes the MySQL integration to use autocommit. This fixes #7234. The rationale in that ticket is that python errors, if caught, could lead to dangling open transactions with unexpected results.  This concern is valid.  If we need transactions we should provide a context manager for them so that exiting the context manager automaticaly closes the transaction.
Due to the nature of this change, there are no extra integration tests required.  Nor is there any additional documentation needed aside from something in the module docstring which I have already added.
In practical terms, this prevents dangling transactions in the case of unexpected python errors and therefore makes the module more robust.
Fixes #7234 
To ensure the changes are …
> Moving MySQL driver to use autocommit

- mindsdb/integrations/handlers/shopify_handler/README.md
- mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
This a new feature for the Shopify Handler. Under this feature, users can update the data for Shopify's Order Table.
Fixes #7846
* Set up mindsdb  on your local as a [documented here](https://docs.mindsdb.com/setup/self-hosted/pip/macos)
* Get your shophify Access key and your shop name URL
* Write the command to create a shophify database as mentioned [here](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler#example-usage)
* Now write a simple update SQL query to test the changes
https://github.com/mindsdb/mindsdb/assets/52901608/6cb5e079-7ead-4c28-b26b-4022c8fdad9e
> Feat add new handler to update Shopify orders

- mindsdb/api/http/initialize.py
Changes:
- Ignore frontend versions like '23.9.2.2'
Version 23.9.2.2 was downloaded some time ago and since that time local version stopped to update (because 23.9.2.2 is greater than any next version)
https://mindsdb-web-builds.s3.amazonaws.com/compatible-config.json
> Fix checking frontend version

- mindsdb/integrations/handlers/clickhouse_handler/README.md
- mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py
This PR solves issue when connecting to CH using https, by connecting using http protocol and sending additional query param for the https protocol (as supported by the [Driver library](https://clickhouse-sqlalchemy.readthedocs.io/en/latest/connection.html#http)). Also protocol parameter is set as optional because we default it to `native`
Fixes #8595
> Fix https CH bug

- mindsdb/integrations/handlers/replicate_handler/replicate_handler.py
This PR fixes the Replicate issue related to using depricate method `get_transformed_schema`.
Fixes #8600 
- [] 🐛 Bug fix (non-breaking change which fixes an issue)
> Fix Replicate schema bug

- .github/workflows/docker_build.yml
> Fix deploy trigger input name

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/release.yml
- docker/docker-bake.hcl
- Add staging and prod deployments on merge to stable/releases respectively.
- Simplify the docker bake file
- On release, push versioned images to ECR as well as dockerhub (this just makes env cleanup easier later on)
> More deploy triggers and simplify docker

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
Finetune was blocked because of:
- if `api_base` not in args, and `OPENAI_API_BASE` not in env, then key error raised
- `api_base` can not be in args because it is not in white list
> fix openai handler `api_base` argument

- docker/docker-bake.hcl
- mindsdb/integrations/handlers/mssql_handler/README.md
- setup.py
Fixes installs on macos. Installing pymssql on macos requires building the package and takes some setting up on macos.
Updates docs for installing and adds mssql back into the cloud docker images
> Remove mssql as default handler

- mindsdb/integrations/handlers/ollama_handler/ollama_handler.py
- `create_validation()`: dropped model registry check, as the API stopped returning officially supported models
- `describe()`: now robust against missing information in the model's description
> [fix] Ollama - Drop model registry check & improve description

- docs/mint.json
as the chatbot icon from mindsdb editor will be temp disabled, the corresponding doc page is removed for now
> removed chatbot ui docs

- .flake8
- .github/workflows/mindsdb.yml
- mindsdb/integrations/handlers/postgres_handler/README.md
- mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
- tests/unit/handlers/test_postgresql.py
This PR:
*  Fixes https://github.com/mindsdb/mindsdb_private/issues/383 by checking if column value is Null or Nan and cast to 0
* Removes postgres_handler from pep8 ignored files and fix all warnings
* Add initial unit test for the handler
* Add missing README for the handler
* Improves logging and code comments
* 
> PostgreSQL Integration improvments

- docs/integrations/app-integrations/youtube.mdx
- mindsdb/integrations/handlers/youtube_handler/README.md
Documentation update to reflect the YouTube handler Readme.md. I assume that the read me is up to date.
Fixes #8667 
- [ x ] 📄 This change requires a documentation update
- [ x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ x ] I have appropriately commented on my code, especially in complex areas.
- [ x ] Necessary documentation updates are either made or tracked in issues.
- [ x ] Relevant unit and integration tests are updated or added.
> youtube documentation update

- mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
> Fix `anyscale-endpoints` finetune

- docs/integrations/data-integrations/postgresql.mdx
Minor updates to PostgreSQL docs.
> PostgreSQL Updates docs

- mindsdb/integrations/handlers/github_handler/github_tables.py
Changes: 
- Show content in files table by default
- default limit is 10
It will enable to use simple join  with model which uses content:
```sql
SELECT t.name, t.content, m.question
FROM my_github.files t
JOIN question_generator as m
where t.path = 'mindsdb/integrations/handlers' 
LIMIT 1 
```
instead of 
```sql
SELECT t.name, t.content, m.question
FROM (
select name, content from my_github.files
where path = 'mindsdb/integrations/handlers' 
LIMIT 1 
) as t
JOIN question_generator as m  
```
> Show content in files by default

- docs/mindsdb_sql/sql/create/jobs.mdx
- docs/mindsdb_sql/sql/create/model.mdx
sql api updates: jobs and models
> sql api updates

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
- mindsdb/integrations/utilities/handler_utils.py
There is no possible to specify api-key when do openai finetune. If put key into `using`, then it ignored.
> Аix getting api-key for openai finetune

- mindsdb/integrations/handlers/utilities/auth_utilities/microsoft/ms_graph_api_auth_utilities.py
This PR updates the logic for the MS Teams authentication process to generate a redirect URI only on the first time that the connection initialized. At this point the redirect URI will be stored in handler storage and subsequent attempts at initializing the same connection will access it from this storage.
This update was required because as the chat bot task runs on a separate thread and does not come through a request, it does not have access to the request headers used to generate the redirect URI.
> Stored MS Teams Redirect URI in Handler Storage

- mindsdb/integrations/handlers/slack_handler/slack_handler.py
Fixes of flask handler for using LAST
- accept created_at **is not null**
- accept ordering by any column (column used in LAST required to be sorted)
- created_at>date filter adds +1 sec to date because slack condition is '>='
> Slack fixex

- mindsdb/integrations/libs/ml_exec_base.py
- mindsdb/integrations/libs/process_cache.py
If exception can not be pickled (pickle.loads(pickle.dumps(e))) then it may lead to termination of the ML process.
Also in this case, the error sent to the user will not be relevant. This wrapper should prevent it.
- [v] My code follows the style guidelines(PEP 8) of MindsDB.
> Better error handling if exception can't be pickled

- docs/sdks/mongo/jobs/insertOne.mdx
- docs/sdks/mongo/models/finetune.mdx
- docs/sdks/mongo/models/retrain.mdx
- docs/sdks/mongo/mongo.mdx
- mindsdb/api/mongo/README.md
`.insert` is replaced to `.insertOne`
`predictors` replaced to `models`
Close #7214
> [Docs] update mongo doc: replace `insert`->`insertOne`, `predictors`->`models`

- mindsdb/api/executor/sql_query/sql_query.py
- mindsdb/api/http/namespaces/handlers.py
- mindsdb/utilities/exception.py
- mindsdb/utilities/log_controller.py
- tests/unit/test_project_structure.py
If use a model in 'error' status, then error message will be like
```
The model 'model_name' cannot be used as it is currently in 'error' status.
For detailed information about the error, please execute the following command:
select error from information_schema.models where name = 'model_name';
```
instead of
```
Can't select from cryptocurrency_forecast_model in project: unkown
```
Also fixed typo `unkown`->`unknown`
Close #8826
> Improve error message if model in 'error' status

- mindsdb/api/executor/sql_query/result_set.py
- mindsdb/api/executor/sql_query/steps/map_reduce_step.py
- tests/integration_tests/flows/test_ts_predictions.py
Reason of issue: if join model and  empty dataframe, then info about columns is loosed. That follow to error.
Close #8842
> Fix: JOIN model with empty dataframe

- mindsdb/integrations/libs/process_cache.py
Continue of #8729
Not every exception can be unpickled, sometimes it can't create instance of exception. Fix is to wrap it in RuntimeException 
How it works:
https://www.loom.com/share/08a74119e8054ea2b8557d27c2b3ce82
> Don't pickle exception, wrap it

- mindsdb/integrations/handlers/file_handler/__init__.py
- mindsdb/interfaces/database/database.py
- mindsdb/interfaces/database/integrations.py
- Mark `files` handler as permanent, therefore it can not be deleted
- Mark `mindsdb` project as not deletable
Fixes #8878
> Mark `files` handler as permanent

- docs/setup/custom-config.mdx
This PR adds the `http_auth_enabled` flag in the default config.json example. This is needed for enabling the authentication and was missing from the example
> Add auth flag in the config example

- mindsdb/__main__.py
- mindsdb/api/mongo/utilities/mongodb_query.py
- mindsdb/utilities/json_encoder.py
Fixes this warning when running MindsDB:
`/mindsdb/mindsdb/__main__.py:145: DeprecationWarning: 'JSONEncoder' is deprecated and will be removed in Flask 2.3. Use 'Flask.json' to provide an alternate JSON implementation instead.`
> Fix warning about flask JSONEncoder deprecation

- mindsdb/interfaces/database/integrations.py
This PR removes icons as a determining factor for handler import status, i.e., for a particular handler, if the path to the icon provided is incorrect or the icon file cannot be read, the import of the handler will not be affected.
> Removed Icons as Determining Factor for Handler Import Status

- setup.py
Won't allow pip installs on python versions we don't support (3.11+)
> Fix supported python versions for pip installs

- mindsdb/integrations/utilities/install.py
This PR fixes the issue where when the installation of dependencies fail for a particular integration, the /<handler_name>/install endpoint succeeds.
Fixes https://github.com/mindsdb/mindsdb/issues/8976
> Sets the 'success' Attribute of /<handler_name>/install Endpoint to False Upon Installation Failure

- .github/workflows/test_on_deploy.yml
- docker/mindsdb.Dockerfile
- mindsdb/metrics/server.py
- Create prometheus dir if `PROMETHEUS_MULTIPROC_DIR` is set, but the dir doesnt exist
- Remove `PROMETHEUS_MULTIPROC_DIR` from the dockerfile as the average user won't use prometheus
- Make log message `info` as it is not an issue for normal users.
- Remove `mkdir prometheus_metrics` from test script
> create prometheus dir if it doesnt exist

- mindsdb/integrations/handlers/rag_handler/requirements.txt
- mindsdb/integrations/handlers/rag_handler/settings.py
- tests/unit/ml_handlers/test_rag.py
Removes the dependency: hugging face `sentence_transformer` package, that requires installation of `torch` and `cudnn`. This simplifies install and streamlines use of LLM endpoints.
- [x ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x ]   Verification Steps:
- Instantiated a RAG model using writer. No errors were thrown.
- [ x] I have appropriately commented on my code, especially in complex areas.
- [ x] Necessary documentation updates are either made or tracked in issues.
- [ x] Relevant unit and integration tests are updated or added.
> removing redundant package lists and sentence-transformers library

- mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
- mindsdb/integrations/handlers/chromadb_handler/requirements.txt
- mindsdb/integrations/handlers/email_handler/requirements.txt
- mindsdb/integrations/handlers/langchain_handler/README.md
- mindsdb/integrations/handlers/langchain_handler/constants.py
- mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
- mindsdb/integrations/handlers/langchain_handler/tools.py
- mindsdb/integrations/handlers/leonardoai_handler/leonardo_ai_handler.py
- mindsdb/integrations/handlers/lightfm_handler/requirements.txt
- mindsdb/integrations/handlers/litellm_handler/requirements.txt
- mindsdb/integrations/handlers/ms_teams_handler/requirements.txt
- mindsdb/integrations/handlers/ollama_handler/ollama_handler.py
- mindsdb/integrations/handlers/openai_handler/openai_handler.py
- mindsdb/integrations/handlers/openbb_handler/requirements.txt
- mindsdb/integrations/handlers/palm_handler/palm_handler.py
- mindsdb/integrations/handlers/palm_handler/requirements.txt
- mindsdb/integrations/handlers/rag_handler/requirements.txt
- mindsdb/integrations/handlers/sentence_transformers_handler/requirements.txt
- mindsdb/integrations/handlers/twelve_labs_handler/requirements.txt
- mindsdb/integrations/handlers/writer_handler/requirements.txt
- mindsdb/integrations/libs/llm/config.py
- mindsdb/integrations/libs/llm/utils.py
- requirements/requirements-test.txt
- requirements/requirements.txt
- tests/unit/ml_handlers/test_langchain.py
- tests/unit/test_llm_utils.py
Fixes RAG-2.
This PR overhauls `langchain_handler`:
- Make as many arguments optional (e.g. `user_column`, `assisstant_column`) as possible
- Remove `mode` argument as it was untested & unused
- Users can pass in `agent_type` to customize behavior ([see agent types](https://api.python.langchain.com/en/latest/agents/langchain.agents.agent_types.AgentType.html#langchain.agents.agent_types.AgentType))
- Add test suite for different providers
- Clean up LLM config into util methods
- Clean up overall implementation
> Refactor Langchain Handler

- mindsdb/integrations/libs/ml_handler_process/learn_process.py
This PR adds a check for import errors when running CREATE MODEL statements and raises the relevant error. This is to avoid the `TypeError: 'NoneType' object is not callable` error being logged when running such statement typically fail.
Fixes https://github.com/mindsdb/mindsdb/issues/9018
With this fix, the errors raised are now more precise and informative as shown below,
Note: I have introduced this error to the RAG handler temporarily for demonstration purposes.
> Added Check for Import Errors When Running CREATE MODEL Statement

- mindsdb/integrations/utilities/install.py
This PR fixes the installation of dependencies for integrations that refer to the `requirements.txt` file of another integration.
Fixes https://github.com/mindsdb/mindsdb/issues/9021
Installation of dependencies now run successfully (as opposed to the failures that have been displayed in the issue),
> Fixed Installation of Dependencies for Integrations That Refer to Other requirements.txt Files

- mindsdb/api/executor/command_executor.py
- tests/unit/test_project_structure.py
Fix delete from table of active database:
```sql
use my_db;
delete from my_table where a=1
```
Also related to https://github.com/mindsdb/mindsdb_sql/pull/369
Fixes #8029
> Fix delete from table in database

- .github/actions/docker-bake-cache/action.yml
- .github/actions/docker-bake/action.yml
- .github/workflows/build_deploy_dev.yml
- .github/workflows/build_deploy_prod.yml
- .github/workflows/build_deploy_staging.yml
- docker/docker-bake.hcl
Currently we build each platform's docker image and push cache layers to a repo separately. This is because buildkit doesn't support building and pushing cache for multiple platforms at once.
The issue with this approach is that we need to push images suffixed with `-amd64` and `-arm64` to dockerhub before building a manifest that merges those two images. This is messy and confusing for users, and triples the number of tags we have in our dockerhub repo.
This PR uses another approach to overcome buildkit's shortcoming
- Build all images for all platforms and push the images but *not* cache
- Build each platform's images again (should now be cached) and don't push the images, but push cache instead
This approach means we can also continue with other jobs without waiting for cache to be …
> Docker build improvements

- mindsdb/integrations/utilities/install.py
This PR fixes the installation of dependencies for integrations that refer to `requirements.txt` files that contain comments. A good example is the RAG handler as illustrated in the issue given below.
Note that both standalone comments and inline comments have been handled in this fix.
Fixes https://github.com/mindsdb/mindsdb_private/issues/487
Given below are screenshots of successfully installing dependencies for the RAG intgration via Docker. This container was built locally using the changes that were made here. The install operation of the 'Manage Integrations' page uses the fixed code in order to install dependencies.
> Fixed Installation of Dependencies When requirements.txt Files Contain Comments

- mindsdb/integrations/handlers/rockset_handler/requirements.txt
- mindsdb/integrations/handlers/rockset_handler/rockset_handler.py
This PR fixes the Rockset handler by removing unnecessary imports (and dependencies) and fixing the types of its connection args. 
Fixes https://github.com/mindsdb/mindsdb/issues/9030
> Fixed Unused Imports and Dependencies in Rockset Integration

- mindsdb/utilities/log.py
Alembic is currently set to output debug logs which doubles up on alembic output. We can use the mindsdb log level and `info` log output will still list migrations being run.
Before:
After:
Fixes #8488
> Make alembic use mindsdb log level

- mindsdb/interfaces/query_context/context_controller.py
Fix context controller:  dn.query could not support projection if it is API handler
Fixes LAST with slack database:
```sql
SELECT   *
FROM mindsdb_slack.channels as t
WHERE t.channel = "general"
AND t.created_at > LAST
```
> Fix LAST with slack

- docs/integrations/ai-engines/ollama.mdx
- mindsdb/integrations/handlers/ollama_handler/README.md
> updated ollama docs

- docs/integrations/data-integrations/snowflake.mdx
This PR adds a tip about the need to install Git in the Docker container before installing the dependencies for the Snowflake integration.
According to [this comment](https://github.com/snowflakedb/snowflake-sqlalchemy/issues/380#issuecomment-1986811951), the official snowflake-sqlalchemy package will add support for SQLAlchemy 2 within this month. When that is done, the dependencies for the integration should be updated and this tip should be removed.
Partially fixes https://github.com/mindsdb/mindsdb/issues/9024
> Updated Snowflake Integration Docs with Tip to Install Git

- mindsdb/integrations/handlers/ms_teams_handler/ms_teams_tables.py
- mindsdb/integrations/handlers/ms_teams_handler/settings.py
This PR fixes running `SELECT` statements on the `chat_messages` table by removing the dependency on the `eventDetails` attribute.
Fixes https://github.com/mindsdb/mindsdb/issues/9014
> Fixed Column Structure of chat_messages Table

- mindsdb/integrations/handlers/langchain_handler/requirements.txt
- mindsdb/integrations/handlers/litellm_handler/requirements.txt
This PR bumps the LiteLLM version to 1.35.0 to address a security issue.
- https://github.com/advisories/GHSA-46cm-pfwv-cgf8
> bump litellm version

- mindsdb/interfaces/storage/fs.py
- mindsdb/utilities/config.py
Allow to disable storage backup via environment variable
> Disable storage backup

- docs/openapi.yml
This PR removes obsolete `v1/api` from the REST API Endpoints URL.
Fixes #9107 
> Fix  REST API Endpoints URL

- default_handlers.txt
- docker/docker-bake.hcl
This PR adds mindsdb_inference and clickhouse to default handlers. ClickHouse was removed due to dependencies issues, which are now resolved.
Also, surreal, ignite, and couchbase are removed from the cloud until we verify them.
> Update Avaiability of handlers

- mindsdb/api/executor/command_executor.py
- mindsdb/interfaces/database/projects.py
- tests/unit/test_project_structure.py
Project and database can't have same name
Fixes #7365
Fixes https://github.com/mindsdb/mindsdb_python_sdk/issues/81
> Project and database can't have same name

- mindsdb/api/http/namespaces/knowledge_bases.py
This PR moves the imports of the file splitter classes (`FileSplitter`, `FileSplitterConfig`) in the module where the API endpoints for Knowledge Bases are defined, to within the function which actually uses them.
Fixes https://github.com/mindsdb/mindsdb/issues/9161
> Moved the File Splitter Imports to the Function They are Used in

- docs/sdks/mongo/models/describe.mdx
- mindsdb/api/mongo/README.md
- mindsdb/api/mongo/responders/__init__.py
- mindsdb/api/mongo/responders/aggregate.py
- mindsdb/api/mongo/responders/describe.py
When 'stat' function is used in [mongo shell](https://www.mongodb.com/docs/mongodb-shell/install/):
```python
> db.home_rentals_model.stats({'scale': 'features'})
```
It calls aggregate command on server with params:
```json
{  
"aggregate": "home_rentals_model", 
"pipeline": [
{ "$collStats":
{"storageStats":
{"scale": 1}
}
}
]
}
```
And this payload doesn't have info about type of description (in our case 'features')
In this PR error message to user is changed to show right command to get call describe:
In our example it is:
```javascript
db.runCommand({describe: "home_rentals_model.attribute"})
```
Fixes #7389
> Mongo shell: describe model error shows right command

- mindsdb/api/executor/sql_query/steps/apply_predictor_step.py
- requirements/requirements.txt
- tests/unit/dummy_ml_handler/dummy_ml_handler.py
- tests/unit/test_project_structure.py
Mapping columns to model in joins
In this example
```sql
select * from db.table1 t
join my_model m on t.a = m.x
```
If table1 has:
```
a | b | c 
---------
1 | 2 | 3 
```
Column 'a' will be renamed to 'x' and my_model will receive input:
```
x | b | c 
---------
1 | 2 | 3 
```
Fixes #4576
Dependent on https://github.com/mindsdb/mindsdb_sql/pull/375
> Model column map

- mindsdb/integrations/handlers/mindsdb_inference/mindsdb_inference_handler.py
- tests/unit/ml_handlers/test_mindsdb_inference.py
This PR updates the MindsDB Inference handler to validate API keys on engine/model creation.
Note: The logic applied the OpenAI handler for this validation does not work with the inference API because the LiteLLM Proxy does not implement the `/models/{model_name}` endpoint, which is called `models.retrieve()`.
Fixes https://github.com/mindsdb/mindsdb/issues/9160
API keys will now be validated on engine/model creation and exceptions will be raised if they are invalid as shown below,
On engine creation:
On model creation:
> MindsDB Inference - Fixed Validation of API Keys on Model/Engine Creation

- .github/workflows/test_on_push.yml
- mindsdb/integrations/handlers/litellm_handler/settings.py
- mindsdb/integrations/handlers/mindsdb_inference/settings.py
- mindsdb/integrations/handlers/ms_teams_handler/settings.py
- mindsdb/integrations/handlers/mysql_handler/settings.py
- mindsdb/integrations/handlers/twelve_labs_handler/settings.py
- mindsdb/integrations/libs/llm/config.py
- mindsdb/integrations/libs/llm/utils.py
- requirements/requirements.txt
Fixes #9185
I've had to rename some pydantic model fields to avoid the protected namespace in pydantic v2.
> Fix pydantic warnings

- LICENSE
- docker/mindsdb.Dockerfile
This change makes a large portion of the docker build time (pip installing all our requirements) be able to be cached more often.
Cache misses were happening when almost any file changed in the repo, and most requirements would have to be installed again without being cached.
In this PR we instead:
- create a layer containing *only* the files required to run `pip install .` (requirements files, `setup.py` etc).
- Copy files from this layer and run `pip install .` and `pip install .[<extras>]` (this will now only miss if a requirements file or `setup.py` etc have changed)
- *Now* copy the whole repo into the container and run `pip install .` again - this will only install MindsDB itself
- Continue with the build as before
> Improve caching of docker builds

- docs/mindsdb_sql/sql/api/finetune.mdx
- docs/mindsdb_sql/sql/api/join.mdx
- docs/mindsdb_sql/sql/api/retrain.mdx
- docs/mindsdb_sql/sql/create/jobs.mdx
- docs/mindsdb_sql/sql/create/model.mdx
- docs/sdks/python/agents.mdx
updates to sql api docs, covering recent developments by @ea-rus 
> updates to sql api docs

- mindsdb/integrations/handlers/chromadb_handler/settings.py
- mindsdb/integrations/handlers/email_handler/settings.py
- mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
- mindsdb/integrations/handlers/lightfm_handler/lightfm_handler.py
- mindsdb/integrations/handlers/litellm_handler/litellm_handler.py
- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
- mindsdb/integrations/handlers/mysql_handler/settings.py
- mindsdb/integrations/handlers/palm_handler/palm_handler.py
- mindsdb/integrations/handlers/rag_handler/rag.py
- mindsdb/integrations/handlers/rag_handler/settings.py
- mindsdb/integrations/handlers/sentence_transformers_handler/sentence_transformers_handler.py
- mindsdb/integrations/handlers/twelve_labs_handler/settings.py
- mindsdb/integrations/handlers/utilities/validation_utilities/parameter_validation_utilities.py
- mindsdb/integrations/handlers/writer_handler/rag.py
- mindsdb/integrations/handlers/writer_handler/settings.py
- mindsdb/integrations/handlers/writer_handler/writer_handler.py
- mindsdb/integrations/utilities/rag/settings.py
There are a few more things changed between pydantic V1 and V2. I've run through this migration guide: https://docs.pydantic.dev/latest/migration/
> Pydantic V2 migration

- requirements/requirements.txt
This PR upgrades Werkzeug to 2.3.8 version to fix https://github.com/mindsdb/mindsdb/security/dependabot/87. Note, we can't upgrade to the latest v3 due to required changes in Flask, then in Flask restx which is still not fully compatible https://github.com/python-restx/flask-restx?tab=readme-ov-file#on-flask-compatibility.
Fixes #https://github.com/mindsdb/mindsdb/security/dependabot/87
> Upgrade Werkzeug to 2.3.8

- mindsdb/integrations/handlers/llama_index_handler/requirements.txt
This PR upgrades llama-hub version to solve https://github.com/mindsdb/mindsdb/security/dependabot/114
> Upgrade llama-hub version

- docs/integrations/data-integrations/scylladb.mdx
- mindsdb/integrations/handlers/cassandra_handler/README.md
- mindsdb/integrations/handlers/scylla_handler/README.md
- mindsdb/integrations/handlers/scylla_handler/scylla_handler.py
This PR fixes the auth mechanism for the ScyllaDB handler (and as a result, the Cassandra handler) to enforce it only if the parameters are provided.
Fixes https://github.com/mindsdb/mindsdb/issues/9215
> Fixed Auth Mechanism for ScyllaDB/Cassandra

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
This PR achieves the following,
1. Fixes the `conversational` model by fixing the issue mentioned below.
2. Removes some code centered around the `assistant_column` that seems redundant. As shown [here](https://github.com/mindsdb/mindsdb/blob/e62634a828488364bc65ab6816c701874884e723/mindsdb/integrations/handlers/openai_handler/openai_handler.py#L143), this column no longer seems to be in the expected list of arguments. @paxcema Let me know what your thoughts are on this.
Fixes https://github.com/mindsdb/mindsdb/issues/9226
`conversational` mode:
`conversational-full` mode:
> Fixed OpenAI Conersational Model

- mindsdb/integrations/handlers/openai_handler/constants.py
This PR adds support to `gpt-4o` to the OpenAI Engine.
Fixes #9210 
> Add gpt-4o

- requirements/requirements.txt
This PR upgrades Flask version to solve https://github.com/mindsdb/mindsdb/security/dependabot/16.
> Upgraded Flask Version

- mindsdb/integrations/handlers/rag_handler/settings.py
- mindsdb/integrations/handlers/writer_handler/settings.py
This PR corrects the import of the field_validator of Pydantic in the RAG and Writer handlers.
Fixes https://github.com/mindsdb/mindsdb/issues/9242
> Fixed Pydantic Import for field_validator in RAG and Writer

- mindsdb/integrations/handlers/couchbase_handler/couchbase_handler.py
This PR adds a check for couchbase cloud host in allowlist instead of string matching.
Fixes https://github.com/mindsdb/mindsdb/security/code-scanning/11
> Check for domain in allowed list

- mindsdb/api/http/namespaces/agents.py
- mindsdb/api/http/utils.py
This PR adds default http_error messages if not provided when raising the exception.
Fixes https://github.com/mindsdb/mindsdb/security/code-scanning/8
> Default http_error messages

- mindsdb/api/executor/datahub/datanodes/integration_datanode.py
Fix error "'list' object has no attribute 'dtypes'" for select from native query with no data
> Fix: select from native query with no data

- .github/workflows/build_deploy_prod.yml
This PR adds a job to the production workflow that deploys MindsDB artifacts to trigger a new release of the Docker Desktop extension. This is done by triggering [this workflow](https://github.com/mindsdb/mindsdb-docker-extension/blob/main/.github/workflows/bump-mindsdb-version.yml) setup in the repository for the extension.
Fixes https://github.com/mindsdb/mindsdb-docker-extension/issues/6
Fixes https://github.com/mindsdb/mindsdb_private/issues/575
> Added Job to Trigger a Release of the Docker Desktop Extension

- mindsdb/api/http/initialize.py
The issue involves the GUI version download for MindsDB when using Docker or self-hosted setups. Currently, MindsDB always downloads the latest GUI version, regardless of the installed MindsDB version. This mismatch causes confusion about which GUI version is compatible with the installed MindsDB version.
**Expected Behavior with Changes:**
- Download the correct GUI version based on the [compatible-json](https://mindsdb-web-builds.s3.amazonaws.com/compatible-config.json) file.
- Retain the same GUI version if no update is needed.
> [FIX] - Download correct GUI version

- docs/mint.json
- docs/setup/cloud/aws-marketplace.mdx
added aws marketplace as installtion option in docs
> added aws marketplace as installtion option in docs

- docs/use-cases/data_enrichment/json-from-text.mdx
- mindsdb/integrations/handlers/openai_handler/openai_handler.py
- tests/unit/ml_handlers/test_openai.py
Deprecate `input_text` keyword argument in favor of `prompt_template` when using `json_struct` mode, both for UX streamlining and also to enable multi-column support.
Example queries change from this:
```
CREATE MODEL mindsdb.nlp_model
PREDICT json
USING
engine = 'openai_engine',
json_struct = {
'rental_price': 'rental price',
'location': 'location',
'nob': 'number of bathrooms'
},
input_text = 'sentence';
SELECT json
FROM mindsdb.nlp_model
WHERE sentence = 'Amazing 3 bedroom apartment located at the heart of Manhattan, has one full bathrooms and one toilet room for just 3000 a month.';
```
To this:
```
CREATE MODEL mindsdb.nlp_model
PREDICT json
USING
engine = 'openai_engine',
json_struct = {
'rental_price': 'rental price',
'location': 'location',
'nob': 'number of bathrooms'
}, …
```
> [ENH] Migrate OpenAI's json_struct mode to use prompt template

- mindsdb/api/executor/datahub/datanodes/integration_datanode.py
- mindsdb/api/executor/datahub/datanodes/system_tables.py
- tests/unit/executor_test_base.py
- tests/unit/test_project_structure.py
If remote database or other project exists in query filter for `information_schema.columns` table:
```sql
SELECT * FROM information_schema.columns
WHERE table_schema='example_db';  -- or table_schema in ('example_db', 'project1')
```
Mindsdb queries columns from connected database (using get_tables, get_columns handler methods)
Why don't query all databases by default: fetching columns from every tables could take a lot of time. For me example_db returns it for 10 sec.
> Support querying columns from connected database

- mindsdb/integrations/handlers/huggingface_handler/requirements.txt
- mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
This PR fixes the dependencies for the HuggingFace handler and makes it usable by pinning the `datasets` package to 2.16.1. The issue mentioned below seems to be a result of using an incompatible version of `datasets` with `pyarrow`.
The newly pinned version of the package works with `pyarrow=11.0.0`, which is a dependency for our BYOM handler (the BYOM handler is one of our default handlers, so this version of `pyarrow` comes pre-installed).
Fixes https://github.com/mindsdb/mindsdb/issues/9056
> Updated Dependencies to Make the HuggingFace Integration Usable

- mindsdb/integrations/utilities/sql_utils.py
Fixes error in shopify handler with query having IN:
```sql
select * from orders
where total_price in (168, 59148, 25);
```
It wasn't properly rendered for executing in duckdb 
> Fix: wrap list into Tuple for proper rendering

- mindsdb/api/http/namespaces/tree.py
- mindsdb/interfaces/database/database.py
- tests/unit/test_executor.py
`drop database` was case sensitive:
```sql
CREATE DATABASE POSTGRES WITH ENGINE = 'postgres' ...;
DROP DATABASE postgres; -- error
```
> Fix case sensitive `drop database`

- docs/integrations/ai-engines/minds_endpoint.mdx
This PR fixes the link to the Minds Endpoint handler in the documentation.
Fixes https://github.com/mindsdb/mindsdb/issues/9459
> Fixed the Link to Minds Endpoint Handler

- docs/integrations/data-integrations/snowflake.mdx
- mindsdb/integrations/handlers/snowflake_handler/README.md
- mindsdb/integrations/handlers/snowflake_handler/requirements.txt
- mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
This PR pins the new release of `snowflake-sqlalchemy` that supports SQLAlchemy 2. Here is the relevant reference: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/380
In relation to this change, the following has also been done:
1. A previously added tip to install Git (when using Docker) in order to support the use of the forked repository for the above package has been removed from the documentation and the README.
2. The imports in the handler have been re-organized to prevent a circular dependency issue.
Fixes https://github.com/mindsdb/mindsdb/issues/9024
> Pinned New Version of snowflake-sqlalchemy Supporting SQLAlchemy 2

- mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
This PR updates the LangChain handler to use `ChatOpenAI` from `langchain_openai` instead of `langchain_community`, which has been depreciated and does not support the use of GPT-4o.
Fixes https://github.com/mindsdb/mindsdb/issues/9406
> Upated LangChain Handler to Use langchain_openai (Support for GPT-4o)

- mindsdb/integrations/handlers/rag_handler/rag_handler.py
- mindsdb/interfaces/skills/skill_tool.py
Code now includes warnings about the upcoming deprecation of the RAG handler and certain skills that encourages users to migrate to supported methods. The RAG handler will be completely removed in v24.8.x.x. Additionally, an informative warning is shown for skills that are now deprecated, recommending the retrieval skill as an alternative.
CC: @martyna-mindsdb - FYI - doc updates required. More background [here](https://docs.google.com/document/d/1yAkHNm7b-CP7JKBrVrWrcwPP9vzCMueQLo2Ej_wXtN0/edit)
next steps:
- update docs
- include a note on these changes in the next release notes
> Add deprecation warnings for RAG handler and kb skill

- mindsdb/integrations/handlers/dspy_handler/requirements.txt
This PR removes Litellm as a dependency from Dspy integration
Fixes #https://github.com/mindsdb/mindsdb/security/dependabot/150
> Update requirements.txt in Dspy

- mindsdb/interfaces/file/file_controller.py
- mindsdb/utilities/config.py
At the moment default storage type is `local`. This means that each item will be copied for backup.
That is not necessary if run mindsdb locally.
> Change default storage type to `absent`

- mindsdb/api/executor/command_executor.py
- mindsdb/interfaces/agents/agents_controller.py
- mindsdb/migrations/versions/2024-07-19_45eb2eb61f70_add_provider_to_agent.py
Changes:
- copy detected provider in runtime to agent.provider
- don't use agent.params['model_name'], use agent.model_name
- copy model_name in migrations
> Fix for agent decoupling fixex

- docs/mint.json
currently this functionality is not available and it will be refined in future ([as mentioned here](https://mindsdbcommunity.slack.com/archives/C01S2T35H18/p1721742012436429?thread_ts=1720615623.582209&cid=C01S2T35H18)), so hiding this doc page for now
> hide data insights docs

- mindsdb/integrations/handlers/crate_handler/crate_handler.py
- mindsdb/integrations/handlers/crate_handler/requirements.txt
The [CrateDB SQLAlchemy dialect](https://github.com/crate-workbench/sqlalchemy-cratedb) needs more love, so it was separated from the [DBAPI HTTP driver](https://github.com/crate/crate-python). This patch intends to accompany the migration.
The new canonical package for the SQLAlchemy CrateDB dialect on PyPI is:
> https://pypi.org/project/sqlalchemy-cratedb/
/cc @hammerhead, @hlcianfagna, @surister
> Dependencies: Migrate from `crate[sqlalchemy]` to `sqlalchemy-cratedb`

- mindsdb/interfaces/agents/langchain_agent.py
Removed `return_direct` from tool config. It allows to send results from tool too llm for preparing response
> Fix: agent with KB skill returns results directly 

- mindsdb/integrations/handlers/ollama_handler/ollama_handler.py
Add a default mode for inference when calling the Ollama API. This avoids confusing behavior with JSON parsing errors or None types coming back in a SQL response. It also provides a reasonable default when a configuration hasn't specified which mode to use.
This fixes a situation where an JSON error is returned for a query:
```
ERROR:  [ollama_engine/llama3_1]: JSONDecodeError: Extra data: line 1 column 5 (char 4)
```
To ensure the changes are working as expected: Follow the [instructions](https://docs.mindsdb.com/integrations/ai-engines/ollama) to setup and run a prediction using ollama.
> Default to Generate for Ollama

- mindsdb/integrations/handlers/google_gemini_handler/google_gemini_handler.py
This PR fixes the import of the `get_completed_prompts()` utility function in the Google Gemini handler.
Fixes https://github.com/mindsdb/mindsdb/issues/9536
> Fixed Incorrect Import in Google Gemini Handler

- mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py
Fixes:
- Update model_args from `using`
- `season_length` is optional model arg
Fix of #9465
Error is reproduced by learning hub example. Also in [community](https://mindsdbcommunity.slack.com/archives/C01S2T35H18/p1722597772533589) 
> Fix Statsforecast: KeyError: 'season_length'

- mindsdb/integrations/handlers/documentdb_handler/connection_args.py
There was an error in dockementdb connection_args: instead of `ARG_TYPE.DICT` there was just dict. Because of it, the connection_args was not be able to dump into json string.
> Fix documentdb connection_args

- mindsdb/interfaces/agents/agents_controller.py
If the agent has a skill that we try to add, then unique constraint will be violated. This fix filter skills with same name when edit agent.
> Fix for add same skill to agent

- mindsdb/interfaces/model/model_controller.py
There was an error: `training_time` in response data was with `timedelta` type. This type is not json serializable. 
> Fix `training_time` type in response

- mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
divides with integer output instead of float so that performing a for loop in range will not throw an error.
Fixes #issue_number #9426
> ensure for loop range is performed on integer and not a float

- mindsdb/integrations/handlers/llama_index_handler/requirements.txt
This PR upgrades LlamaIndex to the latest `0.10.13` version
Fixes #https://github.com/mindsdb/mindsdb/security/dependabot/130
> Upgrade Llamaindex to latest

- docs/mindsdb_sql/sql/create/file.mdx
- mindsdb/api/http/namespaces/file.py
- mindsdb/utilities/security.py
This PR Allows file upload URLs only from trusted domains as s3, g drive, azure blob.
Fixes https://linear.app/mindsdb/issue/BE-53/[dns-rebinding]-file-upload-from-url
- Google Drive file upload:
> FileUpload from  allowed domains

- .github/workflows/test_on_push.yml
Previous addition of ignore-paths in the test-on-push workflow have meant that some required checks don't run for docs updates.
This PR checks if any non-docs files have changed first, and if NOT, then it skips all the steps in the required checks (but importantly the jobs still 'run' and a docs PR can be merged).
> Update skip process for docs updates

- mindsdb/api/executor/command_executor.py
- tests/unit/executor/test_base_queires.py
Fix: prevent of creating alias with multiple parts for system variable
Fixes #9554
> Fix: "Alias can not contain multiple parts" error

- mindsdb/interfaces/database/integrations.py
In the original version type of handler was get from handler module. But module may be `None` if import is not success. 
From other side, `handler_meta` should always exists if handler folder exists, regardless of import status.
> Improved getting of handler type

- mindsdb/interfaces/database/integrations.py
When database is used by knowledge base and user tries to delete it, the error is:
After this PR it will be:
> Delete dbl: show error if it is used by KB

- docs/integrations/ai-engines/llamaindex.mdx
- docs/integrations/app-integrations/web-crawler.mdx
- docs/mindsdb_sql/sql/create/file.mdx
- mindsdb/api/http/namespaces/file.py
- mindsdb/integrations/handlers/llama_index_handler/README.md
- mindsdb/integrations/handlers/llama_index_handler/llama_index_handler.py
- mindsdb/integrations/handlers/web_handler/README.md
- mindsdb/integrations/handlers/web_handler/web_handler.py
- mindsdb/utilities/config.py
- mindsdb/utilities/security.py
This PR adds two `config.json` keys to limit the allowed hosts for File Upload from URL and crawling sites for Web Crawler and LalamaIndex WebPageReader.
Fixes #https://linear.app/mindsdb/issue/BE-54/[dns-rebinding]-web-handler-and-lalamaindex-web-page-reader
If only `docs.mindsdb.com` is added to `web_crawling_allowed_sites`
> Crawl only allowed sites

- requirements/requirements.txt
This PR pins the version of the `langchain-nvidia-ai-endpoints` for compatibility with `langchain-core`.
It can be seen [here](https://github.com/langchain-ai/langchain-nvidia/compare/libs/ai-endpoints/v0.1.7...libs/ai-endpoints/v0.2.0) that in the change log for release 0.2.0 of `langchain-nvidia-ai-endpoints`, the minimum version of `langchain-core` has been bumped up to 0.1.47, which is incompatible with our 0.1.46.
Fixes https://github.com/mindsdb/mindsdb/issues/9690
> Pinned Package Version of langchain-nvidia-ai-endpoints for Compatibility

- .github/workflows/test_on_push.yml
Github doesn't allow access to vars on PRs from forks for some reason.
So we can't use our CI python version var here without making things really messy.
> Fix static checks on forks

- mindsdb/api/mongo/server.py
- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
Removed creation of cert file in mongo server, default ssl cert file is used instead
> Use default ssl certificate for mongo server

- mindsdb/interfaces/storage/db.py
Adds the field `created_at` to skills response.
> Add `created_at` field to skills response

- mindsdb/api/http/namespaces/databases.py
- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
- Add option to `GET /database` endpoint that allows to check database connection
-  Set default connection timeout for mysql handler to 10s
> Option to check connection for `GET /database` endpoint

- mindsdb/api/executor/command_executor.py
- mindsdb/interfaces/database/integrations.py
Don't add handler instance to cache when it is initialized for importing files. If it is added to cache - it will try to connect but because credentials not imported - connect will be failed
> Fix Teams: don't connect when handler files are imported

- mindsdb/integrations/handlers/bedrock_handler/bedrock_handler.py
- mindsdb/integrations/handlers/bedrock_handler/settings.py
This PR updates the `AmazonBedrockHandlerModelConfig` Pydantic model of the Amazon Bedrock integration by converting the `model_id` parameter to `id` in order to dismiss the warning given below that is displayed when MindsDB is started up:
`/usr/local/lib/python3.10/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_id" in AmazonBedrockHandlerModelConfig has conflict with protected namespace "model_".`
> Updated the Pydantic Model for Amazon Bedrock to Dismiss Warning

- mindsdb/interfaces/skills/sql_agent.py
Changes
- only Select query is allowed
- if list tables is defined, don't allow to use other tables
> Agent permissions

- mindsdb/integrations/handlers/postgres_handler/connection_args.py
- mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
This allows to use or redefine any connection parameters for postgres (and any dependent) handler
```sql
CREATE DATABASE example_db_xxx3
WITH ENGINE = "postgres",
PARAMETERS = {
"user": "demo_user",
"password": "demo_password",
"host": "samples.mindsdb.com",
"port": "5432",
"database": "demo",
"schema": "demo_data",
"connection_parameters": {
"connect_timeout": 30
}
};
```
> Allow to use/redefine any connection parameters for Postgres handler

- mindsdb/interfaces/agents/langchain_agent.py
- mindsdb/interfaces/agents/langfuse_callback_handler.py
Fixes https://linear.app/mindsdb/issue/CLOUD-458/langfusenotfounderror-error
See https://github.com/orgs/langfuse/discussions/2879 for more context.
To ensure all batched traces are sent to Langfuse before fetching traces that should exist, we add a call to `flush` before `get_trace`.
This PR also adds error handling to `get_trace`. We should extend this work by implementing similar error handling for _all_ code paths that use Langfuse, not just `get_trace`.
> Add Flush to Langfuse & Handle Errors Properly for Getting Traces

- docs/integrations/data-integrations/sap-hana.mdx
- mindsdb/integrations/handlers/hana_handler/README.md
- mindsdb/integrations/handlers/hana_handler/tests/test_hana_handler.py
This PR updates the incorrect uses of `host` in the docs for the SAP Hana integration to `address`.
> Updated the Uses of host in the SAP Hana Integration Docs to address

- mindsdb/api/executor/sql_query/result_set.py
When two dataframes are concatenated, the resulting dataframe will have duplicate indexes.
```python
a = df([1,2,3], columns=['a'])
b = df([1,2,3], columns=['a'])
pandas.concat([a, b]).index
```
this is cause of error here https://github.com/mindsdb/mindsdb/blob/main/mindsdb/integrations/libs/ml_exec_base.py#L247
```
ValueError: cannot reindex on an axis with duplicate labels
```
> Reset index when join dataframes

- docker-compose.yml
- mindsdb/interfaces/agents/langchain_agent.py
Without this any agentic calls fail if LangFuse is offline or temporarily unavailable due to the uncaught exception of auth.  Also adds the "release" into the init and adds example values into the docker compose file
> Langfuse minor fix during login/auth

- mindsdb/integrations/handlers/ms_teams_handler/ms_graph_api_teams_client.py
- mindsdb/integrations/handlers/ms_teams_handler/ms_teams_handler.py
- mindsdb/integrations/handlers/ms_teams_handler/settings.py
- mindsdb/interfaces/chatbot/chatbot_task.py
- mindsdb/interfaces/chatbot/memory.py
- mindsdb/interfaces/chatbot/polling.py
This PR improves the MS Teams chat-bot with the ability to respond in channels.
In the process of doing so, the following improvements have been made to the chat-bot interface,
1. Added support for tables whose rows are unique based on a composite key. At the moment, the `chat_id_col` parameter of the config only accepts a single ID column, but in the case of the `channels` and `channel_messages` table of the MS Teams integration, rows are uniquely identified based both the team ID and channel ID.
2. Added support for chat-bots that require multiple polling tasks. With the current implementation, only a single polling task is supported per chat-bot. However, for the MS Teams integration, two message count polling tasks are required for chat messages and channel messages.
Fixes …
> Chat-bot Support for Multiple Tables and Multiple ID Columns (MS Teams Chat-bot for Channels)

- mindsdb/integrations/handlers/byom_handler/byom_handler.py
If exception raised during BYOM engine creation and engine type is 'inhouse', then correct error message is missed, because new exception raised when try to delete venv.
> Delete venv only if BYOM use it

- mindsdb/integrations/utilities/rag/loaders/vector_store_loader/MDBVectorStore.py
- mindsdb/integrations/utilities/rag/loaders/vector_store_loader/vector_store_loader.py
- mindsdb/integrations/utilities/rag/settings.py
- mindsdb/interfaces/agents/tools.py
- tests/unit/executor/test_agent.py
Created adapter with which langchain can access to mindsdb knowledge base as to vector store.
Langchain is used in RAG pipeline during executing retrieval skill. This adapter should allow to use any mindsdb vector store type  by langchain
Fixes https://linear.app/mindsdb/issue/BE-81/pgvector-integration-testing
> Langchain adapter for mindsdb KB

- mindsdb/api/http/namespaces/agents.py
- mindsdb/interfaces/agents/tools.py
Fixes:
1. fixed error for stream mode when retrieval skill is used
Workaround before fix: add this param manually:
```python
agent = con.agents.create(
name=f'ollama_agent_retr',
skills=['retrieval_skill'],
model='mistral',
provider='ollama',
params={
'mode': 'retrieval',   #  <---------------------------------------------------
'base_url': 'http://localhost:11434',
"embedding_model_args": {"model": "nomic-embed-text", 'class': 'OllamaEmbeddings'}
}
)
```
2. Fixed error if  OPENAI_API_KEY env variable is not defined
```
validation error for OpenAIEmbeddings\n__root__\n  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
```
To ensure the changes are …
> Fix retrieval skill for stream mode

- mindsdb/integrations/handlers/chromadb_handler/README.md
The port is string datatype in code but is given as integer in chromadb handler docs. Fixed the documentation.
Fixes #9872 
> Chromadb connect doc

- .github/workflows/build_deploy_dev.yml
- .github/workflows/build_deploy_prod.yml
- .github/workflows/build_deploy_staging.yml
- .github/workflows/test_on_push.yml
Due to changes to deal with PRs coming from forks, all workflows are currently running in the same concurrency group, and cancelling each other.
This solves the issue by using `head` ref in the concurrency group to use the source branch with `pull_request_target` workflows.
> Fix concurrency in github actions

- docs/integrations/ai-engines/neuralforecast.mdx
This PR fixes a typo in the [Nixtla's NeuralForecast Integration with MindsDB](https://docs.mindsdb.com/integrations/ai-engines/neuralforecast) page.
- Locate the [Nixtla's NeuralForecast Integration with MindsDB](https://docs.mindsdb.com/integrations/ai-engines/neuralforecast) page and ensure the typo is fixed in the above section after merge and deployment.
> DOCS: Fix Typo on Nixtla's NeuralForecast Integration Page

- docs/generative-ai-tables.mdx
This PR fixes 2 typos in the [Generative AI Tables](https://docs.mindsdb.com/generative-ai-tables) page.
- Locate the [Generative AI Tables](https://docs.mindsdb.com/generative-ai-tables) page and ensure the typos are fixed in the above sections after merge and deployment.
> DOCS: Fix Typos on Generative AI Tables Page

- docs/use-cases/data_enrichment/overview.mdx
This PR fixes a typo in the [Data Enrichment Overview](https://docs.mindsdb.com/use-cases/data_enrichment/overview) page.
- Locate the [Data Enrichment Overview](https://docs.mindsdb.com/use-cases/data_enrichment/overview) page and ensure the typo is fixed in the above section after merge and deployment.
> DOCS: Fix Typo on Data Enrichment Overview Page

- docs/use-cases/ai_agents/create-chatbot.mdx
This PR fixes a typo on the page of [Build a Chatbot with a Text2SQL Skill](https://docs.mindsdb.com/use-cases/ai_agents/create-chatbot).
- Locate the [Build a Chatbot with a Text2SQL Skill](https://docs.mindsdb.com/use-cases/ai_agents/create-chatbot) page and ensure the typo is fixed in the above section after merge and deployment.
> DOCS: Fix Typo on Build a Chatbot with a Text2SQL Skill Page

- docs/use-cases/ai_agents/create-chatbot-kb.mdx
This PR fixes a typo on the page of [Build a Chatbot with a Knowledge Base](https://docs.mindsdb.com/use-cases/ai_agents/create-chatbot-kb).
- Locate the [Build a Chatbot with a Knowledge Base](https://docs.mindsdb.com/use-cases/ai_agents/create-chatbot-kb) page and ensure the typo is fixed in the above section after merge and deployment.
> DOCS: Fix Typo on Build a Chatbot with a Knowledge Base Page

- docs/setup/self-hosted/docker.mdx
This PR fixes a typo in the [Docker for MindsDB](https://docs.mindsdb.com/setup/self-hosted/docker) page.
- Locate the [Docker for MindsDB](https://docs.mindsdb.com/setup/self-hosted/docker) page and ensure the typo is fixed in the above section after merge and deployment.
> DOCS: Fix Typo on Docker for MindsDB Page

- docs/setup/self-hosted/docker-desktop.mdx
- docs/setup/self-hosted/docker.mdx
This PR fixes a typo in the [Docker Desktop Extension](https://docs.mindsdb.com/setup/self-hosted/docker-desktop) page.
- Locate the [Docker Desktop Extension](https://docs.mindsdb.com/setup/self-hosted/docker-desktop) page and ensure the typo is fixed in the above section after merge and deployment.
> DOCS: Fix Typo on Docker Desktop Extension Page

- docs/integrations/ai-engines/timegpt.mdx
This PR fixes a typo in the [Nixtla's TimeGPT Integration](https://docs.mindsdb.com/integrations/ai-engines/timegpt) page.
- Locate the [Nixtla's TimeGPT Integration](https://docs.mindsdb.com/integrations/ai-engines/timegpt) page and ensure the typo is fixed in the above section after merge and deployment.
> DOCS: Fix Typo on Nixtla's TimeGPT Integration Page

- docs/integrations/ai-engines/replicate-audio.mdx
This PR fixes 3 typos in the [Replicate (Audio)](https://docs.mindsdb.com/integrations/ai-engines/replicate-audio) page.
- Locate the [Replicate (Audio)](https://docs.mindsdb.com/integrations/ai-engines/replicate-audio) page and ensure the typos are fixed in the above sections after merge and deployment.
> DOCS: Fix Typos on Replicate (Audio) Page

- mindsdb/api/common/check_auth.py
- mindsdb/api/http/namespaces/default.py
- mindsdb/api/mongo/classes/session.py
- mindsdb/utilities/config.py
- tests/integration_tests/flows/config/config.json
- tests/integration_tests/flows/config/docker_config.json
- tests/integration_tests/flows/test_mysql_api.py
- tests/integration_tests/flows/test_mysql_bin_api.py
This PR enables HTTP authentication credentials to be set via environment variables as well as via the configuration file.
It is, of course, recommended that environment variables be used for this purpose as mentioned in the documentation.
> Enabled Authentication via Environment Variables and the Configuration File

- mindsdb/interfaces/chatbot/chatbot_task.py
This PR updates the chat-bot logic to send an immediate response upon receiving a message. This quick reply aims to engage the user and maintain their attention while the full response is being generated.
Fixes https://linear.app/mindsdb/issue/BE-264/give-the-perception-of-immediate-response-for-the-user-by-giving-the
Fixes https://linear.app/mindsdb/issue/BE-268/give-the-perception-of-immediate-response-for-the-user-by-giving-the
Slack Chat-bot:
MS Teams Chat-bot:
> Added Holding Messages to Chat-bot Responses

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
This allows the OpenAI handler to work correctly in all 3 modes, instead of just the third, by fixing a bug in assigning the prompt when not available.
3 Modes for reference: 
1. a prompt_template
2. a question_column and an optional context_column
3. a prompt, user_column and assistant_column
Fixes ML-147 
https://github.com/mindsdb/mindsdb/issues/9716
Fixes #9716
> Fixing OpenAI conversational mode prompt requirements

- mindsdb/api/http/initialize.py
- mindsdb/interfaces/agents/langchain_agent.py
- mindsdb/utilities/context.py
- requirements/requirements.txt
This PR embeds more data into langfuse traces for the purpose of following along a specific user's journey/session.
Need to handoff this data via the gateway first into the headers for this to work, there's a similarly named branch in mindsdb which uses this. Is backwards compatible as well so won't break if done in a weird order.
Paired PR on Gateway: https://github.com/mindsdb/mindsdb_gateway/pull/966
> Adding new user and session id into traces for langfuse

- mindsdb/api/http/namespaces/tree.py
- mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
For `GET /tree` added a path option to enable output all database schemas (not only default).
Name of the options is `all_schemas`, may be changed later.
> Option to return all handlers' schemas

- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
fix: cannot adapt type 'dict' using placeholder '%s' (format: AUTO)
Fixes:
- convert metadata to string 
Fixes error: psycopg.ProgrammingError: cannot adapt type 'dict' using placeholder '%s' (format: AUTO)
> Fix pgvector metadata column

- docs/integrations/ai-engines/replicate-audio.mdx
- docs/integrations/ai-engines/replicate-img2text.mdx
- docs/integrations/ai-engines/replicate-llm.mdx
- docs/integrations/ai-engines/twelvelabs.mdx
- docs/integrations/app-integrations/dockerhub.mdx
- docs/integrations/app-integrations/youtube.mdx
This PR fixes typos on the following pages.
- https://docs.mindsdb.com/integrations/ai-engines/replicate-audio
- https://docs.mindsdb.com/integrations/ai-engines/replicate-img2text
- https://docs.mindsdb.com/integrations/ai-engines/replicate-llm
- https://docs.mindsdb.com/integrations/ai-engines/twelvelabs#twelevelabs-video-semantic-search
- https://docs.mindsdb.com/integrations/app-integrations/dockerhub
- https://docs.mindsdb.com/integrations/app-integrations/youtube
Please visit the pages listed above and check for the typo corrections.
> DOCS: Fix typos on multiple pages on the Docs site

- mindsdb/api/executor/sql_query/steps/join_step.py
- mindsdb/api/executor/sql_query/steps/subselect_step.py
- requirements/requirements.txt
- tests/unit/executor/test_base_queires.py
Updates:
Subselect step is used to get value from previous step data.
```sql
select distinct <column> from <step data1>
```
Next step is fetching data using these values as filter
```sql
select * from db2.table2 where <column> in (<ids from previous step>)
```
Side fix: 
If join is without condition:
- add `0=0` filter (multiply rows)
- but use limitation. If expected number of rows is exceed limit - raise exception
Dependent on https://github.com/mindsdb/mindsdb_sql/pull/412
- [x My code follows the style guidelines(PEP 8) of MindsDB.
> Optimize join tables from different databases: executor

- mindsdb/interfaces/chatbot/chatbot_controller.py
- mindsdb/interfaces/chatbot/chatbot_task.py
- mindsdb/interfaces/chatbot/model_executor.py
- mindsdb/interfaces/model/model_controller.py
Updates:
- enable using chatbot with model instead of agent
- user info is passed to chatbot model, for now it only user name which can be user id (for example in slack handler)
Demo:
https://www.loom.com/share/7bd4bff67e4a40f4b61af532f59aef68
Fixes https://linear.app/mindsdb/issue/BE-463/send-user-info-alongside-chatbot-answer
Fixes https://linear.app/mindsdb/issue/BE-462/cant-drop-chatbot
> Pass user info to chatbot model

- mindsdb/integrations/handlers/openai_handler/openai_handler.py
This PR enables the use of custom base APIs with the OpenAI integration by re-organizing the logic for setting the `api_base` parameter. Additionally, this change prioritizes the `base_api` parameter set during model creation before that which is set when creating the ML engine.
Fixes https://github.com/mindsdb/mindsdb/issues/10126
> Fixed the OpenAI Integration's Logic for Setting the Base API Parameter

- mindsdb/api/executor/datahub/datanodes/integration_datanode.py
- mindsdb/api/executor/datahub/datanodes/project_datanode.py
- mindsdb/api/executor/sql_query/result_set.py
Updates:
Fixes in create table logic:
- try to infer values in result: 
- if column has floats and None, it is object dtype. It will be converted float dtype with to float and nan values
- convert nan to None in export from resultset
- don't convert None to string (otherwise it inserts 'None' strings to table)
- create view from query with duplicated columns:
- remove duplicated columns in view result
- at the moment they are visible with `_1` suffix
> Fix types in 'create table' 

- mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
For small responses old logic works a bit faster because it doesn't use pandas apply function
Continue of #9974
Fixes https://linear.app/mindsdb/issue/BE-360/tpc-h-benchmarks-improvements
> Mysql server: use old version for small responses

- requirements/requirements.txt
Don't  update pydantic version outside minor version
Fix error in CI which brake agents and minds:
```
pydantic.errors.PydanticUserError: `ConversationSummaryBufferMemory` is not fully defined; you should define `BaseCache`, then call `ConversationSummaryBufferMemory.model_rebuild()`.
```
> Fix pydantic version 

- mindsdb/integrations/handlers/slack_handler/slack_handler.py
- mindsdb/interfaces/chatbot/chatbot_task.py
- mindsdb/interfaces/chatbot/memory.py
- mindsdb/interfaces/chatbot/polling.py
This PR enables Slack chat-bots to respond directly within a thread when a user posts a message in that thread. 
In order to achieve this, a new tables called 'threads' has been introduced to the Slack handler, which will handle all operations related to threads.
A few changes were also required to be made to the chat interfaces to allow multiple chat ID columns and multiple tables to be supported.
Fixes https://linear.app/mindsdb/issue/BE-514/slack-threads-support
**There's a slight limitation here in how the bot handles the memory (previous messages) from the thread until it is first mentioned.** @ZoranPandovski Shall I handle this in another PR?
https://www.loom.com/share/e11f6ce62b3e4d639f71476f0c609270?sid=6fcc7827-8be9-43c9-ba14-53f6aa31 …
> Enabled Slack Chat-bots to Respond in Threads

- docs/integrations/app-integrations/slack.mdx
This PR adds the `threads` table to the Slack documentation.
> Added the `threads` Table to the Slack Documentation

- mindsdb/utilities/render/sqlalchemy_render.py
- requirements/requirements.txt
- tests/unit/render/test_sqlalchemyrender.py
Updates:
- bumped version of parser for supporting of [mixed join](https://github.com/mindsdb/mindsdb_sql_parser/pull/3)
- Render fixes:
- Fixed alias of CASE (was absent)
- Fixed extra cast for division operator:
- `a/b` used to become `a/(cast b as numeric)`
- Disable quoting of mixed-case identifier
- `SELECT Test` used to become `SELECT "Test"`
Fixes https://linear.app/mindsdb/issue/BE-511/tpc-ds-pending-improvments
> TPC-DS fixes

- docker-compose.yml
Auto-restarts containers that are unhealthy in our docker-compose.
Also adds definitions to all containers that restarts the container if it _exits_ on error
> Add auto-heal to auto-restart unhealthy containers in docker-compose

- README.md
In the Readme.md file.
.Before: 
Join our [Slack community](https://mindsdb.com/j
After: 
Join our [Slack community](https://mindsdb.com/joincommunity)
> fix:  Broken Link(for slack) syntax

- mindsdb/__main__.py
- mindsdb/utilities/config.py
- mindsdb/utilities/fs.py
- added config option `max_restart_interval_seconds` that define interval for `max_restart_count`. If it is exceeded, no new restarts will occur. '0' means no limit.
- `process_marks` now works on windows. This means that if the training process fails, the model will be marked as 'error' on Windows as well.
> Add `max_restart_interval_seconds` config option

- mindsdb/integrations/handlers/slack_handler/slack_tables.py
- tests/unit/handlers/test_slack.py
This PR adds unit tests for the other 'APIResource' class implementations of the Slack integration and resolves some bugs discovered in the process.
> Added Unit Tests for Slack Tables and Fixed a Few Bugs

- mindsdb/api/http/initialize.py
- mindsdb/utilities/config.py
Added ability to change default HTTP session lifetime (31 day) if set one of env vars to value in seconds:
- MINDSDB_HTTP_PERMANENT_SESSION_LIFETIME
- FLASK_PERMANENT_SESSION_LIFETIME
Added config option with same meaning:
`config['auth']['http_permanent_session_lifetime']`
[Doc issue](https://github.com/mindsdb/mindsdb/issues/10260)
> Make HTTP session lifetime configurable via env vars

- mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
- mindsdb/utilities/render/sqlalchemy_render.py
- tests/unit/render/test_sqlalchemyrender.py
**Fixes:**
Fix snowflake handler:
- fetch_pandas fails if columns names are duplicated 
- if such error appears: switch to simple fetch
Fix render:
- fix render of 'interval' for snowflake
- it accepts format: interval '1 day'
- TextClause doesn't have operate method, if it is first argument: try to use reverse_operate (and apply operator to second argument)
- disable truediv in render
-  truediv adds cast to 'div' operation
Fixes https://linear.app/mindsdb/issue/BE-475/snowflake-passes-100percent-of-tpc-ds
Fixes https://linear.app/mindsdb/issue/BE-474/snowflake-passes-100percent-of-tpc-h
> Snowflake fixes for TPC benchmarks

- mindsdb/api/executor/sql_query/steps/subselect_step.py
- tests/unit/executor/test_base_queires.py
Fix: 
- Skip checking 'single-path' identifiers, they could be aliases defined inside of a query
Example of query which had error:
```sql
SELECT t1.a + t2.b  col1
FROM db1.tbl1 as t1
JOIN db2.tbl2 as t2 
order by col1
```
col1 is an alias defined in query. Don't try to check it as a column of used tables.
Also col1 could exist in tbl1 table, but if it is defined as alias it will be skipped
Fixes https://linear.app/mindsdb/issue/BE-549/check-positional-indexes-for-sql
> Fix: Table not found for column (don't check alias of a query) 

- docs/integrations/files/csv-xlsx-xls.mdx
- docs/integrations/files/json.mdx
- docs/integrations/files/parquet.mdx
- docs/integrations/files/pdf.mdx
- docs/integrations/files/txt.mdx
docs - update no file size limit
as discussed with the frontend, there is no file size limit when MindsDB runs locally
> docs - update no file size limit

- mindsdb/api/http/namespaces/databases.py
This PR enables temporary storage files to be copied over when creating the integration via the `POST /databases` API. This is currently causing connections created to MS OneDrive via Minds to fail.
Fixes https://linear.app/mindsdb/issue/BE-579/enable-temp-storage-to-be-copied-when-creating-database-via-api
> Enabled Copy Storage for Creating Database via API

- .github/workflows/build_deploy_prod.yml
This PR updates the PyPI deployment workflow to replace the `python setup.py sdist `with python -m build, which ensures PEP 625-compliant filenames.
Fixes https://linear.app/mindsdb/issue/BE-518/[pypi]-deprecation-notice-for-recent-source-distribution-upload-to
> Update sdist to build

- mindsdb/utilities/render/sqlalchemy_render.py
- tests/unit/render/test_from_parser.py
Fix: frame options were skipped by render:
- ROW_NUMBER() OVER(ORDER BY some_column **RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW**)
Fixes https://linear.app/mindsdb/issue/BE-473/redshift-passes-100percent-of-tpc-ds
> Render frame of window function

- mindsdb/metrics/metrics.py
If `prometheus` is not initialized, then it still requests many memory allocations on each quey.
> Disable metrics decorator if `prometheus` not initialized

- mindsdb/api/http/start.py
- mindsdb/integrations/libs/process_cache.py
- mindsdb/utilities/config.py
- env var `MINDSDB_HTTP_SERVER_TYPE` is now obsolete (but still can be used). `MINDSDB_HTTP_SERVER_TYPE` should be used instead.
- MINDSDB_HTTP_SERVER_TYPE can be: waitress (default), flask or gunicorn.
- as alternative, server type can be set in `config['api']['http']['server']['type']`
- HTTP server is now configurable. Relevant options can be set in `config['api']['http']['server']['config']`. Default options are:
```js
//  waitres 
{
"threads": 16,
"max_request_body_size": (1 << 30) * 10,    # 10GB
"inbuf_overflow": (1 << 30) * 10
}
// flask
{}
// gunicorn
{
'workers': min(multiprocessing.cpu_count(), 4),
'timeout': 600,
'reuse_port': True,
'preload_app': True,
'threads': 4
}
```
Any options that are supported by the server can be set there. Except host/port, they are configured in …
> Set HTTP server type and options via `config.json`

- mindsdb/integrations/utilities/query_traversal.py
- tests/unit/executor/test_project_structure.py
Fix query_traversal function: handle function.from_arg
It fixes error such as: `Binder Error: Referenced table "t" not found!`
For this type of query:
```sql
SELECT extract(hour from t.created_at)
FROM example_db.home_rentals as t
JOIN mindsdb.home_rentals_model as m
```
> Fix 'extract' function in joins

- mindsdb/integrations/handlers/github_handler/github_tables.py
- mindsdb/integrations/libs/api_handler.py
- mindsdb/integrations/utilities/sql_utils.py
This PR adds a fallback sort mechanism for `APIResource` implementations to handle ORDER BY clauses (before LIMIT is executed).
Fixes https://linear.app/mindsdb/issue/BE-595/no-default-sort-mechanism-available-for-api-handlers
> Added Fallback Sort Logic for API Resources

- mindsdb/__main__.py
- mindsdb/interfaces/storage/fs.py
- mindsdb/utilities/starters.py
- requirements/requirements.txt
- import `boto3` only if it is required by config. This saves memory.
- replace 3d-part dependency `checksumdir` to buildin `filecmp`. We need only compare dirs, `filecmp` works perfectly for it (and much faster).
- Indirect import of APIs startup functions. This saves decent amount of memory and also reduces the overall startup time significantly. Local tests shows startup time changes in average for APIs:
- http: 12.4s->10.5s (-15%)
- mysql: 9.1->6.5 (-29%)
- mongodb: 9.0->6.5 (-28%)
> Reduce startup time and memory optimizations

- mindsdb/integrations/utilities/rag/rag_pipeline_builder.py
- mindsdb/integrations/utilities/rag/retrievers/__init__.py
- mindsdb/integrations/utilities/rag/retrievers/multi_hop_retriever.py
- mindsdb/integrations/utilities/rag/retrievers/retriever_factory.py
- mindsdb/integrations/utilities/rag/settings.py
- tests/integrations/utilities/rag/retrievers/test_multi_hop_retriever.py
Introduce a new retriever type, `MULTI_HOP`, to the RAG pipeline, enabling multi-hop retrieval functionality. Implement required logic, update the RetrieverType enum, and add corresponding unit tests to ensure proper behavior for various use cases.
A retriever that implements multi-hop question reformulation strategy.
This retriever enhances the standard retrieval process by:
1. Making an initial query to find relevant documents
2. Analyzing the retrieved context to identify information gaps
3. Formulating follow-up questions to fill these gaps
4. Making additional queries with these follow-up questions
This is particularly useful for complex questions that require connecting information from multiple documents.
To ensure …
> Add MultiHopRetriever support to RAG pipeline

- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- mindsdb/integrations/utilities/rag/loaders/vector_store_loader/pgvector.py
Updated query logic in pgvector loader to handle result formatting and ordering based on vector type. Adjusted `pgvector_handler` to retrieve `is_sparse` and `vector_size` from connection arguments instead of `kwargs`.
to validate I created a script to run it using agents - [here ](https://github.com/mindsdb/CW-Internal/blob/main/scripts/nrc_fermi_sparse_agent.py)
> Refactor pgvector utilities and fix query result formatting

- docker/mindsdb.Dockerfile
- docs/setup/environment-vars.mdx
- mindsdb/__main__.py
This PR allows the MindsDB APIs to be started to be defined via the environment variable `MINDSDB_APIS`. This has been added mainly to support Docker users.
The following command can be run to define the APIs to be started when using Docker:
`docker run -p 47334:47334 -p 47335:47335 --name mindsdb_container -e MINDSDB_APIS='http,mysql,mongodb' mindsdb/mindsdb`
This also updates the entrypoint to our Docker image in order to start both the HTTP and MySQL APIs.
Fixes https://linear.app/mindsdb/issue/BE-605/[docker]-define-which-apis-of-mindsdb-to-start
> Added Support for Defining APIs to Start via the Environment Variable MINDSDB_APIS

- docs/setup/self-hosted/docker.mdx
This PR updates the documentation for running MindsDB via Docker by omitting the exposure of the MySQL API's port because as mentioned in the issue below, by default, only the HTTP API is started.
A tip for running the other APIs using the `MINDSDB_APIS` environment variable has also been added. 
Fixes https://linear.app/mindsdb/issue/BE-612/update-the-documentation-for-docker-by-removing-exposure-of-the-mysql
The use of the `MINDSDB_APIS` environment variable depends on https://github.com/mindsdb/mindsdb/pull/10354
> Updated the Documentation for Docker by Omitting the Exposure of the MySQL API's Port

- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- mindsdb/integrations/utilities/rag/loaders/vector_store_loader/pgvector.py
As it is negative inner product order by asc
> standardise op order in pgvector

- mindsdb/utilities/render/sqlalchemy_render.py
- requirements/requirements.txt
Raise error for asof join in sqlachemy render (as it doesn't support it). It is rendered by standard render
**Examples:**
- Questdb:
- Duckdb:
Dependent on https://github.com/mindsdb/mindsdb_sql_parser/pull/5
Fixes:  https://linear.app/mindsdb/issue/BE-608/asof-join-support
> Render asof join render by standard render

- mindsdb/utilities/render/sqlalchemy_render.py
- tests/unit/executor/test_base_queires.py
This PR checks for unregistered keywords in SqlalchemyRender. This fixes the failing integration tests.
Fixes https://linear.app/mindsdb/issue/BE-607/investigate-and-fix-failing-integration-tests
> Added Reserved Keywords to SqlalchemyRender

- docker-compose.yml
- docker/mindsdb.Dockerfile
Edit the entrypoint for our devel docker image to auto-reload on code changes by default.
This makes the image more useful for debugging without the user having to set the entrypoint 
> Run auto-reload on devel container by default.

- mindsdb/api/executor/__init__.py
- mindsdb/api/executor/command_executor.py
- mindsdb/api/executor/data_types/answer.py
- mindsdb/api/executor/datahub/datanodes/project_datanode.py
- mindsdb/api/executor/sql_query/__init__.py
- mindsdb/api/mysql/mysql_proxy/executor/mysql_executor.py
- mindsdb/api/postgres/postgres_proxy/executor/executor.py
- mindsdb/integrations/libs/ml_handler_process/learn_process.py
- mindsdb/interfaces/chatbot/chatbot_controller.py
- mindsdb/interfaces/database/projects.py
- mindsdb/interfaces/database/views.py
- mindsdb/interfaces/model/functions.py
- mindsdb/interfaces/model/model_controller.py
- mindsdb/interfaces/storage/db.py
- mindsdb/migrations/versions/2025-01-15_c06c35f7e8e1_project_company.py
- tests/unit/executor/test_mongodb_server.py
Fixes:
- In local installation company_id=0 (instead of null) is used for projects table  
-  With null value constrain which checks project names is not working
- Side-update: don't import SqlQuery during executor's imports
Fixes https://linear.app/mindsdb/issue/BE-569/duplicate-project-names
> Prevent creating duplicated project names

- mindsdb/api/http/namespaces/sql.py
Currently a number of errors that occur in the HTTP MySQL api are caught and not printed to the console logs. This change prints these errors to the console to aid in debugging.
> Add error logs for caught http api errors

- mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
- mindsdb/integrations/handlers/chromadb_handler/requirements.txt
- mindsdb/integrations/handlers/langchain_handler/requirements.txt
- tests/unit/executor/test_agent.py
Changes:
- adapted chromadb handler for changed API to version 0.6.3
- fixed chromadb version in langchain handler
- it is default handler and used to lead to install latest version of chromadb 
- added unit test to check queries which didn't work with knowledge base:
- `show tables from mykb_chromadb`, the same when clicks on created default chromadb database for KB in objects tree in GUI
- `select * from my_kb` - getting all objects from KB
Fixes https://linear.app/mindsdb/issue/BE-615/chromadb-error-in-latest-mindsdb-version-notimplementederror-in-chroma
> Fixes for updated chromadb version

- mindsdb/api/executor/datahub/datanodes/datanode.py
- mindsdb/api/executor/datahub/datanodes/information_schema_datanode.py
- mindsdb/api/executor/datahub/datanodes/project_datanode.py
- mindsdb/integrations/libs/ml_handler_process/learn_process.py
- mindsdb/interfaces/database/projects.py
- tests/unit/executor/test_schema.py
Fixes:
- added added `schema_name` param to `get_table_columns` method of other datanodes
- implemented getting columns of a view. It is done by selecting first row from view and using columns from result
Fixes https://linear.app/mindsdb/issue/BE-619/mindsdb-agent-cannot-read-data-from-a-skill-that-was-created-based-on
> Fix: agent with skill based on view

- mindsdb/integrations/handlers/file_handler/requirements.txt
- mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_handler.py
- mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_tables.py
- mindsdb/integrations/handlers/web_handler/requirements.txt
- mindsdb/integrations/utilities/files/file_reader.py
- mindsdb/integrations/utilities/handlers/api_utilities/microsoft/ms_graph_api_utilities.py
- requirements/requirements.txt
- tests/scripts/check_requirements.py
Changes:
- copied (to utils) code which handles reading different files format from file handler
- it will be used by other handlers which read files from sources (file handler)
- for one drive handler added support pdf/txt files
-  it is temporal solution, to keep old formats working with old code, and it will be replaced by code from utils
Fixes https://linear.app/mindsdb/issue/BE-635/ms-onedrive-support-for-pdf-docdocx-and-txt-files
> Add types of files to one drive handler: pdf, txt

- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- mindsdb/interfaces/knowledge_base/controller.py
Fixes:
- Fix pgvector types: 
- id type is TEXT
- vector type is without parens
- create table for vector database when kb is created
Used  queries:
```sql
CREATE DATABASE pvec
WITH
ENGINE = 'pgvector',
PARAMETERS = {
"host": "127.0.0.1",
"port": 5432,
"database": "vector",
"user": "postgres"
};
CREATE KNOWLEDGE_BASE kb20
USING
model = embedding_model_hf,
storage = pvec.kb20
insert into kb20 (content)
values ('asdf')
```
> Fix pgvector handler, work with KB

- mindsdb/interfaces/skills/skill_tool.py
Fix agent work with snowflake db (using sql skill)
`get_tables` method of handler can return different names of tables. For snowflake it is in uppercase "TABLE_NAME".
Update in this PR:
- lowercase all columns
- try to find `table_schema` column
- if not exist: no schema is used
- try to find `table_name` column
- if not exist: use first column
Fixes https://linear.app/mindsdb/issue/BE-647/minds-via-sdk-cannot-get-an-answer
> Fix agent snowflake sql skill: table names in upper case

- docs/integrations/app-integrations/web-crawler.mdx
- mindsdb/integrations/handlers/web_handler/README.md
when I use the IN() operator, it lists only pages from one of the listed urls:
the workaround is to use the UNION operator
related PR - https://github.com/mindsdb/mindsdb/pull/7396
> docs - web handler

- mindsdb/interfaces/agents/mindsdb_database_agent.py
- mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_toolkit.py
- mindsdb/interfaces/skills/skill_tool.py
- mindsdb/interfaces/skills/sql_agent.py
- fixed `get_sample` for long string (>100) and not-strings in sample
- added instruction to always escape tables names
- added instruction to enclose the input query between $START$ and $STOP$. It should help from broken input like this:
- query result will be send to agent as text in CSV. Otherwise agent may go crazy if any cell in response contain multi line text, or text with tabs.
> Fix issues with agents

- mindsdb/integrations/handlers/snowflake_handler/requirements.txt
This PR upgrades the snowflake connector to the latest version.
Fixes [#issue_number](https://github.com/mindsdb/mindsdb/security/dependabot/181)
> Upgrade Snowflake connector

- mindsdb/integrations/handlers/snowflake_handler/requirements.txt
- mindsdb/utilities/config.py
This PR adds the default `mindsdb` user for the MySQL API to avoid auth errors in db clients where system user was used by default.
Fixes https://linear.app/mindsdb/issue/BE-671/mysql-cant-connect
> Set default user in MySQL API

- mindsdb/utilities/render/sqlalchemy_render.py
- tests/unit/render/test_sqlalchemyrender.py
Changes:
- overrode `_requires_quotes` internal method of sqlalchemy:
- to not quote string in upper- or mixed-case
- if string is marked as quoted: quote unconditionally
- to be able to mark string: `AttributedStr` is created
- Quoting rules applied to:
- tables
- identifiers 
- aliases
Fixes https://linear.app/mindsdb/issue/BE-663/snowflake-handler-renders-queries-incorrectly
> Fix quoting in render: use same rules for tables/aliases/identifiers

- mindsdb/api/executor/command_executor.py
- mindsdb/api/executor/planner/query_planner.py
- mindsdb/api/executor/sql_query/steps/fetch_dataframe.py
- mindsdb/api/executor/sql_query/steps/subselect_step.py
- mindsdb/integrations/utilities/query_traversal.py
- mindsdb/utilities/render/sqlalchemy_render.py
- tests/unit/executor/test_base_queires.py
Updates:
- added `callstack` parameter for callback in `query_traversal` utility
- it contents all parent nodes (direction: from deepest to outer)
- it can be useful to check parent node in callback
- `answer_single_row_select` was moved from `command_executor` to `QueryStep` of the planner
Fixes: 
- Handle option `cast(<select 1> as FLOAT) / <select 2>`
- The problem with it: it used to update only `select 2` and then skip this whole binary operation (skipping `select1` also)
- Fix render of tuple 
> Fix single line select with subqueries

- mindsdb/integrations/handlers/ms_one_drive_handler/ms_graph_api_one_drive_client.py
This PR fixes the retrieval of child items (items within folders) when using the MS OneDrive integration.
Fixes https://linear.app/mindsdb/issue/BE-672/child-items-in-ms-onedrive-are-retrieved-incorrectly
> Fixed Retrieval of Child Items in MS OneDrive

- mindsdb/integrations/handlers/huggingface_handler/requirements.txt
- mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
- mindsdb/integrations/handlers/writer_handler/requirements.txt
This PR upgrades/pin the NLTK version in writer and hf handlers.
Fixes https://linear.app/mindsdb/issue/BE-697/[urgent]-nltk-cve-2024-39705
>Note; We may get an incompatible version warning due to pined version in Lightwood. We will bump this in Lightwood too but for now it is not breaking any functionality
> Bump nltk version

- requirements/requirements.txt
- tests/unit/executor/test_base_queires.py
- tests/unit/executor/test_executor.py
- tests/unit/executor/test_udf.py
Updated duckdb dependency to latest version
Changes in behavior with version 0.9.1 which are adapted in unit tests:
- order is not the same in selects with join and distinct (without using order by)
- UDF requires matching of input types. In 0.9.1 they were cast automatically 
Fixes https://linear.app/mindsdb/issue/BE-694/[urgent]-duckdb-cve-2024-22682
> Bump duckdb version

- mindsdb/utilities/render/sqlalchemy_render.py
- tests/unit/render/test_sqlalchemyrender.py
Fix render of aliases for snowflake dialect: quoted alias was not quoted after render
Fixes https://linear.app/mindsdb/issue/BE-745/incorrect-sql-render-to-snowflake
> Fix rendering of quoted alias

- mindsdb/migrations/versions/2025-02-14_4521dafe89ab_added_encrypted_content_to_json_storage.py
This PR converts the resource_id column of the json_storage table to `BigInteger` to allow the storage of temporary integration IDs (in Postgres databases) that are generated.
Fixes https://github.com/mindsdb/mindsdb/issues/10513
> Converted the resource_id Column in json_storage to BigInt

- .github/workflows/release_notes.yml
Pass the release event body in as a env var so that bash escapes any special characters
> Fix LLM release notes.

- mindsdb/api/executor/sql_query/steps/union_step.py
- tests/unit/executor/test_base_queires.py
Use duckdb to handle UNION step, it speeds up union operation 
For union 3 tables per 20k records:
- the time was 30s
- tie time become 1.1s 
> Perform UNION step in duckdb

- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- requirements/requirements.txt
Changes:
- `query` method is inherited from postgres handler (used to be from VectorStoreHandler)
It makes pgvector handler support both:
- postgres sql operations when direct queries to this database is used
- work with knowledge base interface because KB controller used VectorStoreHandler methods to work with pgvector
Updated parser with support pgvector operators:
Fixes https://linear.app/mindsdb/issue/BE-630/pgvector-make-enterprise-ready
Dependent on https://github.com/mindsdb/mindsdb_sql_parser/pull/8
> PGvector handler supports sql

- mindsdb/api/http/gui.py
GUI auto update was broken, because used deleted `distutils` instead of `packaging`
> Fix GUI auto update

- mindsdb/integrations/handlers/slack_handler/slack_handler.py
`table_name` parameter was recently added to `subscribe` function of slack handler. But chatbot engine calls `subscribe` function without passing table name there. And it fails to start chatbot
Fixed by adding default value to `table_name` parameter
> Set default table for slack chatbot

- mindsdb/utilities/render/sqlalchemy_render.py
- requirements/requirements.txt
- tests/unit/render/test_from_parser.py
1. Added support  LATERAL JOIN in sqlalchemy render
```sql
SELECT t.name AS name, t.driver AS driver, r.*
FROM tags t INNER JOIN LATERAL
(SELECT longitude, latitude
FROM readings r
WHERE r.tags_id=t.id
ORDER BY time DESC LIMIT 1)  r ON true
WHERE t.name IS NOT NULL
AND t.fleet = 'South'
```
2. Added support `distinct on` in sqlalchemy render
```sql
SELECT DISTINCT ON (t.hostname) * FROM tags t 
```
It is required for [TSBS benchmark](https://github.com/timescale/tsbs)
Dependent on 
- https://github.com/mindsdb/mindsdb_sql_parser/pull/10
- https://github.com/mindsdb/mindsdb_sql_parser/pull/11
> Support `lateral join` and `distinct on` in render

- mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- mindsdb/integrations/libs/vectordatabase_handler.py
- mindsdb/interfaces/knowledge_base/controller.py
- mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
Changes:
- checked/fixed filter by metadata columns in pgvector and chroma handlers:
- it is possible to use metadata columns in where filter (`original_row_id` is key of metadata):
- `select * from kb3 where original_row_id='1' `
- original document id located in metadata.original_row_id
- removed duplicated columns in generated id:
- was `4_content_content_chunk_1`
- will be `4_content_chunk_1` 
- handle delete documents. it is also possible to use metadata columns:
-  `delete from kb3 where original_row_id='1' `
- filter by distance moved to chromadb handler
Related to:
- https://linear.app/mindsdb/issue/PRD-51/313-soft-delete-implementation
- https://linear.app/mindsdb/issue/PRD-49/4311-basic-kb-result-format
Demo …
> KB select/delete by metadata

- docs/integrations/app-integrations/slack.mdx
- mindsdb/integrations/handlers/slack_handler/README.md
This PR fixes the incorrect use of the `channel_id` parameter (with the conversations table) listed in the documentation.
Fixes
> Fixed the Incorrect Use of channel_id with the Conversations Table

- mindsdb/integrations/handlers/confluence_handler/confluence_api_client.py
We were using the entire next url as the cursor value which caused 400 error. Now we extract cursor value not a full url and create a new param dict for each request instead of modifying the original
> Fix cursor pagination in Confluence

- .github/workflows/build_deploy_dev.yml
- .github/workflows/build_deploy_prod.yml
- .github/workflows/build_deploy_staging.yml
Removes the workflow-wide `cancel-in-progress: true` concurrency rules so that the deployment step can have `cancel-in-progress: false` so we stop cancelling deployment part-way through.
> fix concurrency settings for deploys

- mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- mindsdb/integrations/libs/vectordatabase_handler.py
- mindsdb/interfaces/knowledge_base/controller.py
Update of https://github.com/mindsdb/mindsdb/pull/10627:
- 'relevance' column is always in KB table (if not limited by targets)
- 'distance' column is removed
- relevance calculateion is moved to separated functions
- distance and relevance removed from vectordb schema (because they are not columns of vector table)
- tried to simplify logic
> Updated relevance

- .github/workflows/release_notes.yml
- .github/workflows/test_on_push.yml
This PR fixes the GitHub Action for enhancing release notes with the use of a LLM.
Fixes https://linear.app/mindsdb/issue/BE-870/fix-the-github-action-for-generating-release-notes
This issue was caused as a result of an incorrect payload that was being passed in the body of the API call:
The solution here is to use `jq` in order to format the payload better.
> Fixed the Action for Enhancing Release Notes

- mindsdb/interfaces/knowledge_base/controller.py
Added filtering_threshold to the query conditions, and it can be tested using this query:
```
SELECT *
FROM kb_custom_model_ada
WHERE content = "Kindle Voyage" AND reranking_threshold =0.6 LIMIT 5;
```
> Added filtering_threshold in the query

- mindsdb/interfaces/knowledge_base/controller.py
This PR accomplishes the following:
1. The logic where the API key for providers is set using value passed in the parameters directly has been updated to use the lowercase of that value.
2. The bug where the `model` is being extracted from the parameters and set to `model_name` for the arguments to the class has been reversed.
3. Adds support for the use of Azure OpenAI embeddings. 
> Fixed Issues with New CREATE KNOWLEDGE_BASE Syntax + Azure OpenAI

- mindsdb/__main__.py
- mindsdb/interfaces/database/projects.py
This PR disables the default project of MindsDB from being dropped.
Furthermore, a provision has been put in place to allow users of older versions of the application to run the app without crashing if they have in fact dropped the default project.
Fixes https://linear.app/mindsdb/issue/BE-889/fix-default-project-issue
> Disabled the Default Project from Getting Dropped

- mindsdb/interfaces/knowledge_base/controller.py
Changed the reranking_threshold to relevance_threshold:
example query:
```
SELECT *
FROM kb_custom_model_ada
WHERE content = "Kindle Voyage" AND relevance_threshold=0.6 LIMIT 50;
```
> Changed the reranking_threshold to relevance_threshold

- mindsdb/utilities/auth.py
AWS has sunset the v1 version of metadata api we were using. We now need a session token to get the info we need
> Update AWS metadata method

- mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- mindsdb/interfaces/knowledge_base/controller.py
- tests/integration_tests/knowledge_bases/test_kb_sql.py
Moved default limit in KB controller. It works only if KB is queried with content columns
If vectordb is selected there is no limit.
> Default limit in KB controller

- .github/workflows/matrix_includes.json
- .github/workflows/test_on_push.yml
This PR updates the matrix for tests to always run on Windows and Mac using Python 3.11. On ubuntu we keep 3.10 until we migrate our Docker image to 3.11
> Run 3.11 for Windows and Mac

- docs/mindsdb_sql/knowledge-bases.mdx
This PR updates the name of the created knowledge base to be consistent across the page.
> Fixed the Name of the Knowledge Base Used in the Documentation

- mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py
The small PR fixes the `bs4` deprecation warnings by replacing `findAll()` with `find_all()` The resolves the warnings found in the[ CI logs](https://github.com/mindsdb/mindsdb/actions/runs/14538889061/job/40792916457#step:9:127):
```python
/Users/runner/work/mindsdb/mindsdb/mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py:154: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
for a_tag in soup.findAll("a"):
```
> Resolve bs4 deprecation warnings

- docs/integrations/vector-db-integrations/chromadb.mdx
- mindsdb/integrations/handlers/chromadb_handler/README.md
- mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
- mindsdb/integrations/handlers/chromadb_handler/settings.py
- tests/integration_tests/knowledge_bases/test_kb_sql.py
Default distance for chromadb is cosine, it is the same distance as in pgvector
To switch to previous behaviour:
```sql
CREATE DATABASE l2_chroma
WITH
ENGINE = "chromadb"
PARAMETERS = {
"persist_directory": '/srv/chromadb',  -- optional
"distance": "l2"  -- optional
};
```
Possible options for distance: l2, cosine, ip ([more info](https://docs.trychroma.com/docs/collections/configure))
> ChromaDB: cosine is default distance

- docs/integrations/vector-db-integrations/pgvector.mdx
- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
- tests/integration_tests/knowledge_bases/test_kb_sql.py
Added optional `distance` setting for pgvector handler
Posible options for it:  cosine (default),  l1, l2, ip, hamming, jaccard ([more info](https://github.com/pgvector/pgvector?tab=readme-ov-file#querying))
Example:
```sql
CREATE DATABASE pvec
WITH
ENGINE = 'pgvector',
PARAMETERS = {
"host": "127.0.0.1",
"port": 5432,
"database": "postgres",
"user": "user",
"password": "password",
"distance": "l2" -- optional, default is cosine
};
```
> Distance setting for pgvector

- mindsdb/api/executor/command_executor.py
This PR fixes running `DESCRIBE` queries on objects like Knowledge Bases when the name has been prefixed by the project. For example:
`DESCRIBE KNOWLEDGE_BASE kb_proj.test_proj_kb;`
Fixes https://linear.app/mindsdb/issue/BE-903/fixed-describe-commands-for-knowledge-bases-and-other-objects-in
> Fixed DESCRIBE Commands for Objects in Projects

- docker/mindsdb.Dockerfile
This change means when using our dev image for local development, changing e.g. a test file won't cause `watchfiles` to restart mindsdb.
> Only watch code folder for changes in dev image

- mindsdb/api/executor/datahub/datanodes/information_schema_datanode.py
- mindsdb/api/executor/datahub/datanodes/system_tables.py
- tests/unit/executor/test_schema.py
Fixed error `AttributeError: 'list' object has no attribute 'iterrows'` when 'columns' table is selected:
`SELECT * FROM information_schema.columns`
The information_schema_datanode didn't use 'get_table_columns_df' introduced in: 
https://github.com/mindsdb/mindsdb/pull/10663 
> Fix getting columns for information schema

- mindsdb/api/http/namespaces/file.py
This change ensures that the file object's buffer is explicitly flushed to disk before closing the file handle. 
> Ensure file buffer is flushed before closing in file upload

- mindsdb/integrations/handlers/huggingface_handler/requirements.txt
- mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
- requirements/requirements.txt
This PR adds `transformers` dependency in HF handler. It looks like this was added in this [PR](https://github.com/mindsdb/mindsdb/pull/9488), but so far from what I have tested transformer are not required for our agents to work.
> Transformers optional

- mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
- mindsdb/integrations/handlers/bigquery_handler/tests/test_bigquery_handler.py
- mindsdb/integrations/handlers/gmail_handler/gmail_handler.py
- mindsdb/integrations/handlers/google_calendar_handler/google_calendar_handler.py
- mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_handler.py
- mindsdb/integrations/handlers/ms_teams_handler/ms_teams_handler.py
- mindsdb/integrations/handlers/vertex_handler/vertex_client.py
- mindsdb/integrations/handlers/youtube_handler/youtube_handler.py
- mindsdb/integrations/utilities/handlers/api_utilities/__init__.py
- mindsdb/integrations/utilities/handlers/auth_utilities/__init__.py
- tests/unit/handlers/test_bigquery.py
This PR fixes the imports of API and auth utilities within the handlers that they are used in.
Fixes https://linear.app/mindsdb/issue/BE-990/bigquery-integration-cannot-be-used-with-minds
> Fixed Imports of Handler Utilities

- mindsdb/integrations/handlers/huggingface_handler/requirements.txt
- mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
- requirements/requirements.txt
This PR reverts #10847 , due to required transformers dependency for agents to work
> Add transformers to main requirements

- mindsdb/api/executor/command_executor.py
- mindsdb/interfaces/knowledge_base/controller.py
- tests/unit/executor/test_agent.py
- tests/unused/integration/knowledge_bases/test_kb_sql.py
This PR disables MindsDB models from being used as embedding models when creating knowledge bases.
Fixes https://linear.app/mindsdb/issue/UNI-24/disable-passing-models-to-kb
> Disabled Use of MindsDB Models for Knowledge Bases

- mindsdb/api/a2a/common/server/server.py
This new endpoint returns server status, uptime, and configuration details, enabling easier monitoring and diagnostics. The implementation includes tracking server start time and leveraging the agent card for contextual data.
`curl -v http://localhost:47338/status`
```
{
"status": "ok",
"service": "mindsdb-a2a",
"uptime_seconds": 23.03,
"host": "localhost",
"port": 47338,
"agent_name": "MindsDB Agent Connector",
"version": "1.0.0"
}
```
> Add /status endpoint for A2A to provide server health information

- mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
Previously, only `"ssl": true` had an effect, while `"ssl": false` was treated the same as omitting the parameter - in both cases, the database's default SSL settings were used.
Now the behavior is more explicit and consistent:
- When `ssl` is omitted: Use database's default SSL settings
- When `"ssl": true`: Force SSL connection
- When `"ssl": false`: Force non-SSL connection
> Fix `ssl` option of mysql handler

- mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
This PR adds a description and default value for Salesforce columns. Note that  inlineHelpText provides actual additional information about the field's purpose and usage but is not a required value.
Fixes https://linear.app/mindsdb/issue/BE-1146/salesforce-data-catalogue-missing-fields
> Add default value and description for SF columns metadata

- tests/integration/flows/test_mysql_api.py
Two small changes to `test_mysql_api.py` to avoid 'features' of `mysql.connector`:
- `mysql.connector` may return values of columns with `BYTEA` type as bytes/bytearray or string depend on env
- it seems like `mysql.connector` may set `NUM_FLAG` to numeric columns at client side
> Changes to `test_mysql_api.py` based on db driver features

- mindsdb/integrations/handlers/litellm_handler/litellm_handler.py
- mindsdb/integrations/utilities/rag/rerankers/base_reranker.py
- mindsdb/interfaces/knowledge_base/controller.py
- mindsdb/interfaces/knowledge_base/llm_client.py
Updates:
- don't hide error from reranker. if something wrong with config or api usage: show error
- updated litellm handler: logic for preparating of args moved into litellm handler
-  'google' provider is alias to 'gemini'
Fixes https://linear.app/mindsdb/issue/UNI-141/querying-kbs-is-unstable
> Fix KB reranker: show error, support gemini

- mindsdb/interfaces/knowledge_base/controller.py
Improved error messaging during creating knowledge base:
- checking 'create knowledge base' set of parameter using [pydantic model](https://github.com/mindsdb/mindsdb/pull/11198/files#diff-dbf2257347198d1e8e904591465da2f38dcbe69c9b9163809bca0b9ae237a852R53)
- check input names and types
- forbid using unknown parameters
-  check 'embedding_model' parameters:
- 'provider' have to be passed 
- for litellm models: 'model_name' have to be passed
- for openai/azure models: 'api_key' have to be passed 
-  check 'reranking_model' parameters
- 'model_name' have to be passed
- 'provider' have to be passed
- try to call reranker llm to check if parameters are OK: api key, base_url and others
Fixed problem with litellm embedding model
- if it was set in config and knowledge base is created without …
> KB error messages

- mindsdb/api/http/namespaces/config.py
- mindsdb/utilities/config.py
This PR updates the PUT /config endpoint to overwrite the configuration items related to default models rather than merge them.
The reason for this to handle situations where users change between model providers and the first provider contains parameters that are not compatible with the second. For example, if the user first sets the default model to Azure OpenAI, which expects an `api_version` parameter and then switches to OpenAI, if the configs are merged, `api_version` will still be passed when running OpenAI. This will result in errors.
Fixes https://linear.app/mindsdb/issue/UNI-121/to-markdown-function-fails-when-default-model-settings-are-applied
> Changed Config Update Behavior to Overwrite Default Model Parameters

- mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
- mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
This PR fix the issue with mapping Salesforce table names for the data catalog, assuming they are all lowercase
> Fix Salesforce Data Catalog

- mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
- mindsdb/interfaces/data_catalog/data_catalog_loader.py
Cast `min_val` and `max_val` to supported types before saving.  This ensures that all values being inserted into the database are of a type that SQLite can handle, preventing the InterfaceError.
Fixes https://linear.app/mindsdb/issue/BE-1166/fix-snowflake-dc-stats
> Fix `InterfaceError` for Snowflake Data Catalog stats

- mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py
- mindsdb/integrations/handlers/web_handler/web_handler.py
Added `user_agent` filter to `crawler` table to specify user-agent header for requests to resources
Example:
```sql
SELECT * FROM web.crawler
WHERE url = 'https://docs.mindsdb.com/integrations/app-integrations/web-crawler'
and user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.3';
```
Also updated default user-agent
Fixes https://linear.app/mindsdb/issue/CONN-596/web-crawler-cannot-crawl-some-webpages
> Web handler: accept user-agent

- mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
Use sqlalchemy render  for rendering queries instead of composing strings manually. It should solve many issues with qouting, special caracters, reserved keywords and so on
Updated functions:
- select
- delete
- keyword_select
`hybrid_search` was skipped because the query composed there is pretty heavy.
Fixes https://linear.app/mindsdb/issue/CONN-298/kb-insert-fails-in-pgvector-due-to-invalid-column-name-formatting-eg
> Pgvector: render queries with sqlalchemy render

- mindsdb/utilities/ps.py
`psutil.Process().connections()`  is [deprecated](https://psutil.readthedocs.io/en/latest/#psutil.Process.connections)  and will be removed. Replaced to `psutil.Process().net_connections()`
> Replace deprecated `psutil.Process().connections()` to `net_connections()`

- mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py
This PR handles queries that include quoted dates/datetimes in the `WHERE` clause; SOQL expects arguments to be passed  unquoted.
Fixes https://linear.app/mindsdb/issue/CONN-1305/handle-quotes-dates-in-salesforce
Given below are some example queries that now work:
```
SELECT Id, Name FROM sf_datasource.Account WHERE CreatedDate = 2025-04-03
SELECT Id, Name FROM sf_datasource.Account WHERE CreatedDate = '2025-05-19T12:44:50.000+00:00'
SELECT Id, Name FROM sf_datasource.Account WHERE CreatedDate = '2025-05-19T12:44:50.000+0000'
```
> Fixed Date and DateTime Handling in Salesforce Integration

- mindsdb/api/executor/command_executor.py
If try to create a BYOM engine with error in model file, then exception may appear when do check `"No module named" in handler_module_meta["import"]["error_message"]` because there is no import error in BYOM handler itself.  In this case ml-engine will be created (because `self.answer_drop_ml_engine(ast_drop)` never reached) and irrelevant error message showed to the user.
Also changed the error message itself (added `or msg}`) because for BYOM there is no error message in `handler_module_meta["import"]["error_message"]` if the error is in the user's code.
`
Fixes CONN-1357
> Fix error message when creating BYOM

- mindsdb/api/executor/sql_query/steps/fetch_dataframe.py
- mindsdb/api/executor/sql_query/steps/subselect_step.py
- requirements/requirements.txt
- tests/unit/executor/test_executor.py
Fixed a bug in processing queries with multiple CTEs.
This query:
```sql
WITH ta AS (
SELECT 'a' AS a, 2 AS b
), tb AS (
SELECT 'a' AS a, 3 AS c
)
SELECT ta.a, ta.b, tb.c
FROM ta
LEFT JOIN tb ON test_a.a = tb.a;
```
Failed with error:
```
syntax error at or near "'a'"
```
Also fixed inconsistent results for queries with multiple CTEs.
This query:
```sql
WITH ta AS (
SELECT 'a' AS a, 2 AS b
UNION ALL
SELECT 'b' AS a, 2 AS b
), tb AS (
SELECT 'a' AS a, 'b' AS c
)
SELECT ta.a, ta.b, tb.c
FROM ta
LEFT JOIN tb ON ta.a = tb.a;
```
returned different set of values for column `tb.c`.
Fixes CONN-846
> Fix CTE issue

- mindsdb/interfaces/database/projects.py
- tests/unit/executor/test_base_queires.py
Added optimization for querying views:
View's query is wrapped into outer query of the view (instead of getting all data of the view and then filtering it in mindsdb server's memory)
For example:
```sql
create view v1 (
SELECT * FROM example_db.car_info where year=2010
);
select mpg from v1 where fueltype='Petrol';
```
This query will be sent to database:
```sql
SELECT mpg FROM ( 
SELECT * 
FROM car_info 
WHERE year = 2010
) 
WHERE fueltype = 'Petrol'
```
Fixes https://linear.app/mindsdb/issue/CONN-1371/queries-against-mindsdb-are-simply-not-returning
> Combine  view's query with outer query

- mindsdb/api/executor/sql_query/steps/fetch_dataframe.py
- mindsdb/api/executor/sql_query/steps/fetch_dataframe_partition.py
- mindsdb/interfaces/query_context/context_controller.py
Changed the way of counting processed rows:
- the function that proccesed a chunk of data is updating count processed rows 
- also after shutdowning thread pool (in case of error) - wait till all worker finish their chunk data to calculate all successful results
Fixes https://linear.app/mindsdb/issue/CONN-600/bug-incorrect-reporting-in-describe-kb
> Fix of calculation processed rows 

- docs/setup/self-hosted/docker.mdx
This PR resolves the error that comes up when the [docker command](https://docs.mindsdb.com/setup/self-hosted/docker#:~:text=docker%20run%20%2D%2Dname%20mindsdb_container%20%2De%20MINDSDB_APIS%3Dhttp%20%2Dd%20%2Dp%2047334%3A47334%20%2Dv%20mdb_config.json%3A/root/mindsdb_config.json%20mindsdb/mindsdb) in the documentation is run
Fixes #11405 
`mindsdb/docs/setup/self-hosted/docker.mdx`
> added pwd to reflect existing folder path

- mindsdb/__main__.py
- mindsdb/utilities/fs.py
- tests/integration/flows/test_knowledge_base.py
Updates:
Changed place when pidfile is removed (do it earlier, main process can be closed abruptly):
- WAS: after `__main__` function is completed (all services are closed successfuly)
- IS: before trying to stop services
Use pid file only in case the env variable is set: USE_PIDFILE=1
Fixes https://linear.app/mindsdb/issue/CONN-1404/mindsdb-docker-container-fails-to-restart-due-to-stale-pid-file
> Don't use pidfile in docker

- mindsdb/interfaces/agents/langchain_agent.py
- mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_toolkit.py
- mindsdb/interfaces/skills/skill_tool.py
- mindsdb/interfaces/skills/sql_agent.py
Fixes:
- don't include sql tools if no tables available for agent. otherwise LLM tries to use tables tools even if only a single KB is available
- Show error message if model is not defined for agent (not in 'create agent' or default config)
- WAS: "KeyError: 'model_name'" error
- Check all tables in "sql_db_schema" tool and return messages with all not found tables together. it reduces number of iteration of llm calls
Fixes https://linear.app/mindsdb/issue/CONN-1360/bug-agents-do-not-query-data-from-kbs
> Fix Agent works with KB

- mindsdb/interfaces/knowledge_base/controller.py
- tests/unit/executor/test_knowledge_base.py
Store embedding and reranking setting into knowledge base if they were used from default values (in config)
If values in config are changed - KB will keep using the same model setting (defined at time when KB was created)
Fixes https://linear.app/mindsdb/issue/CONN-1435/add-embedding-model-and-reranking-model-to-describe-kb
> Store default model setting in KB

- mindsdb/utilities/render/sqlalchemy_render.py
- tests/unit/handlers/test_clickhouse.py
There was an error with the SQL renderer for the `INTERVAL` statement. This error occurred for dialects that do not have the 'driver' attribute.
Fixes #11422, CONN-1391
> Fix SQL renderer for `INTERVAL` statement

- mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
If schema is not set - use PUBLIC. It will show tables from PUBLIC schema
Example: `snowflake_datasource` connection was created with schema, `snowflake_sales_data` - without:
Fixes https://linear.app/mindsdb/issue/FQE-1486/snowflake-handler-fails-to-discover-tables-on-connection
> Fix snowflake:  use PUBLIC schema if is not set

- mindsdb/interfaces/knowledge_base/evaluate.py
- mindsdb/interfaces/knowledge_base/llm_client.py
Fix for `EVALUATE KNOWLEDGE_BASE` when azure-openai is used.
To replicate, create a KB, upload any test_data and run:
```sql
EVALUATE KNOWLEDGE_BASE my_kb
USING
test_table = files.kb_test_data,
generate_data=true,
llm= {
"provider": "azure_openai",
"model_name" : "gpt-4.1",
"base_url": "https://url.openai.azure.com/",
"api_key": 'key,
"api_version": "2023-05-15"
},
save_to=files.my_result_test;
```
> Fix `EVALUATE KNOWLEDGE_BASE` with azure-openai

- mindsdb/interfaces/knowledge_base/controller.py
- tests/unit/executor/test_knowledge_base.py
If create KB and try to filter:
```sql
CREATE KNOWLEDGE_BASE my_kb
USING
embedding_model = {
"provider": "openai",
"model_name" : "text-embedding-3-large",
"api_key": "sk-abc123"
},
reranking_model = {
"provider": "openai",
"model_name": "gpt-4o",
"api_key": "sk-abc123"
},
metadata_columns = ['product'],
content_columns = ['notes'],
id_column = 'order_id';
INSERT INTO my_kb
SELECT order_id, product, notes
FROM sample_data.orders;
SELECT chunk_content, distance, relevance
FROM my_kb
WHERE product = 'Bluetooth Speaker'
AND content = 'portable'
AND relevance > 0.01;
```
then the query fail with
```
'>' not supported between instances of 'str' and 'float'
```
Fixes #FQE-1623
> fix KB `GREATER THAN` filter
