mindsdb/mindsdb

mindsdb/api/mysql/mysql_proxy/executor/executor_client.py, mindsdb/api/mysql/mysql_proxy/executor/executor_wrapper.py, mindsdb/integrations/handlers_client/db_client.py, mindsdb/integrations/handlers_client/ml_client.py, mindsdb/integrations/handlers_wrapper/db_handler_wrapper.py, mindsdb/integrations/handlers_wrapper/ml_handler_wrapper.py, mindsdb/integrations/libs/handler_helpers.py, mindsdb/integrations/libs/response.py
Microservice mode:
- Use flask app.before_request to log incoming request on service side
- Use flask app.after_request to log returned result on service side
- Use custom decorator to log call+params and returned results for clients
=> Use flask feature to log incoming params and request results

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py, mindsdb/integrations/libs/ml_exec_base.py, mindsdb/interfaces/database/projects.py, mindsdb/interfaces/model/model_controller.py, tests/integration_tests/flows/test_company_independent.py, tests/integration_tests/flows/test_http.py, tests/unit/test_project_structure.py
Return model record (with version) as a result of 'create', 'retrain', 'adjust' commands
#4323
#4194
https://www.loom.com/share/69cceb9a5fab4d6c8ea168862059897d
=> 'Create' returns model record

mindsdb/integrations/handlers/rockset_handler/rockset_handler.py
Minor fix to enable rockset integration.
=> Fix rockset import errors

mindsdb/integrations/handlers/openai_handler/openai_handler.py, mindsdb/integrations/libs/ml_exec_base.py, tests/unit/executor_test_base.py
**Fixes**:
- Increased default max tokens to 100  #4406 and #4407
- Raise exception if model is not completed #4403
- [+] 🐛 Bug fix (non-breaking change which fixes an issue)
=> Openai fixes

mindsdb/integrations/handlers/phoenix_handler/README.md, mindsdb/integrations/handlers/phoenix_handler/phoenix_handler.py, mindsdb/integrations/handlers/phoenix_handler/requirements.txt
I have included authentication mechanisms for the Apache Phoenix integration.
=> Authentication for Apache Phoenix Integration

docs/setup/custom-config.mdx, mindsdb/api/http/initialize.py, mindsdb/api/http/namespaces/config.py, mindsdb/api/http/start.py, mindsdb/utilities/config.py
to the `config.json` added new option:
```
"gui": {
"autoupdate": true
},
```
`False` value disable gui autoupdate
=> option to disable GUI autoupdate

docs/data-integrations/all-data-integrations.mdx
* Updated the mongo template in `docs/data-integrations/all-data-integrations.mdx` file to include the database field.
**Fixes** #4421 
Updated the Mongo template in docs to include the required `database` field
=> docs: update mongodb template

docs/nlp/nlp-mindsdb-openai.mdx
Updated the documentation to fix issue #4424 
**Fixes** #4424 
- [x ] 📄  documentation update
added a section in the docs before what's next, called it parameter descriptions and added parameter descriptions there.
=> added parameter descriptions

docs/mint.json, docs/sql/api/adjust.mdx
**Fixes** #4358 
- created a doc page for adjust statement
[ADJUST - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10709507/ADJUST.-.MindsDB.pdf)
=> created a doc page for adjust statement

mindsdb/integrations/handlers/sheets_handler/sheets_handler.py
This PR initially solves the issues when connecting to an Excel sheet.
Resolves #4445 
>NOTE: There are a few things we can improve here as loading the whole sheet in duckdb, better handling the `private` sheets issue etc. I will post separate issues for those. Initially, this works for the public sheets.
=> Resolve the connection issues with Excel sheet

mindsdb/api/http/namespaces/default.py, tests/integration_tests/flows/test_http.py
=> `Logout` route

mindsdb/interfaces/jobs/jobs_controller.py
Fix: user doesn't see history of jobs
=> Jobs manage: fix company id in job history

docs/contribute/tutorials.mdx
**Fixes** [#83 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/83)
- added /docs/tutorials directory
- added markdown link
=> added markdown link and 

docs/rest/sql.mdx
This pull changes the python code example in the sql.mdx file
**Fixes** #4471
=> Resolved role sql query code example

docs/contribute/issue-labels.mdx, docs/mint.json
**Fixes** [#84 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/84)
- issue labels page
=> doc page on issue labels

docs/what-is-mindsdb.mdx
Updated the end of what-is-mindsdb.dx with the following:
```
<Tip>
**From Our Community**
Check out the articles and video guides created by our community:
- Article on [What is MindsDB?](https://medium.com/@okekeebubechukwu08/what-is-mindsdb-b6862af21492)
by [Gloria Okeke E.J](https://medium.com/@okekeebubechukwu08)
- Article on [What is MindsDB? How to get started with it ](https://medium.com/@hritikd3/what-is-mindsdb-how-to-get-started-2b3cf6d99707)
by [Hritik Dangi](https://github.com/hritikd3)
- Video guide on [Video: What is MindsDB?](https://www.youtube.com/watch?v=SrDPYqQrzaw) by
[Alissa Troiano](https://github.com/alissatroiano)
- Video guide on [What is MindsDB | How to Get Started | A Cloud/AI Enabled Database](https://www.youtube.com/watch?v=XWDVxYVGH9M)
by [Arman …
```
=> Added community tips to what-is-mindsdb.mdx

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
=> Fix: limitStep brakes result

docs/sql/api/retrain.mdx
Fixed the link in retrain doc page
**Fixes** #4507 
Fixed the link as suggested in the issue description.
=> Fix file upload link in retrain doc page

docs/quickstart.mdx
I added the query to quickstart.mdx as mentioned in [#4500](https://github.com/mindsdb/mindsdb/issues/4500)
**Fixes** #([#4500](https://github.com/mindsdb/mindsdb/issues/4500))
- [ ✓] 📄 This change requires a documentation update
- [ ✓] I have updated the documentation, or created issues to update them.
=> add query to quickstart.mdx 

docker/docker-compose.yml, mindsdb/api/mongo/classes/query_sql.py, mindsdb/api/mysql/mysql_proxy/executor/executor.py, mindsdb/api/mysql/mysql_proxy/executor/executor_grpc_client.py, mindsdb/api/mysql/mysql_proxy/executor/executor_grpc_wrapper.py, mindsdb/grpc/executor/executor_pb2.py, mindsdb/grpc/executor/executor_pb2.pyi, mindsdb/grpc/executor/executor_pb2_grpc.py, mindsdb/utilities/config.py, protos/executor.proto
Handle Mongo API requests in microservice way (for microservice mode)
Mongo used ExecutorCommands instance directly. Now it uses same instance, but as a part of Executor instance
=> Handle Mongo API requests in microservice mode

docs/sql/create/jobs.mdx
**Fixes** [#82 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/82)
- updating a doc page on jobs in progress
=> updated a doc page on jobs

docs/data-integrations/all-data-integrations.mdx
**Fixes** [#85 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/85)
- updated snowflake connection example
=> updated snowflake connection example

docs/rest/projects/get-projects.mdx
=> docs: fix typo in api endpoint [ci skip]

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py, mindsdb/interfaces/database/projects.py
Added columns `created_at` to `models` and `models_versions`
=> Add `created_at` columns to `models` and `models_versions`

mindsdb/api/http/namespaces/default.py
=> del 'is_first_launch'

docs/tutorials.mdx
Added my tutorial to Predict the Energy Usage using MindsDB and MongoDB to the list of tutorials
**Fixes** #3537
Tutorial
=> Added my tutorial to the list

mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
=> Fix for `snowflake` talbes names output

mindsdb/api/http/namespaces/file.py, mindsdb/api/http/utils.py
Solve the security issue reported by [Trellix team](https://github.com/mindsdb/mindsdb/pull/4286#issuecomment-1431419234). Since they are not responding on the PR we created new one.
**Fixes** https://github.com/mindsdb/mindsdb/security/advisories/GHSA-7x45-phmr-9wqp#advisory-comment-78174
=> Resolve CVE-2007-4559 bug

docs/sql/api/adjust.mdx
As per the instruction provided by [martyna-mindsdb](https://github.com/martyna-mindsdb), I have removed the previous content, and added the new link.
- [✓] 📄 This change requires a documentation update
- [✓] I have updated the documentation, or created issues to update them.
=> Fixed the link as requested

docs/contribute/data-integration-page.mdx
**Fixes** [#88 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/88)
updated a doc page on how to create a data integration doc page
=> updated a doc page on how to create a data integration doc page

docs/sql/create/view.mdx
##Description
modified:
- docs/sql/create/view.mdx 
resolves:
- #4558
=> 4558 added doc changes for including community tutorial

mindsdb/integrations/handlers/duckdb_handler/duckdb_handler.py
Change how the DuckDB connection arguments are handled to use all handler configuration parameters.
**Fixes** #4611
=> Fix DuckDB handler connection args

docs/connect/mongo-compass.mdx
Added community tutorial links to the Using MindsDB via Mongo API -> Connect to MindsDB -> MongoDB Compass page 
This is in response to issue #4557
=> Added community tutorial links to the Using MindsDB via Mongo API -> Connect to MindsDB -> MongoDB Compass page #4557

docs/connect/tableau.mdx
**Fixes** 
-  📄 This change requires a documentation update
-  I have updated the documentation, or created issues to update them.
- I have read the CLA Document and I hereby sign the CLA
=>  added the commutnity  tutorial links

docs/contribute/tutorials.mdx
https://github.com/mindsdb/mindsdb/issues/4600
=> Fixed typo

docs/connect/mindsdb_editor.mdx
=> Fixed typo, MacOs to MacOS

mindsdb/interfaces/jobs/scheduler.py
=> Jobs connection fix

mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py, tests/unit/ml_handlers/test_statsforecast.py
=> Improve inference of frequency in date series

docs/setup/self-hosted/pip/source.mdx
Change Sourcecode to Source Code in the docs
**Fixes** #4599
=> change heading in docs

docker/db_handler.Dockerfile, docker/executor.Dockerfile, docker/mindsdb.Dockerfile, docker/ml_handler.Dockerfile, mindsdb/grpc/ml/ml_pb2.py, mindsdb/grpc/ml/ml_pb2.pyi, mindsdb/grpc/ml/ml_pb2_grpc.py, mindsdb/integrations/handlers_client/ml_client_factory.py, mindsdb/integrations/handlers_client/ml_grpc_client.py, mindsdb/integrations/handlers_wrapper/db_grpc_wrapper.py, mindsdb/integrations/handlers_wrapper/huggingface_requirements.txt, mindsdb/integrations/handlers_wrapper/ml_grpc_wrapper.py, mindsdb/integrations/libs/ml_exec_base.py, mindsdb/interfaces/database/integrations.py, protos/ml.proto
=> Microservices: move splitting point from BaseMLEngineExec to MLHandler

docs/tutorials.mdx
added tutorial to Predict Gold Prices to the list
**Fixes** #3538 
tutorial
=> added tutorial to Predict Gold Prices to the list

docs/sql/tutorials/eeg-forecasting.mdx
**Fixes** #([issue](https://github.com/mindsdb/mindsdb/issues/4595))
=> Fixed typo in the eef-forecasting-doc

docs/data-integrations/DynamoDB.mdx
issue: #4584
Added Docs for DynamoDB.
=> Created the Doc for DynamoDB

docs/using-mongo-api/classification.mdx
Added a community todo link.
**Fixes** #(4686)
I have added the links as mentioned in original issue #4686
=> Added a community todo link to classfication page

docs/nlp/nlp-mindsdb-openai.mdx
Changes "optionaly" to "optionally"
**Fixes** #4594
=> Fix typo in docs: optionaly -> optionally

docs/mint.json
add ckan page in mint.json.
**Fixes** #4687 
Added ckan.mdx to "Data integrations" group pages in mint.json file
=> add ckan page in mint.json

mindsdb/integrations/handlers/openai_handler/helpers.py
=> Openai: don't repeat on invalid_request_error

mindsdb/migrations/versions/2023-02-27_ef04cdbe51ed_jobs_user_class.py
=> Fix collision in migrations

mindsdb/integrations/handlers/ckan_handler/README.md
Removal of additional apostrophes
It was just the line 27, that I needed to delete some apostrophes to make the documentation look clean a bit.
=> readme file has been updated

docs/mongo/collection-structure.mdx
**Fixes** [#87 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/87)
updated mongo collection structure doc page
=> updated mongo collection structure doc page

docs/mint.json, docs/nlp/json-from-text.mdx
**Fixes** #4438 
- added openai example on extracting json from text
=> added openai example on extracting json from text

requirements.txt
Updated mindsdb_sql dependency with regular insert support
=> Twitter handler fix: mindsdb_sql dependency for insert support

mindsdb/integrations/libs/ml_exec_base.py, tests/unit/dummy_ml_handler/dummy_ml_handler.py, tests/unit/test_project_structure.py
create_validation method of ml handler is not calling
=> HF: fix create validation

docs/mint.json, docs/setup/community-deploys-mindsdb.mdx, docs/sql/tutorials/time-series-community.mdx
from issues:
https://github.com/mindsdb/mindsdb/issues/4710
https://github.com/mindsdb/mindsdb/issues/4709
=> Doc pages update

docs/data-integrations/Google-BigQuery.mdx
done.
Added Docs for Google bigquery handler
issue: #4707
=> Added Docs for Google BigQuery

docs/data-integrations/hive.mdx
This PR adds a Doc page on Hive Data Integration to the MindsDB Docs website.
**Fixes** #4726 
This will add a new Info Page to the Docs website about Hive Data Integration.
=> Doc page for the Hive data integration

docs/data-integrations/impala.mdx
This PR adds a Doc page on Impala Data Integration to the MindsDB Docs website.
**Fixes** #4727 
This will add a new Info Page to the Docs website about Impala Data Integration.
=> Doc page for the Impala data integration

docs/data-integrations/google-sheets.mdx
Added document for google sheets data integration - Issue#4708
- [x ] 📄 This change requires a documentation update
Created new markdown file for data integration
- [x ] I have updated the documentation, or created issues to update them.
=> issue#4708 - doc for sheets data integration

docs/data-integrations/cassandra.mdx
This PR adds a Doc page on Cassandra Data Integration to the MindsDB Docs website.
**Fixes** #4756 
This will add a new Info Page to the Docs website about Cassandra Data Integration.
=> Doc page for the Cassandra data integration

docs/data-integrations/elasticsearch.mdx
This PR adds a Doc page on Elasticsearch Data Integration to the MindsDB Docs website.
**Fixes** #4753 
This will add a new Info Page to the Docs website about Elasticsearch Data Integration.
=> Doc page for the Elastic Search data integration

docs/data-integrations/databricks.mdx
This PR adds a Doc page on Databricks Data Integration to the MindsDB Docs website.
**Fixes** #4754 
This will add a new Info Page to the Docs website about Databricks Data Integration.
=> Doc page for the Databricks data integration

docs/data-integrations/mariadb.mdx
This PR adds a Doc page on MariaDB Data Integration to the MindsDB Docs website.
**Fixes** #4758 
This will add a new Info Page to the Docs website about MariaDB Data Integration.
=> Doc page for the MariaDB data integration

docs/setup/custom-config.mdx
**Fixes** #4779 
Add comma in custom-config.mdx and change "autoupdate": True -> "autoupdate": true
=> Fix missing comma and boolean value

docs/sql/api/update.mdx
Added an admonition box in `/docs/sql/api/update.mdx`
**Fixes** #4755 
Added an admonition box in the `docs/sql/api/update.mdx` as per the requirement of the issue.
=> [DOC-FIX-4755]: Add an admonition box in update.mdx

docs/setup/environment-vars.mdx
**Fixes** #4593 
Replaced dirs to directories in environment-vars.mdx
=> #4593 Issue: Fixed typo in docs

docs/data-integrations/microsoft-access.mdx
=> doc:microsoft access data integration - issues#4783

docs/sql/tutorials/eeg-forecasting.mdx
=> [Docs][Bug]: Fix typo in Docs #4596

docs/quickstart.mdx
**Fixes** #4462
The solution adds links to articles and video guides from the community to the Quickstart -> Try It Out! page
=> Add community tutorial links

docs/custom-model/openai.mdx, docs/nlp/nlp-mindsdb-openai.mdx, docs/setup/self-hosted/docker.mdx
**Fixes** #4691 and [#91 from minds_private](https://github.com/mindsdb/mindsdb_private/issues/91)
- added CREATE ML_ENGINE command to OpenAI docs
- added info that own OpenAI API key is required for Docker
=> added create ml_engine to openai docs

docs/data-integrations/Couchbase.mdx
=> Created Doc Couchbase handler

docs/data-integrations/oracle.mdx
added documentation on the oracle data integration handler.
Fixes #(issue)
issue: #4885
=> added documentation for oracle data integration

docs/data-integrations/twitter.mdx, docs/mint.json, docs/sql/create/jobs.mdx
**Fixes** [#93 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/93)
- created a Twitter doc page under Data Integrations
[Building a Chatbot for Twitter using MindsDB and GPT-3 - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10941872/Building.a.Chatbot.for.Twitter.using.MindsDB.and.GPT-3.-.MindsDB.pdf)
- added a Twitter Chatbot example in the CREATE JOB doc page
=> twitter docs

docs/data-integrations/twitter.mdx, docs/sql/create/jobs.mdx
**Fixes** [#93 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/93)
- restructured Twitter doc page
- added a link to example
=> restructured twitter docs

docs/mint.json, docs/sql/tutorials/twitter-chatbot.mdx
**Fixes** [#93 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/93)
- added a Twitter Chatbot tutorial
=> added twitter tutorial

docs/contribute/api-handlers.mdx, docs/contribute/app-handlers.mdx, docs/mint.json, mindsdb/integrations/libs/api_handler.py
Initial docs version for writing Application Handler. As an example is used the TwitterAPI Handler.
=> App handler docs

mindsdb/integrations/handlers/openai_handler/helpers.py, mindsdb/integrations/handlers/openai_handler/openai_handler.py, mindsdb/integrations/handlers/openai_handler/requirements.txt
=> [ENH] Conversational mode for GPT-3.5 models

docs/sql/create/jobs.mdx, docs/sql/tutorials/twitter-chatbot.mdx
**Fixes** fixed code in Twitter docs
fixed code in Twitter docs
=> fixed twitter code in docs

docs/sql/create/jobs.mdx
**Fixes** added a twitter tutorial link to jobs
added a twitter tutorial link to jobs
=> added a twitter tutorial link to jobs

README.md
**Fixes** #4887
- Update a link to the Teradata integration
=> Update a link to the Trino integration

docs/data-integrations/MongoDB.mdx
Create a doc page for the MongoDB data integration
**Fixes** #4831
- Create a doc page for the MongoDB data integration
=> Create a doc page for the MongoDB data integration

docs/data-integrations/planet-scale.mdx
This commit updates the MindsDB documentation for PlanetScale. 
The related issue addressed in this commit is #4906 .
=> Documentation for PlanetScale

docs/data-integrations/Apache-Pinot.mdx
Adding Doc page for Pinot Data Integration. (Apache-Pinot.mdx) 
**Fixes** #(4905)
- [] I have commented my code, particularly in hard-to-understand areas.
=> Pinot Data Integration doc page

docker/release
=> Docker image: No module named psycopg2

docs/mint.json
**Fixes** [#94 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/94)
- removed the brain activity tutorial from navigation until the bug is fixed
- aligned the tutorials listed in two navigation sections
=> aligned the tutorials listed in navigation sections

docs/tutorials.mdx
**Fixes** #4948 
I updated the tutorials page with a tutorial I wrote.
=> tutorial for solving house price prediction challenge

docs/data-integrations/questdb.mdx
=> doc:questdb data integration issue#4944

docs/contribute/ml-handlers.mdx
**Fixes** [#92 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/92)
- added a couple of sections to the docs page on building an ml handler
=> updated a doc page on ml handlers

mindsdb/integrations/handlers/openai_handler/openai_handler.py
Adds support for GPT4 via the OpenAI integration.
Adds GPT4 models to the list of supported chat models, as it uses the chat endpoint instead of normal text completion endpoint.
=> Add support for GPT4

docs/nlp/text-summarization-inside-mysql-with-openai.mdx
it was a documentation change in mysql file which was done by me .
- [YES ] 📄 This change requires a documentation update
- [yes ] I have updated the documentation, or created issues to update them.
=> /docs/nlp/text-summarization-inside-mysql-with-openai.mdx

docs/nlp/sentiment-analysis-inside-mongodb-with-openai.mdx
=> Update a title of the MongoDB Sentiment Analysis tutorial

docs/data-integrations/oceanbase.mdx
I have created a doc page for the OceanBase data integration.
**Fixes** #4951
I have created a doc page for the OceanBase data integration.
=> Create a Doc Page for the OceanBase Data Integration

docs/nlp/sentiment-analysis-inside-mysql-with-openai.mdx
Update `/docs/nlp/sentiment-analysis-inside-mysql-with-openai.mdx` with the following:
- title: Sentiment Analysis with MindsDB and OpenAI using SQL
- sidebarTitle: Sentiment Analysis using SQL
Fixes #5005
- Replace existing title and subtitle with content from issue #5005
=> Update documentation with content from Issue #5005

mindsdb/interfaces/jobs/scheduler.py
Fix a lot of connections from jobs
=> Jobs connect fix

docs/setup/self-hosted/pip/linux.mdx
Made a change to the documentation by adding a point in the linux.mdx file.
=> added a point in the using python module section of the linux.mdx file

mindsdb/__about__.py, requirements.txt
Revert to `lightwood==23.2.1.1`.
=> Hotfix: 23.3.3.4

docs/data-integrations/twitter.mdx, docs/sql/tutorials/twitter-chatbot.mdx
**Fixes** [#95 from mindsdb_prvate](https://github.com/mindsdb/mindsdb_private/issues/95)
- updated Twitter Chatbot tutorial
[Building a Chatbot for Twitter using MindsDB and GPT-4 - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10995037/Building.a.Chatbot.for.Twitter.using.MindsDB.and.GPT-4.-.MindsDB.pdf)
- updated instructions on how to connect Twitter to MindsDB
[Twitter - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10995040/Twitter.-.MindsDB.pdf)
=> updated twitter docs

docs/data-integrations/solr.mdx
- Create a doc page for the Solr data integration
**Fixes** #5029 
- Doc update
- Created doc page for the Solr data integration
=> Created doc page for the Solr data integration

docs/data-integrations/MonetDB.mdx
**Fixes** #4843 
- Created a doc page for the MonetDB data integration
=> Created a doc page for the MonetDB data integration

mssql.mdx
I have created a doc page for the Microsoft SQL Server data integration. 
**Fixes** #4845
I have created a doc page for the Microsoft SQL Server data integration.
=> Create a Doc Page for the Microsoft SQL Server Data Integration

mindsdb/integrations/handlers/twitter_handler/twitter_handler.py
=> fix: twitter handler config.json param check 

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py, mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py, mindsdb/integrations/handlers/twitter_handler/twitter_handler.py, mindsdb/integrations/libs/ml_exec_base.py
Changes:
- show db or ml handler name in error messages
- twitter:
- long tweet is reply to reply 
- adding counting of messages
=> Twitter fixes 20/03

docs/mint.json
**Fixes** #none
fixed mint.json
=> fixed mint.json

README.md
* Cleanup HTML + layout in header of README.md
* Add OSSRank shield to the header
Non-breaking, readme update
=> Cleanup HTML + layout in header of README.md, add OSSRank shield

mindsdb/integrations/handlers/openai_handler/__init__.py
Openai is permanent engine. It is not possible to remove it now
=> Openai is permanent

mindsdb/integrations/handlers/openai_handler/openai_handler.py, mindsdb/integrations/handlers/twitter_handler/twitter_handler.py
Log using of Twitter and Openai API:
- in/out to openai
- in to twitter api
=> Logging of using of APIs 

docs/nlp/nlp-extended-examples.mdx
**Fixes** [#5003](https://github.com/mindsdb/mindsdb/issues/5003)
Documentation Update
Opened a text editor, then changed the requested text from `Here are the tasks supported by MindsDB and Hugging Face:` to `Here are the tasks supported by MindsDB and OpenAI:`
- [ N/A ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ N/A ] I have commented my code, particularly in hard-to-understand areas.
- [   Y   ] I have updated the documentation, or created issues to update them.
- [ N/A ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [   Y   ] I have shared a short loom video or screenshots demonstrating any new functionality.
=> [Docs] Update text (Hugging Face into OpenAI) #5003

docs/mint.json
Added Airtable to the data-integrations group.
=> Added Airtable to the data-integrations group.

docs/mint.json
Add `clickhouse.mdx` to mint.json
**Fixes** #5123 
Added the file to the navigation section
=> Add clickhouse to mint.json

docs/mint.json
**Fixes** #(issue) - no issue related
fixed nav items in docs
=> fixed nav items in docs

docs/nlp/question-answering-inside-mongodb-with-openai.mdx
Updated a title of the MongoDB Question Answering tutorial
- Changed `Title` and `SideTitle` in the documentation.
**Fixed** #5009
- Documentation changes.
- [✔️] 📄 This change requires a documentation update
- [✔️] My code follows the style guidelines(PEP 8) of MindsDB.
- [✔️] I have updated the documentation, or created issues to update them.
=> [Doc Updated] - Title changed

docs/data-integrations/matrixone.mdx
Create a doc page for the Matrix One data integration
**Fixes** #4782 
Creating a new doc page for Matrix One data integration
=> created a doc page for Matrixone

docs/custom-model/ray-serve.mdx
Added additional information to the readme with links for further articles.
=> Update ray-serve.mdx with issue number #5157

docs/mint.json
Added "data-integrations/Google-BigQuery" to line #329
Simply added the line to the docs file as instructed.
=> Added Google-BigQuery.mdx to docs navigation

mindsdb/integrations/handlers/neuralforecast_handler/requirements.txt
=> [BUG FIX] Fix neuralforecast requirements file

docs/data-integrations/TiDB.mdx
I have created a doc page for the TiDB data integration.
**Fixes** #5170 
I have created a doc page for the TiDB data integration.
=> Create a Doc Page for the TiDB Data Integration

docs/data-integrations/SQLite.mdx
i have created a doc file that explaines what SQLite is, how to implement it and how to use it!
fixed #5080
=> Created a doc page for the SQLite data integration.

docs/mint.json
Added hive.mdx into mint.json 
**Fixes** #5181 
=> Fixes for Issue #5181

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py
=> fix: set training progress in lightwood handler

docs/custom-model/mlflow.mdx
**Fixes** #4362 
- updated mlflow docs
[MindsDB and MLflow - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/11002719/MindsDB.and.MLflow.-.MindsDB.pdf)
=> updated mlflow docs

mindsdb/integrations/handlers/openai_handler/openai_handler.py
=> fix: prediction-time temperature for OpenAI models

docs/mint.json
Add impala.mdx file to mint.json. 
**Fixes** #5182
=> Add impala.mdx file to docs navigation

docs/mint.json, docs/mongo/insert.mdx, docs/nixtla/house-sales-statsforecast.mdx, docs/nixtla/statsforecast.mdx
**Fixes** #5224 
- page under ML Engines
- page under Tutorials
=> updated statsforecast docs

.github/workflows/acceptance_tests.yml, tests/integration_tests/flows/test_predict_text_sentiment_openai_tutorial.py
Now is not possible to run 'CREATE ML_ENGINE openai'. Fixing test for learning hub
=> Fix LH test: openai is permanent

docs/mint.json
Adding Microsoft-access to the docs
**Fixes** #5251 
update in mints.json
Adding the Microsoft-access file to pages
=> Added microsoft-access Fix #5251

docs/mint.json
=> added mysql.mdx file to the pages of Data-integration

docs/mint.json
Adding MongoDB file to the docs
**Fixes** #5253 
Added MongoDB.mdx file to docs navigation
=> Added MongoDB file to docs navigation

docs/mint.json
Added the Firebird.mdx file to docs navigation
**Fixes** #5272
I added the `Firebird.mdx` file to the `pages` to `/docs/mint.json` file
=> Solved #5272 issue.

docs/setup/self-hosted/pip/linux.mdx, docs/setup/self-hosted/pip/macos.mdx, docs/setup/self-hosted/pip/source.mdx, docs/setup/self-hosted/pip/windows.mdx
**Fixes** #5203 
- updated requirement for pip version to `pip >= 20.3`
=> docs: updated pip version requirement

docs/mint.json
Added elasticsearch.mdx file to the "pages".
=> Updated mint.json

docs/custom-model/openai.mdx, docs/nlp/nlp-mindsdb-openai.mdx, docs/nlp/question-answering-inside-mongodb-with-openai.mdx, docs/nlp/question-answering-inside-mysql-with-openai.mdx, docs/nlp/sentiment-analysis-inside-mongodb-with-openai.mdx, docs/nlp/sentiment-analysis-inside-mysql-with-openai.mdx, docs/nlp/text-summarization-inside-mongodb-with-openai.mdx, docs/nlp/text-summarization-inside-mysql-with-openai.mdx, docs/setup/self-hosted/docker.mdx
**Fixes** https://mindsdb.slack.com/archives/C027S7MHU49/p1680098572897039
- updated openai docs according to latest developments
=> updated openai docs

docs/mint.json
Updated mint.json with the Apache-Druid page info.
**Fixes** 
#5286
- [✅ ] 📄 This change requires a documentation update
Added page info
- [ ✅] My code follows the style guidelines(PEP 8) of MindsDB.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] I have updated the documentation, or created issues to update them.
- [✅ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [✅ ] I have shared a short loom video or screenshots demonstrating any new functionality.
=> updated mint.json with Apache-Druid page

docs/mint.json
Add the oceanbase.mdx file to docs navigation
[#5279](https://github.com/mindsdb/mindsdb/issues/5279)
=> Add the oceanbase.mdx file to docs navigation

docs/mint.json
amazon-s3.mdx was added to mint.json under Data Integrations
=> Add the amazon-s3.mdx file to docs navigation #5285

docs/mint.json
Added the `oracle.mdx` file to the docs navigation as per the instructions!
It solves this issue #5280
Please check the code changes 😅
=> Added "oracle.mdx" file in docs

docs/contribute/app-handlers.mdx
**Fixes** #5330 
- updated app-handlers doc page
=> updates to app-handlers doc page

mindsdb/api/http/namespaces/default.py, mindsdb/integrations/libs/ml_exec_base.py, mindsdb/integrations/utilities/sql_utils.py
`GET /status` now returns mindsdb version
=> return mindsdb version via GET /status

docs/data-integrations/Informix.mdx
Added Informix.mdx file to data-integrations
=> Added Informix.mdx file to data-integrations

docs/mint.json
Add the questdb.mdx file to docs navigation #5314
- [✓] ⚡ New feature (non-breaking change which adds functionality)
I have added the questdb to docs/mint.json
- [ ✓] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ✓] I have commented my code, particularly in hard-to-understand areas.
- [ ✓] I have updated the documentation, or created issues to update them.
- [ ✓] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ✓] I have shared a short loom video or screenshots demonstrating any new functionality.
=> Add the questdb.mdx file to docs navigation

docs/mint.json
=> #5281 - Add the OrioleDB.mdx file to docs navigation

docs/contribute/loanTutorial/loanTutorial.mdx
=> Fix several typos in LoanTutorial

docs/contribute/issues.mdx
=> Fix typos in issues.mdx

docs/data-integrations/sap-hana.mdx
Created a documentation page for the SAP HANA data integration.
**Fixes** #5191
=> Created doc for SAP HANA data integration

docs/data-integrations/starrocks.mdx
=> Added starrocks.mdx

mindsdb/integrations/handlers/couchbase_handler/couchbase_handler.py
Looks like `ClusterTimeoutOptions` was not used. Fixed.
=> `Couchbase` handler improvements

tests/handler_tests/test_openai_handler.py
Updated updated test_openai_handler.py by integrating the test for invalid openai name parameters
**Fixes** #5112 
=> updated test_openai_handler.py

docs/setup/self-hosted/pip/linux.mdx, docs/setup/self-hosted/pip/macos.mdx, docs/setup/self-hosted/pip/source.mdx, docs/setup/self-hosted/pip/windows.mdx
Update self-hosted pip instructions to note Python 3.9.x support.
**Fixes** #5311 
Doc update.
=> Fix issue 5311

mindsdb/integrations/handlers/neuralforecast_handler/README.md, mindsdb/integrations/handlers/neuralforecast_handler/neuralforecast_handler.py, mindsdb/integrations/utilities/time_series_utils.py, tests/unit/ml_handlers/test_neuralforecast.py
Implements the `describe()` method for the Neuralforecast handler.
New code in `mindsdb/integrations/handlers/neuralforecast_handler/`
Added to tests in `tests/unit/ml_handlers/test_neuralforecast.py`
Made sure tests for Statsforecast and the time series utilities still run.
```
CREATE MODEL 
mindsdb.nf_desc
FROM example_db
(SELECT * FROM demo_data.house_sales)
PREDICT ma
ORDER BY saledate
GROUP BY type, bedrooms
-- as the target is quarterly, we will look back two years to forecast the next one
WINDOW 8
HORIZON 4
USING engine='neuralforecast', train_time=0.01
;
```
```
DESCRIBE mindsdb.nf_desc;
```
```DESCRIBE mindsdb.nf_desc.model;```
```DESCRIBE mindsdb.nf_desc.features;```
=> Implement NeuralForecast describe method 

mindsdb/integrations/handlers/langchain_handler/langchain_handler.py, mindsdb/integrations/handlers/openai_handler/openai_handler.py
Reverted changes for function _get_api_key #4851
=> Fix Openai API_KEY

mindsdb/integrations/handlers/twitter_handler/twitter_handler.py
This query returned an error:  object has no attribute 'media_upload'
```
INSERT INTO my_twitter.tweets (
select in_reply_to_tweet_id, text, media_url FROM postgres.responses_with_media
where in_reply_to_tweet_id is not null limit 2 );
```
=> Twitter upload images bug fix: object has no attribute 'media_upload'

mindsdb/integrations/handlers/ray_serve_handler/__about__.py, mindsdb/integrations/handlers/ray_serve_handler/__init__.py, mindsdb/integrations/handlers/ray_serve_handler/example.md, mindsdb/integrations/handlers/ray_serve_handler/ray_serve_handler.py, mindsdb/integrations/handlers/ray_serve_handler/requirements.txt, mindsdb/integrations/handlers/ray_serve_handler/setup.py
Includes handler for BYOM via Ray Serve, plus a hands-on example.
**Fixes** #4868
=> [fix] restore ray serve handler

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
If sql query doesn't return error native query raised exception `cannot unpack non-iterable NoneType object`
Example
```
SELECT * from integration (delete from aaa where real_price=6)
```
=> Fix native query without response

docs/contribute/ml-handlers.mdx, mindsdb/integrations/handlers/langchain_handler/langchain_handler.py, mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py, mindsdb/integrations/handlers/openai_handler/openai_handler.py, mindsdb/integrations/libs/ml_exec_base.py
=> [fix] finetune calls

docs/mint.json
**Fixes**  #5574
Followed the instruction to add  the `scylladb` item to the `"pages"`, like this:
```
{
"group": "Data Integrations",
"pages": [
"data-integrations/scylladb"
]
}
```
=> Added scylladb item to data integration group

docs/rest/models/query-model.mdx, docs/rest/projects/get-projects.mdx, docs/rest/sql.mdx
The cookies parameter in `requests.get` accepted object dict while string was passed. Also removed a unwanted curly bracket which lead to *SynataxError*
=> Fixed the python code for RESTAPI

docs/mint.json
Solved issue Add `tdengine` to the docs navigation#5572
Added the `tdengine` file as the last item to the `"pages"` in the `"Data Integrations"` group(at line 310 in `docs\mint.json`)
=> Solved issue#5572

mindsdb/__about__.py, requirements.txt
- revert Lightwood requirement to be compatible with models trained with previous version
=> Release 23.4.3.2

docs/mindsdb-handlers.mdx
I fixed two links that could not be pressed upon.
**Fixes** #5588
=> Fix broken links

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py, mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py, mindsdb/integrations/handlers/langchain_handler/langchain_handler.py, mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py, mindsdb/integrations/handlers/mlflow_handler/mlflow_handler.py, mindsdb/integrations/handlers/neuralforecast_handler/neuralforecast_handler.py, mindsdb/integrations/handlers/openai_handler/openai_handler.py, mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py, mindsdb/interfaces/model/model_controller.py
Changes in describe model:
`describe model_name` will return the same result as `select * from models where name='model_name'` plus information about possible choices to describe in first column:
```
> describe lw_model;
+-------------------------------+----------+-----------+---------+...+----------------------------+
| TABLES                        | NAME     | ENGINE    | PROJECT |...| CREATED_AT                 |
+-------------------------------+----------+-----------+---------+...+----------------------------+
| info, model, features, jsonai | lw_model | lightwood | mindsdb |...| 2023-03-15 15:17:39.522451 |
+-------------------------------+----------+-----------+---------+...+----------------------------+
```
Values from from first column have to be used as attributes in describe …
=> Changes in describe model

mindsdb/interfaces/jobs/jobs_controller.py, mindsdb/interfaces/jobs/scheduler.py, mindsdb/interfaces/storage/db.py, mindsdb/migrations/versions/2023-04-11_b8be148dbc85_jobs_history_query.py, tests/unit/test_project_structure.py
Changes:
- Show rendered query in jobs_history table #5378
- Use updated_at as lock time in jobs_history table  #5101
=> Jobs query render

docs/setup/self-hosted/pip/linux.mdx
Fixed a typo in `docs/setup/self-hosted/pip/linux.mdx` file.
**Fixes** #5658
=> [docs] fix typo

docs/setup/self-hosted/pip/macos.mdx
Fixed the mysqul typo to close #5659
**Fixes** #5659
- 🐛 Bug fix (non-breaking change which fixes an issue)
- 📄 This change requires a documentation update
=> Fixed mysqul typo

docs/nlp/nlp-mindsdb-openai.mdx
- Added the tip for mindsDB pro users on Open API key.
- Fixed a typo on text bolding style in the open API docs.
**Fixes** #5665
=> Update for pro users on open API key requirement.

docs/sql/create/project.mdx
- Created a new file project.mdx in docs/sql/create/ folder.
- Added provided documentation to project.mdx for CREATE PROJECT statement.
**Fixes** #5695
=> Add CREATE PROJECT Documentation Page

docs/nlp/question-answering-inside-mongodb-with-openai.mdx
Update in nlp doc file question-answering-inside-mongodb-with-openai.mdx
**Fixes** #5671 
**TYPO**
=> Update nlp docs - question-answering-inside-mongodb-with-openai

docs/contribute/ml-handlers.mdx
I have updated the ML docs accordingly.
**Fixes** #5722 
- [X ] ⚡ New feature (non-breaking change which adds functionality)
Copied and Pasted the given code at the appropriate spot.
=> updated ml docs

docs/setup/self-hosted/pip/windows.mdx
Creating this for the issue #5657 
**Fixes** #5657
=> Updated windows.mdx

docs/contribute/ml-handlers.mdx
Updated ml-handlers.mdx file at https://github.com/mindsdb/mindsdb/blob/staging/docs/contribute/ml-handlers.mdx
with links to template unit tests.
**Fixes** #5723
=> Updated ML handler contribution docs with links to template unit tests

docs/nixtla/statsforecast.mdx
**Fixes** #-
updated statsforecast+hierarchicalforecast docs
=> updated statsforecast+hierarchicalforecast docs

docs/nlp/sentiment-analysis-inside-mongodb-with-openai.mdx
Add below line to doc
"Please note that it is required to provide an OpenAI API key when using MindsDB Pro version."
**Fixes** #5670 
Update "sentiment-analysis-inside-mongodb-with-openai.mdx"
=> Update doc file mongodb with openai

mindsdb/integrations/handlers/bigquery_handler/README.md, mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py, mindsdb/integrations/libs/const.py, mindsdb/interfaces/database/integrations.py
Changes:
```
CREATE DATABASE bq
With ENGINE = 'bigquery',
PARAMETERS =  {
"project_id": "bgtest-1111",
"dataset": "mydataset",
"service_account_keys": "/tmp/keys.json"
}
```
Tables in objects tree will be showed from selected dataset
And this dataset will be used as default in queries:
`select * from bq.rentals`
Also choosing dataset (same or different will work too:
`select * from bq.mydataset.rentals`
`select * from bq.otherdataset.fish`
It is possible to put json content in service_account_json key instead of using file in (service_account_keys) in connection arguments:
```
CREATE DATABASE bq
With ENGINE = 'bigquery',
PARAMETERS =  {
"project_id": "bgtest-1111",
"dataset": "mydataset",
"service_account_json": {
"type": "service_account",
"project_id": "bgtest-1111",
"private_key_id": …
```
=> Bigquery fixes

docs/setup/environment-vars.mdx
Documentation changes 
* #(issue)
=> fixing the environment variable

docs/contribute/app-handlers.mdx
This PR fixes a typo from the docs. Changed `Aplication` to `Application`
#5749
=> Changed Aplication to Application

README.md
…
A new point had been extended in the previous line resulting in lack of visibility of one of the main use case of Mindsdb .
Added a new line/point
=> A new point has been added

docs/custom-model/openai.mdx
=> update openai.mdx : #5666

docs/sql/tutorials/ai-tables.mdx
**Fixes** #-
updated page for ai tables
=> updated page for ai tables

docker/release
This PR adds the missing tweepy dependency in the Docker image.
**Fixes** #5789 
Include tweepy in the image.
=> Add missing dependency

docs/sql/drop/jobs.mdx
=> Add content to the DROP JOB page

docs/sql/drop/project.mdx
=> Added content to the DROP PROJECT page

docs/data-integrations/ckan.mdx
=> Replaced <Note> with <Info>

docs/sql/drop/table.mdx
Documentation update for instructions on how to DROP a file.
**Fixes** #5766
Adds documentation on how to DROP a file to `docs/sql/drop/table.mdx` file
=> Add docs on how to DROP a file.

mindsdb/integrations/utilities/sql_utils.py
=> Fixed twitter handler import 

assets/contributions-agreement/signatures/cla.json, docs/data-integrations/all-data-integrations.mdx, docs/data-integrations/ckan.mdx, docs/data-integrations/duckdb.mdx, docs/data-integrations/google-bigquery.mdx, docs/sql/drop/jobs.mdx, docs/sql/drop/ml-engine.mdx, docs/sql/drop/project.mdx, docs/sql/drop/table.mdx, docs/sql/drop/view.mdx, mindsdb/__about__.py, mindsdb/integrations/utilities/sql_utils.py
=> Release 23.4.4.2

docs/data-integrations/mongodb.mdx
Correct Title in `mongodb.mdx `
**Fixes** #5801 
Changed Title parameter from "Mongo" to "MongoDB"
=> [Docs] Correct title in mongodb.mdx 

docs/data-integrations/elasticsearch.mdx
Correct sidebarTitle in elasticsearch.mdx
**Fixes** #5798
Changed sidebarTitle parameter from "Elastic" to "Elasticsearch"
=> [Docs] Correct sidebarTitle in elasticsearch.mdx 

docs/data-integrations/apache-solr.mdx
Correct sidebarTitle in apache-solr.mdx
**Fixes** #5793 
Changed sidebarTitle to Apache Solr from Solr
=> [Docs] Correct sidebarTitle 

docs/sql/drop/database.mdx
Added the content to the DROP DATABASE page
**Fixes**  #5805
=> Added the content to the DROP DATABASE page

docker/release
There was missed dependency in the docker file
=> Fix missed statsforecast dependency

docs/sql/tutorials/twitter-chatbot.mdx
**Fixes** #-
updated twitter tutorial according to latest fixes
=> updated twitter tutorial

docs/data-integrations/ibm-db2.mdx
I added IBM at line 6  
**Fixes** #5800
**Fixes** #5800
=> I added IBM

docs/sql/api/describe.mdx
**Fixes** #5601 
updated DESCRIBE docs
https://www.loom.com/share/a407937e00564c7cb0e7326545a93c41
=> updated DESCRIBE docs

docs/sql/create/ml-engine.mdx
Documentation edited n ml-engine.mdx from lines 23-26 edited. Also, this is my first contribution to an open-source project.
Documentation edited n ml-engine.mdx from line 23-26 edited.
=> changed the ml-engine.mdx doc file

mindsdb/integrations/handlers/github_handler/README.md, mindsdb/integrations/handlers/github_handler/github_handler.py, mindsdb/integrations/handlers/github_handler/github_tables.py
Pull requests table implementation of the GitHub handler #5357
=> Pull requests table implementation for the github_handler

requirements.txt
=> Test use 0.6.0 duckdb

docs/mint.json
added the What's New anchor that links to Changelog - awaiting info from Mintlify on how to add an icon
**Fixes** #-
added the What's New anchor that links to Changelog - awaiting info from Mintlify on how to add an icon
=> added whats new to docs anchors

docs/mint.json
added an icon in docs to what's new
**Fixes** #-
added an icon in docs to what's new
=> added an icon in docs to what's new

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
=> Remove 'model' key on describe <model>.info for LW

mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
=> [ENH] Writing tool for Langchain agents

mindsdb/integrations/handlers/langchain_handler/langchain_handler.py, mindsdb/integrations/handlers/openai_handler/openai_handler.py
Small fixes so that `gpt-3.5-turbo` works correctly. As of now, GPT-4 doesn't really work as it does not comply with the format that LangChain asks so that the pipeline actually works, so the user should avoid it (for now).
Note: #5479 should be merged first.
=> [ENH] Add support for chat models in grounded langchain

docs/tutorials.mdx
update Forecast Uber Stock Prices tutorial
=> update Forecast Uber Stock Prices tutorial

docs/sql/api/describe.mdx
the changes made to DESCRIBE docs were not correct - it is undone now
**Fixes** #-
the changes made to DESCRIBE docs were not correct - it is undone now
=> docs changes to describe undone

mindsdb/integrations/handlers/mongodb_handler/Manual_QA.md
Manual QA - Test MongoDB Handler Manually
**Fixes** #3228 
N/A
=> Mongodb handler manual test

docs/mint.json, docs/ml-engines/automl/autosklearn.mdx
=>  [Docs] Create and add the autosklearn file to navigation #5988 

docs/custom-model/langchain.mdx, docs/mint.json
Initialized langchain documentation and added navigation to it.
**Fixes** #5989
As described in issue #5989
=> Added langchain to navigation

docs/mint.json, docs/nixtla/neuralforecast.mdx
Create and add the neuralforecast file to navigation 
**Fixes** #5991
updated documentation as requested
=> add  neuralforecast file to navigation #5991

docs/custom-model/byom.mdx, docs/mint.json
**Fixes** #5990 
As aforementioned in #5990
=> Description

docs/manual-qa/template.mdx
added manual-qa folder to docs with page template
**Fixes** #-
added manual-qa folder to docs with page template
=> added manual-qa folder to docs with page template

mindsdb/integrations/handlers/statsforecast_handler/__init__.py
=> Fix init.py for statsforecast

docs/manual-qa/customer_churn_tutorial_test.mdx
This PR tests the Customer Churn tutorial
https://docs.mindsdb.com/sql/tutorials/customer-churn and documents the all executed commands and their output.
**Fixes** #6052
=> Added Customer Churn tutorial test

docs/manual-qa/text_summarization_tutorial_test.mdx
This PR tests the text summarization tutorial 
https://docs.mindsdb.com/nlp/text-summarization-inside-mysql-with-openai and documents the all executed commands and their output.
**Fixes** - [#6057](https://github.com/mindsdb/mindsdb/issues/6057)
- 📄 Tested the Text Summarization tutorial
=> Add Text-Summarization tutorial

docs/manual-qa/sentiment_analysis_tutorial_test.mdx
- Documents all executed commands and their output which tests the model used to determine sentiment as positive, negative, neutral given a statement using the OpenAI's gpt-3.5-turbo model.
Documentation
=> Adds SQL query and code for sentiment analysis tutorial

mindsdb/integrations/handlers/google_calendar_handler/README.md, mindsdb/integrations/handlers/google_calendar_handler/google_calendar_handler.py, mindsdb/integrations/handlers/google_calendar_handler/google_calendar_tables.py
This PRs resolves a few issues related to the calendar integration and fixes README examples.
**Fixes** https://github.com/mindsdb/mindsdb/issues/6048, https://github.com/mindsdb/mindsdb/issues/6050, https://github.com/mindsdb/mindsdb/issues/6051, https://github.com/mindsdb/mindsdb/issues/6054 , https://github.com/mindsdb/mindsdb/issues/6059 , https://github.com/mindsdb/mindsdb/issues/6060 , https://github.com/mindsdb/mindsdb/issues/6061
Minor changes to the google calendar logic as changing the date time parsing, adding a check for split method when there is only one string in the attendee's list, solving the bug with the email key, changing the proper API call method, and fixing all code examples in the README.
=> Resolve GoogleCalendar bugs

docs/manual-qa/openai_qa_with_context_tutorial_test.mdx
Added ```openai_qa_with_context_tutorial_test.mdx``` that tests OpenAI - Answering Questions with Context tutorial in the documentation
**Fixes** #6093
Documentation
=> Add openai_qa_with_context_tutorial_test.mdx test documentation

docs/connect/dbt.mdx, docs/connect/kafka.mdx, docs/mint.json, docs/mongo/database.mdx, docs/mongo/insert.mdx, docs/quickstart.mdx, docs/sdk/javascript_sdk.mdx, docs/sdk/python_sdk.mdx, docs/setup/cloud-pro.mdx, docs/setup/cloud-starter.mdx, docs/setup/cloud.mdx, docs/sql/api/join-on.mdx, docs/sql/api/join.mdx, docs/sql/api/manage-models-versions.mdx, docs/sql/create/database.mdx, docs/sql/create/jobs.mdx, docs/sql/create/ml-engine.mdx, docs/sql/create/model.mdx, docs/sql/create/project.mdx, docs/sql/create/table.mdx, docs/sql/create/view.mdx, docs/sql/drop/database.mdx, docs/sql/drop/jobs.mdx, docs/sql/drop/ml-engine.mdx, docs/sql/drop/model.mdx, docs/sql/drop/project.mdx, docs/sql/drop/table.mdx, docs/sql/drop/view.mdx, docs/tutorials_mindsdb_no_sql.mdx, docs/tutorials_mindsdb_sql.mdx
new docs navigation
**Fixes** #-
=> new docs navigation

docs/manual-qa/hf_crypto_buy_signals_tutorial_test.mdx
Added Manual QA for Hugging face - Crypto Buy Signals
=> Added manual qa for Hugging face Crypto Buy Signals

docs/manual-qa/hf_industry_tutorial_test.mdx
Merging this Pull Request closes Issues #6087
=> Added Manual QA Test the Hugging Face - Industry tutorial

docs/manual-qa/hf_hate_speech_tutorial_test.mdx
merging this pull request closes issue #6083
=> added hatespeech tutorial

mindsdb/integrations/handlers/openai_handler/openai_handler.py
=> fix openai api key

assets/contributions-agreement/signatures/cla.json, mindsdb/__about__.py, requirements.txt
Fixes
- Fixed openai api key #6136
- Failed to fetch table from yugabytedb #6070
=> Release 23.5.3.2

docs/manual-qa/quickstart_tutorial_test.mdx
Added Manual QA for MindsDB Quickstart tutorial #6074
=> Added Manual QA for MindsDB Quickstart tutorial

docs/setup/self-hosted/pip/macos.mdx
Updated Python versions in `docs/setup/self-hosted/pip/macos`
**Fixes** #6139 
- [ ☑️ ] 📄 This change requires a documentation update
- [ ✅ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ❌ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅ ] I have updated the documentation, or created issues to update them.
- [ ❌ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ❌ ] I have shared a short loom video or screenshots demonstrating any new functionality.
=> self-hosted/pip/source.mdx is updated

docs/manual-qa/openai_qa_without_context_tutorial_test.mdx
Merging this Pull Request closes the Issue #6092
=> added openai mdx file

docs/mint.json
updates to docs nav
**Fixes** #-
=> updated docs nav

docs/mint.json, docs/mongo/database.mdx, docs/mongo/insert.mdx, docs/mongo/ml_engine.mdx
added ml engines to mongo docs
**Fixes** #5778 
=> added ml engines to mongo docs

docs/setup/self-hosted/docker.mdx
added min req for docker docs
**Fixes** #-
=> added min req for docker docs

docs/sql/create/ml-engine.mdx
changed create ml engine example to openai
**Fixes** #-
=> changed create ml engine example to openai

docs/sql/create/ml-engine.mdx
corrections on ml engine doc page (added PREDICT clause)
**Fixes** #-
=> corrections on ml engine doc page

docs/data-integrations/yugabytedb.mdx, mindsdb/integrations/handlers/yugabyte_handler/README.md
=> add schema param to yugabyte integration docs

docs/manual-qa/hf_zsc_bart_tutorial_test.mdx
Added mdx file for bart tutorial steps
=> Added mdx file for bart tutorial steps

docs/manual-qa/openai_prompt_completion_with_parameters_at_prediction_tutorial_test.mdx
Test the OpenAI - Prompt Completion with Parameters Provided at Prediction Time tutorial
**Fixes** #6095
Manual QA / Doc
Test the OpenAI - Prompt Completion with Parameters Provided at Prediction Time tutorial
=> Manual QA: Test the OpenAI - Prompt Completion with Parameters Provided at Prediction Time tutorial

docs/connect/tableau.mdx
Merging this PR closes issue #6193
=> [Docs] Corrected port value in tableau

docs/manual-qa/question_answering_tutorial_test.mdx
I included all the outputs from the tutorial but wasn't sure if I should've added the output for this query: 
```sql
SELECT * FROM models
WHERE name = 'question_answering_model';
```
=> Test the Question Answering tutorial #6194

docs/connect/mongo-compass.mdx
Corrected port value in mongo-compass
resolves #6187
=> corrected port value in mongo-compass

docs/data-integrations/google-bigquery.mdx
updated google bigquery doc page:
**Fixes** #5606 
=> updated google bigquery doc page

docs/app-integrations/twitter.mdx, docs/sql/tutorials/twitter-chatbot.mdx
added a note about twitter elevated access
**Fixes** #6029 
=> docs twitter elevated access

docs/connect/mongo-shell.mdx
Description
Updated the Docs, to reflect the correct port number.
**Fixes** #6189 
Changed the port value from <port> to 3306
=> Updated port value in mongo-shell connect docs.

mindsdb/api/http/start.py, mindsdb/integrations/libs/ml_exec_base.py, mindsdb/interfaces/database/integrations.py, mindsdb/interfaces/model/functions.py, mindsdb/interfaces/model/model_controller.py, tests/integration_tests/flows/conftest.py
- finetuned model version was incorrect in some cases
- base model was incorrect in some cases
=> fix `finetune` issues

docs/data-integrations/apache-druid.mdx
made changes as mentioned in the issue
update the docs (docs/data-integrations/apache-druid.mdx) as mentioned in the issue.
added the instruction in docs/data-integrations/apache-druid.mdx file.
- [ Yes] 📄 This change requires a documentation update
it's instruction. which is needed to add to a specific file.
=> Update instructions for Apache Druid #6238

docs/data-integrations/apache-cassandra.mdx
Updated the instructions for Apache Cassandra
**Fixes** #6237
=> Updated instructions for Apache Cassandra

docs/setup/self-hosted/pip/windows.mdx
Ensure the user installs correct version of Python to not have dependency errors.
It fixes the issue #6240 
Changed the python version in /setup/self-hosted/pip/windows doc page.
=> Updated Python versions in the /setup/self-hosted/pip/windows doc page

docs/custom-model/langchain.mdx
langchain docs (reviewed by Patricio)
**Fixes** #-
=> langchain docs

docs/data-integrations/apache-hive.mdx
Added a Tip (Mentioned in issue #6268) at the end of `Implementation` chapter, in the `docs/data-integrations/apache-hive.mdx` file. 
**Fixes** #6268 
Documentation Update.
=> Solved the [Docs] Update instructions for Apache Hive issue.

docs/sdk/javascript-sdk.mdx, docs/setup/self-hosted/pip/linux.mdx, docs/setup/self-hosted/pip/macos.mdx, docs/setup/self-hosted/pip/source.mdx, docs/setup/self-hosted/pip/windows.mdx
- added instructions to all pip pages to install libmagic
- btw: corrected model name in js sdk docs
**Fixes** #-
=> added how to fix pip error

docs/tutorials/mindsdb-huggingface-tutorial.mdx
=> learning hub community tutorials

docs/data-integrations/cloud-spanner.mdx
#6274 
Added tip in cloud-spanner mdx file.
Added Tip in cloud-spanner mdx file.
=> Added in cloud-spanner

docs/data-integrations/couchbase.mdx
Tip was added under the implementation section.
This resolves issue #6276
**Fixes** #(6276)
=> add tip to couchbase implementation (#6276)

docs/data-integrations/cockroachdb.mdx
Updated per #6275
Adds Tip language
**Fixes** #6275 
Added HTML to explain Tip
=> Adds Tip language per #6275

docs/data-integrations/amazon-s3.mdx
=> [Docs] Updated instructions for Amazon S3

docs/tutorials/mindsdb-huggingface-tutorial.mdx, docs/tutorials/multilingual_spam_tutorial.mdx, docs/tutorials/zero-shot-classification-postgresql.mdx
=> updated learning hub tutorials

docs/faqs/whitelist-ips.mdx, docs/mint.json
- created FAQs section
- added what IPs need to be whitelisted
**Fixes** #-
=> docs faqs section

docs/data-integrations/d0lt.mdx
I have updated the instructions for D0It as mentioned in the issue #6299 
- [✅ ] 📄 This change requires a documentation update
- [✅ ] I have updated the documentation, or created issues to update them.
=> Updated instructions for D0It

mindsdb/integrations/handlers/langchain_handler/langchain_handler.py, mindsdb/integrations/handlers/langchain_handler/requirements.txt
1. Swap memory for one that never surpasses the model’s token limit
2. Revokes write tool if the user doesn’t explicitly confer write access into other integrations
3. Fix bugs, improve argument passing.
4. Bumps to newest langchain version
=> [fix] langchain: various improvements in memory and prompt templating

docs/data-integrations/cratedb.mdx
**Fixes**- #6298
I added the provided content at the end of the implementation chapter inside cratedb.mdx.
=> Updated cratedb.mdx

mindsdb/integrations/handlers/mongodb_handler/Manual_QA.md
Add three datasets tests commands and screenshots
1. Covid19 Vaccination trends Data Set
2. Algerian Forest Fire Data Set
3. Wine Quality Data Set
**Fixes** #6223 
All three tests were successful
PS- There was one more test that I need to append in the file but it failed due to TypeError. I will update the file and open an issue.
=> MongoDB handler tests manually: 3/3 successful

docs/tutorials/mindsdb-huggingface-tutorial.mdx, docs/tutorials/multilingual_spam_tutorial.mdx, docs/tutorials/zero-shot-classification-postgresql.mdx
=> learning hub update

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
Fixes #6063
Remove checking of associated dataset
https://www.loom.com/share/0f01caa180eb42ab9e91452e63809829
=> Fix: 'The model does not have an associated dataset' error

docs/data-integrations/apache-impala.mdx
=> Update [DOCS] in `docs/data-integrations/apache-impala.mdx`

docs/data-integrations/duckdb.mdx
Added Tip to duckdb.mdx
Added Tip at the end of Implementation in the duckdb.mdx file.
Thanks.
=> Added Tip to duckdb.mdx

docs/custom-model/huggingface.mdx
added hf inference api to hf docs
**Fixes** #-
=> added hf inference api to hf docs

docs/manual-qa/hf_question_detection_tutorial_test.mdx
**Fixes** #6241 
Tested the Hugging Face Question detection tutorial and captured test results
=> Test Question Detection tutorial

docs/sql/tutorials/diabetes.mdx
```diff
-[Slack](https://join.slack.com/t/mindsdbcommunity/shared_invite/zt-o8mrmx3l-5ai~5H66s6wlxFfBMVI6wQ)
+[Slack](https://mindsdb.com/joincommunity)
```
Used a online MDX formatter to replace/update the slack link in the *diabetes.mdx* file according to the instructions of the issue.
=> Update Slack link according to given instruction in the issue

docs/faqs/persist-predictions.mdx
added explanation for persisting predictions
**Fixes** #-
=> added explanation for persisting predictions

mindsdb/integrations/handlers/monkeylearn_handler/README.md, mindsdb/integrations/handlers/monkeylearn_handler/__about__.py, mindsdb/integrations/handlers/monkeylearn_handler/__init__.py, mindsdb/integrations/handlers/monkeylearn_handler/monkeylearn_handler.py, mindsdb/integrations/handlers/monkeylearn_handler/requirements.txt, mindsdb/integrations/handlers/monkeylearn_handler/setup.py, tests/unit/executor_test_base.py
This is a handler for monkeylearn API 
**Fixes** #5367 
=> Monkeylearn handler for Mindsdb

mindsdb/integrations/handlers/llama_index_handler/README.md, mindsdb/integrations/handlers/llama_index_handler/__about__.py, mindsdb/integrations/handlers/llama_index_handler/__init__.py, mindsdb/integrations/handlers/llama_index_handler/llama_index_handler.py, mindsdb/integrations/handlers/llama_index_handler/requirements.txt, mindsdb/integrations/handlers/llama_index_handler/setup.py
Implemented the LlamaIndex  ML handler as per the new ML handler framework
=> Add support for LlamaIndex handler

mindsdb/api/mysql/mysql_proxy/utilities/sql.py, tests/unit/test_executor.py
=> Workaround for duckdb.TypeMismatchException2

CONTRIBUTING.md
[Docs] Updated link in CONTRIBUTING.md
**Fixes** #6366 
Replaced the [old ](https://join.slack.com/t/mindsdbcommunity/shared_invite/zt-o8mrmx3l-5ai~5H66s6wlxFfBMVI6wQ) link with the [new ](https://mindsdb.com/joincommunity) one
=> Updated link in mindsdb/CONTRIBUTING.md

docs/data-integrations/amazon-redshift.mdx
Updated text as required
**Fixes** #6235
=> Resolve issue #6235

docs/sql/tutorials/crop-prediction.mdx
**Fixes** #([#6383](https://github.com/mindsdb/mindsdb/issues/6383))
Documentation
Replaced the slack join link in crop-prediction.mdx
=> replaced slack join link

docs/data-integrations/amazon-dynamodb.mdx
Adding the given instruction into the implementation chapter in amazon-dynamodb.mdx file
**Fixes** #(6234)
Adding Tip in the implementation section 
Add the given instruction at the given location or section in the document
=> Update implementation chapter

docs/sql/create/file.mdx
Update link in docs\sql\create\file.mdx from `/sql/create/predictor` to `/sql/create/model`
=> Updated link in docs\sql\create\file.mdx

docs/sql/api/manage-models-versions.mdx
Update link in docs\sql\api\manage-models-versions.mdx 
**Fixes** #6360 
Documentation
Replace /sql/create/predictor with /sql/create/model .
=> Update predictor link

docs/sql/tutorials/twitter-chatbot.mdx
Updated the link as mentioned in the issue #6412
=> Updated link in docs/sql/tutorials/twitter-chatbot.mdx

docs/data-integrations/databricks.mdx
Updated documents for databricks db
=> added tip for databricks

mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
Replaced link in huggingface_handler.py on line 26 within the Exception. 
**Fixes** #6414 
Deleted original link and replaced with specified link. 
Please let me know that I have made the correct change and thank you for creating this beginners opportunity. 
Phil.
=> Changed link in Exception

docs/sql/tutorials/mindsdb-superset-snowflake.mdx
Updated link in docs/sql/tutorials/mindsdb-superset-snowflake.mdx
**Fixes** #6410
=> Updated link in docs/sql/tutorials/mindsdb-superset-snowflake.mdx

docs/sql/api/stream.mdx
Updated link in docs/sql/api/stream.mdx
closes #6381 
Replaced the [old ](https://join.slack.com/t/mindsdbcommunity/shared_invite/zt-o8mrmx3l-5ai~5H66s6wlxFfBMVI6wQ)link with the [new ](https://mindsdb.com/joincommunity)one
[✔️] My code follows the style guidelines(PEP 8) of MindsDB.
[ ] I have commented my code, particularly in hard-to-understand areas.
[✔️] I have updated the documentation, or created issues to update them.
[ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
[ ] I have shared a short loom video or screenshots demonstrating any new functionality.
=> Updated link in docs/sql/api/stream.mdx

docs/nlp/nlp-mindsdb-openai.mdx
**Fixes** #6359 
update link in docs\nlp\nlp-mindsdb-openai.mdx #6359
=> docs: update link in docs\nlp\nlp-mindsdb-openai.mdx

docs/manual-qa/home_rentals_tutorial_test.mdx
=> Fixed Issue 6244

docs/ml-engines/automl/lightwood.mdx
=> added lightwood docs link

docs/sql/tutorials/house-sales-forecasting.mdx
Replacing the line from this "/sql/create/predictor" to "/sql/create/model" in the file "docs\sql\tutorials\house-sales-forecasting.mdx" 
**Fixes** #6456 
=> #6456 Issue: Update link in docs\sql\tutorials\house-sales-forecasting.mdx

mindsdb/integrations/handlers/sendinblue_handler/sendinblue_tables.py
I have improved on the Sendinblue integration by using the `query_utilities` available in the common `utilities` package.
=> Improved Sendinblue Integration Using query_utilities

docs/quickstart.mdx
=> docs: Update query in quickstart.mdx

docker/release
Adding HF inference dependency to the docker
=> Add missing HF dependency

docs/app-integrations/github.mdx, docs/mint.json
=> github docs

docs/custom-model/huggingface.mdx
- updated hf inference api docs
- created a bug for one task: https://github.com/mindsdb/mindsdb/issues/6503
**Fixes** #-
=> updated hf inference api docs

docker/db_handler.Dockerfile, docker/executor.Dockerfile, docker/mindsdb.Dockerfile, docker/ml_handler.Dockerfile
Update microservices base image (python3.8 instead of python3.7)
Update installation requirements according the latest changes there
Perform acceptance testing (check that it works)
=> Keep microservice mode up to date

MANIFEST.in
=> Fix MANIFEST file to fix installation

docs/setup/self-hosted/pip/source.mdx
updated pip source install instructions
**Fixes** #-
=> updated pip source install instructions

docs/model-types.mdx
=> Issue #6487 Updating the sql query for model-types.mdx file

docs/nlp/nlp-mindsdb-hf.mdx
Updating the SQL to verify the status of the spam_classifier model. Issue - https://github.com/mindsdb/mindsdb/issues/6514
**Fixes** #6514 
Replaced - 
`
SELECT *
FROM mindsdb.models
WHERE name = 'spam_classifier';`
with 
`
DESCRIBE spam_classifier;
`
in `docs\nlp\nlp-mindsdb-hf.mdx` file
=> Updating the SQL to verify the status of the spam_classifier model

docs/custom-model/mlflow.mdx
I updated the query in `docs\custom-model\mlflow.mdx` to a simpler query.
=> Updated query in docs\custom-model\mlflow.mdx

docs/data-integrations/mongodb.mdx
Changed the `user` parameter with `username`
Issue [#6523](https://github.com/mindsdb/mindsdb/issues/6523)
Changed the `user` parameter with `username`
=> Issue #6523: [Docs]: Change Mongo docs user to username

docs/sql/tutorials/customer-churn.mdx
=> Fixes #6453

docs/tutorials.mdx
The list is updated with a new tutorial on how to `Predict Sales of Manufacturing with MindsDB using Java`,
A new blog is published on the above topic and its respective link has been added to the Tutorials List.
**Fixes** #3448
=> New Tutorial: Predict Sales of Manufacturing with MindsDB using Java

docs/sdk/python-sdk.mdx
added python sdk example that solves one of the community inquiries
**Fixes** #-
=> python sdk example

requirements/requirements.txt
=> Return old set of requirements

docker/release
This PR includes the llamaindex handler dependencies in the Docker image
=> Add llamaindex dependency to Docker

mindsdb/integrations/handlers/mysql_handler/mysql_handler.py, mindsdb/integrations/libs/const.py
Update MySQL information to tart using it on GUI forms  
=> Update Mysql handler documentation

docker/release
This PR adds langchain as a dependency to the Docker image
=> Add langchain dependency

docs/data-integrations/all-data-integrations.mdx
- Yugabyte has new parameter named schema i have added it to it's template and example in documentation.
=> Added schema Param in yugabyte template and example

docs/app-integrations/gmail.mdx, docs/app-integrations/google-calendar.mdx, docs/mint.json, mindsdb/integrations/handlers/google_calendar_handler/google_calendar_handler.py
This PR adds more docs about generating credentials.json file for gmail and calendar integrations and solves an issue with importing DataFrame.
=> Google handlers changes

docs/tutorials/sentiment-analysis-on-french-tweets-using-mysql.mdx
I have read the CLA document and I hereby sign the CLA
=> fixed #6413 docs link issue

docs/manual-qa/hf_esg6_tutorial_test.mdx
=> Created hf_esg6_tutorial_test.mdx #6801

docs/custom-model/mlflow.mdx, docs/custom-model/openai.mdx, docs/custom-model/ray-serve.mdx
**Fixes** #6513 
I have replaced the query with given query in file of docs 
path  : docs/custom-model/ray-serve.mdx
=> I have replaced the query of issue #6513

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py, requirements/requirements.txt
Changes:
- Updated dependency for this [mindsdb_sql update](https://github.com/mindsdb/mindsdb_sql/pull/277)
- Accept Select from Join in fetchdataquery step
=> Accept join in fetchdataquery step

mindsdb/api/http/namespaces/analysis.py
=> Rename duplicates cols on analyze dataset

mindsdb/integrations/handlers/gmail_handler/gmail_handler.py
=> storage for gmail

docs/manual-qa/hf_toxicity_tutorial_test.mdx
[Docs][Manual QA] Test the Hugging Face - Toxicity tutorial
https://github.com/mindsdb/mindsdb/issues/6080
[Docs][Manual QA] Test the Hugging Face - Toxicity tutorial
- [N/A] My code follows the style guidelines(PEP 8) of MindsDB.
- [N/A] I have commented my code, particularly in hard-to-understand areas.
- [Y] I have updated the documentation, or created issues to update them.
- [N/A] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [N/A] I have shared a short loom video or screenshots demonstrating any new functionality.
=> [Docs][Manual QA] Test the Hugging Face - Toxicity tutorial

mindsdb/integrations/handlers/gmail_handler/README.md
Fixed a broken link in the Gmail handler's README and made a few small grammatical fixes.
=> Fixed Broken Link in Gmail README

docs/data-integrations/datastax.mdx
Tip added at the end of the implementation
**Fixes** #6546
=> Update datastax.mdx Issue : #6546

mindsdb/integrations/handlers/llama_index_handler/llama_index_handler.py, mindsdb/integrations/handlers/llama_index_handler/requirements.txt
Partly refactored the handler to appropriately use and leverage LlamaIndex abstractions for a minimal set of functionality. More to come soon.
```sql
CREATE MODEL my_qa_model
FROM files (SELECT * FROM HDI)
PREDICT answer
USING 
engine = 'llama_index', 
index_class = 'GPTVectorStoreIndex',
reader = 'DFReader',
input_column = 'question';
CREATE MODEL my_qa_model2
PREDICT answer
USING 
engine = 'llama_index', 
reader = 'SimpleWebPageReader',
source_url_link = 'https://docs.mindsdb.com',
input_column = 'question',
prompt_template = 'We have provided relevant context below:\n{context_str}\nAnswer concisely:\n{query_str}';
SELECT * 
FROM my_qa_model
WHERE question = 'What is the literacy of the particular country with infant mortality of 93.82?'; …
```
=> [LlamaIndex] Handler improvements

docs/mint.json, docs/sql/tutorials/eeg-forecasting.mdx
fixed eeg tutorial
**Fixes** #4360 
=> fixed eeg tutorial

docs/manual-qa/house_sales_statsforecast_tutorial_test.mdx
Created house_sales_statsforecast_tutorial_test.mdx using tutorial and updated it with executed commands and output using given template.
**Fixes** (#6049) 
- Created house_sales_statsforecast_tutorial_test.mdx in docs/manual-qa 
- Executed and verified all commands from https://docs.mindsdb.com/nixtla/house-sales-statsforecastin in MindsDB editor
- Documented it with executed commands including outputs using given template
=> Create and update house_sales_statsforecast_tutorial_test.mdx (#6049)

mindsdb/integrations/handlers/google_calendar_handler/google_calendar_handler.py
fixed duplicated events in google calendar handler
**Fixes** #-
=> fixed duplicated events in google calendar handler

docs/data-integrations/amazon-aurora.mdx
Added the documentation for the Amazon Aurora handler.
=> Amazon Aurora Handler Documentation

mindsdb/integrations/handlers/mysql_handler/mysql_handler.py, mindsdb/integrations/handlers/postgres_handler/__init__.py, mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
Update MySQL information to tart using it on GUI forms
=> Update PostgreSQL handler documentation

mindsdb/integrations/handlers/mendeley_handler/README.md
I fixed some typos in README of Mendeley Handler.
=> Fix typos in README of Mendeley Handler

docker/build.py
optimized the code for better performance. 
used try, except to handle HTTP request errors rather than exiting the program if the API response status code is not 200. This will make the code more robust and prevent it from crashing if the API request fails for any reason.
=> optimized code for build.py

docker/build.py
This PR solves the flake8 warning in docker build.py
=> Solve pep warning

mindsdb/integrations/handlers/openai_handler/openai_handler.py, tests/unit/ml_handlers/test_openai.py
=> [fix] openai bulk normal completion

docs/sql/project.mdx
- [] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [] I have shared a short loom video or screenshots demonstrating any new functionality.
=> Note-Changes Done

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py, mindsdb/interfaces/model/model_controller.py, mindsdb/utilities/functions.py, tests/unit/dummy_ml_handler/dummy_ml_handler.py, tests/unit/test_project_structure.py
Fix wrong output of 
`describe mindsdb.home_rentals_model.info`
Fixes #6592
=> Fix describe mindsdb.model

docs/data-integrations/influxdb.mdx
Added the tip at the end of Implementation chapter in influxdb.mdx
#6671 
Added the tool at the end of chapter
- [x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have updated the documentation, or created issues to update them.
=> Updated the Instructions for influxdb

docs/data-integrations/ibm-db2.mdx
**Fixes** #6669
Updated a doc file
=> Issue-6669: docs update

docs/mint.json
Add "data-integrations/amazon-aurora" to the "Database" group in mint.json.
**Fixes** #6677
=> Add Amazon Aurora docs to navigation

docs/data-integrations/google-sheets.mdx
Please include a summary of the change and the issue it solves.
Added the tip at the end of the Implementation chapter in docs/data-integrations/google-sheets.mdx
#6668 
=> [Docs]:Update instructions for Google Sheets

docs/tutorials/mindsdb-huggingface-tutorial.mdx, docs/tutorials/multilingual_spam_tutorial.mdx, docs/tutorials/sentiment-analysis-intercom-data-airbyte.mdx, docs/tutorials/zero-shot-classification-postgresql.mdx
updated learning hub community tutorials
**Fixes** #-
=> learning hub tutorials

docs/data-integrations/monetdb.mdx, docs/data-integrations/mongodb.mdx
This issue updates the installation guides of MongoDB. The issue being solved is the dependency error that occurs when MongoDB is installed via pip. To solve the problem, you have to navigate to the handlers folder and manually install all the dependencies by running the pip install -r requirements.txt command.
**Fixes** #6694
in case the dependencies are broken due to errors in MongoDB installation,  you have to navigate to the handlers folder and manually install all the dependencies by running the pip install -r requirements.txt command.
#I have read the CLA Document and I hereby sign the CLA
=> updating mongodb DOCS

docs/data-integrations/orioledb.mdx
This PR solves the #6699 issue, adds a tip in oriole.mdx
It simply updates oriole.mdx
=> Update orioledb.mdx #6699

docs/data-integrations/planetscale.mdx
Updated instructions for PlanetScale
**Fixes** #6702
- [ X] 📄 This change requires a documentation update
Updating docs
- [ X] My code follows the style guidelines(PEP 8) of MindsDB.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have updated the documentation, or created issues to update them.
- [ X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ X] I have shared a short loom video or screenshots demonstrating any new functionality.
=> updated instructions for PlanetScale

docs/data-integrations/postgresql.mdx
Update instructions to PostgreSQL. 
**Fixes** #6703
- [✔️] 📄 This change requires a documentation update
Required content added as per instructions. 
- [✔️] I have updated the documentation, or created issues to update them.
=> Update instructions for PostgreSQL

docs/data-integrations/microsoft-access.mdx
=> updated microsoft-access.mdx

mindsdb/integrations/handlers/langchain_handler/requirements.txt
**Fixes** #6726 
updated requirements.txt for langchain handler to include OpenAIHandler dependencies.
=> updated langchain requirements

docs/tutorials/sentiment-analysis-intercom-data-airbyte.mdx
updated learning hub airbyte content
**Fixes** #-
=> updated learning hub airbyte content

assets/contributions-agreement/signatures/cla.json, docs/data-integrations/questdb.mdx
[Docs] Update instructions for QuestDB #6705. Updating documentation
**Fixes** #(issue) 
#6705 
- [X ] ⚡ New feature (non-breaking change which adds functionality)
- [ X] 📄 This change requires a documentation update
Updating documentation
- [X ] My code follows the style guidelines(PEP 8) of MindsDB.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have updated the documentation, or created issues to update them.
- [X ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ X] I have shared a short loom video or screenshots demonstrating any new functionality.
I have read the CLA Document and I hereby sign the …
=>  [Docs] Update instructions for QuestDB #6705 

docs/data-integrations/microsoft-sql-server.mdx
Added the Installation Tip in the implementation chapter doc.
**Fixes** #6692 
Simply adding the tip at the end of the implementation chapter.
=> Added the tip in the implementation chapter

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py, mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py, mindsdb/interfaces/storage/fs.py
- make archive in memory (if there is enough ram)
- do not compress models 
=> Optimization of S3 storage

docs/data-integrations/opengauss.mdx
=> Update instructions for OpenGauss

mindsdb/integrations/handlers/frappe_handler/frappe_handler.py
Changes:
- Added check_item_code tool (instead of item name)
- Adapted register_sales_invoice
=> Changes in olla chatbot

mindsdb/interfaces/storage/fs.py
=> Fix download files from s3

mindsdb/integrations/handlers/mssql_handler/mssql_handler.py
=> fix `show tables` for mssql

mindsdb/integrations/utilities/sql_utils.py
=> Fix column renaming

mindsdb/interfaces/database/projects.py
=> fix: `select * from models` taked too much ram

mindsdb/api/http/initialize.py, mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py, mindsdb/integrations/libs/ml_exec_base.py, mindsdb/interfaces/database/projects.py, mindsdb/interfaces/model/model_controller.py
=> Fix: add `get_model_by_id` instead of use `get_models(model_id=x)`

mindsdb/interfaces/database/integrations.py
Pass integration_id to data handler even if it is create_tmp_handler
fixes #6796
=> Pass integration_id to data handler

docs/manual-qa/hf_sum_bart_tutorial_test.mdx
Tested the Hugging Face - Summarization Bart. I have added SQL commands and output Images in the hf_sum_bart_tutorial_test.mdx file.
**Fixes** #6090 
Added results after testing in docs/manual-qa/hf_sum_bart_tutorial_test.mdx file.
=> Test the Hugging Face - Summarization Bart

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py, mindsdb/interfaces/database/database.py
Fixes #6652
**1. Handlers**
To returns all possible handlers (ml and data) need to run any of:
```sql
show handlers;
-- does the same as 'show handlers'
select * from information_schema.handlers;
```
If we need to filter by type of engine
```sql
show handlers where type = 'data';
-- or
select * from information_schema.handlers where type = 'data';
```
Example output (added 'type' collumn):
**2. To return created databases need to run:**
```sql
select * from information_schema.databases
```
Example output (added 'connection_data' column):
**3. Default args (existed feature)**
If connection args was modified inside of handler:
updated data will be visible in connection_data of 'select * from information_schema.databases'
=>  SHOW Handlers improvements

docs/mint.json, docs/sql/api/delete.mdx, docs/sql/api/update.mdx
docs for update and delete statements
**Fixes** #6593 
=> docs for update and delete statements

docs/custom-model/langchain.mdx, docs/custom-model/openai.mdx
updates to openai and langchain doc pages
**Fixes** #-
=> updates to openai and langchain doc pages

docs/data-sources-overview.mdx, docs/mindsdb-mongo-ql-overview.mdx, docs/mindsdb-sql-overview.mdx, docs/mint.json, docs/ml-engines-overview.mdx
created overview doc pages for Data Sources, ML Engines, MindsDB SQL, MindsDB Mongo-QL
https://www.loom.com/share/da77e15136644a0586e92217550bc1cb
**Fixes** #-
=> overview doc pages

docs/sql/tutorials/bodyfat.mdx
Quick fix of a type in the bodyfat tutorial
=> Fix typo in bodyfat tutorial

docs/data-integrations/edgelessdb.mdx, docs/mint.json, mindsdb/integrations/handlers/edgelessdb_handler/Manual_QA.md
Qa testing and documentation for EdgelessDB.
**Fixes** #(#6766)
Done manual qa testing for EdgelessDB and also updated the documentation of it.
=> Documentation and Qa Testing for EdgelessDB

docs/setup/self-hosted/docker.mdx, docs/setup/self-hosted/pip/linux.mdx, docs/setup/self-hosted/pip/macos.mdx, docs/setup/self-hosted/pip/source.mdx, docs/setup/self-hosted/pip/windows.mdx
updated self-hosted docs with space required for docker and pip
**Fixes** #-
=> updated self-hosted docs

docs/data-sources-overview.mdx, docs/ml-engines-overview.mdx, docs/sql/table-structure.mdx
updated show handler commands info in docs
**Fixes** #6848 
=> updated show handler commands info

docs/custom-model/openai.mdx, docs/nlp/nlp-mindsdb-openai.mdx, docs/sql/api/finetune.mdx
added openai finetuning examples
(as the fine-tuning process is running for two hours as of now, this pr will be completed once done)
**Fixes** #4734 
=> openai finetuning examples

docs/data-integrations/surrealdb.mdx, docs/mint.json, mindsdb/integrations/handlers/surrealdb_handler/Manual_QA.md
Successfully tested and documented `SurrealDB` in local and public cloud editor.
**Closes** #6777 
Documented and tested the existing `SurrealDB` Integration.
=> [Testing]: SurrealDB

docs/app-integrations/twitter.mdx
added info to twitter docs
**Fixes** #6902 
=> added info to twitter docs

docker/release
This PR adds required dependencies for SurrealDB and GitHub to Docker.
=> Update Docker file

docs/app-integrations/confluence.mdx, docs/app-integrations/github.mdx, docs/app-integrations/gmail.mdx, docs/app-integrations/google-calendar.mdx, docs/app-integrations/plaid.mdx, docs/app-integrations/reddit.mdx, docs/app-integrations/twitter.mdx
updated info for all apps, including:
- 4 apps (tested and listed in docs)
- 3 apps (not tested, not listed in docs, but having ready doc pages)
**Fixes** #-
=> updated info for all apps

docs/what-is-mindsdb.mdx
updated what-is-mindsdb
**Fixes** #-
=> updated what-is-mindsdb

mindsdb/integrations/handlers/mongodb_handler/__init__.py, mindsdb/integrations/handlers/mongodb_handler/mongodb_handler.py
Update MongoDb handler documentation
=> Update MongoDb handler documentation

mindsdb/api/mysql/mysql_proxy/utilities/sql.py
Fixes #6168 for models_versions table
=> Fix typemismatch for models_versions table

docs/app-integrations/youtube.mdx, docs/mint.json, mindsdb/integrations/handlers/youtube_handler/Manual_QA.md
Tested the YouTube Integration in different env(s) like local, public cloud, docker. It is working nicely in every environment. Added docs tutorial for `YouTube` Integration.
Tutorial for `YouTube` integration.
=> Tested & Added docs for YouTube Integration

docs/manual-qa/hf_us_political_party_tutorial_test.mdx
Manual QA - Tested the Hugging Face - US Political Party tutorial and everything seem to work as required
#6602 
Manual Testing
=> Add Manual QA Test for US Political Party tutorial #6602

docs/mint.json, docs/openapi.yml, docs/rest/views/update-view.mdx
added rest api update view page
**Fixes** #5139
=> added rest api update view page

mindsdb/api/mongo/responders/insert.py
=> Fix create ml engine without params

README.md
I addressed an issue in the README where there was a duplicate list number within a sequence.
=> Fix duplicate list number in README

docs/sdk/javascript-sdk.mdx
added openai example to js sdk docs
**Fixes** #-
=> added openai example to js sdk docs

mindsdb/integrations/handlers/supabase_handler/Manual_QA.md
Create manual qa for supabase handler.
Create Manual Qa for Supabase database.
=> Create Manual_QA.md for supabase handler.

docs/data-integrations/surrealdb.mdx
Removed the `Testing SurrealDB` chapter and 28-50 lines
=> Fixed: SurrealDB docs

mindsdb/integrations/handlers/shopify_handler/Manual_QA.md
Update the Manual QA testing file for Shopify handler.
**Fixes** ##6957
Add Qa testing for insert method.
=> Update Manual_QA.md for Shopify handler

docs/app-integrations/shopify.mdx, docs/mint.json
added shopify docs to nav
**Fixes** #-
=> added shopify docs to nav

docs/data-integrations/google-bigquery.mdx
updated when to use service_account_keys or service_account_json
**Fixes** #6984 
=> updated when to use service_account_keys or service_account_json

docker/release
Fix installation of `statsforecast` on docker
fix https://github.com/mindsdb/mindsdb/issues/6838
=> Fix `statsforecast` on docker

mindsdb/integrations/handlers/bigquery_handler/Manual_QA.md
Test Google BigQuery Handler Manually.
#6920 
Tested Google BigQuery Handler Manually
=> Update Manual_QA.md after testing Google BigQuery Handler manually

mindsdb/integrations/handlers/ignite_handler/Manual_QA.md
Performed manual QA for the Apache Ignite handler.
=> Manual QA for Apache Ignite

mindsdb/interfaces/model/model_controller.py
fix typo `Can't remove active version: **f**{model}`
Close #6994
=> fix typo `Can't remove active version: f{model}`

mindsdb/interfaces/model/model_controller.py
If describe is not implemented just return model record
#6905
=> Don't fall if describe is not implemented

mindsdb/api/http/namespaces/chatbots.py, mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py, mindsdb/api/mysql/mysql_proxy/datahub/datanodes/project_datanode.py, mindsdb/interfaces/chatbot/chatbot_controller.py, mindsdb/interfaces/database/projects.py, tests/integration_tests/flows/test_company_independent.py
Added table chatbots to project to get info about created chatbots:
```sql
select * from chatbots
```
=> Chatbots table

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
In case if ml engine can not be create, then output more detailed error message:
instead of
```
Can't import engine 'openai'. to use it please install it 'pip install mindsdb[openai]'
```
will be 
```
Handler 'openai' cannot be used. Reason is:
No module named 'openai'
If error is related to missing dependencies, then try to run command in shell and restart mindsdb:
pip install mindsdb[openai]
```
=> Improve error message when create ml engine

docs/contribute/install.mdx
=> Update install.mdx to new path for requirements.txt

mindsdb/integrations/handlers/monkeylearn_handler/monkeylearn_handler.py
Seems there was an error appending the pred_dict in df_list, which is fixed now #7033
=> Fix same value error in batch for monkeylearn handler

mindsdb/integrations/handlers/youtube_handler/youtube_handler.py
improve youtube documentation
**Fixes** 
https://github.com/mindsdb/mindsdb-frontend/issues/1604
improve youtube documentation
=> improve youtube documentation

mindsdb/__about__.py, mindsdb/api/mysql/mysql_proxy/classes/sql_query.py, mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py, mindsdb/integrations/utilities/time_series_utils.py, mindsdb/interfaces/jobs/jobs_controller.py, mindsdb/interfaces/jobs/scheduler.py, mindsdb/interfaces/tasks/task_monitor.py
=> Fixes for update

docs/what-is-mindsdb.mdx
updated a query
**Fixes** #7025
=> updated a query

mindsdb/interfaces/chatbot/memory.py
Fix getting history from rocketchat integration
=> Fix chat history limit

docs/sql/tutorials/twitterbot-mariadb-enterprise-server-skysql.mdx
=> referenced git in twitter tutorial

docs/sql/tutorials/twitterbot-mariadb-enterprise-server-skysql.mdx
=> fixed reference to a gif

docs/sql/tutorials/twitterbot-mariadb-enterprise-server-skysql.mdx
added author link to twitter tutorial
=> added author link to twitter tutorial

docs/sql/tutorials/slack-chatbot.mdx
=> fixed image in slack tutorial

docs/data_sources.mdx, docs/ml_engines.mdx, docs/sql/project.mdx
fixed links in Concepts pages
**Fixes** #-
=> fixed links

mindsdb/integrations/handlers/web_handler/requirements.txt, mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py, mindsdb/integrations/handlers/web_handler/web_handler.py
=> Web crawler updates

docker/release, mindsdb/integrations/handlers/clickhouse_handler/requirements.txt, requirements/requirements.txt
Allow to use clickhouse handler with sqlalchemy2
=> Fix for clickhouse+sqlalchemy2

docs/integrations/app-integrations/binance.mdx, docs/integrations/data-sources-overview.mdx, docs/mint.json
Updated Docs for Binance Integration
Tested Binance Integration and updated the docs for Binance
=> [Docs]: Binance

mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py
Fixing error of getting content if link is without href
=> Fix web handler

mindsdb/api/mysql/mysql_proxy/utilities/sql.py
since pandas sucks at detecting types, this fix will allow us to use almost all duckdb functions on columns
=> convert types to duck db friendly ones

docs/integrations/app-integrations/web-crawler.mdx, docs/mint.json
docs for web crawler
there is a bug when querying without passing `LIMIT`: https://github.com/mindsdb/mindsdb/issues/7118
**Fixes** #7099 
=> docs for web crawler

mindsdb/integrations/handlers/pypi_handler/.bumpversion.cfg, mindsdb/integrations/handlers/pypi_handler/README.md, mindsdb/integrations/handlers/pypi_handler/__about__.py, mindsdb/integrations/handlers/pypi_handler/api.py, mindsdb/integrations/handlers/pypi_handler/pypi_handler.py, mindsdb/integrations/handlers/pypi_handler/pypi_tables.py, mindsdb/integrations/handlers/pypi_handler/requirements.txt
I just made the PyPI Handler optimized. It's now AI-friendly with the vast range of data that it's presenting compared to how it was before.
I dropped the support for the `pypistats` package and used a custom API interface which is more stable and customized in a way that we need to drive and train the AI models based on. From now on, all the queries are more descriptive and informative.
<details>
<summary>Overall query</summary>
</details>
<details>
<summary>Recent query</summary>
</details>
<details>
<summary>Python major query</summary>
</details>
=> PyPI Handler Optimization

docs/integrations/app-integrations/binance.mdx, docs/integrations/app-integrations/confluence.mdx, docs/integrations/app-integrations/email.mdx, docs/integrations/app-integrations/plaid.mdx, docs/integrations/app-integrations/reddit.mdx, docs/integrations/app-integrations/shopify.mdx, docs/integrations/data-sources-overview.mdx, docs/mint.json
- added email docs
- added updates in other app pages
**Fixes** #-
=> added email docs

docs/faqs/mindsdb-with-php.mdx, docs/mint.json
added an faq page
**Fixes** #-
=> added an faq page

mindsdb/integrations/handlers/timegpt_handler/timegpt_handler.py
:﻿## Description
While doing the monthly expenditure tutorial (see #7145), I had the following error:
This PR fixes the problem.
=> fix: convert date column to datetime (monthly expenditure fix))

mindsdb/integrations/libs/ml_exec_base.py
Return always new model record when call train/finetune
=> Return always new model record  when call train/finetune

mindsdb/interfaces/database/integrations.py
Fix for rare issue raised if integration data is empty
=> fix issue with empty integration data

mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py
Fix labels and description on clickhouse
Can't submit datasource creation(Alpha release) #1633
complete the documentation on handler
=> Fix clickhouse documentation

mindsdb/integrations/handlers/ignite_handler/ignite_handler.py
Add Apache Ignite form #1618
- [x ] 🐛 Bug fix (non-breaking change which fixes an issue)
=> Update Ignite documentation

mindsdb/integrations/handlers/github_handler/__init__.py, mindsdb/integrations/handlers/github_handler/github_handler.py
Add GitHub Documentation. 
**Fixes** [#(issue)](https://github.com/mindsdb/mindsdb-frontend/issues/1614)
Add Github Documentation
=> Improve Github Documentation

docker/release
Predownload  nltk data in docker: `punkt` and `stopwords`
Close #6664
=> Predownload  nltk data in docker

mindsdb/interfaces/database/projects.py
=> fix: self param typo

docs/sql/tutorials/house-sales-timegpt.mdx
This PR includes an example of how to use TimeGPT to forecast house sales.
Here's an output of the forecasts in mindsdb cloud (locally).
Documentation.
=> feat: add tutorial house sales timegpt

docs/sql/tutorials/monthly-expediture-timegpt.mdx
This PR includes an example of how to use TimeGPT to forecast monthly expenditures.
Here's an output of the forecasts in mindsdb cloud (locally).
=> feat: add monthly expenditure timegpt tutorial

mindsdb/integrations/handlers/huggingface_handler/requirements.txt, mindsdb/integrations/handlers/lightwood_handler/requirements.txt, mindsdb/integrations/handlers/ludwig_handler/requirements.txt, mindsdb/integrations/handlers/merlion_handler/requirements.txt, mindsdb/integrations/handlers/mlflow_handler/requirements.txt, mindsdb/integrations/handlers/monkeylearn_handler/requirements.txt, mindsdb/integrations/handlers/openai_handler/requirements.txt, mindsdb/integrations/handlers/ray_serve_handler/requirements.txt
In some handlers requirements there was `mindsdb` and `mindsdb-sql`. Deleted to avoid conflicts.
**Fixes**
Part of fix for  https://github.com/mindsdb/mindsdb/issues/7017
=> Del `mindsdb` from handlers requirements

mindsdb/integrations/handlers/timegpt_handler/timegpt_handler.py
Fix frequency parameter passing #7149.
=> TimeGPT: fixes for frequency and levels

docker/release
This PR includes the missing dependency for the MonkeyLearn in the Docker image.
**Fixes** #7175 
=> Add dependencies for MonkeyLearn in Docker

mindsdb/integrations/handlers/lightfm_handler/lightfm_handler.py
Adds describe function for lightfm handler
=> add describe for lightfm_handler.py

docs/integrations/app-integrations/slack.mdx, docs/sql/tutorials/slack-chatbot.mdx
updated slack docs with permissions
**Fixes** [#(issue)](https://github.com/mindsdb/mindsdb_private/issues/171)
=> updated slack docs with permissions

docs/contribute/install.mdx
updated git clone
**Fixes** #7142 
=> updated git clone

mindsdb/integrations/handlers/cassandra_handler/cassandra_handler.py, mindsdb/integrations/handlers/scylla_handler/scylla_handler.py
Update documentation on Scylla and Cassandra
-
update the documentation
=> Update documentation on Scylla dna Cassandra

mindsdb/integrations/handlers/huggingface_handler/requirements.txt
Current huggingface deps are incompatible with base requirements file
=> Fix hugginface pandas required version

docs/nlp/json-from-text.mdx
added json_extract() to docs
**Fixes** #-
=> added json_extract() to docs

mindsdb/integrations/handlers/surrealdb_handler/surrealdb_handler.py
Complete SurrealDB Documentation
Complete field description to surrealdb
=> complete surrealDB documentation

docs/integrations/data-integrations/scylladb.mdx, mindsdb/integrations/handlers/scylla_handler/README.md
In this PR there are a few minor changes to the ScyllaDB handler README and the docs.
=> Update Scylla README and docs

docs/quickstart.mdx
added quickstart video
**Fixes** #-
=> added quickstart video

docs/sdk_javascript/connect.mdx
updates to docs js sdk connect
=> updates to docs js sdk connect

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py
**Fixes** #6833, see attached picture for new output.
=> [fix] lightwood: alert missing data when training

mindsdb/interfaces/model/model_controller.py
The methods obsolete and cannot be used anymore. 
=> Delete unused export/import model methods

mindsdb/interfaces/jobs/README.md
Added technical docs  for jobs
=> Jobs: technical docs 

mindsdb/interfaces/database/integrations.py
DB handlers cache was not working because of error in previous commits
=> Fix db handlers cache

docker/release
This PR add Plaid and Confluence dependencies to the image
**Fixes** #7169 , #7170 
Added missing dependencies to both handlers
=> Docker dependencies

mindsdb/interfaces/database/integrations.py, mindsdb/interfaces/storage/model_fs.py
A little refactoring of handlers creation
**Fixes**
=> Refactoring of handlers creation

docs/quickstart.mdx
added jobs to quickstart docs (analogically to the learning hub examples)
=> added jobs to quickstart docs

docs/mint.json, docs/sql/tutorials/create-chatbot.mdx
=> created chatbot syntax docs

docs/sql/project.mdx
updated project doc page
https://github.com/mindsdb/mindsdb/discussions/7238
=> updated project doc page

mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
fixed langchain hardcoded parameter
before fix:
after fix:
**Fixes** #7229 
=> fixed langchain hardcoded parameter

mindsdb/integrations/libs/vectordatabase_handler.py, tests/handler_tests/test_vectordatabase_dispatch.py
Add the base class for vector database implementations. 
Serves as a dependency of #6941 and #7069
**How I test**
```
python -m pytest tests/handler_tests/test_vectordatabase_dispatch.py
```
TODO:
=> Add vector database common apporach

mindsdb/integrations/handlers/chromadb_handler/Manual_QA.md, mindsdb/integrations/handlers/chromadb_handler/README.md, mindsdb/integrations/handlers/lightfm_handler/README.md, mindsdb/integrations/handlers/popularity_recommender_handler/README.md, mindsdb/integrations/handlers/writer_handler/README.md
add read me files for chromadb, writer, popularity and lightfm
=> add read me for chromadb, popularity, lightfm and writer handlers

mindsdb/integrations/handlers/couchbase_handler/Manual_QA.md
Create manual qa testing for Couchbase.
=> Manual Qa for Couchbase

docs/integrations/app-integrations/slack.mdx
=> added slack connection options in docs

mindsdb/interfaces/jobs/jobs_controller.py
Switch off "Minimal allowed period can't be less than one day" restriction for not-paid users
=> Disable restriction for jobs period for not paid users

mindsdb/api/postgres/postgres_proxy/postgres_proxy.py
This will allow postgres API to work in cloud mode by performing handshake
**Fixes** gw # 627
=> Postgres api fix for cloud connections

mindsdb/__about__.py
**Features**
- LLM:
- #7268
- #7195
- #7272
- #7269
- #6941
- Gmail handler on cloud: 
- #7210
- #7273
- #6675
**Documentation**
- #7271
- #5981
- #7275
- #7259
- #6975
- #7287
- #4891
- #7263
**Fixes**
- #7286
- #7265
- #7254
- #7258
- #7264
- #7256
=> Release 23.9.1.1

docs/mint.json, docs/sql/api/update.mdx, docs/sql/create/trigger.mdx, docs/sql/drop/trigger.mdx, docs/sql/query-triggers.mdx
- updated `update` docs
- added `trigger` docs (atm works only for mongodb)
**Fixes** #6881 
=> update docs and trigger docs

docs/integrations/ai-engines/neuralforecast.mdx, docs/integrations/ai-engines/statsforecast.mdx, docs/integrations/ai-engines/timegpt.mdx, docs/integrations/ml-engines-overview.mdx, docs/mint.json
nixtla models docs:
- statsforecast - updated
- neuralforecast - created
- timegpt - created
atm, these doc pages use quarterly forecaster example.
**Fixes** #https://github.com/mindsdb/mindsdb-docs/issues/220
=> nixtla models docs

docs/integrations/ai-engines/timegpt.mdx
updated timegpt example
**Fixes** #-
=> updated timegpt example

mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
Use user column instead of prompt for conversational mode
=> Chatbot langchain fix

docs/generative-ai-tables.mdx, docs/mint.json, docs/what-is-mindsdb.mdx
mindsdb intro updates - reviewed by @ianu82 
=> mindsdb intro updates

mindsdb/integrations/handlers/gmail_handler/__init__.py, mindsdb/integrations/handlers/gmail_handler/gmail_handler.py, mindsdb/interfaces/database/integrations.py
Changes:
- Added 'credentials' field to upload files
- Read credentials from url in config 
Linked with https://github.com/mindsdb/mindsdb-frontend/pull/1715
=> GMAIL: upload Service Account Keys

docs/integrations/data-integrations/datastax.mdx, mindsdb/integrations/handlers/datastax_handler/README.md, mindsdb/integrations/handlers/scylla_handler/scylla_handler.py
These PRs allow cloud users to connect to Astra using a secure bundle.
**Fixes** #7301 
=> Astra bundle

docs/integrations/data-integrations/amazon-s3.mdx, mindsdb/integrations/handlers/s3_handler/README.md
fixed amazon s3 keys in docs
**Fixes** #-
=> fixed amazon s3 keys in docs

docs/integrations/ai-engines/llamaindex.mdx
added titles to llamaindex docs
=> added titles to llamaindex docs

docs/contribute/contribute.mdx
updated contribute page
**Fixes** #-
=> updated contribute page

docs/integrations/data-integrations/couchbase.mdx, mindsdb/integrations/handlers/couchbase_handler/README.md, mindsdb/integrations/handlers/couchbase_handler/couchbase_handler.py, mindsdb/integrations/handlers/couchbase_handler/requirements.txt
This PR improves the Couchbase handler:
- Simplifies native_query code and solves timeout issues
- Fix installing requirements
- Better docs, improved README, remove prints
**Fixes** #5816 
=> Couchbase improvments

mindsdb/integrations/handlers_wrapper/ml_grpc_wrapper.py, mindsdb/integrations/libs/ml_exec_base.py, mindsdb/interfaces/database/integrations.py, mindsdb/interfaces/storage/fs.py, mindsdb/interfaces/storage/model_fs.py
Changes
- Fix: import_files method on created databases doesn't send files to S3
- added is_temporal handler storage
- removed unused code
- [x ] 🐛 Bug fix (non-breaking change which fixes an issue)
=> Fix copy files for gmail

mindsdb/integrations/handlers/hackernews_handler/README.md
Fixed the example CREATE DATABASE statement given in the README for the Hacker News integration.
=> [PR] Quick Fix to Hacker News README

README.md, docs/setup/self-hosted/pip/linux.mdx, docs/setup/self-hosted/pip/macos.mdx, docs/setup/self-hosted/pip/source.mdx, docs/setup/self-hosted/pip/windows.mdx
updated supported python versions in docs
**Fixes** #-
=> updated supported python versions in docs

docs/integrations/app-integrations/hackernews.mdx, docs/integrations/data-sources-overview.mdx, docs/integrations/ml-engines-overview.mdx, docs/mint.json, mindsdb/integrations/handlers/hackernews_handler/README.md
tested and documented hacker news integration
**Fixes** #7367
=> hacker news docs

docs/integrations/ai-engines/lightfm.mdx, docs/integrations/ai-engines/popularity-recommender.mdx, docs/mint.json, docs/sql/tutorials/recommenders.mdx
added recommender models to docs
**Fixes** #-
=> added recommender models to docs

docs/integrations/ai-engines/llamaindex.mdx
updated llamaindex docs
**Fixes** #7378 
=> updated llamaindex docs

docs/integrations/ai-engines/timegpt.mdx
updated timegpt docs - added disclaimer about inconsistent data row intervals
**Fixes** #-
=> updated timegpt docs

docs/sdk_python/create_ml_engine.mdx, docs/sdk_python/create_model.mdx, docs/sdk_python/create_table.mdx, docs/sdk_python/delete_file.mdx, docs/sdk_python/delete_from.mdx, docs/sdk_python/delete_table.mdx, docs/sdk_python/drop_ml_engine.mdx, docs/sdk_python/drop_model.mdx, docs/sdk_python/get-batch-predictions.mdx, docs/sdk_python/get-single-prediction.mdx, docs/sdk_python/insert_into_table.mdx, docs/sdk_python/list_data_handlers.mdx, docs/sdk_python/list_ml_engines.mdx, docs/sdk_python/list_ml_handlers.mdx, docs/sdk_python/query_files.mdx, docs/sdk_python/update_table.mdx, docs/sdk_python/upload_file.mdx
python sdk docs updates
**Fixes** #-
=> python sdk docs updates

mindsdb/__about__.py
version increase from release PR
=> version increase

docs/integrations/app-integrations/mediawiki.mdx, docs/integrations/data-sources-overview.mdx, docs/mint.json
Added the documentation for the MediaWiki handler.
=> Documentation for the MediaWiki Handler

docs/integrations/app-integrations/stripe.mdx, docs/integrations/data-sources-overview.mdx, docs/mint.json
Added the documentation for the Stripe handler.
=> Documentation for the Stripe Handler

docs/integrations/app-integrations/binance.mdx, docs/integrations/app-integrations/confluence.mdx, docs/integrations/app-integrations/email.mdx, docs/integrations/app-integrations/github.mdx, docs/integrations/app-integrations/gmail.mdx, docs/integrations/app-integrations/google-calendar.mdx, docs/integrations/app-integrations/hackernews.mdx, docs/integrations/app-integrations/mediawiki.mdx, docs/integrations/app-integrations/plaid.mdx, docs/integrations/app-integrations/reddit.mdx, docs/integrations/app-integrations/shopify.mdx, docs/integrations/app-integrations/slack.mdx, docs/integrations/app-integrations/stripe.mdx, docs/integrations/app-integrations/twitter.mdx, docs/integrations/app-integrations/web-crawler.mdx, docs/integrations/app-integrations/youtube.mdx
updated intro to all app integrations doc pages to include:
- description of the app
- how it can be used within MindsDB
**Fixes** #-
=> updated app integrations doc pages

docker/docker-compose-ci.yml
Re-adds the docker-compose-ci file as it was removed but still in use.
=> Revert removal of ci docker-compose

docs/ai_workflow.mdx, docs/mint.json
added ai workflow docs that explain the ai workflow concept and steps from the ai workflow doc section
**Fixes** #-
=> ai workflow docs

mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
Fixes: #6483
How it is going to work: https://www.loom.com/share/b4939bff9f0c41f9934602b1cfe0183b
=> PG handler: show objects only from current schema

.github/workflows/acceptance_tests.yml, .github/workflows/mindsdb.yml, tests/integration_tests/flows/test_predict_text_sentiment_openai_tutorial.py, tests/unit/ml_handlers/test_huggingface.py, tests/unit/ml_handlers/test_openai.py, tests/unit/ml_handlers/test_statsforecast.py
Related to #7203.
Restore OpenAI tests.
=> [CI] re-enable OpenAI tests

mindsdb/integrations/handlers/writer_handler/evaluate.py, mindsdb/integrations/handlers/writer_handler/requirements.txt, requirements_dev.txt
solves `writer_handler` requirements conflict on cloud that prevents it being used
error with rel imports
**Fixes** #7364 
=> fix #7364 bug on demo cloud i am unable to creare ml engine with writer handler

docker/release
Update docker dependencies for llama index handler.
Fixes #7406
=> Fix: Update docker deps for llama

mindsdb/integrations/handlers/druid_handler/druid_handler.py
Fix druid documentation. 
Fixes [#issue_number](https://github.com/mindsdb/mindsdb/issues/7451)
=> Improve druid Documentation

mindsdb/integrations/handlers/Handlers_Manual_QA.md
added handlers manual qa file to store test results
Fixes #-
=> added handlers manual qa file to store test results

README.md
This pull request addresses issue #7462 by fixing non-working links in the README file. It ensures that all links in the documentation are functional and lead to the correct destinations.
Fixes #7462
=> Fixed non-working links in README file

mindsdb/integrations/handlers/databend_handler/README.md, mindsdb/integrations/handlers/databend_handler/databend_handler.py, mindsdb/integrations/handlers/databend_handler/requirements.txt, mindsdb/integrations/handlers/databend_handler/tests/test_databend_handler.py
This PR includes an update to the Databend handler by rewriting it using the newly introduced databend-sqlalchemy package. This package was not available at the time this integration was initially written.
https://github.com/mindsdb/mindsdb/issues/7447
The updated integration seems to be working fine after some initial testing. Given below is a screenshot from running a SELECT statement against a newly created data source,
=> Databend Integration Update

docs/callbacks.mdx, docs/mint.json
added callbacks docs
Fixes #[issue_number](https://github.com/mindsdb/mindsdb_private/issues/251)
=> added callbacks docs

docs/contribute/app-handlers.mdx, docs/contribute/data-handlers.mdx
This PR updates the `connection_args` and `connection_args_example` sections of the documentation for making handler contributions.
https://github.com/mindsdb/mindsdb/issues/7501
=> Updates to the connection_args and connection_args_example of the Contribution Documentation

docs/Docs_Manual_QA.md
added a file to store docs manual qa results
Fixes #-
=> added a file to store docs manual qa results

mindsdb/integrations/handlers/writer_handler/README.md, mindsdb/integrations/handlers/writer_handler/evaluate.py, mindsdb/integrations/handlers/writer_handler/writer_handler.py
Updating docs are they are outdated
a couple of fixes
=> updated writer docs, fix new error introduced by subsequent changes in file store

mindsdb/__main__.py
There was wrong error message if python version is incompatible.
=> Update message if wrong python version

docs/integrations/data-sources-overview.mdx, docs/sdk_javascript/list_databases.mdx, docs/sql/list-projects.mdx, docs/sql/table-structure.mdx
updated `show [full]` commands in docs
Fixes #-
=> updated show [full] commands in docs

docs/Docs_Manual_QA.md
Tested all command listed in 7514
Fixes #7514 
Tested commands in the following links:
https://docs.mindsdb.com/sql/list-data-handlers
https://docs.mindsdb.com/sql/create/database
https://docs.mindsdb.com/sql/drop/database
https://docs.mindsdb.com/sql/show-databases
https://docs.mindsdb.com/sql/api/use
=> updated manual QA doc with test results

tests/unit/test_check_handler_imports.py
-check handler imports are valid
-ensure handler external requirments are covered by either handler `requirements.txt` or main mindsdb `requirements.txt`
=> test to check that handler imports are valid and external requirements

docs/integrations/app-integrations/newsapi.mdx, docs/mint.json
Added docs for newsapi integration.
Fixes #7522 
=> added newsappi docs

docs/integrations/app-integrations/sendinblue.mdx, docs/mint.json
Added docs for sendinblue integration
Fixes #7523 
=> added sendinblue docs

mindsdb/integrations/handlers/github_handler/github_handler.py, mindsdb/integrations/handlers/github_handler/github_tables.py
Implement the Commits table for a GitHub repository
Fixes #7541 
=> add Github Commits Table github_tables.py

mindsdb/integrations/handlers/shopify_handler/shopify_tables.py, mindsdb/integrations/handlers/utilities/query_utilities/__init__.py, mindsdb/integrations/handlers/utilities/query_utilities/base_query_utilities.py, mindsdb/integrations/handlers/utilities/query_utilities/delete_query_utilities.py, mindsdb/integrations/handlers/utilities/query_utilities/insert_query_utilities.py, mindsdb/integrations/handlers/utilities/query_utilities/select_query_utilities.py, mindsdb/integrations/handlers/utilities/query_utilities/update_query_utilities.py
This PR adds the following to make the process of developing App handlers easier:
- UPDATE Query Parser and Executor
- DELETE Query Parser and Executor
To be more precise, it makes parsing and executing SQL queries for App handlers easier.
=> UPDATE and DELETE Query Utilities

docs/callbacks.mdx
Add description of each key in callback payload
=> Update callbacks doc

docs/Docs_Manual_QA.md
=> Added AI_WORKFLOW_SECTION Test to Docs_Manual_QA.md

docs/Docs_Manual_QA.md
=> AI workflow test

mindsdb/integrations/handlers/databricks_handler/databricks_handler.py
Error on Databricks labels and helper #7603
Fixes #7603
1. Go to add data
2. Select databricks handler. 
3. Check labels, helpers and required validator
=> Add Databricks fields

docker/release
This PR adds the dependencies for the Web Handler in the Docker image.
Fixes #7452 
=> Add  Web Handler dependencies 

mindsdb/integrations/handlers/github_handler/README.md, mindsdb/integrations/handlers/github_handler/github_handler.py, mindsdb/integrations/handlers/github_handler/github_tables.py
implemented github contributors table
Fixes #7606 
=> implemented github contributors table

docker/release
This PR adds the dependencies for the Sendinblue, News API and Databend handlers.
=> Added Dependencies for Sendinblue, News API and Databend to Docker

mindsdb/integrations/handlers/plaid_handler/plaid_handler.py
Fixed the typo change for mindsdb integrations in plaid_handler.py
Fixes #7611 
- [✓ ] 📄 This change requires a documentation update
- [ ✓] Necessary documentation updates are either made or tracked in issues.
=> Fixed Typo for mindsdb integrations in plaid_handler.py

docs/tutorials.mdx
=> Added a new tutorial

docs/Docs_Manual_QA.md, mindsdb/integrations/handlers/Handlers_Manual_QA.md
fixed manual qa files
Fixes #-
=> fixed manual qa files

docs/integrations/app-integrations/email.mdx, mindsdb/integrations/handlers/email_handler/README.md
This PR updates the docs and readme for the Email integration with additional info about connecting to Outlook.
Fixes #7647 
=> Outlook to Email docs

mindsdb/integrations/handlers/tripadvisor_handler/tripadvisor_api.py, mindsdb/integrations/handlers/tripadvisor_handler/tripadvisor_handler.py, mindsdb/integrations/handlers/tripadvisor_handler/tripadvisor_table.py
Fixed code style of tripadvisor handler
=> Fix flake8 tripadvisor

.github/workflows/mindsdb.yml
Changes
- removed init file from tests
Fixes https://github.com/mindsdb/mindsdb_private/issues/272
=> Fix ci: removed init from tests

docs/integrations/app-integrations/email.mdx
modified the email handler docs to not duplicate the usage section. it follows this pr: https://github.com/mindsdb/mindsdb/pull/7648
=> fixed email handler docs

.flake8, mindsdb/integrations/handlers/d0lt_handler/__about__.py, mindsdb/integrations/handlers/d0lt_handler/__init__.py, mindsdb/integrations/handlers/d0lt_handler/d0lt_handler.py, mindsdb/integrations/handlers/d0lt_handler/tests/test_d0lt_handler.py, mindsdb/integrations/handlers/databricks_handler/__about__.py, mindsdb/integrations/handlers/databricks_handler/__init__.py, mindsdb/integrations/handlers/databricks_handler/databricks_handler.py, mindsdb/integrations/handlers/databricks_handler/tests/test_databricks_handler.py
=> cleanup(flake8): clean d0lt_handler & databricks_handler

mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
implemented [INSERT]() functionality to products table in shopify handler. 
Fixes #7658
exception if title not provided
=> Implemented insert for product table in shopify handler

docs/integrations/ai-engines/langchain.mdx
updated langchain docs with the new template for ai engines docs
Fixes #-
=> updated langchain docs

.flake8, mindsdb/integrations/handlers/datastax_handler/__about__.py, mindsdb/integrations/handlers/datastax_handler/__init__.py, mindsdb/integrations/handlers/datastax_handler/datastax_handler.py, mindsdb/integrations/handlers/datastax_handler/tests/test_cassandra_handler.py, mindsdb/integrations/handlers/db2_handler/__about__.py, mindsdb/integrations/handlers/db2_handler/__init__.py, mindsdb/integrations/handlers/db2_handler/db2_handler.py, mindsdb/integrations/handlers/db2_handler/tests/test_db2_handler.py
=> cleanup(flake8): clean datastax_handler & db2_handler

mindsdb/integrations/handlers/shopify_handler/README.md, mindsdb/integrations/handlers/shopify_handler/shopify_handler.py, mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
Shipping Zone table implementation
Fixes #7659 
=> shipping zone table implementation

mindsdb/integrations/handlers/statsforecast_handler/requirements.txt, mindsdb/integrations/handlers/statsforecast_handler/statsforecast_handler.py, mindsdb/integrations/utilities/time_series_utils.py
=> [fix] StatsForecast - correct sampling frequency

docs/sql/tutorials/slack-chatbot.mdx, docs/sql/tutorials/twitter-chatbot.mdx
updates related to openai api key
Fixes #-
=> updates related to openai api key

mindsdb/integrations/handlers/byom_handler/byom_handler.py, mindsdb/integrations/handlers/byom_handler/const.py, mindsdb/integrations/handlers/byom_handler/proc_wrapper.py, mindsdb/integrations/handlers/couchbase_handler/couchbase_handler.py, mindsdb/interfaces/model/model_controller.py, tests/unit/test_project_structure.py
Allows to run `describe` command for BYOM models
=> Describe method for BYOM

MANIFEST.in
add evaluation data to cloud
Fixes [issue](https://github.com/mindsdb/mindsdb_private/issues/266)
=> add evaluation data to MANIFEST.in

mindsdb/integrations/handlers/sentence_transformer_handler/sentence_transformer_handler.py
fix invalid import in `sentence_transformer` handler
=> fix invalid import in sentence_transformer_handler

mindsdb/integrations/handlers/hackernews_handler/README.md, mindsdb/integrations/handlers/hackernews_handler/hn_handler.py, mindsdb/integrations/handlers/hackernews_handler/hn_table.py
Implemented the Hacker News GET /askstories.json endpoint (https://hackernews.api-docs.io/v0/live-data/ask-hn-stories) 
Created separate table (hnstories) for storing the data from GET /askstories.json endpoint. Also added the sample query in the Hacker News handler readme.
Fixes #7705 
1. Create database using following command:
`CREATE DATABASE my_hackernews
WITH 
ENGINE = 'hackernews'`
2. Test the implemented endpoint data:
`SELECT *
FROM my_hackernews.hnstories
LIMIT 5;`
=> implemented hackernews askstories endpoint

mindsdb/integrations/handlers/rag_handler/ingest.py, mindsdb/integrations/handlers/rag_handler/rag_handler.py, mindsdb/integrations/handlers/rag_handler/requirements.txt, tests/unit/ml_handlers/test_rag.py
A bug has been introduced to rag handler by changes to handler storage interface
=> fix regression bug caused by updates to handlerstorage

docs/integrations/data-integrations/couchbase.mdx, mindsdb/integrations/handlers/couchbase_handler/README.md
This PR adds a few pointers that users should be aware of when establishing a connection to Couchbase Capella.
=> Documentation for Couchbase Capella Connections

mindsdb/integrations/handlers/hackernews_handler/README.md, mindsdb/integrations/handlers/hackernews_handler/hn_handler.py, mindsdb/integrations/handlers/hackernews_handler/hn_table.py
Implemented the Hacker News GET /jobstories.json endpoint (https://hackernews.api-docs.io/v0/live-data/job-hn-stories)
Created separate table (jobstories) for storing the data from GET /jobstories.json endpoint. Also added the sample query in the Hacker News handler readme.
Fixes #7706 
[1] Create database using following command:
`CREATE DATABASE my_hackernews WITH  ENGINE = 'hackernews'`
[2] Test the implemented endpoint data:
`SELECT * FROM my_hackernews.jobstories LIMIT 7;`
=> implements hacker news GET/jobstories.json endpoint

mindsdb/integrations/handlers/Handlers_Manual_QA.md
This PR performing integration testing for the Apache Pinot data integration with update Handlers_Manual_QA.
Fixes #7702 
Hi @chandrevdw31 @martyna-mindsdb , could you please review this pull request
=> [Integration Testing] Test the Apache Pinot data integration

.devcontainer/devcontainer.json
Added `devcontainer.json` for working with GitHub codespaces.
Similar to Gitpod, codespaces are native to GitHub for creating workspaces in the cloud. 
=> add devcontainer config for codespaces

mindsdb/integrations/handlers/Handlers_Manual_QA.md
This PR performing integration testing for the Microsoft Teams app integration with update Handlers_Manual_QA.
Fixes #7482 
Hi @chandrevdw31 @martyna-mindsdb , could you please review this pull request
=> [Integration Testing] Test the Microsoft Teams app integration

mindsdb/integrations/handlers/stripe_handler/README.md, mindsdb/integrations/handlers/stripe_handler/stripe_handler.py, mindsdb/integrations/handlers/stripe_handler/stripe_tables.py
I have created Refund Table and Registered the Table with stripe handler. I have also updated Documentation accordingly
Fixes #7764 
- [ X] 🐛 Bug fix (non-breaking change which fixes an issue)
I have created the tables by following the initial Steps, Stripe documentation for python SDK
=> add Refunds Table to Stripe 

mindsdb/integrations/handlers/shopify_handler/README.md, mindsdb/integrations/handlers/shopify_handler/shopify_handler.py, mindsdb/integrations/handlers/shopify_handler/shopify_tables.py
Implemented Sales Channel
Fixes #7756 
=>  Sales Channel Table for Shopify Implementation

mindsdb/integrations/handlers/hackernews_handler/hn_handler.py, mindsdb/integrations/handlers/hackernews_handler/hn_table.py
This commit aims to **optimize** the code by removing **redundant code** in the `Hacker News Handler`
=> Remove duplicate code

mindsdb/integrations/handlers/Handlers_Manual_QA.md
This PR performing integration testing for the Google Big Query data integration with update Handlers_Manual_QA.
Fixes #7644
Hi @chandrevdw31  @martyna-mindsdb , could you please review this pull request
=> [Integration Testing] Test the Google Big Query data integration

mindsdb/integrations/handlers/writer_handler/README.md, mindsdb/integrations/handlers/writer_handler/settings.py, mindsdb/integrations/handlers/writer_handler/writer_handler.py
Adds additional detail to writer_handler readme
=> updating writer handler docs to include all supported parameters

mindsdb/api/http/namespaces/default.py
Minor spelling errors in http namespaces debug messages.
=> Minor spelling error change in http namespaces debug messages

mindsdb/integrations/handlers/elasticsearch_handler/elasticsearch_handler.py
Fixes #7828
- This change addresses a bug where the Elasticsearch connection was not properly closed when an exception occurred. - This bug was causing resource leaks and connection issues.
- Improved error handling during the connection setup by handling `ConnectionError` and `AuthenticationException`.
=> Connect error in elasticsearch

mindsdb/integrations/handlers/slack_handler/README.md, mindsdb/integrations/handlers/slack_handler/slack_handler.py
Added the update_message functionality for updating slack messages based on timestamp. 
Fixes #7872 
https://github.com/mindsdb/mindsdb/assets/42097653/b73902e0-adc9-4544-b073-020e84309ff9
=> Slack adding update_message functionality

mindsdb/integrations/handlers/Handlers_Manual_QA.md
This PR performing integration testing for the Web Crawler Integration with update Handlers_Manual_QA.
Fixes https://github.com/mindsdb/mindsdb/issues/7896
Hi @chandrevdw31 @martyna-mindsdb , could you please review this pull request
=> Added Web Crawler Integration Test Results in  Handlers_Manual_QA.md

docker/release
This PR adds the dependencies for the Weaviate handler to Docker image.
=> Added Dependencies for Weaviate to Docker

mindsdb/integrations/handlers/youtube_handler/README.md, mindsdb/integrations/handlers/youtube_handler/youtube_handler.py, mindsdb/integrations/handlers/youtube_handler/youtube_tables.py
- standardized table names
- updated README
Fixes #-
=> updates to youtube handler

docs/integrations/data-integrations/couchbase.mdx
=> chore(docs/integrations): fix typos in couchbase.mdx

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py, mindsdb/interfaces/database/projects.py
Created different functions to drop model and view. They will show different error messages if mode/view doesn't exist
New error messages expected to be:
Fixes https://github.com/mindsdb/mindsdb_private/issues/262
- go to web editor.
- try to drop model/view
=> Drop model and view functions

mindsdb/integrations/handlers/Handlers_Manual_QA.md
This PR performing integration testing for the Microsoft Access integration with update Handlers_Manual_QA. 
Fixes #7978
Hi @ZoranPandovski @chandrevdw31 , could you please review this pull request
=> [Integration Testing] Test Microsoft Acess Integration

mindsdb/integrations/handlers/autogluon_handler/autogluon_handler.py, mindsdb/integrations/handlers/autogluon_handler/config.py, tests/unit/ml_handlers/test_autogluon.py
=> Fix flake8

.github/workflows/mindsdb.yml, mindsdb/integrations/handlers/langchain_handler/requirements.txt
=> Minor py deps issue resolving install issues on Marketplace/ManagedCloud

docker/README.md
added "." at the end of the build statement 
Fixes #7921
=> added . at the end of the docker build command

docs/data_sources.mdx
=> chore(docs/data_sources): fixed typos

docs/generative-ai-tables.mdx
=> chore(docs/generative-ai-tables): fixed typos

docs/mindsdb-gui.mdx
=> chore(docs/mindsdb-gui.mdx): typo fixes

docs/ml-types.mdx
=> chore(docs/ml-types.mdx): fix typos

docs/connect/connect-mariadb-skysql.mdx
=> chore(docs/connect-mariadb-skysql.mdx): fix typos

docs/connect/metabase.mdx
=> chore(docs/metabase.mdx): fix typos

docs/connect/mongo-compass.mdx
=> chore(docs/mongo-compass.mdx): fix typos

docs/connect/mysql-client.mdx
=> chore(docs/mysql-client.mdx): fix typos

docs/connect/postgres-client.mdx
=> chore(docs/postgres-client.mdx): fix typos

docs/connect/sql-alchemy.mdx
=> fix(docs/sql-alchemy.mdx): fix typo

docs/connect/tableau.mdx
=> chore(docs/tableau.mdx): fix typos

docs/integrations/app-integrations/pypi.mdx, docs/integrations/data-sources-overview.mdx, docs/mint.json
This PR adds the documentation for the PyPI integration.
Fixes https://github.com/mindsdb/mindsdb/issues/8043
=> Documentation for the PyPI Integration

docs/integrations/app-integrations/reddit.mdx
Fixed typos and improved grammar.
respecitvely -> respectively
=> chore(docs/integration): fix typo in reddit.mdx

docs/integrations/app-integrations/slack.mdx
=> chore(docs/integration): improve grammar in slack.mdx

docs/integrations/data-integrations/all-data-integrations.mdx
=> chore(docs/integrate): fixed tiny typo in all-data-integrations.mdx

docs/integrations/data-integrations/d0lt.mdx
=> chore(docs/integrations): fix typos in d0lt.mdx

.devcontainer/devcontainer.json
=> fix dev container build context

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py, mindsdb/api/mysql/mysql_proxy/utilities/sql.py
Increase butch size when duckdb do types infer. Need to prevent `Failed to cast value` errors.
=> increase duckdb data analysis batch size

mindsdb/utilities/ml_task_queue/consumer.py, mindsdb/utilities/ml_task_queue/producer.py
Try connect to Redis multiple time before raise error.
=> Reconnect to Redis if first connection failed

.pre-commit-config.yaml, mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py, mindsdb/integrations/handlers/chromadb_handler/README.md, mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py, mindsdb/integrations/libs/vectordatabase_handler.py, requirements/requirements.txt, tests/unit/test_knowledge_base.py
Allows user to create knowledge base without defining storage. By default, it will create in memory ChromaDB
continuing from https://github.com/mindsdb/mindsdb/pull/7886
e.g.
```
CREATE KNOWLEDGE_BASE  my_kb
USING
MODEL=cohere_embedding_model;
```
Fixes #7184 
=> Add support for default vectorDB for Knowledge Base

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
Allow multiple elements in `DESCRIBE`, like:
```sql
DESCRIBE model.accuracy.group_name
```
=> Allow multiple elements in `DESCRIBE`

mindsdb/integrations/handlers/Handlers_Manual_QA.md
Testing of Jira App integration with Mindsdb
Fixes #7852
=> Jira_App_Integration

mindsdb/integrations/handlers/Handlers_Manual_QA.md
Fixes #8091 
Tested the Frappe Handler Manually and reported findings.
=> chore(handlers_qa): add new manual qa test for the frappe app

docs/integrations/data-integrations/clickhouse.mdx
=> fix: fix minor typos

docs/integrations/data-integrations/airtable.mdx
=> fix(data-integrations): fixed minor typo

docs/integrations/app-integrations/dockerhub.mdx, docs/integrations/data-sources-overview.mdx, docs/mint.json
This PR adds the documentation for the Docker Hub integration.
Fixes https://github.com/mindsdb/mindsdb/issues/8059
=> Added the Documentation for the Docker Hub Integration

mindsdb/integrations/handlers/Handlers_Manual_QA.md
Tested google_search integration 
Fixes #8118
=> Tested Google search integration

mindsdb/integrations/handlers/Handlers_Manual_QA.md
Fixes #8047 
Tested the Sendinblue Handler Manually and reported findings.
=> misc(handlers_qa): append sendinblue qa test url

requirements/requirements.txt, tests/unit/test_executor.py
Bump `duckdb` requirement to rid of from bugs
=> Bump duckdb requirement

mindsdb/integrations/handlers/Handlers_Manual_QA.md
Update Handlers_Manual_QA.md with Reddit app integration Test Failed.
Fixes #7801
@chandrevdw31, can you review it
=> Reddit app integration Test Failed

mindsdb/utilities/ml_task_queue/base.py, mindsdb/utilities/ml_task_queue/consumer.py, mindsdb/utilities/ml_task_queue/producer.py, mindsdb/utilities/ml_task_queue/utils.py
Connection to Redis may disappear at any time. To prevent undesirable consequences there is added check for `ping` before call to db.
=> Wait for `redis.ping` before interact with `redis`

mindsdb/integrations/handlers/sendinblue_handler/sendinblue_tables.py
=> unhashable type dict in sendinblue

mindsdb/integrations/handlers/twilio_handler/README.md, mindsdb/integrations/handlers/twilio_handler/twilio_handler.py
added the phone numbers table, and checked that we can join, it works, see docs
=> add phone numbers table

.github/workflows/add_to_pr_review.yml, .github/workflows/mindsdb.yml
This PR ignores test workflow if the changes are related to markdown files.
=> GitHub action ignore .md files

mindsdb/integrations/handlers/twilio_handler/twilio_handler.py
Fix  sending only one message in insert from select 
=> Fix twilio sends only one message

mindsdb/integrations/handlers/Handlers_Manual_QA.md, mindsdb/integrations/handlers/strava_handler/Readme.md
This PR performing integration testing for the GitLab integration with update Handlers_Manual_QA. and I have updated `mindsdb/integrations/handlers/strava_handler/Readme.md` 
Fixes #8150
Hi @chandrevdw31  , can you please review this PR
=> [Integration Testing] Test the Strava app integration

mindsdb/integrations/handlers/paypal_handler/README.md, mindsdb/integrations/handlers/paypal_handler/paypal_handler.py, mindsdb/integrations/handlers/paypal_handler/paypal_tables.py, tests/handler_tests/test_paypal_handler.py
Fixes [#8145](https://github.com/mindsdb/mindsdb/issues/8145)
=> Paypal orders table implementation

docs/contribute/app-handlers.mdx
=> fix(contribution-docs): fix typos in app-handlers.mdx

mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
New rules have an ability to specify username and password in either the URL or the connection info supplied via JSON.  Failure to have any required information set up triggers an error.
Fixes #7235 
To test manually, one can connect to a local system using a URI in the format as follows, making changes as needed.  This is submitted in the "url" field of the API request.
mysql://user:passwprd@host/db
I was unable to find automatic authentication tests in the test suite.  I could add them there if you can direct me.
See above, could not find authentication tests.
=> Adding url support for mysql db connections

mindsdb/integrations/handlers/Handlers_Manual_QA.md
The testing of medeley app if finished and it passes all the test
Fixes #8206 
=> Mendeley App integrations test successfull

mindsdb/utilities/fs.py
=> make logging clearer in fs.py

mindsdb/integrations/handlers/twilio_handler/twilio_handler.py
=> updated twilio handler msg length

.github/workflows/mindsdb.yml
Del `pre-commit` from github actions, since this should be done before the commit, not after
=> Del pre-commit from githubactions

docs/integrations/app-integrations/shopify.mdx
=> updated shopify docs

docs/connect/jupysql.mdx
=> fix(jupysql): update docs to fix typos

docs/connect/dbeaver.mdx
=> fix(dbeaver): update documentation to reflect typo fixes

mindsdb/integrations/handlers/paypal_handler/paypal_handler.py, mindsdb/integrations/handlers/paypal_handler/paypal_tables.py
Implementing Payouts Table in Paypal 
Fixes #8051
Paypal table
=> Implementing Payouts table in Paypal Conflict Fixed

mindsdb/integrations/handlers/web_handler/tests/example_data.py, mindsdb/integrations/handlers/web_handler/tests/test_helpers.py, mindsdb/integrations/handlers/web_handler/urlcrawl_helpers.py
=> web handler enhancements

docs/integrations/ai-engines/langchain.mdx
=> fix(langchain): update docs to reflect typo fixes

docs/integrations/ai-engines/huggingface.mdx
=> fix(huggingface): update docs to reflect typo fixes

mindsdb/integrations/handlers/youtube_handler/youtube_tables.py
Updated the YouTube comments table to include replies and sub replies
Fixes #8249 
=> feat(youtube-handler): add comment replies column to comments table

docs/integrations/data-sources-overview.mdx
I have added icons for integrations (application) docs. 
Fixes #7802
=> [docs] adds icons to integrations page

docs/integrations/ai-engines/anthropic.mdx, docs/integrations/ml-engines-overview.mdx, docs/mint.json, mindsdb/integrations/handlers/anthropic_handler/README.md
This PR adds the documentation for the Anthropic integration.
Fixes https://github.com/mindsdb/mindsdb/issues/7930
=> Added the Documentation for the Anthropic Integration

docker/release, mindsdb/integrations/handlers/llama_index_handler/requirements.txt
This PR consolidates the dependency versions for the LlamaIndex and LangChain integrations.
Once this is approved, I will also raise another PR to update these versions in Cloud.
Fixes https://github.com/mindsdb/mindsdb/issues/8252
Given below is a screenshot of running the integration after installing the new versions of the depdencies,
Given below are the versions of `llama-index` and `langchain` that have been used for the above,
=> Consolidation of LlamaIndex and LangChain Dependency Versions

mindsdb/integrations/handlers/rag_handler/README.md, mindsdb/integrations/handlers/rag_handler/rag_handler.py, mindsdb/integrations/handlers/rag_handler/settings.py, mindsdb/integrations/handlers/writer_handler/README.md
-writer auth was deprecated in later sdk
-url wasn't parsing into vectordb
-update docs
-make `vector_store_folder_name` mandatory 
=> hot fix for rag_handler

mindsdb/integrations/handlers/openai_handler/constants.py
we should just pass through s…tuff, anyway, adding support for gpt4 1106
@paxcema 
=> [feat] OpenAI: add support for GPT4-Turbo preview

mindsdb/integrations/handlers/openai_handler/constants.py, mindsdb/integrations/handlers/openai_handler/helpers.py, mindsdb/integrations/handlers/openai_handler/openai_handler.py
-remove ft_suffix
-simplify retreival of all models
=> simplify getting all models openai

.flake8, mindsdb/utilities/fs.py, mindsdb/utilities/log.py, tests/unit/test_project_structure.py
There was an error in creation of `process_mark`  with custom name. Such marks was never deleted.
=> Fix creation of custom process marks

mindsdb/integrations/handlers/openai_handler/requirements.txt
Avoids errors on fresh installs of this handler due to today's release of OpenAI's 1.0.0 version (and subsequent hotfixes) for their Python SDK
=> [fix] OpenAI: bound SDK to < 1.0.0

docs/integrations/app-integrations/gmail.mdx, docs/nlp/json-from-text.mdx, docs/nlp/nlp-mindsdb-openai.mdx, docs/nlp/question-answering-inside-mysql-with-openai.mdx, docs/nlp/sentiment-analysis-inside-mysql-with-openai.mdx, docs/nlp/text-summarization-inside-mysql-with-openai.mdx, docs/sql/api/finetune.mdx, docs/sql/tutorials/image-generator.mdx, docs/sql/tutorials/slack-chatbot.mdx, docs/sql/tutorials/twitter-chatbot.mdx, docs/sql/tutorials/twitterbot-mariadb-enterprise-server-skysql.mdx, docs/tutorials/sentiment-analysis-intercom-data-airbyte.mdx
updated openai tutorials to create ml_engine before model
Fixes #-
=> updated openai tutorials

mindsdb/integrations/handlers/byom_handler/byom_handler.py, mindsdb/integrations/libs/ml_exec_base.py, mindsdb/interfaces/storage/model_fs.py
Set BYOM `engine_version` in `create_validation`
=> Validate arguments when create/finetune BYOM model

mindsdb/integrations/handlers/byom_handler/byom_handler.py
=> Fix BYOM engine versioning

docker/release
This PR adds the dependencies for the Popularity Recommender handler to Docker image.
Fixes https://github.com/mindsdb/mindsdb/issues/8300
=> Added Dependencies for Popularity Recommender to Docker

mindsdb/integrations/handlers/twitter_handler/twitter_handler.py
If message is greater than 280 symbols and contents url:
- split text
- publish image with the lase tweet
Fixes error if long tweet contents url
```
[twitter/my_twitter]: create_tweet() got an unexpected keyword argument 'media_url'
```
=> Publish media of long tweet with the last message

mindsdb/integrations/handlers/sendinblue_handler/sendinblue_tables.py
added update method for email campaigns table
Fixes #8116
Video attachment:
https://github.com/mindsdb/mindsdb/assets/119131588/5d3e69fc-7c0f-43c5-8b46-e107a45c5a7c
=> Added update method for  Email campaigns table
