setup.py

This enhancement is dependent on #3

generate install_requires for setup.py from requirements.txt

---

.github/ISSUE_TEMPLATE/feature-mindsb-request.md

This PR adds new features template. Creating features is accomplished through the use of this feature templates. Feature template defines all the information required to create or propose a new feature in mindsdb.

Add features request template

---

docs/Config.md

Fixing some markdown errors and a typo.

Fixing typo on Config.md

---

distributions/aws/001-prepare-ubuntu.sh
distributions/aws/002-prepare-anaconda.sh
distributions/aws/003-prepare-mindsdb.sh
distributions/aws/build-aws-ami.sh
distributions/aws/packer-mindsdb-aws-backup.json
distributions/aws/packer-mindsdb-aws.json
distributions/aws/packer-null-builder.json
distributions/docker/Dockerfile
distributions/docker/build-docker.sh
distributions/docker/requirements-docker.txt

Implementations of scripts to create AWS AMIs for distribution and Docker Images.  This can easily be handed off to an individual who is doing CI to integrate with a CI pipeline to automatically do builds.
There is a build shell script in both current distribution folders that will start running the build process for that distribution type.  An insane about of inline comments to explain everything has been placed absolutely everywhere.
Enjoy.
- Farley Farley Farley

AWS and Docker distributions completed

---

docs/GoogleColab.md

I found a typo in documentation. Hope this small effort will be appreciated.

typo in code

---

docs/examples/kaggle/house_prices.md

Change model_name to kaggle_house_sale from house_sale in mdb.predict()

Changed model_name to kaggle_house_sale in mdb.predict()

---

docs/examples/nlp/train.py
mindsdb/libs/controllers/mindsdb_controller.py

hi, @torrmal ，For a variety of data sources, consider using the encapsulation function of pandas to achieve, okay?

NLP Text categorization support for Chinese corpus（the separator of the  csv file ） 

---

mindsdb/libs/constants/mindsdb.py
mindsdb/libs/data_types/batch.py
mindsdb/libs/helpers/norm_denorm_helpers.py
mindsdb/libs/helpers/text_helpers.py
mindsdb/libs/ml_models/pytorch/libs/base_model.py
mindsdb/libs/ml_models/pytorch/models/ensemble_fully_connected_net/ensemble_fully_connected_net.py
mindsdb/libs/phases/data_encoder/data_encoder.py
mindsdb/libs/phases/data_vectorizer/data_vectorizer.py
mindsdb/libs/phases/stats_generator/stats_generator.py

-some code comments
-methods renaming to adhere to pep8
-renaming data types class->categorical
-renaming data types full_texr->text

Dev gh addons

---

docs/examples/time_series/README.md

Fixed some typos in the readme file which is explaining the time series analysis example

Fixed typo in README.md of TimeSeries example

---

README.md
docs/Config.md
docs/DataSources.md
docs/FAQ.md
docs/GoogleColab.md
docs/InsideMindsDB.md
docs/Installing.md
mindsdb/README.md

Amend wording and spelling in several parts of the documentation.
This includes the following files:
1. Two READMEs
2. Config
3. DataSources
4. FAQ
5. GoogleColab
6. InsideMindsDB
7. Installing

Proofread documentation

---

.github/ISSUE_TEMPLATE/feature-mindsdb-request.md

I think you meant `mindsdb` and not `mindsb` :)

fix typo in issue template

---

docs/examples/basic/test.py
mindsdb/libs/controllers/predictor.py
mindsdb/libs/controllers/transaction.py
mindsdb/libs/data_types/mindsdb_logger.py
mindsdb/libs/data_types/probability_evaluation.py
mindsdb/libs/data_types/transaction_metadata.py
mindsdb/libs/data_types/transaction_output_data.py
mindsdb/libs/data_types/transaction_output_row.py
mindsdb/libs/ml_models/probabilistic_validator.py
mindsdb/libs/phases/model_analyzer/model_analyzer.py
mindsdb/libs/phases/model_predictor/model_predictor.py
mindsdb/libs/phases/model_trainer/model_trainer.py
mindsdb/libs/phases/stats_generator/stats_generator.py
mindsdb/libs/workers/train.py

updates to the way we calculate the probability distribution of the result being correct

V1 prob dist

---

.gitignore
mindsdb/libs/backends/ludwig.py
mindsdb/libs/phases/stats_generator/stats_generator.py
test.out

Fixed a few issues relating to hardcoded separator and a missing gitignore file from the previous PR.
This PR resolves #108

Support timeseries cell

---

requirements.txt

This PR updates tensorflow requirements to use latest stable 1.13.1 version.

Fix tensorflow requirements

---

docs/website/docs/AdvancedExamples.md
docs/website/docs/BasicExample.md
docs/website/docs/Config.md
docs/website/docs/DataSources.md
docs/website/docs/FAQ.md
docs/website/docs/InsideMindsDB.md
docs/website/docs/Installing.md
docs/website/website/core/Footer.js
docs/website/website/sidebars.json
docs/website/website/siteConfig.js
docs/website/website/static/css/style.css

This PR adds menu bar in the documentation page. Also, footer links are changed and the new font is used in the pages.

Docs improvements

---

docs/website/docs/AdvancedExamples.md
docs/website/docs/Config.md
docs/website/docs/FAQ.md
docs/website/docs/InsideMindsDB.md
docs/website/website/README.md

This PR updates Readme for docs website and fix some typos in the docs.

Website docs update

---

docs/website/docs/Installing.md

Add details collected in #152 to the documentation.

Add details about tkinter (fixes #152)

---

docs/website/docs/FAQ.md

Fix docs link 

---

README.md
docs/website/docs/BasicExample.md

added link to google codelab in the correct places

---

README.md
docs/examples/basic/train.py
docs/website/docs/AdvancedExamples.md
docs/website/docs/BasicExample.md
mindsdb/libs/phases/data_extractor/data_extractor.py
mindsdb/libs/phases/model_analyzer/model_analyzer.py
mindsdb/libs/phases/stats_generator/stats_generator.py
test.py

Replaced link to githubraw home_rentals dataset with link to the same dataset as a public file on our s3 

---

mindsdb/libs/controllers/predictor.py

* Added `load_model` and `export_model` to import and export individual models 
*minor modifications to comments/logging in `export` and `load`

Added import and export for individual models

---

README.md

Change link to PyPI MindsDB. #216

Rename link to MindsDB

---

README.md
mindsdb/libs/controllers/predictor.py
requirements-win.txt

Made `get_models` return a list of valid models, instead of crashing if one or more of the model's metadata is incorrect.

Fixed issues with get_models

---

mindsdb/libs/controllers/predictor.py

Small changes to the creation of adapted metadata in order to allow it to be server when the model is still training (when stats generator hasn't run and when model analysis hasn't run respectively).

Intermediate adapted metadata

---

README.md
integration_testing/run_a_file.py

Added docker link to REAMDE.
Resolves #221

added docker links to readme

---

mindsdb/libs/controllers/predictor.py
mindsdb/libs/phases/stats_generator/stats_generator.py

* Added the most correlated column[s] to the of warning
* Made the scores inside the stats generator go from 0[worst] to 10[best]
This should resolve: #236

Score exposition changes

---

mindsdb/libs/backends/ludwig.py

Implemented and imperfect fix (batching of training dataset) to allow ludwig to operate on large datasets of images (such as CIFAR) when feed the data via the API.

Fixes for cifar

---

integration_testing/run_travis_tests.py
mindsdb/libs/backends/lightwood.py
mindsdb/libs/controllers/predictor.py
mindsdb/libs/controllers/transaction.py
mindsdb/libs/helpers/text_helpers.py
mindsdb/libs/phases/data_transformer/data_transformer.py
mindsdb/libs/phases/model_interface/model_interface.py
test.py

Finished integration with lightwood, now proper predictions can be made using lightwood.
Added a new `DataTransform` phase to normalize data before learning.

Lightwood integration

---

mindsdb/__about__.py
mindsdb/libs/backends/lightwood.py
mindsdb/libs/controllers/predictor.py
mindsdb/libs/phases/data_transformer/data_transformer.py
mindsdb/libs/phases/stats_generator/stats_generator.py

Some improvements for dealing with large datasets and various data types.
* Cast categorical types as `category` type in pandas df
* Treating `DATE` subtypes as `datetime` when passing to lightwood backend
* Stats generator is less aggressive when it comes to turning numerical columns into categorical ones
* Removed some outdated keys in adapted metadata generation

Large files

---

mindsdb/libs/phases/data_transformer/data_transformer.py
mindsdb/libs/phases/stats_generator/stats_generator.py
requirements.txt

* Being less aggressive about making values categorical, especially for dates and datetimes
* Fixed a syntax error in data transformer

Categorical imperative

---

mindsdb/libs/data_sources/file_ds.py

Add semicolon as accepted delimiters

---

README.md
docs/website/docs/Installing.md
mindsdb/__about__.py
mindsdb/libs/controllers/transaction.py

* Handle quoted csvs and other formats the sniffer can't detect via trying to call `pd.read_csv` when the sniffer produced csv reading seems incorrect (e.g. inconsistent number of columns in certain rows)
* Added contributing / developing info to docs
* Removed outdated docker references from docs
* Added better failure messages for permissions errors and other errors related to saving / reading the metadata

Various changes

---

mindsdb/__about__.py
mindsdb/libs/constants/mindsdb.py
mindsdb/libs/controllers/transaction.py
mindsdb/libs/data_types/probability_evaluation.py
mindsdb/libs/data_types/transaction_output_data.py
mindsdb/libs/data_types/transaction_output_row.py
mindsdb/libs/helpers/general_helpers.py
mindsdb/libs/helpers/probabilistic_validator.py
mindsdb/libs/phases/data_transformer/data_transformer.py
mindsdb/libs/phases/model_analyzer/helpers/column_evaluator.py
mindsdb/libs/phases/model_analyzer/model_analyzer.py
test.py

* Changed the way we make predictions, now the probabilistic validator "decides" what the final value is, if the model predicts a bucket it thinks to be improbable
* Displaying value ranges for numerical and Date data types
* Cleared and refactored a bunch of code
* Fixed logic around getting the value buckets in the `ProbabilityEsimation` class
* Added `explain` (return a JSON with details about the prediction) and `epitomize` (returns a string summarzing the prediction) to transaction output row
* Changed the Bayesian model used by the probabilistic validator
* Data Transformer, when balancing target categories, now does so in the train, test and validation dataset separately, and does it in all of them, rather than  just train. The refactoring here also caused an amazing speedup.

Probabilistic validator and prediction changes

---

docs/examples/kaggle/README.md
docs/examples/kaggle/house_prices.md
docs/website/docs/BasicExample.md
docs/website/docs/ColumnMetrics.md
mindsdb/libs/phases/stats_generator/stats_generator.py

* Updated the description for various scores inside the documentation
* Updated the check performed inside the stats generator to give a warning based on a score
* Fixed a few links in the docs

Score improvements

---

docs/website/docs/GoogleColab.md
docs/website/docs/JupyterNotebook.md
mindsdb/__about__.py
requirements.txt
setup.py

* Update docs for install on jupyer and for google cloab
* Updated requirements to run with latest lightwood

Small fixes

---

mindsdb/libs/phases/data_extractor/data_extractor.py

This PR checks if the data frame value is boolean before casting it to 'True' or 'False'. Fixes #294

Check if column is Boolean before casting #294

---

docs/website/docs/AdvancedExamples.md

fixed typo in code example in advanced use cases documentation.

Fixed typo in code example in Advanced usecases

---

mindsdb/__about__.py
mindsdb/libs/controllers/predictor.py
mindsdb/libs/helpers/general_helpers.py

Remove update check

---

mindsdb/libs/phases/stats_generator/stats_generator.py

This PR will fix some typos in `stats_generator.py`

fix some typos

---

docs/website/docs/Installing.md
docs/website/docs/JupyterNotebook.md
mindsdb/__about__.py

This "fixes" and issue @ZoranPandovski reported that was causing upgrades on windows to fail due to lightwood never getting re-insalled (since the master version on github looked to be the same to pip)

Install doc update

---

docs/website/docs/ComparsionWithOtherLibraries.md
docs/website/website/sidebars.json

This documentation is added for comparing how Mindsdb
is different from other libraries and frameworks. It
contains some key points and code samples of different
libraries for comparison. closes #45

Add comparison between Mindsdb and other libraries

---

docs/website/docs/AccuracyComparison.md
docs/website/docs/AdvancedExamples.md
docs/website/docs/ComparsionWithOtherLibraries.md
docs/website/docs/DataSources.md
docs/website/docs/Interface.md
docs/website/docs/PredictorInterface.md
docs/website/website/sidebars.json
mindsdb/__about__.py
mindsdb/libs/controllers/predictor.py

A lot of documentation updates, corrections and changes. Also some very small fixes to the interface that  I realized should be done as I was documenting this stuff.

Advanced docs update

---

.travis.yml

addresses #280 . Add publishing to docker hub when deploying. 
@George3d6 Please review. 
Please add environment variables `$REGISTRY_USER` and `$REGISTRY_PASS` else the travis build will fail

Publish to dockerhub after publishing to pypi

---

README.md

Add badge for monthly downloads from PyPI

Add PyPI downloads

---

mindsdb/__about__.py
mindsdb/libs/backends/lightwood.py
mindsdb/libs/helpers/general_helpers.py
tests/accuracy_benchmarking/benchmark.py
tests/accuracy_benchmarking/compare.py

* Correctly enabling cache enabling and disabling code in lightwood backend
* Fixed benchmark code reporting
* Added telemetry check
* Cleaned up some code

Benchmarks, version check, cahce

---

mindsdb/__about__.py
mindsdb/config/__init__.py
mindsdb/libs/controllers/transaction.py
mindsdb/libs/helpers/general_helpers.py
mindsdb/libs/phases/data_transformer/data_transformer.py
tests/accuracy_benchmarking/compare.py
tests/ci_tests/fast_test.py
tests/ci_tests/full_test.py
tests/ci_tests/tests.py

No longer running data splitter in `predict` transactions unless they are of type timeseires.

Multilabel splitter fix

---

mindsdb/__about__.py
mindsdb/libs/backends/ludwig.py
mindsdb/libs/helpers/explain_prediction.py
mindsdb/libs/helpers/general_helpers.py
test.py

Fixed the human-readable explaination for the impact of the most important and unimportant columns. Moved some now-boilerplate code into `general_helpers`.

Explain fix

---

mindsdb/__about__.py
requirements.txt

Fix scikit version that works on windows. Same fix as lightwood.

Fix scikit version to work on windows

---

mindsdb/__about__.py
requirements.txt

DO NOT MERGE.
This is here just to test various fixes to the segfault bug in travis.

Segfault fix

---

README.md

Add new badge with a link to and status of the website, minor typos fixed.

Add website badge and minor typos fixes

---

.travis.yml

Skip the CI when docs are changed

---

requirements.txt
setup.py
tests/accuracy_benchmarking/benchmark.py

* Changed windows install
* Changed accuracy benchmarks

New install

---

docs/website/docs/JupyterNotebook.md
docs/website/docs/SageMakerSDK.md
docs/website/docs/UseMindsDBinSage.md
docs/website/website/sidebars.json

This PR adds additional information about how to use MindsDB container with SageSDK. Fixed some typos and markdown structure for older docs.

Add additional documentation for SageMaker SDK

---

mindsdb/__about__.py
mindsdb/libs/backends/lightwood.py

Removed print statement which is filling all the console

---

.travis.yml
mindsdb/__about__.py
mindsdb/libs/phases/data_transformer/data_transformer.py
requirements.txt

* Upgraded lightwood version
* Making sure `TEXT` columns are always converted to `str`

Text transofrmation

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Amie asked me to add them, use the lightwood ones as a template

Added code of conduct and contributing docs

---

docs/website/docs/ChurnReduction.md
docs/website/docs/HotelBooking.md
docs/website/docs/MedicalDiagnosis.md
docs/website/docs/PredictiveMaintenance.md
docs/website/website/sidebars.json
mindsdb/__about__.py

This PR adds additional use case examples to the documentation. MindsDB version is upgraded so the website gets updated with the new changes.

Add more use cases to the examples 

---

mindsdb/__about__.py
mindsdb/__init__.py
mindsdb/libs/backends/lightwood.py
mindsdb/libs/controllers/predictor.py
mindsdb/libs/controllers/transaction.py

This PR removes the sys.exit logic, and use ValueError and Exception when needed. @George3d6 Maybe it would be better if we raise RuntimeError error in __ini__.py for the wrong python version?

Cleanup exceptions

---

docs/website/website/siteConfig.js

Sorry :( trial and error on this.

Website config BaseUrl change

---

README.md
docs/website/docs/AccuracyComparison.md
docs/website/website/sidebars.json
docs/website/website/siteConfig.js
docs/website/website/static/index.html

Add a new domain to the docs configuration.

Docs new domain

---

docs/website/website/siteConfig.js
docs/website/website/static/index.html

Revert the latest changes, after this we are decoupling mindsdb repo and migrating documentation in its own repository.

Revert website changes

---

mindsdb/__about__.py
mindsdb/libs/controllers/predictor.py
mindsdb/libs/controllers/transaction.py
mindsdb/libs/helpers/probabilistic_validator.py
requirements.txt
tests/ci_tests/fast_test.py
tests/ci_tests/full_test.py
tests/ci_tests/tests.py
tests/functional_testing/custom_model.py

@torrmal if you have time please review & confirm that this is indeed as you want it.
Method implemented as:
`test(self, when_data, accuracy_score_functions, score_using='predicted_value', predict_args=None)`
*`when_data` same as the one passed to `predict`, it's a data source, file, url, pandas dataframe.
*`accuracy_score_functions` a single function or  a dictionary for the form `{target_name: acc_func}` for when we have multiple targets
*`score_using` what values from the `explanation` of the target to use in the score function, defaults to the predicted_value (alternative here is the `confidence_range` for numbers, maybe more in the future)
*`predict_args` dictionary of arguments to be passed to `predict`, e.g: `predict_args={'use_gpu': True}`
*`return` a dictionary for the form …

Test method

---

mindsdb/__about__.py
mindsdb/__init__.py
mindsdb/libs/data_sources/clickhouse_ds.py
mindsdb/libs/data_sources/mysql_ds.py
mindsdb/libs/data_sources/postgres_ds.py

Clickhouse datasource

---

mindsdb/__about__.py
mindsdb/__init__.py

This PR adds ImportErrors and informative messages for the missing extra_data_sources requirements.

Add import error messages

---

mindsdb/__about__.py
mindsdb/libs/controllers/predictor.py
mindsdb/libs/controllers/transaction.py
mindsdb/libs/phases/data_cleaner/data_cleaner.py
mindsdb/libs/phases/data_splitter/data_splitter.py
mindsdb/libs/phases/stats_generator/data_preparation.py
mindsdb/libs/phases/stats_generator/preprocessing.py
mindsdb/libs/phases/stats_generator/scores.py
mindsdb/libs/phases/stats_generator/stats_generator.py
tests/ci_tests/tests.py

* Resolves #450 
* Resolves #435 (Not fully, but what it doesn't, is now part of other issues)
* Adds a new data cleaning phase that runs multiple times (much less complex than other phases).
* Major refactoring to the StatsGenerator that greatly simplify the logic and remove a bunch of bugs, that being said, the original `stats` object returned by it should remain unchanged, all the new stuff is inside `stats_v2`, which will soon (TM) fully replace it.

Data Analytics Backend V2

---

mindsdb/__about__.py
mindsdb/libs/phases/stats_generator/stats_generator.py

dictionaries were not instantiated for empty columns.
Resolves #469

fix empty column error

---

mindsdb/__about__.py
mindsdb/libs/backends/lightwood.py
mindsdb/libs/phases/stats_generator/stats_generator.py
optional_requirements_ludwig_model.txt

* Bump Ludwig version and removed TensorFlow optional dependencies. Mainly to get rid of the big warning displaying over out GitHub repo about a security issue in an optional dependency -_-
* Made changes to the stats generator based on the issues arising from the discussion that was had today.
Resolves #461 
Resolves #458 
Resolves #453 
Also, manually close https://github.com/mindsdb/mindsdb_gui/issues/330 once @setohe0909 confirms that the ordering works properly in scout.
Added descriptions as per  #462 with the text `TBD` just so that the key is there and the GUI can use it, we'll replace them with real descriptions as soon as we refine those provided by [Daniel](https://github.com/dfernan).
Review as soon as possible since it's critical to get this + #460 solved by Friday... ideally …

Various change required to finalize Scout v2

---

mindsdb/__about__.py
mindsdb/libs/phases/stats_generator/stats_generator.py

outlier buckets

---

mindsdb/__about__.py
mindsdb/libs/phases/data_analyzer/data_analyzer.py

Fixes https://github.com/mindsdb/mindsdb/issues/484

Avoid ZeroDivisionError in case of no values in hist bucket

---

mindsdb/__about__.py

This PR bumps version of MindsDB so we have latest pushed on PyPi. Fixes **FileNotFoundError** error.

Upgrade version to push everything on PyPi

---

MANIFEST.in
mindsdb/__about__.py

Fixes https://github.com/mindsdb/mindsdb/issues/489

Add requirements_test.txt to manifest and bump version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-mindsdb-request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

This PR includes simple PR template, and simplify the templates we have for reporting the bugs.

Update GH templates

---

mindsdb/__about__.py
mindsdb/libs/data_sources/file_ds.py

This is an idea how to determine delimiter before read_csv (as it cant do it). It works, but may be someone know how do it better.

Fix issue 495

---

mindsdb/__about__.py
mindsdb/api/http/initialize.py
mindsdb/api/http/namespaces/datasource.py
mindsdb/api/http/namespaces/predictor.py

https://github.com/mindsdb/mindsdb/issues/516

fix #516 flask global objects

---

mindsdb/README.md
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/integrations/clickhouse/clickhouse.py
mindsdb/integrations/mariadb/mariadb.py
tests/integration_tests/test_mariadb.py

Close #547. Now in result of sql-query will returns for each predicted columns *_explain column, and for Numeric columns *_min and *_max columns.
Additionally fixed very hard to find bug with keeping packets order number

Added _max _min and _explain columns

---

mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

allow returns unlimited number of packets via mysql-interface

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/utilities/wizards.py
requirements.txt

close #539
now if field 'certificate_path' not in config.json, then for each connection will be make new temp ssl-cert

new ssl-cert  for each connection

---

mindsdb/api/http/namespaces/predictor.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/interfaces/native/mindsdb.py
mindsdb/interfaces/native/predictor_process.py

MindsdbNative.predict() 'when' parameter moved to 'when_data' like in mindsdb_native

move .predict 'when' param to 'when_data'

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/integrations/clickhouse/clickhouse.py
mindsdb/integrations/mariadb/mariadb.py

Close #555
Capture information about query source using db username

Capture information about

---

.travis.yml
mindsdb/api/http/initialize.py
mindsdb/api/http/namespaces/config.py
mindsdb/api/http/namespaces/configs/config.py
mindsdb/api/http/start.py
mindsdb/utilities/config.py
tests/integration_tests/api/test_http.py

* Added some modification method to the `Config` object
* Added modification endpoints to the HTTP API
* Added tests for the config modification

Http modification of config

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/controllers/session_controller.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
tests/docker/mariadb/connect.cnf
tests/integration_tests/flows/common.py
tests/integration_tests/flows/test_clickhouse.py
tests/integration_tests/flows/test_mariadb.py

Tests of using FileDS in sql queries

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

Fixes #608
Regexp used to parse 'insert' statement was not enough. If brackets were used in the expression then it followed to error.

Fix 'insert' statement parsing

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

Current sql parser split table and field by dot. All brokes if field contains dot. Example:
```
> parse('''select * from test.`pm2.5` where test.pm.`PM2.5` = 1''')
> {'select': '*', 'from': 'test.pm2.5', 'where': {'eq': ['test.pm.PM2.5', 1]}}
```
`test.pm2.5` and `test.pm.PM2.5` obviously wrong. This PR should fix it.

fix sql query if table field contains dot

---

mindsdb/__about__.py
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

Release 2.1.1

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py

Fix: timestamp sql filter if host use not utc timezone.

fix no-utc timestamp filter

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

Fix 'insert' where some columns is 'null'

fix inserts with null

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py

Fixes:
- filtering by timestamp through sql interface
- 'insert predictor' will work well if 'column = null' in query

Release 2.1.2

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/interfaces/datastore/datastore.py

Before in save_datasource method arguments for saving datasource was taking from 'default_' config keys.

fix integration type in save_datasource

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/interfaces/datastore/datastore.py

Release 2.2.1

---

.travis.yml
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/controllers/session_controller.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_datum.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/__init__.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/binary_resultset_row_package.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/column_definition_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/command_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/stmt_prepare_header.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/datasource_datanode.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/api/mysql/mysql_proxy/libs/constants/mysql.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/integrations/postgres/postgres.py
mindsdb/interfaces/database/database.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/utilities/wizards.py
requirements.txt
requirements_test.txt
tests/docker/cli.sh
tests/docker/docker-compose.yml
tests/docker/postgres/Dockerfile
tests/integration_tests/api/test_http.py
tests/integration_tests/flows/config/config.json
tests/integration_tests/flows/test_postgres.py

PostgreSQL integration and couple fixes

PostgreSQL integration

---

mindsdb/api/http/namespaces/datasource.py
mindsdb/interfaces/datastore/datastore.py

Fixes #638 
Reason of issue is not closed uploaded file.

Close uploaded file

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
mindsdb/api/mysql/mysql_proxy/controllers/session_controller.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/command_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/stmt_prepare_header.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/utilities/wizards.py
requirements.txt
tests/integration_tests/api/test_http.py

'insert' parser rewrited using pyparsing. It should make it more 'reliable', especially when parsed 'insert' statement with parameters.
also fixed:
- mysql default config

Improve 'Insert' parser

---

.github/workflows/cla.yml

Version 2 has a few bug fixes https://github.com/cla-assistant/github-action/blob/master/CHANGELOG.md.

Upgrade CLA bot to version 2

---

mindsdb/api/http/namespaces/datasource.py

**Issues from MindsDB Scout:**
- https://github.com/mindsdb/mindsdb_gui/issues/522
- https://github.com/mindsdb/mindsdb_gui/issues/523

Analyzing thread every analyze process - GUI

---

.travis.yml
mindsdb/__init__.py
mindsdb/api/http/namespaces/config.py
mindsdb/api/http/namespaces/datasource.py
mindsdb/utilities/config.py
tests/integration_tests/api/test_http.py

Fixes #656 #655
- hide db passwords in api answers
- improve errors text in `/config` routes

/config routes improvements

---

mindsdb/api/http/start.py
requirements.txt

Default flask server changed to gunicorn

Gunicorn http server

---

mindsdb/api/http/initialize.py
requirements.txt

Add CORS policy to web scout petitions.
mindsdb

Add CORS  library

---

.github/workflows/mindsdb.yml

This PR adds check to deploy step, so if the admin pushes to stable(CLA sign) the deploy shall be ignored.

Ignore deploy, if admin push to stable

---

.github/workflows/mindsdb.yml

This PR fixes the Docker deploy action, by including the path to the Docker file in GA yml

Add path to Docker file

---

mindsdb/__init__.py
mindsdb/__main__.py
mindsdb/api/http/namespaces/predictor.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/utilities/config.py
mindsdb/utilities/fs.py
mindsdb/utilities/wizards.py
tests/integration_tests/flows/common.py
tests/integration_tests/flows/config/config.json

Replace two paths
`config.interface.datastore.storage_dir`
`config.interface.mindsdb_native.storage_dir`
to one root path for all user data:
`config.storage_dir`

One storage path in config

---

.flake8
mindsdb/__about__.py

fixes:
- added more errors check for GUI downloading

Release 2.7.2

---

mindsdb/api/http/namespaces/predictor.py
mindsdb/interfaces/custom/custom_models.py
tests/integration_tests/flows/test_custom_model.py

Added `trained` status to `/predicotrs/custom` endpoint.

Trained status

---

mindsdb/__about__.py
requirements.txt

Release 2.8.1

---

mindsdb/__main__.py

Error message if no api config part

---

mindsdb/__about__.py
mindsdb/__main__.py

Fixes:
- Error will be shown if 'api' part missing in config

Release v2.8.2

---

mindsdb/__about__.py
mindsdb/__main__.py
tests/integration_tests/flows/common.py
tests/integration_tests/flows/test_mongo.py

Release 2.8.3

---

mindsdb/api/mongo/op_msg_responders/__init__.py
mindsdb/api/mongo/op_msg_responders/add_shard.py
mindsdb/api/mongo/op_msg_responders/is_master.py
mindsdb/api/mongo/op_msg_responders/is_master_lower.py
mindsdb/api/mongo/op_msg_responders/recv_chunk_start.py
mindsdb/api/mongo/op_msg_responders/update_range_deletions.py
mindsdb/api/mongo/op_query_responders/is_master.py

It should make possible connect to MongoDB v4.4.

fixes for mongo 4.4

---

mindsdb/__about__.py

Release v2.9.0 (version bump)

---

.github/workflows/mindsdb.yml
requirements.txt

Features:
- using relative path in `config['storage_dir']`
Fixes:
- additional checks for config migration 1.1->1.2.

Release v2.9.1

---

mindsdb/__main__.py

fix for `AccessDenied` error at start

hotfix for OSX

---

mindsdb/__about__.py

Fixes:
- fix for `AccessDenied` error at OSX

Release 2.10.1

---

mindsdb/__about__.py
mindsdb/api/http/initialize.py

Fixes:
- Scout address will be in terminal output at any logging level.

Release 2.10.2

---

mindsdb/__main__.py
mindsdb/utilities/ps.py
requirements.txt

At this moment 'api started' msg shows on macos before api actually start.

Fix 'api started' console message for macos

---

.gitignore
mindsdb/__main__.py

Fixes #742 
- Added version check using **sys.version_info** for both **major** and **minor** version of **python**.
- Added **venv** folder in **.gitignore** for **virtualenv**

Added check if python version < 3.6 on server start

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/controllers/session_controller.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/command_packet.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

Fix for 'use database' query in mysql console client. It sends as COM_INIT_DB command

fix 'use database' query

---

.github/workflows/mindsdb.yml
mindsdb/api/http/namespaces/datasource.py
mindsdb/interfaces/datastore/datastore.py

Added support for snowflake integration datasource-side.

Let it snowflake

---

.github/workflows/mindsdb.yml
distributions/windows/build_installer.py
distributions/windows/install.py
distributions/windows/make.bat

- Change default installation dir of windows installer to `C:/Program Files`
- Installer now creates a shortcut on desktop
- Build and deploy windows installer with github actions

Improve and deploy windows installer

---

.gitignore
conda.recipe/bld.bat
conda.recipe/build.sh
conda.recipe/meta.yaml
toconda.sh

Fixes #
On the basis of issue #776 
I am trying to build the conda package
Might need a new set of eyes for the yaml file
Please provide stern review on the code
mindsdb

Added conda.recipe

---

.github/workflows/mindsdb.yml
mindsdb/__init__.py
mindsdb/__main__.py
mindsdb/api/mongo/op_msg_responders/find.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/integrations/clickhouse/clickhouse.py
mindsdb/integrations/mariadb/mariadb.py
mindsdb/integrations/mysql/mysql.py
mindsdb/integrations/postgres/postgres.py
mindsdb/interfaces/custom/custom_models.py
mindsdb/utilities/config.py
mindsdb/utilities/fs.py
tests/integration_tests/flows/test_postgres.py

Getting list of columns from new `model['data_analysis_v2']['columns']` where it needed.
Move all predictors trained before to `{storage_dir}/obsolete/predictors` folder.

'columns' field in model

---

mindsdb/api/http/initialize.py

1. if current MindsDB version not in compatible.json, then closest gui version from compatible.json will be downloaded.
2. `js` and `css` archives can store files in root or in `build/static/js`

Improves for static downloading

---

mindsdb/__about__.py
mindsdb/__main__.py
mindsdb/api/http/initialize.py

Fixes:
- Change Scout url opened by browser

Release 2.11.1

---

mindsdb/__about__.py
mindsdb/api/http/initialize.py

Fixes:
- cnahged gui paths for js and css

Release 2.11.2

---

mindsdb/api/http/namespaces/util.py

Fixes #811
- Added endpoint for mindsdb version in [Utils](https://github.com/yash2189/mindsdb/blob/add-endpoint/mindsdb/api/http/namespaces/util.py)
mindsdb

Added endpoint for mindsdb version

---

.github/workflows/mindsdb.yml

- compile windows installer (via pyinstaller) on windows so it produces a windows executable

fix windows installer

---

README.md

Fixes #822 
- Fixed the Explainability GUI Link in `README.md`
mindsdb

Changed the documentation link to point to docs 

---

README.md

Update Documentation URL

---

distributions/linux/install.sh

- Don't create daemon process for now (throws error)
- Fix `FileNotFoundError`

Linux installer fix

---

mindsdb/__main__.py
mindsdb/interfaces/database/database.py
mindsdb/utilities/fs.py
mindsdb/utilities/log.py

- fixed: mindsdb starting fail if two integrations to one db exists
- fixed: mindsdb starting fail if one of predictors corrupted
- added logger for main process

Fix issues with predictors loading

---

mindsdb/interfaces/datastore/datastore.py

Fixed delete so that it works for malformed datasources.

Fixed delete

---

mindsdb/interfaces/datastore/datastore.py

Add check column names for unique in DS

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
requirements.txt

https://github.com/mindsdb/mindsdb/issues/862
requires native release 2.18.0 (https://github.com/mindsdb/mindsdb_native/pull/250)

use numpy json encoder

---

mindsdb/utilities/fs.py

fix 'posix path' error

---

mindsdb/utilities/functions.py

small fix to dt types, to show it correct in mysql api

fix datetime types cast

---

mindsdb/__main__.py
mindsdb/api/http/namespaces/config.py
mindsdb/utilities/functions.py

Run integrations setup on config change.
Close https://github.com/mindsdb/mindsdb_gui_web/issues/269

Setup integration on config change

---

mindsdb/__init__.py
mindsdb/utilities/functions.py

`import mindsdb` now work from notebooks

---

mindsdb/interfaces/datastore/sqlite_helpers.py
tests/integration_tests/flows/test_clickhouse.py

Fixes #911
If one of ds column have not any value, then error appear on upload.

Fix upload DS with null column

---

mindsdb/api/mongo/op_msg_responders/find.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py

since we want remove move['data_source'] from mindsdb_native, we need remove it from mindsdb too.
https://github.com/mindsdb/mindsdb_native/pull/295

remove model['data_source']

---

tests/integration_tests/api/test_http.py

I hope GUI downloading will be async soon, so i put test to the end and set timeout.

Check GUI is served

---

mindsdb/api/http/initialize.py
mindsdb/api/http/start.py

Async download Scout on start

---

.github/workflows/mindsdb.yml
.github/workflows/release.yml
distributions/docker/Dockerfile
distributions/docker/Usage.md
distributions/docker/builder_docker.py
distributions/linux/install.sh
distributions/linux/rename_installers.py
distributions/linux/snapcraft.yaml
distributions/osx/rename_installers.py

* More polish added to snapcraft, doesn't work due to torch install fail
* Added versioning inside and to the filenames of the installer for linux and osx
* Added versioning inside the docker installer
* Added venv creation inside the linux and OSX installers

Installer improvements

---

.github/workflows/mindsdb.yml
tests/integration_tests/flows/common.py
tests/integration_tests/flows/http_test_helpers.py
tests/integration_tests/flows/test_user_flow_1.py
tests/integration_tests/flows/test_user_flow_2.py

'User flow' tests

---

mindsdb/__main__.py
mindsdb/api/http/namespaces/config.py
mindsdb/api/http/namespaces/predictor.py
mindsdb/interfaces/database/database.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/interfaces/native/mindsdb.py
mindsdb/utilities/config.py
mindsdb/utilities/wizards.py
tests/integration_tests/api/test_http.py
tests/integration_tests/flows/common.py
tests/integration_tests/flows/config/config.json
tests/integration_tests/flows/test_clickhouse.py
tests/integration_tests/flows/test_custom_model.py
tests/integration_tests/flows/test_mariadb.py
tests/integration_tests/flows/test_mistakes.py
tests/integration_tests/flows/test_mongo.py
tests/integration_tests/flows/test_mssql.py
tests/integration_tests/flows/test_mysql.py
tests/integration_tests/flows/test_postgres.py
tests/integration_tests/flows/test_user_flow_1.py
tests/integration_tests/flows/test_user_flow_2.py

Only merge after #969
Solves #796

Renamed enabled to publish

---

mindsdb/api/http/namespaces/config.py
mindsdb/interfaces/database/database.py
mindsdb/utilities/wizards.py
tests/integration_tests/api/test_http.py
tests/integration_tests/flows/common.py
tests/integration_tests/flows/config/config.json
tests/integration_tests/flows/test_clickhouse.py
tests/integration_tests/flows/test_custom_model.py
tests/integration_tests/flows/test_mariadb.py
tests/integration_tests/flows/test_mistakes.py
tests/integration_tests/flows/test_mongo.py
tests/integration_tests/flows/test_mssql.py
tests/integration_tests/flows/test_mysql.py
tests/integration_tests/flows/test_postgres.py
tests/integration_tests/flows/test_user_flow_1.py
tests/integration_tests/flows/test_user_flow_2.py

Refactor analysis

---

mindsdb/api/http/namespaces/config.py

Close #930
That need to checking connection to DB on 'Connect to Database' screen in GUI.

Checking connection to DB without creating integration.

---

tests/integration_tests/flows/common.py

Close #952
Recently i removed thousands of databases from test servers. That should prevent this in future.

Change test db name from 'mindsdb_{timestamp}' to 'mindsdb_{port}'

---

.github/workflows/mindsdb.yml
mindsdb/utilities/ps.py
tests/integration_tests/api/test_http.py
tests/integration_tests/flows/common.py
tests/integration_tests/flows/test_mistakes.py

Patrly fixed #967 
**What**
- psutil.net_connections requires privileged (sudo) mode in macOS
**How**
- Provide cross-platform net_connections functions, based on psutil features which works without sudo

Run tests on macOS

---

mindsdb/api/http/namespaces/datasource.py

**why**
to create mongodb-ds need 'find' instead 'query'

fix mongo ds creation through http

---

mindsdb/integrations/mongodb/mongodb.py
mindsdb/interfaces/database/database.py

**why**
Checking connection to mongodb in GUI always return false.
**how**
Add new class 'mongodb integration' with method 'check_connection'. All other methods is empty, but that should not be problem.

Check connection for mongo integration

---

mindsdb/interfaces/datastore/datastore.py

**why**
We have error in GUI in data preview: if data have 'NaN', then it can be serialized to json on backend, but cant be deserialized on frontend, because flask dumps 'NaN' as is.
**how**
replace NaN to None as described here:
https://stackoverflow.com/a/34467382

Change nan in data to null

---

mindsdb/interfaces/native/mindsdb.py

Now registering newely imported models

Better model importing

---

mindsdb/__main__.py
mindsdb/api/http/initialize.py
mindsdb/api/mongo/server.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/datasource_datanode.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/interfaces/custom/custom_models.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/interfaces/native/native.py
mindsdb/utilities/fs.py
mindsdb/utilities/functions.py
tests/integration_tests/flows/common.py

* Solve #1052 
* Also renamed `MindsdbInterface` to `NativeInterface` which makes much more sense

Change default config dir

---

mindsdb/api/http/namespaces/config.py

**why**
'check connection' was broken on one of last updates
**how**
fix it

fix check db connection for gui

---

.github/workflows/mindsdb.yml
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/integrations/mssql/mssql.py
requirements.txt
tests/integration_tests/flows/common.py
tests/integration_tests/flows/test_mssql.py

**why**
there was no test for mssql in flow.
**how**
added test for mssql.
fixed bug with mssql: it keep connection for a long time, and after some time mssql can send commant to change database to 'null'

mssql integration tests

---

mindsdb/api/mongo/responders/insert.py
mindsdb/interfaces/datastore/datastore.py
tests/integration_tests/flows/test_clickhouse.py

**why**
We need ability to train predictors through mongo api using any integration as source of data
**how**

choose connection in mongo insert

---

mindsdb/__about__.py
requirements.txt

Only change from 2.19.5 is new native dependency.

Release 2.20.0

---

mindsdb/api/mongo/responders/find.py

**why**
It was not able to make bunch prediction at mongo api.
**how**
Predict using existing datasource:
`db.predictor.find({external_datasource: 'datasource_name'})`
Predict using select_data_query:
`db.predictor.find({connection: 'conn_name', select_data_query: {'database': 'database_name', 'collection': 'collection_name', 'find': {}}})`

Bunch prediction for mongo api

---

mindsdb/api/http/namespaces/config.py

Allow for an already existing integration to be tested with new parameters (to check whether a modification would break the connection)

Test-mode works for existing integrations

---

requirements.txt

ability to use tls and srv in mongo connection string

---

mindsdb/__init__.py
mindsdb/__main__.py
mindsdb/api/http/initialize.py
mindsdb/api/mongo/utilities/log.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_datum.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/binary_resultset_row_package.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/column_count_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/column_definition_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/eof_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/err_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/handshake_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/ok_packet.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/resultset_row_package.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/switch_auth_packet.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/api/mysql/mysql_proxy/utilities/log.py
mindsdb/utilities/fs.py
mindsdb/utilities/log.py

**why**
to reduce messages count
**how**

change logging levels

---

mindsdb/__init__.py
mindsdb/interfaces/storage/db.py

switched to connection string

---

mindsdb/__about__.py
mindsdb/__init__.py
mindsdb/api/http/initialize.py
mindsdb/interfaces/storage/db.py
mindsdb/utilities/config.py

Compiling various bugs found today here, will release by EOD

Release 2.21.3

---

mindsdb/api/mongo/classes/scram.py
mindsdb/api/mongo/classes/session.py
mindsdb/api/mongo/responders/sasl_continue.py
mindsdb/api/mongo/responders/sasl_start.py

**why**
To validate password on client and server
**how**

checking mongo password

---

mindsdb/api/http/namespaces/util.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/interfaces/native/learn_process.py
mindsdb/interfaces/native/native.py
requirements.txt

**why**
To resolve https://github.com/mindsdb/mindsdb/issues/1121
**how**
By set title for native process, and check that title at route handler.

Route to check native process exists

---

mindsdb/utilities/log.py

Naitve&Lightwood log captrue

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

**why**
hardcoded answer for `select connection_id()
**how**

sql answer for `select connection_id()`

---

mindsdb/utilities/log.py

**why**
Tests was failing, because logging worked too slow.
**how**

Fix logging to fix tests

---

mindsdb/api/http/initialize.py
mindsdb/api/http/start.py

**why**
to fix sqlalchemy errorrs

Close db session for init static threads

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py

**why**
looker query this field when try get tables list
**how**

'table_rows' field for table info

---

mindsdb/api/http/namespaces/entitites/predictor_status.py
mindsdb/api/http/namespaces/predictor.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/interfaces/model/model_controller.py
mindsdb/interfaces/storage/db.py

Added model updating capabilites

---

mindsdb/api/http/start.py
requirements.txt

**why**
to reduce page load time
**how**

Compression for http responses

---

mindsdb/__main__.py
mindsdb/api/http/namespaces/config.py
mindsdb/api/http/namespaces/predictor.py
mindsdb/api/http/namespaces/util.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/interfaces/model/learn_process.py
mindsdb/interfaces/model/model_controller.py
mindsdb/interfaces/model/model_interface.py
mindsdb/utilities/fs.py
mindsdb/utilities/functions.py
requirements.txt
tests/integration_tests/flows/common.py

**why**
to check is any learn process exists
**how**
Detecting learn process if ray in use is little bit tricky then without it. Ray setting his own process names, so using 'setproctitle' to mark learn processes is impossible. Best what i can found is creating temp files for all learn time.

Detecting learn processes

---

mindsdb/api/http/initialize.py

**why**
to close #1190
**how**

Format date types for flask responses

---

mindsdb/api/http/initialize.py
mindsdb/api/http/start.py

**why**
it was some issues with GUI opening if 'storage_dir' is relative
**how**
move all static_paths to absolute

fix static paths

---

mindsdb/api/http/namespaces/stream.py
mindsdb/integrations/base/__init__.py
mindsdb/integrations/base/integration.py
mindsdb/integrations/kafka/kafkadb.py
mindsdb/integrations/redis/redisdb.py
mindsdb/interfaces/database/database.py
mindsdb/interfaces/storage/db.py
mindsdb/streams/kafka/kafka_stream.py
mindsdb/streams/redis/redis_stream.py
requirements.txt

Support Kafka streams at it was done for Redis

Support Kafka streams

---

mindsdb/integrations/redis/redisdb.py
mindsdb/streams/kafka/kafka_stream.py
mindsdb/streams/redis/redis_stream.py

Caching historical data for streams

---

mindsdb/api/http/namespaces/config.py
mindsdb/api/http/utils.py

Improve dependencies installation

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

**why**
to fix connection with last mariadb shell
Fixes #1208

Fix mariadb shell connection

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py

**why**
xmlrpc can not transfer complex types, like pandas timestamp

Fix xmlrpc timestamp conversion

---

mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

**why**
* improve 'create predictor' sql 
* added processing for queries `show tables from` and `show tables`

Improve create predictor sql

---

mindsdb/api/http/start.py
mindsdb/api/mongo/responders/__init__.py
mindsdb/api/mongo/responders/company_id.py
mindsdb/api/mongo/server.py

**why**
prepare for catching company_id at http and mongo api

Catch company id from cloud

---

mindsdb/api/mysql/mysql_proxy/controllers/session_controller.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

**why**
catch company_id at mysql api

Catch company_id from cloud at mysql api

---

.github/workflows/matrix_includes.json
.github/workflows/mindsdb.yml

Update actions flow:
1. Use ubuntu with Ray for a push on branches and staging
2.  Use other os and 3.7, 3.8 pythons on merge to stable
>NOTE: Everything could be configured inside matrix_include.json if we want to include additional scenarios.

GH actions load configuration matrix

---

mindsdb/api/http/namespaces/stream.py
mindsdb/integrations/base/integration.py
mindsdb/integrations/kafka/kafkadb.py
mindsdb/integrations/redis/redisdb.py
mindsdb/interfaces/storage/db.py
mindsdb/streams/base/base_stream.py
mindsdb/streams/kafka/kafka_stream.py
mindsdb/streams/redis/redis_stream.py

Getting TS parameters from predictor db record instead of providing it via API

Get TS settings from predictor

---

mindsdb/api/mongo/responders/company_id.py
mindsdb/api/mongo/responders/insert.py
tests/integration_tests/flows/test_company_independent.py

Company independent test

---

mindsdb/__about__.py
requirements.txt

Release 2.30.1

---

mindsdb/__main__.py
mindsdb/api/http/namespaces/stream.py
mindsdb/integrations/kafka/kafkadb.py
mindsdb/integrations/redis/redisdb.py
mindsdb/streams/kafka/kafka_stream.py

Changes in db changes, integrations launch (setup) weren't implemented for Stream Integration and Stream API

Fix broken stream integration

---

mindsdb/api/http/namespaces/predictor.py
mindsdb/interfaces/model/model_controller.py

Added check for existing before inserting predictor record

Fix multiple model creation

---

.github/workflows/mindsdb.yml
tests/integration_tests/flows/common.py
tests/integration_tests/flows/test_redis.py

redis stream/integration tests

---

mindsdb/api/mongo/server.py
mindsdb/integrations/__init__.py
mindsdb/integrations/cassandra/cassandra.py
mindsdb/integrations/scylladb/scylladb.py

Close https://github.com/mindsdb/mindsdb/issues/1270

scylla and cassandra connection checkers

---

mindsdb/streams/base/base_stream.py
mindsdb/streams/kafka/kafka_stream.py
mindsdb/streams/redis/redis_stream.py
mindsdb/utilities/cache.py
mindsdb/utilities/config.py

Cache for timeseries streams based on python shelve.

Shelve-based cache

---

.github/workflows/mindsdb.yml
mindsdb/utilities/cache.py
mindsdb/utilities/config.py

Redis based cache. In general it has same API as built-in dict

Redis based cache

---

mindsdb/__about__.py
mindsdb/api/http/namespaces/predictor.py
mindsdb/interfaces/model/learn_process.py
mindsdb/interfaces/model/model_controller.py
mindsdb/interfaces/model/model_interface.py
requirements.txt

Remove ray actor and replace with the library interface

Realease 2.37.0

---

mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py

allow not use spacebar after 'insert' in sql statement

---

mindsdb/api/http/namespaces/predictor.py

Make 'when' arg mandatory for prediction.

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

fixed bug when request contains 'limit x, y'
added answer for 'show variables' query

MySQL api bugfixes

---

mindsdb/api/http/start.py

changes in configs of gunicorn and waitress

Web servers config changes

---

mindsdb/__main__.py

Fixes #1293
- Add checking that integration is `publish`
- Add checking that integration from config doesn't conflict with existing integration in db

Mess in integrations setup

---

.github/workflows/matrix_includes.json
mindsdb/__about__.py
requirements.txt

Release 2.41.2

---

mindsdb/api/http/namespaces/datasource.py

Fixes #1326
**why**
we have issue with uploading big files with waitress server
**how**
Usually file ds can reduce size significantly if archive it. So waitress will consume less memory.

Allow upload archived file as ds

---

mindsdb/interfaces/datastore/datastore.py
requirements.txt

Avoid fetching ds at creation

---

mindsdb/__about__.py
requirements.txt

Make the snowflake datasource default

Snowflake default

---

mindsdb/integrations/__init__.py

added the actual snowflake integration

---

mindsdb/api/http/namespaces/config.py
mindsdb/interfaces/model/learn_process.py
mindsdb/interfaces/model/model_controller.py

Fixes to get the mindsdb version that uses the lightwood refactor to work properly on cloud

Cloud-related fixes

---

.github/workflows/mindsdb.yml
mindsdb/__about__.py
tests/integration_tests/flows/common.py

Release 2.51.1

---

mindsdb/api/http/namespaces/predictor.py

Fix TS prediction via http api

---

mindsdb/api/http/namespaces/stream.py
mindsdb/interfaces/storage/db.py
tests/integration_tests/flows/test_redis.py

Stream HTTP API cloud compatibility

---

mindsdb/__about__.py
mindsdb/__main__.py
mindsdb/api/http/namespaces/predictor.py
mindsdb/api/http/namespaces/stream.py
mindsdb/integrations/mongodb/mongodb.py
mindsdb/interfaces/storage/db.py
tests/integration_tests/flows/common.py
tests/integration_tests/flows/test_redis.py

Fixed bug with checking connection to MongoDB.

Release 2.51.2

---

mindsdb/integrations/base/integration.py
mindsdb/interfaces/storage/db.py

Fixes #1441
- Add relationship to Integration and Predictor tables

Cascade delete for streams

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/interfaces/database/integrations.py

Fix getting integration name

---

mindsdb/api/http/namespaces/util.py
mindsdb/interfaces/model/learn_process.py
mindsdb/interfaces/model/model_controller.py
mindsdb/utilities/fs.py
mindsdb/utilities/functions.py
tests/integration_tests/flows/test_clickhouse.py

Removing process mark on exception

---

mindsdb/api/http/initialize.py
mindsdb/interfaces/datastore/datastore.py
mindsdb/streams/kafka/kafka_stream.py
mindsdb/streams/redis/redis_stream.py
mindsdb/utilities/json_encoder.py
requirements.txt
tests/integration_tests/flows/test_user_flow_1.py

Dump analysis using custom json encoder

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/integrations/base/integration.py
mindsdb/interfaces/datastore/datastore.py

create ds on predictor creation

---

mindsdb/__main__.py
mindsdb/interfaces/model/model_controller.py
mindsdb/utilities/functions.py

Do it only if run locally, at cloud check will be at valet

Checking that predictors need to be updated

---

mindsdb/interfaces/datastore/datastore.py

Remove related semaphores when removing ds

---

mindsdb/interfaces/model/model_controller.py

convert ignore_columns to ignore_features

---

docs/mindsdb-docs/mkdocs.yml

Fixes #1725
- Renamed nav name in docs .
mindsdb

Nav update in docs

---

docs/mindsdb-docs/docs/sql/tutorials/mindsdb-superset-snowflake.md

Fixes #1739
**- Improve many sql code block And Fixed On link typo**
mindsdb

Improved Code Block And one typo

---

docs/mindsdb-docs/docs/sql/tutorials/mindsdb-superset-snowflake.md

Fixes #1737
- Updated the links
mindsdb

Updated links for deployment

---

.github/workflows/mindsdb.yml
.github/workflows/release.yml

Clarifies https://github.com/mindsdb/mindsdb/actions contents.

Rename actions workflows

---

setup.py

Currently following the instructions for installation from source would fail with the following error:
```
error in MindsDB setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'+https:/'": Expected stringEnd
```
The proposed change looks at requirements.txt and if it finds 'git+https' it will add that to dependecy_links see https://github.com/pypa/pip/issues/3610

Correct to allow for github urls in requirements.txt

---

docs/mindsdb-docs/docs/connect.md

Fixes #1769
- remove the table along with the tip

Solves #1769

---

docs/mindsdb-docs/mkdocs.yml

Fixes #1770
- rename navigation menu in docs

Solves #1770

---

mindsdb/interfaces/model/model_controller.py

Remove predictor from cache is it was updated

Fix predictor cache issue

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

- Added error wrapping to MySQL proxy, that improves the information displayed to the user.

chore: added error wrapping

---

docs/mindsdb-docs/docs/sql/api/select.md

Fixes Issue #1792 
I changed the first Select statement so it doesn't use when_data and removed its mention in the column names. I also fixed the image paths for the pictures in the file.

Fixes image paths and Select statement without when_data

---

mindsdb/integrations/postgres/postgres.py
requirements.txt

Fix cocroachdb connection

---

docs/mindsdb-docs/docs/sql/tutorials/customer-churn.md

Fixes #1802
- Just added link to customer-churn dataset in its tutorial 
mindsdb

Added Customer chur data set link

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datahub.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/file_datanode.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/api/mysql/mysql_proxy/utilities/sql.py
mindsdb/utilities/wizards.py
requirements.txt

Files list not in 'file' database.

Selecting from files

---

mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py

Allow quotation marks in 'create predictor'

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/utilities/sql.py
tests/integration_tests/flows/test_mysql_api.py

Complex column ids in planner/executioner

Complex column ids

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/interfaces/model/model_controller.py

* fix for join step (wrong left-right sides)
* return back 'union' step
* fix for unwrapping of ts predictions

Fix for 'join' step

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
tests/integration_tests/flows/test_mysql_api.py

Processing for query `show datasources`

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datahub.py
mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
tests/integration_tests/flows/test_mysql_api.py

Refresh datasources list on each 'show datasources' query

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py

Fix for `nr_predictions == 1`

---

mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
requirements.txt

should work after https://github.com/mindsdb/mindsdb_sql/issues/144

'show engines' using information_schema

---

mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
mindsdb/api/mysql/mysql_proxy/data_types/mysql_packets/command_packet.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

replace internal parser for 'insert' to mindsdb_sql
NOTE: require upcoming mindsb_sql version

Parse 'insert' statement using mindsdb_sql

---

.github/workflows/docker.yml
docker/build.py

This PR includes GitHub Action for deploying the latest mindsdb image to Dockerhub.

Docker GH Action

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

fix selecting from files

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

SQL API: unexpected rows in TS results

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py

MySqlApi: ts prediciton error if nr_predicitons==1

---

mindsdb/__main__.py
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

1. run migrations only locally
2. temporary hide removing of unexpected rows with ts predictions

Release fixes

---

mindsdb/api/mysql/mysql_proxy/utilities/sql.py
requirements.txt

Converting query to string using new mindsdb_sql feature

---

.github/workflows/release.yml

too often we get error related to shared resources

ban parallel building

---

mindsdb/__about__.py
setup.py

Fixes #
- "No module named '__init__'"

Release 2.62.4

---

docs/mindsdb-docs/docs/model/mongodb.md
docs/mindsdb-docs/docs/model/timeseries.md
docs/mindsdb-docs/docs/tutorials/Timeseries.md
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
tests/integration_tests/flows/test_kafka.py
tests/integration_tests/flows/test_redis.py

rename `nr_predictions` to `horizon`

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

Add processing for LimitOffsetStep sql planner step

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
requirements.txt

Change sql planner var naming from $var[index] to $var[var_alias]

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py
tests/integration_tests/flows/test_http.py

Render for postgres and snowflake dialects

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

fix prediction for multiple groups

---

docs/mindsdb-docs/docs/sql/api/predictor.md

Fixes #1919
- Use the correct syntax for the `USING` keyword in the examples

[#1919] Update USING documentation

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py

fix direct datasource quering

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

fix for `select null`

---

README.md

- #1635 changed the issue template from markdown to yaml, this PR fixes the relevant link in the repositories README that I found

fix link to feature request in readme

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/information_schema.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/api/mysql/mysql_proxy/utilities/sql.py
requirements.txt

Should close #1946 
- added virtual `CHARACTER_SETS` and `COLLATIONS` tables
- refactored other `show` queries

Refactoring of 'show' statements

---

mindsdb/integrations/clickhouse/clickhouse.py
mindsdb/integrations/mariadb/mariadb.py
mindsdb/integrations/mysql/mysql.py
mindsdb/integrations/postgres/postgres.py

fix dtypes casting

---

docs/mindsdb-docs/docs/sql/api/view.md

Introduce a docs page for `CREATE VIEW` / AI Tables.

Docs: edit create view page

---

mindsdb/__about__.py
requirements.txt

Release 22.2.2.1

---

mindsdb/api/mysql/mysql_proxy/utilities/sql.py

Fix NaN->None casting

---

docs/mindsdb-docs/docs/sql/tutorials/bodyfat.md
docs/mindsdb-docs/docs/sql/tutorials/insurance-cost-prediction.md
docs/mindsdb-docs/docs/sql/tutorials/process-quality.md

Use relative link paths, fix 'sed' command

fix tutorials docs

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
tests/integration_tests/flows/test_mysql_api.py

Fixes [#27](https://github.com/mindsdb/gh-issues-private/issues/27)

Show ensemble type in 'DESCRIBE' + tests

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

fix for
show charset
show variable

fix show statement

---

mindsdb/__about__.py

- fixed issues with 'show charset' and 'show variable'

Release 22.2.4.1

---

mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py

This PR, adds BEGIN keyword to SQL statement parser. The other required changes are already implemented in mindsdb_sql

Accept begin keyword

---

docs/mindsdb-docs/docs/deployment/Getting Started with MindsDB on Digital Ocean.md

Fixes #1928
- A new tutorial has been published on how to deploy MindsDB on a Digital Ocean Droplet.
- The article has been published already on Dev.to and can be found [here](https://dev.to/heyrutam/deploying-mindsdb-on-a-digital-ocean-droplet-31ed).
- This PR adds a reference copy in the MindsDB documentation as well.

Created Getting Started with MindsDB on Digital Ocean.md

---

docs/README_HIN.md

Created README_HIN.md

---

mindsdb/interfaces/model/model_controller.py

Found a missed datasource_id -> dataset_id rename

---

mindsdb/interfaces/model/learn_process.py
mindsdb/interfaces/model/model_controller.py

- BYOM status is now updated more appropriately to what its real status (training, error or complete)
- BYOM error message should now always be part of the predictor
- Remove some redundant status-computing logic from the model controller

BYOM better status updates

---

mindsdb/api/http/namespaces/datasource.py

Fixes #
- https://docs.mindsdb.com/

Get Data from query

---

mindsdb/__about__.py

Bump version to v22.3.4.2

---

docs/mindsdb-docs/docs/stylesheets/extra.css

This PR updates the primary color of docs.

Update primary color of docs

---

docs/mindsdb-docs/docs/index.md

Link CREATE statements in quickstart to docs

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/mindsdb_datanode.py

Fixes #
- Fixed minor typo raised in issue [Issue 2104](https://github.com/mindsdb/mindsdb/issues/2104)
mindsdb

Fixed minor typo of Predictor

---

docs/mindsdb-docs/docs/sql/api/databases.md
mindsdb/interfaces/datastore/datastore.py

Add support for `CREATE DATASOURCE engine='questdb'` , include example in docs.

Add QuestDB

---

mindsdb/__about__.py
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

Release 22.4.2.1

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

Fix 'show' statements for 'information schema'

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

Better error messaging for mysql api

---

docs/mindsdb-docs/docs/sql/tutorials/spam_emails_tutorial.md

Fixes #
- Added tutorial document for building and training a classification model using Mindsdb Cloud. 
- Model predicts whether a given email is spam mail.
[spam_emails_tutorial.md](https://github.com/mindsdb/mindsdb/files/8499268/spam_emails_tutorial.md)
mindsdb

Adding Spam email tutorial doc

---

tests/integration_tests/flows/test_mysql_api.py

Add test of selecting from files

---

mindsdb/api/mysql/mysql_proxy/mysql_proxy.py

del direct queries to db

---

tests/integration_tests/flows/test_mysql_api.py

Add learning and use test for timeseries predictors

---

mindsdb/integrations/postgres_handler/tests/test_postgres_handler.py
mindsdb/integrations/questdb_handler/__about__.py
mindsdb/integrations/questdb_handler/questdb_handler.py
mindsdb/integrations/questdb_handler/tests/test_questdb_handler.py

This PR:
- Adds new QuestDB handler
- Fix tests for PostgreSQL handler

Add QuestDB handler

---

mindsdb/integrations/mssql_handler/__about__.py
mindsdb/integrations/mssql_handler/mssql_handler.py
mindsdb/integrations/mssql_handler/tests/test_mssql_handler.py
mindsdb/integrations/mysql_handler/tests/test_mysql_handler.py
mindsdb/integrations/postgres_handler/postgres_handler.py
mindsdb/integrations/postgres_handler/tests/test_postgres_handler.py
mindsdb/integrations/questdb_handler/questdb_handler.py

This PR:
- Adds a handler and tests for Microsoft SQL Server

Add Microsoft SQL Server handler

---

docs/mindsdb-docs/docs/mongo/mongo.md
docs/mindsdb-docs/docs/sql/connect/dbt.md
docs/mindsdb-docs/docs/sql/connect/deepnote.md
docs/mindsdb-docs/docs/sql/connect/kafka.md
docs/mindsdb-docs/docs/sql/connect/sql-alchemy.md
docs/mindsdb-docs/docs/sql/connect/tableau.md
docs/mindsdb-docs/docs/sql/tutorials/huggingface.md
docs/mindsdb-docs/docs/sql/tutorials/mlflow.md
docs/mindsdb-docs/docs/sql/tutorials/openai.md
docs/mindsdb-docs/docs/sql/tutorials/ray-serve.md
docs/mindsdb-docs/mkdocs.yml

updates on docs
still some missing parts
Fixes #
-
mindsdb

updates on docs

---

docs/mindsdb-docs/docs/sql/api/databases.md
docs/mindsdb-docs/docs/sql/connect/deepnote.md
docs/mindsdb-docs/docs/sql/connect/kafka.md
docs/mindsdb-docs/docs/sql/connect/sql-alchemy.md
docs/mindsdb-docs/docs/sql/connect/tableau.md
docs/mindsdb-docs/docs/sql/tutorials/bodyfat.md

Minor updates to the new Docs WIP pages.

Docs update

---

docs/mindsdb-docs/docs/deployment/macos.md

UI changes on Deploy using pip on MacOs
-
mindsdb

Changes on MacOs Docs

---

docs/mindsdb-docs/mkdocs.yml

Add detecting email spam tutorial to the docs navigation.

Add email spam tutorial

---

mindsdb/__about__.py
requirements.txt

bump-lightwood-to-22.5.1.0

---

docs/mindsdb-docs/mkdocs.yml
mindsdb/__about__.py
requirements.txt

Release v22.5.1.2

---

mindsdb/api/mysql/mysql_proxy/utilities/sql.py

Proper columns names for results of internal queries

---

docs/mindsdb-docs/docs/sql/api/insert.md
docs/mindsdb-docs/docs/sql/create/table.md

Fixes on CREATE TABLE and INSERT

---

docs/mindsdb-docs/docs/sql/create/databases.md

@ZoranPandovski   A couple of questions. 
On the examples for questdb and cassandra. The password is: "questdb" and  "cassandra", can those be changed for a random password, or they have to be "password:questdfb" and "password:cassandra"
mindsdb

Changes on CREATE DATABASSES docs.

---

docs/mindsdb-docs/docs/sql/api/describe.md
docs/mindsdb-docs/docs/sql/create/table.md

@torrmal and @ZoranPandovski  You know what to do. 
mindsdb

Changes to the DESCRIBE docs

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
requirements.txt

Changes:
- Added support InsertToTable step
- Removed workaround for tableau
- Support if_exists flag on DropPredictor

Support insert from select

---

docs/mindsdb-docs/docs/index.md

Fixes #
Fix link to CREATE DATABASE statement #2223
mindsdb

updated index.md file

---

docs/mindsdb-docs/docs/index.md

Fixes #2222 #2223 
-
Fixed link to docker docs & Create database

Updated link

---

docs/mindsdb-docs/overrides/partials/header.html

This PR changes the link to the slack community.

Fix Join community lin

---

docs/mindsdb-docs/docs/connect/mindsdb_editor.md

Fixes #
- issue https://github.com/mindsdb/mindsdb/issues/2232
mindsdb

issue https://github.com/mindsdb/mindsdb/issues/22

---

docs/mindsdb-docs/docs/index.md

Fixes #
-
I replaced the old link with a new one that works.
mindsdb

Updated Link for CREATE DATABASE

---

mindsdb/integrations/trino_handler/requirements.txt
mindsdb/integrations/trino_handler/tests/test_trino_config.ini
mindsdb/integrations/trino_handler/tests/test_trino_handler.py
mindsdb/integrations/trino_handler/trino_config.ini
mindsdb/integrations/trino_handler/trino_config_provider.py
mindsdb/integrations/trino_handler/trino_handler.py
requirements.txt

Enhancement
- Added trino handler (using kerberos authentication, trino supports many connection types https://trino.io/docs/current/security/authentication-types.html ) Perhaps we can add connection type as a parameter and then plugin in the specific trino-kerberos connector.
mindsdb

Add trino kerberos connector

---

docs/mindsdb-docs/docs/index.md

Fixed Issue of CREATE PREDICTOR Link

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #2240
Removed duplicate scylladb config entry in docs
-
mindsdb

Removed duplicate scylladb config in docs

---

.github/ISSUE_TEMPLATE/config.yml

This PR adds an option to join slack when creating a new issue

Join slack

---

docs/mindsdb-docs/docs/sql/api/select_files.md
docs/mindsdb-docs/docs/sql/create/predictor.md

Select from files: 
New 'CREATE PREDICTOR from file' Section under 'CREATE PREDICTOR'

SELECT statement from files and added crete prediction from files

---

docs/mindsdb-docs/docs/connect/kafka.md

Signed-off-by: Ryan Russell <ryanrussell@users.noreply.github.com>
Fixes various readability issues in the MindsDB / Kafka docs

Improve MindsDB / Kafka tutorial

---

docs/mindsdb-docs/docs/connect/dbeaver.md
docs/mindsdb-docs/docs/connect/sql-alchemy.md
docs/mindsdb-docs/docs/custom-model/mlflow.md
docs/mindsdb-docs/docs/custom-model/ray-serve.md

Went through:
- DBeaver
- MLFlow
- SQLALchemy
- Ray
Separate commits to make it a little easier to modify if something needs it.

Integration Guide Readability Improvements

---

docs/mindsdb-docs/docs/sql/tutorials/bodyfat.md

Fixes #2292 
- I have Changed path of images in bodyfat Tutorials
mindsdb

Corrected The path of images

---

docs/mindsdb-docs/docs/setup/self-hosted/pip/linux.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/macos.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/source.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/windows.md

Fixed shared typos across `self-hosted` templates and a moderate rewrite on `source` to make it easier to folllow

Improve Self Hosted Docs

---

mindsdb/__about__.py
requirements.txt

Fixed issue with Clickhouse datasource

Release 22.6.2.1

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py
mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py

should be faster in (count of integrations) times

Optimization for 'show tables'

---

docs/mindsdb-docs/docs/sql/api/describe.md
docs/mindsdb-docs/docs/sql/api/drop.md
docs/mindsdb-docs/docs/sql/api/insert.md
docs/mindsdb-docs/docs/sql/create/databases.md
docs/mindsdb-docs/docs/sql/create/predictor.md
docs/mindsdb-docs/docs/sql/create/table.md
docs/mindsdb-docs/docs/sql/table-structure.md
docs/mindsdb-docs/docs/sql/tutorials/bitcoin-forecasting.md

Signed-off-by: Ryan Russell <git@ryanrussell.org>
Improving readability in the SQL docs

docs(SQL): Improve readability

---

mindsdb/integrations/handlers/file_handler/file_handler.py

ignore space in file headers

---

docs/mindsdb-docs/docs/sql/create/predictor.md

remove redundant whitespace

---

.github/workflows/mindsdb.yml

Github Actions should ignore all docs and  markdown files changes

Ignore docs in GitHub Actions

---

mindsdb/integrations/handlers/singlestore_handler/__about__.py
mindsdb/integrations/handlers/singlestore_handler/__init__.py
mindsdb/integrations/handlers/singlestore_handler/requirements.txt
mindsdb/integrations/handlers/singlestore_handler/singlestore_handler.py
mindsdb/integrations/handlers/singlestore_handler/tests/test_singlestore_handler.py

This PR adds initial support for Stingle Store.

Add Single Store

---

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py

Added column Table_type filled with "BASE TABLE" if  'full' is used
`show **full** tables`

Show full tables

---

helm/README.md
helm/mindsdb/templates/ingress.yaml

added needed configs in templates.ingress.yaml to make helm work 

---

mindsdb/api/mongo/classes/query_sql.py
mindsdb/api/mongo/responders/coll_stats.py
mindsdb/api/mongo/responders/find.py
mindsdb/api/mongo/responders/insert.py
mindsdb/api/mongo/responders/list_collections.py
mindsdb/api/mongo/responders/list_databases.py
mindsdb/api/mongo/server.py
mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
mindsdb/integrations/handlers/mongodb_handler/utils/mongodb_ast.py

Changes:
1. Support working with integrations using mongo
2. Describe predictor
3. Fixed error with create predictor from mongo shell

Mongodb handler updates. 8 July

---

mindsdb/integrations/handlers/sqlite_handler/sqlite_handler.py

Made a quick fix to one of the arguments passed into a f string that makes up an error message.

fixed bug in arguments passed to log message

---

mindsdb/integrations/handlers/mariadb_handler/tests/test_mariadb_handler.py
mindsdb/integrations/handlers/mssql_handler/tests/test_mssql_handler.py
mindsdb/integrations/handlers/mysql_handler/tests/test_mysql_handler.py
mindsdb/integrations/handlers/postgres_handler/tests/test_postgres_handler.py
mindsdb/integrations/handlers/questdb_handler/tests/test_questdb_handler.py
mindsdb/integrations/handlers/snowflake_handler/__about__.py
mindsdb/integrations/handlers/snowflake_handler/__init__.py
mindsdb/integrations/handlers/snowflake_handler/requirements.txt
mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
mindsdb/integrations/handlers/snowflake_handler/tests/test_snowflake_handler.py
mindsdb/integrations/handlers/trino_handler/__init__.py
mindsdb/integrations/handlers/trino_handler/tests/test_trino_handler.py

This PR adds initial implementation of Snowflake handler and tests

Snowflake handler

---

MANIFEST.in
mindsdb/__about__.py

Release 22.7.3.1

---

mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py

This PR resolves connection issues with the snowflake handler.

Fix snowflake connection

---

mindsdb/interfaces/model/model_controller.py

Fixes #
- Changed response properties to handlers api.

fix retrain

---

.github/workflows/mindsdb.yml
docker/release
mindsdb/__about__.py
mindsdb/api/http/namespaces/handlers.py
mindsdb/api/http/namespaces/util.py
mindsdb/interfaces/database/integrations.py
mindsdb/interfaces/model/model_controller.py
requirements.txt

- fix for 'RETRAIN' command
- new Lightwood dependency
- fix for handler dependency installation

Release 22.7.3.3

---

mindsdb/interfaces/model/model_controller.py
mindsdb/interfaces/storage/db.py
mindsdb/migrations/versions/2022-07-15_b5b53e0ea7f8_training_data_rows_columns_count.py

Add rows and columns count fields to `predictor` table

---

mindsdb/__about__.py
mindsdb/api/http/namespaces/util.py
mindsdb/interfaces/model/model_controller.py
mindsdb/interfaces/storage/db.py
mindsdb/migrations/versions/2022-07-15_b5b53e0ea7f8_training_data_rows_columns_count.py
mindsdb/utilities/json_encoder.py
requirements.txt

- added `rows count` and `columns count` fields to `predictors` table
- fix for `decimal` json encoder

Release v22.7.3.4

---

docs/mindsdb-docs/docs/sql/create/table.md

 hotfix on CREATE OR REPLACE TABLE

---

mindsdb/integrations/handlers/clickhouse_handler/README.md
mindsdb/integrations/handlers/clickhouse_handler/__about__.py
mindsdb/integrations/handlers/clickhouse_handler/__init__.py
mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py
mindsdb/integrations/handlers/clickhouse_handler/requirements.txt
mindsdb/integrations/handlers/clickhouse_handler/tests/test_clickhouse_handler.py
mindsdb/integrations/handlers/mysql_handler/tests/test_mysql_handler.py

This PR adds initial implementation for the new ClickHouse handler.

Add ClickHouse handler

---

docs/mindsdb-docs/docs/sql/tutorials/customer-churn.md
docs/mindsdb-docs/docs/sql/tutorials/home-rentals.md
docs/mindsdb-docs/docs/sql/tutorials/house-sales-forecasting.md
docs/mindsdb-docs/docs/sql/tutorials/mindsdb-superset-snowflake.md
docs/mindsdb-docs/docs/sql/tutorials/process-quality.md

Fixes: Add closing statement after all tutorials #20->number from a different repo
- added the 'What's Next?' section (marked in red box) at the end of each of the five tutorials (marked in red box)
mindsdb

Completed: Add closing statement after all tutorials #20

---

docs/mindsdb-docs/docs/sql/create/predictor.md

Fixes #21->issue number from a different repository
- added a link
mindsdb

added a link on how to upload a file to the section on creating predictor from file

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/mindsdbs-team-user-request.md

Auto assigning BUGs
Created Team User Request. 
Auto assigning USER REQUESTS

Update issue templates

---

docs/mindsdb-docs/docs/sql/api/select_files.md
docs/mindsdb-docs/docs/sql/create/file.md
docs/mindsdb-docs/mkdocs.yml

Fixes #2497 
- added a new page
- added a link
mindsdb

created a new page for file upload and created a link to it in select from files

---

docs/mindsdb-docs/mkdocs.yml

Fixes #2546 
- moved process quality to community tutorials
mindsdb

moved process quality to community tutorials

---

docs/mindsdb-docs/mkdocs.yml

Fixes #2469 
- updated two section titles
mindsdb

updated titles of two sections (Data Setup in MindsDB and Upload a File to MindsDB)

---

docs/mindsdb-docs/docs/sql/create/file.md

Fixes #2545 
- added a next steps section
mindsdb

added a next steps section to upload a file page

---

mindsdb/integrations/handlers/scylla_handler/README.md
mindsdb/integrations/handlers/scylla_handler/__about__.py
mindsdb/integrations/handlers/scylla_handler/__init__.py
mindsdb/integrations/handlers/scylla_handler/requirements.txt
mindsdb/integrations/handlers/scylla_handler/scylla_handler.py
mindsdb/integrations/handlers/scylla_handler/tests/test_scylla_handler.py

This PR adds the initial version of the ScyllaDB handler.

Add ScyllaDB

---

mindsdb/integrations/handlers/supabase_handler/README.md
mindsdb/integrations/handlers/supabase_handler/__about__.py
mindsdb/integrations/handlers/supabase_handler/__init__.py
mindsdb/integrations/handlers/supabase_handler/icon.svg
mindsdb/integrations/handlers/supabase_handler/requirements.txt
mindsdb/integrations/handlers/supabase_handler/supabase_handler.py
mindsdb/integrations/handlers/supabase_handler/tests/test_supabase_handler.py

This pull request has new handler of supporting Supabase

Supabase integration

---

docs/mindsdb-docs/docs/sql/create/databases.md

Addresses this issue: https://github.com/mindsdb/mindsdb/issues/2300
- With the help of @chandrevdw31, I added the documentation to connect a local database with Ngrok tunneling

Add documentation to connect through ngrok.

---

mindsdb/__main__.py

This PR changes the default import message of missing handlers' dependencies. Solves #2570

Improve handlers import message

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #2620 
- ordered the supported integrations alphabetically
mindsdb

ordered (currently available in docs) supported integrations alphabetically

---

docs/mindsdb-docs/docs/sql/table-structure.md
docs/mindsdb-docs/mkdocs.yml

Fixes #2498 
- moved this page out of _SQL API_ section and modified its header
- created intro section
- created `predictors` table section
- created `databases` table section
- question regarding the `[integration_name]` table section: as I know, integration is an external database connected to MindsDB (in the above screenshot, the `example_db` is an integration), so is this section valid?
- the `model` table section is not completed (is the `model` table a work in progress? because I don't have it in my locally connected MindsDB, nor do I see it in the MindsDB Cloud editor)
mindsdb

Docs issue 2498

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #2621 
- corrected cockroach engine name (now it is 'cockroachdb')
mindsdb

corrected cockroach engine name

---

docs/mindsdb-docs/docs/contribute/integrations.md

Fixes #2627 
- added links to handlers
mindsdb

added links to handlers

---

docs/mindsdb-docs/docs/sql/table-structure.md

Fixes #2626 
- deleted the last two sections from the MindsDB Tables Structure page
mindsdb

deleted the last two sections

---

mindsdb/integrations/handlers/file_handler/file_handler.py
mindsdb/interfaces/file/file_controller.py
requirements.txt

Handler non-utf-8 .CSVs

---

integrations_contest.md

- Changed August to September in Integration Contest in page
mindsdb

Changed August to  September in Integration Contest in Page

---

docs/mindsdb-docs/docs/sql/tutorials/crop-prediction.md

Fixes #2606
- This PR fixes the broken links for MindsDB GUI inside the tutorial.

Updated broken MindsDB Cloud GUI links

---

docs/mindsdb-docs/docs/getting-started.md

Fixes #2607
- This PR fixes a broken asset path and some broken links in the documentation page.

Updated broken asset path and links

---

docs/mindsdb-docs/docs/info.md

Fixes #2608
- This PR fixes a few broken links in the document.

Updated broken links in the document

---

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
mindsdb/integrations/handlers/lightwood_handler/requirements.txt
mindsdb/integrations/handlers/lightwood_handler/setup.py
mindsdb/integrations/handlers/lightwood_handler/tests/test_lightwood_handler.py

Supersedes #2551 
- Fixes couple of things in the handler to fix non-TS tests
- Adds more TS test coverage

[LW Handler] Add more TS tests

---

assets/contributions-agreement/signatures/cla.json
mindsdb/__about__.py

- added dependencies for docker

Release 22.8.2.1

---

docs/mindsdb-docs/docs/connect/dbt.md
docs/mindsdb-docs/docs/contribute/integrations.md
docs/mindsdb-docs/docs/custom-model/huggingface.md
docs/mindsdb-docs/docs/custom-model/mlflow.md
docs/mindsdb-docs/docs/custom-model/openai.md
docs/mindsdb-docs/docs/custom-model/ray-serve.md
docs/mindsdb-docs/docs/index.md
docs/mindsdb-docs/docs/sql/api/describe.md
docs/mindsdb-docs/docs/sql/api/drop.md
docs/mindsdb-docs/docs/sql/api/join.md
docs/mindsdb-docs/docs/sql/api/retrain.md
docs/mindsdb-docs/docs/sql/api/select.md
docs/mindsdb-docs/docs/sql/api/select_files.md
docs/mindsdb-docs/docs/sql/create/databases.md
docs/mindsdb-docs/docs/sql/create/predictor.md
docs/mindsdb-docs/docs/sql/create/table.md
docs/mindsdb-docs/docs/sql/create/view.md
docs/mindsdb-docs/docs/sql/tutorials/bodyfat.md
docs/mindsdb-docs/docs/sql/tutorials/crop-prediction.md
docs/mindsdb-docs/docs/sql/tutorials/customer-churn.md
docs/mindsdb-docs/docs/sql/tutorials/diabetes.md
docs/mindsdb-docs/docs/sql/tutorials/heart-disease.md
docs/mindsdb-docs/docs/sql/tutorials/home-rentals.md
docs/mindsdb-docs/docs/sql/tutorials/house-sales-forecasting.md
docs/mindsdb-docs/docs/sql/tutorials/insurance-cost-prediction.md
docs/mindsdb-docs/docs/sql/tutorials/mushrooms.md
docs/mindsdb-docs/docs/sql/tutorials/process-quality.md
docs/mindsdb-docs/docs/sql/tutorials/spam_emails_tutorial.md
docs/mindsdb-docs/docs/what-is-mindsdb.md

Fixes #2584
- implemented current docs rules throughout the entire MindsDB docs
- each docs page has a separate commit
mindsdb

Docs issue 2584

---

docs/mindsdb-docs/docs/connect/kafka.md

Fixes #2407 
- I have reviewed the Kafka docs page, but I am still about to run some of the codes from the Examples section.
- Please see the updated page here: [Kafka - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9299803/Kafka.-.MindsDB.Documentation.pdf)
mindsdb

Docs issue 2407

---

docs/mindsdb-docs/docs/connect/dbt.md

Fixes #2592 
- updated the links according to https://github.com/mindsdb/mindsdb/issues/2592#issuecomment-1207917072
mindsdb

link updated

---

mindsdb/api/http/namespaces/analysis.py

POST /analysis/data
Request body is JSON:
```
{
"columns_names": ["a", "b"] // list of column names
"data": [[1,2], [3,4]]  // array of rows
}
```
Response is also JSON:
```
{
"analysis": {object},
"timestamp": 12345
}
```

route to analyse data

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #2679
- I changed the CREATE DATABASE query for scylladb so users can connect with Scylla.
mindsdb

Changed Scylladb connection docs

---

docs/mindsdb-docs/docs/connect/sql-alchemy.md

Fixes #2667
- refactored sql alchemy page - [SQL Alchemy - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9353821/SQL.Alchemy.-.MindsDB.Documentation.pdf)
mindsdb

refactored sql alchemy page

---

docs/mindsdb-docs/docs/connect/kafka.md

Fixes #2661
- corrected the info on config file in kafka
mindsdb

corrected the info on config file in kafka

---

README.md

Update the contribution link

---

mindsdb/api/http/namespaces/handlers.py

Route to get handler icon

---

docs/mindsdb-docs/docs/setup/custom-config.md
docs/mindsdb-docs/mkdocs.yml

Fixes #2660
- created a new page, as below
mindsdb

created a page for custom configuration of mindsdb

---

docs/mindsdb-docs/docs/setup/civo.md
docs/mindsdb-docs/docs/setup/digital-ocean.md
docs/mindsdb-docs/docs/setup/gcp.md
docs/mindsdb-docs/docs/setup/vultr.md
docs/mindsdb-docs/mkdocs.yml

* Rename Setup to Deployments
* Add links to tutorials for GCP, Digital Ocean, Civo and Vultr Cloud.
>Note: these tutorials should soon be converted to the above pages.

Deployment docs navigation

---

docs/mindsdb-docs/docs/connect/dbeaver.md

Fixes #2706 
- created tabs
mindsdb

created tabs

---

docs/mindsdb-docs/docs/connect/dbeaver.md
docs/mindsdb-docs/docs/connect/dbt.md
docs/mindsdb-docs/docs/connect/deepnote.md
docs/mindsdb-docs/docs/connect/kafka.md
docs/mindsdb-docs/docs/connect/mindsdb_editor.md
docs/mindsdb-docs/docs/connect/mysql-client.md
docs/mindsdb-docs/docs/connect/sql-alchemy.md
docs/mindsdb-docs/docs/connect/tableau.md

Fixes #2711 
- created a common what's next chapter for all the pages from the connect to mindsdb section
- standardized all the pages from the connect to mindsdb section
mindsdb

added what's next chapter and standardized all the pages from the connect to mindsdb section

---

docs/mindsdb-docs/docs/connect/kafka.md

Fixes #2710
- removed trailing white spaces
mindsdb

removed trailing white spaces

---

docs/mindsdb-docs/docs/index.md

Fixes #2722 
- worked on the quickstart page - [Quickstart - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9374524/Quickstart.-.MindsDB.Documentation.pdf)
mindsdb

worked on the quickstart page

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #2725
- added databases
- please verify if the create database statements are correct
mindsdb

added databases

---

docs/mindsdb-docs/docs/sql/create/databases.md

This PR adds the `CREATE DATABASE statement for Google BigQuery.

Add create database for bigquery

---

docker/release
mindsdb/__about__.py
mindsdb/integrations/handlers/bigquery_handler/requirements.txt

Fix for BigQuery handler dependencies list

Release 22.8.4.1

---

mindsdb/integrations/handlers/scylla_handler/scylla_handler.py

Fixes:
1. Fixed data type serialization error
https://github.com/mindsdb/mindsdb/issues/2697
2. Fixed problem with table aliases: they are removed before send query to astra.
https://github.com/mindsdb/mindsdb/issues/2700

Astra fixes

---

docs/mindsdb-docs/docs/setup/self-hosted/docker.md

Fixes #2766 
- worked on docker page
[Docker - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9418217/Docker.-.MindsDB.Documentation.pdf)
mindsdb

worked on docker page

---

docs/mindsdb-docs/docs/what-is-mindsdb.md

Fixes #2762 
- worked on the what is mindsdb page
[What is MindsDB_ - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9418000/What.is.MindsDB_.-.MindsDB.Documentation.pdf)
mindsdb

worked on the what is mindsdb page

---

docs/mindsdb-docs/docs/setup/self-hosted/pip/windows.md

Fixes #2769 
- worked on windows via pip page
[Windows via pip - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9418450/Windows.via.pip.-.MindsDB.Documentation.pdf)
mindsdb

worked on windows via pip page

---

docs/mindsdb-docs/docs/setup/self-hosted/pip/linux.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/windows.md

Fixes #2778 
- worked on linux via pip page (it has now similar structure to windows via pip page)
[Linux via pip - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9425449/Linux.via.pip.-.MindsDB.Documentation.pdf)
mindsdb

worked on linux via pip page

---

mindsdb/migrations/versions/2022-08-25_6a54ba55872e_view_integration.py

Ordering parallel migrations in one sequence

Set migration sequence

---

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py

In 'describe predictor.model' created new columnn accuracy_functions. 
It filed with the same value of 'accuracy_functions' from 'describe predictor.ensemble'
#2373

Added accuracy_functions columns

---

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py

[Fix] add probability-per-class

---

mindsdb/__main__.py
mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py

Add Lightwood db

---

docs/mindsdb-docs/docs/setup/self-hosted/pip/macos.md

Fixes #2782 
- worked on macos via pip page (all 3 pages '... via pip' have a similar structure)
[MacOS via pip - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9426351/MacOS.via.pip.-.MindsDB.Documentation.pdf)
mindsdb

worked on macos via pip page

---

docs/mindsdb-docs/docs/setup/self-hosted/pip/source.md

Fixes #2784 
- worked on source via pip page
[Sourcecode via pip - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9426604/Sourcecode.via.pip.-.MindsDB.Documentation.pdf)
mindsdb

worked on source via pip page

---

mindsdb/api/mongo/classes/query_sql.py
mindsdb/api/mongo/responders/insert.py
tests/unit/test_mongodb_server.py

- fixed creating TS predictor from mongo
- rework mongo server tests

Mongo fix: create TS predictor

---

docs/mindsdb-docs/docs/sql/create/view.md

Fixes [#22](https://github.com/mindsdb/mindsdb_private/issues/22)
- added output messages
- also, suggested [improvement to the `CREATE VIEW` command here](https://github.com/mindsdb/mindsdb_private/issues/22#issuecomment-1230482188)
mindsdb

added output messages

---

docs/mindsdb-docs/docs/setup/cloud.md

Fixes #2817
- worked on the deployment->mindsdb cloud page
[MindsDB Cloud - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9446492/MindsDB.Cloud.-.MindsDB.Documentation.pdf)
mindsdb

worked on the deployment->mindsdb cloud page

---

docs/mindsdb-docs/docs/connect/dbeaver.md

Fixes #2820
- worked on connect to mindsdb->dbeaver page
[DBeaver - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9446742/DBeaver.-.MindsDB.Documentation.pdf)
mindsdb

worked on connect to mindsdb->dbeaver page

---

docs/mindsdb-docs/docs/connect/dbt.md

Fixes #2822 
- worked on connect to mindsdb->dbt page
[DBT - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9447168/DBT.-.MindsDB.Documentation.pdf)
mindsdb

worked on connect to mindsdb->dbt page

---

docs/mindsdb-docs/docs/setup/cloud.md
docs/mindsdb-docs/docs/setup/custom-config.md
docs/mindsdb-docs/docs/setup/self-hosted/docker.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/linux.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/macos.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/source.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/windows.md

Fixes #2814 
- standardized the what's next section of each ready page under deployment header
mindsdb

standardized the what's next section of each ready page under deployment header

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #2830 
- added mongo
mindsdb

added mongo

---

docs/mindsdb-docs/docs/connect/mindsdb_editor.md

Fixes #2832 
- worked on connect to mindsdb->minsdb sql editor page
[MindsDB SQL Editor - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9455383/MindsDB.SQL.Editor.-.MindsDB.Documentation.pdf)
mindsdb

worked on connect to mindsdb->minsdb sql editor page

---

docs/mindsdb-docs/docs/connect/metabase.md

Fixes #2835 
- worked on connect to mindsdb->metabase page
[Metabase - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9456141/Metabase.-.MindsDB.Documentation.pdf)
mindsdb

worked on connect to mindsdb->metabase page

---

mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py
mindsdb/integrations/handlers/clickhouse_handler/requirements.txt

- Added click house Dialect
mindsdb

Added ClickHouse Dialect

---

mindsdb/integrations/handlers/informix_handler/README.md

- Added More helpful README for Informix Handler
mindsdb

ADDED Improved README in Informix

---

docs/mindsdb-docs/docs/connect/mysql-client.md

Fixes #2861 
- worked on connect to mindsdb->mysql cli page
[MySQL CLI - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9484499/MySQL.CLI.-.MindsDB.Documentation.pdf)
mindsdb

worked on connect to mindsdb->mysql cli page

---

docs/mindsdb-docs/docs/connect/kafka.md

Fixes #2859 
- worked on connect to mindsdb->kafka page
[Kafka - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9484442/Kafka.-.MindsDB.Documentation.pdf)
mindsdb

worked on connect to mindsdb->kafka page

---

docs/mindsdb-docs/docs/sql/create/databases.md
docs/mindsdb-docs/docs/sql/table-structure.md

Fixes #2885
- worked on sql api->create->database page
mindsdb

worked on sql api->create->database page

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes [#42 from mindsdb_private repo](https://github.com/mindsdb/mindsdb_private/issues/42)
- capitalized names
mindsdb

capitalized names

---

mindsdb/__about__.py
requirements.txt

Release 22.9.3.1

---

docs/mindsdb-docs/docs/sql/create/view.md

Fixes #2908 
- worked on sql api->create->view page
[VIEW - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9559744/VIEW.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->create->view page

---

docs/mindsdb-docs/docs/sql/api/drop.md

Fixes #2919 
- worked on sql api->drop predictor page
[DROP PREDICTOR - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9568745/DROP.PREDICTOR.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->drop predictor page

---

mindsdb/integrations/handlers/lightwood_handler/tests/test_lightwood_handler.py

Fix lightwood test

---

docs/mindsdb-docs/docs/sql/create/predictor.md

Fixes #2888 
- worked on sql api->create->predictor page
[PREDICTOR - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9550966/PREDICTOR.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->create->predictor page

---

docs/mindsdb-docs/docs/sql/api/select_files.md

Fixes #2923 
- worked on sql api->select from files page
[SELECT from files - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9570185/SELECT.from.files.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->select from files page

---

docs/mindsdb-docs/docs/sql/api/select.md

Fixes #2921 
- worked on sql api->select page
[SELECT - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9569601/SELECT.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->select page

---

docs/mindsdb-docs/docs/sql/api/insert.md

Fixes #2910 
- worked on sql api->insert into page
[INSERT INTO - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9560294/INSERT.INTO.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->insert into page

---

docs/mindsdb-docs/docs/sql/api/retrain.md

Fixes #2917 
- worked on sql api->retrain page
[RETRAIN - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9568536/RETRAIN.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->retrain page

---

docs/mindsdb-docs/docs/sql/api/join.md

Fixes #2951 
- worked on sql api->join page
[JOIN - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9608455/JOIN.-.MindsDB.Documentation.pdf)
mindsdb

worked on sql api->join page

---

docs/mindsdb-docs/docs/mongo/collection-structure.md
docs/mindsdb-docs/docs/mongo/database.md
docs/mindsdb-docs/docs/mongo/delete.md
docs/mindsdb-docs/docs/mongo/find.md
docs/mindsdb-docs/docs/mongo/insert.md
docs/mindsdb-docs/docs/mongo/stats.md

Fixes #2953 
- implemented minor changes
mindsdb

worked on mongo api pages

---

docs/mindsdb-docs/docs/custom-model/ray-serve.md

Fixes #2964 
- worked on using custom models->ray serve
[Ray Serve - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9610569/Ray.Serve.-.MindsDB.Documentation.pdf)
mindsdb

worked on using custom models->ray serve

---

docs/mindsdb-docs/docs/custom-model/mlflow.md
docs/mindsdb-docs/mkdocs.yml

Fixes #2956 
- worked on using custom models->mlflow page
[MLflow - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9610145/MLflow.-.MindsDB.Documentation.pdf)
mindsdb

worked on using custom models->mlflow page

---

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py

Fix to get #2500 up and running.

[fix] Check column existence in lightwood.predict()

---

docs/mindsdb-docs/docs/connect/sql-alchemy.md

Fixes #2913
-  updated the documentation on SQLAlchemy with engine.connect()
mindsdb

Updated documentation on  sql-alchemy.md

---

docs/mindsdb-docs/docs/sql/tutorials/home-rentals.md

Fixes #2975 
- worked on tutorials->regression->home rentals page
[Home Rentals - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9619484/Home.Rentals.-.MindsDB.Documentation.pdf)
mindsdb

worked on tutorials->regression->home rentals page

---

docs/mindsdb-docs/docs/custom-model/openai.md

Fixes #2973 
- worked on using custom models->openai page
[OpenAI - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9618632/OpenAI.-.MindsDB.Documentation.pdf)
mindsdb

worked on using custom models->openai page

---

docs/mindsdb-docs/docs/connect/sql-alchemy.md

Fixes #2914
- Added pymysql library and Port change 
mindsdb

Updated Docs for SQLAlchemy

---

mindsdb/__about__.py
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
tests/unit/executor_test_base.py
tests/unit/test_executor.py

Release v22.9.5.3

---

docs/mindsdb-docs/docs/connect/sql-alchemy.md

Fixes #2997
- added line of code
mindsdb

added line of code

---

docs/mindsdb-docs/docs/contribute/install.md

Fixes #3003 
- worked on contributing guide->mindsdb installation for development page
[MindsDB Installation for Development - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9648667/MindsDB.Installation.for.Development.-.MindsDB.Documentation.pdf)
mindsdb

worked on contributing guide->mindsdb installation for development page

---

docs/mindsdb-docs/docs/mongo/mongo.md
docs/mindsdb-docs/docs/sql/tutorials/customer-churn.md

Fixes #3026 
- removed important_missing_information field from docs
mindsdb

removed important_missing_information field from docs

---

docs/mindsdb-docs/docs/contribute/integrations.md

Fixes #3014 
- worked on contributing guide->building a new integration page
[Building a New Integration - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9668432/Building.a.New.Integration.-.MindsDB.Documentation.pdf)
mindsdb

worked on contributing guide->building a new integration page

---

docs/mindsdb-docs/docs/sql/tutorials/house-sales-forecasting.md

Fixes #3001 
- ready for review
mindsdb

worked on tutorials->time series->house sales page (2 commits)

---

docs/mindsdb-docs/docs/sql/api/describe.md
docs/mindsdb-docs/docs/sql/api/select.md
docs/mindsdb-docs/docs/sql/api/update.md
docs/mindsdb-docs/docs/sql/create/view.md

Added to doc:
- Implement New syntax for DESCRIBE {model} #2392
- Syntax for raw query to integration #2760
- Add predictions as a column to the original table #2454
- Support Union / Union all #2871

Add new syntaxes to docs

---

docs/mindsdb-docs/docs/sql/api/select.md

Fixes https://github.com/mindsdb/mindsdb/issues/3046
- Fix a typo in the Complex queries section in the documentation.
mindsdb

Fix typo in complex queries section

---

docs/mindsdb-docs/mkdocs.yml

Resolves #3049
- Add update link to navigation menu.
mindsdb

Add update link to the navigation menu

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- Added a published community tutorial to the tutorial list

modified tutorial list

---

docs/mindsdb-docs/docs/custom-model/huggingface.md
docs/mindsdb-docs/docs/custom-model/mlflow.md
docs/mindsdb-docs/docs/custom-model/openai.md
docs/mindsdb-docs/docs/custom-model/ray-serve.md
docs/mindsdb-docs/docs/sql/api/describe.md
docs/mindsdb-docs/docs/sql/api/insert.md
docs/mindsdb-docs/docs/sql/api/retrain.md
docs/mindsdb-docs/docs/sql/api/select.md
docs/mindsdb-docs/docs/sql/api/select_files.md
docs/mindsdb-docs/docs/sql/api/update.md
docs/mindsdb-docs/docs/sql/api/use.md
docs/mindsdb-docs/docs/what-is-mindsdb.md

Fixes #2947 (only one fix to a single doc file to start. But more needs to be done later)
- I added a prefix `!#sql` to a SQL command `WHERE` on line 84 in `what-is-mindsdb.md` file

add SQL format style to doc per issue #2947

---

README.md
integrations_contest.md

Hey there, while going through the repository documentation, i found two typos in `CONTRIBUTING.md` and `integrations_contest.md` and thought of fixing them. I hope that is under the contributions guidelines and i really appreciate if possible you could mention the hacktoberfest-accepted tag if you choose to accept this change since this my first year participating in hacktoberfest. Let me know if there's any changes to be done. I'll be happy to work on them. :)

Typo fix in documentation

---

docs/mindsdb-docs/docs/sql/create/view.md

Remove "AS predicted_column" from VIEW Page
Fixes #3078
-Remove AS {name} from VIEW Page
mindsdb

Remove AS {name} from VIEW Page

---

docs/mindsdb-docs/docs/sql/tutorials/eeg-forecasting.md
docs/mindsdb-docs/mkdocs.yml

Fixes #3067 
- standardized the tutorial content (Patricio is looking into one error that might have been caused by the MindsDB version)
[Brain Activity - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9698427/Brain.Activity.-.MindsDB.Documentation.pdf)
mindsdb

not ready to merge

---

docs/mindsdb-docs/docs/sql/api/describe.md
docs/mindsdb-docs/mkdocs.yml

Fixes [#47 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/47)
- worked on sql api->describe predictor page
mindsdb

worked on sql api->describe predictor page

---

docs/mindsdb-docs/docs/contribute/tutorials.md

Fixes [#48 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/48)
- created contributing guide->writing tutorials page
[Writing Tutorials - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9709956/Writing.Tutorials.-.MindsDB.Documentation.pdf)
mindsdb

created contributing guide->writing tutorials page

---

docs/mindsdb-docs/docs/connect/mariadb-cloud.md
docs/mindsdb-docs/mkdocs.yml

MVP docs for MariaDB Cloud. As requested internally. 
-
mindsdb

Created connect to MariaDB Cloud doc

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3095 
- Added a community article to the list - Deploying MindsDB on GCP by Rutam
**💚 MindsDB**

Updated with a Community Tutorial by Rutam 😎

---

mindsdb/integrations/handlers/file_handler/file_handler.py

Replace not valid symbols in file

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3095 
-
Added a new tutorial link Named [Easy machine learning with MindsDB](https://medium.com/codesight/easy-machine-learning-with-mindsdb-664e27c974f9) by [Liron Navon](https://medium.com/@codesight)
mindsdb

new tutorial addition

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3095
- Added a community article on How To Forecast Purchase Orders for Shopify Stores Using Open-Source by John Lafleur
mindsdb

Added a Community Tutorial

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3095 
**File Changed:**
-Added Medium article to tutorials.md
**Type of Change:**
Addition
**Details:**
- Added new article to tutorials.md list
Article: [How to bring your own machine learning model to databases](https://medium.com/mindsdb/how-to-bring-your-own-machine-learning-model-to-databases-47a188d6db00) 
Author: [Patricio Cerda Mardini](https://medium.com/@paxcema)

Added article tutorial to tutorials.md

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3095
**File Changed:**
-Added Medium article to tutorials.md
**Type of Change:**
Addition
**Details:**
- Added new article to tutorials.md list
Article: [Multivariate time series forecasts inside databases with MindsDB and PyTorch](https://medium.com/mindsdb/multivariate-time-series-forecasts-inside-databases-with-mindsdb-and-pytorch-13745ada6b7e)
Author: [Patricio Cerda Mardini](https://medium.com/@paxcema)

Added Medium article tutorial to tutorials.md

---

docs/mindsdb-docs/docs/tutorials.md

ref: issue #3095 
Addition
Added new article to tutorials.md list
Article: [Forecast bitcoin price using MindsDB](https://medium.com/@kinkusuma/forecast-bitcoin-price-using-mindsdb-75f9f0500e86)
Author: [Kinie K Kusuma](https://medium.com/@kinkusuma) to tutorials.md
mindsdb

Added an article to tutorials.md

---

docs/mindsdb-docs/docs/Getting Started with MindsDB on Digital Ocean.md

Fixes #
Updated MindsDB Documentation dead links
mindsdb

Updated MindsDB Documentation dead links

---

docs/mindsdb-docs/docs/connect/mongo-shell.md
docs/mindsdb-docs/mkdocs.yml

This PR adds new documentation for connecting to MindsDB MongoDB API using the mongo shell.

Add Mongo shell docs

---

docs/mindsdb-docs/docs/tutorials.md

Signed-off-by: Marcel Coetzee <marcelcoetzee@tutanota.com>

Add car prices Tutorial

---

docs/mindsdb-docs/docs/connect/connect-mariadb-skysql.md
docs/mindsdb-docs/docs/connect/mariadb-cloud.md
docs/mindsdb-docs/mkdocs.yml

Fixes #
Passed a grammar check over the mariaDB cloud connecting docs.
-
mindsdb

grammar check on mariaDB cloud doc

---

docs/mindsdb-docs/docs/tutorials.md

ref: issue #3095 
Addition
Added new article to tutorials.md list
Article: [MindsDB: Predicting Supply Chain Demand with Machine Learning using SQL](https://www.devforce.one/18303637/mindsdb-predicting-supply-chain-demand-with-machine-learning-using-sql#/)
Author: [Chandre Van Der Westhuizen](https://github.com/chandrevdw31)
mindsdb

addition: new article on predicting supply chain demand

---

docs/mindsdb-docs/docs/hacktoberfest-facebook-post.md
docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

Fixes #3129
- Post to LinkedIn about experience with MindsDB and Hacktoberfest
- mindsdb/docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md with link to post
mindsdb

updated hacktoberfest linkedin post documentation file

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Fixes #3127 
- I shared my experience using MindsDB on Twitter.
- [Click here if you would love to read it.](https://twitter.com/teslimodus23/status/1577703809823911937?s=20&t=D0K9KolS5HmGVDB8Rr3ADg)
mindsdb

Twitter Thread on MindsDB

---

docs/mindsdb-docs/docs/tutorials.md

ref: issue #3095 
Addition
Added new article to tutorials.md list
Article: [Why Your Database Needs a Machine Learning Brain](https://medium.com/mindsdb/why-your-database-needs-a-machine-learning-brain-fc580fac47e4)
Author: [James Wilson](https://medium.com/@jameswilsonai) to tutorials.md
mindsdb

addition: new article to `tutorials.md`

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #3185
- Adding SAP Hana Handler info (template and example) to the CREATE DATABASE documentation
mindsdb

Adding SAP Hana to the CREATE DATABASE docs

---

README.md

Fixes #
I have checked and have made some grammar mistakes and spelling mistakes in the documentation (README.md file).
mindsdb

doc: Updated README.md

---

docs/mindsdb-docs/mkdocs.yml

Fixes #3184
- Re-ordering menu items in "Connect to MindsDB" section to be in alphabetical order
mindsdb

Order the navigation menu items

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
Added a new community tutorial. This closes this issue #3216 
mindsdb

Community tutorial 34

---

docs/mindsdb-docs/docs/tutorials.md

Added a Tutorial to Predict the Genre of Books and linked it here.
Fixes #
- I have written a short tutorial to use MindsDB functionalities to predict the genre of a book, given a summary. The data is from Kaggle and uses the MindsDB cloud solution. 
- The tutorial is available on dev.to and is linked in the .md file here
mindsdb

Closes #3199 Tutorial Added

---

docker/release
mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py
mindsdb/integrations/handlers/snowflake_handler/requirements.txt
mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py

native snowflake sql renderer

---

mindsdb/__about__.py
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py

Release 22.10.2.1

---

docs/mindsdb-docs/docs/connect/mongo-shell.md

Fixes #3217
- Remove the default user for local MongoDB API connection.
mindsdb

Removing unnecessary MongoDB argument

---

docs/mindsdb-docs/docs/connect/mongo-shell.md

Fixes #3209
- Edited connectiong in the file mindsdb/docs/mindsdb-docs/docs/connect/mongo-shell.md as mentioned in the issue.

Fixed connectiong type

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3139 
- I have written a new Blog on **Predict Purchasing Power per Country using MindsDB**.
- I have updated the list of community tutorials with the links to this new article.
- 5️⃣ Points for writing a new Tutorial
- 1️⃣ Point for adding a new Tutorial Link to the Community List
💚 mindsdb

Added new Community Tutorial by Rutam 😎

---

docs/mindsdb-docs/docs/tutorials.md

Added tutorial to predict TYE

---

mindsdb/integrations/libs/ml_exec_base.py
tests/unit/test_ml_handlers.py

Fix: one line prediction fails for ml handler api

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
Addition of video tutorial.
- I've added my video tutorial link in the tutorial section. 
mindsdb

added video tutorial

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

My honest opinion on Mindsdb on LinkedIn
mindsdb

LinkedIn Post

---

mindsdb/integrations/handlers/postgres_handler/Manual_QA.md

Fixes #3224
- Testing Postgres Handler Manually, copying code, screenshots, and providing remarks.
mindsdb

Test Postgres Handler Manually 

---

docs/mindsdb-docs/docs/connect/connect-mariadb-skysql.md

Added Explanatory videos Feat. @Dav1dF 
mindsdb

Added missing videos for MariaDB SkysQL conection

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3280
- Predicting Life Expectancy using MindsDB Cloud
mindsdb

Predicting Life Expectancy using MindsDB Cloud

---

mindsdb/integrations/handlers/mysql_handler/Manual_QA.md

Fixes #3226
- Test MySQL Handler Manually Predictive Maintenance
Points Earned
1️⃣ Point for Manual QA testing.
💚 mindsdb

Test MySQL Handler Manually Predictive Maintenance

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Fixes #3318
-Share your experience with MindsDB 💚 on Twitter
mindsdb

Experience with MindsDB 💚 

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

Fixes #3319 
- Experience with MindsDB
mindsdb

Experience with MindsDB

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md
docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Shared my experience with MindsDB on Linkedin and Twitter

Twitter and LinkedIn experience

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md
docs/mindsdb-docs/docs/tutorials.md

- #3287 
- Followed instructions in issue #3287 to predict retail sales
- Published [article](https://medium.com/@alissatroianonyc/using-mindsdb-to-predict-future-retail-sales-a300f63a086b) on Medium.
- Updated `tutorials.md` with links to article

#3287 - Create tutorial to predict retail sales in Brazil

---

mindsdb/integrations/handlers/clickhouse_handler/Manual_QA.md

Fixes # https://github.com/mindsdb/mindsdb/issues/3250
- Test Clickhouse Handler Manually House Rent Prediction
mindsdb

Test Clickhouse Handler Manually House Rent Prediction

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- add a new article link for the tutorial
mindsdb

Tutorial for predicting store sales data

---

docs/mindsdb-docs/docs/mongo/insert.md

Fixes #3358
- Updated both the syntax description and example.
- Used [this](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/api/mongo/README.md#creating-predictor) as reference
mindsdb

select_data_query updated

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3283
- Predicting Employee Attrition using MindsDB Cloud
mindsdb

Predicting Employee Attrition using MindsDB Cloud

---

docs/mindsdb-docs/docs/tutorials.md

ref: issue #3095 
Added new article to tutorials.md list
Article: [Predicting Employee Attrition & Performance using MindsDB Cloud](https://dev.to/armanchand/predicting-employee-attrition-performance-using-mindsdb-cloud-3cm6)
Author: [Arman Chand](https://dev.to/armanchand)
mindsdb

Adding new mindsdb tutorial

---

docs/mindsdb-docs/docs/tutorials.md

- #3372 
- Make visual video tutorial: Create a Free MindsDB Cloud Account

Video Tutorial: Create a Free Account on MindsDB

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3369 
- I have uploaded a new video on the topic- **What is MindsDB?**.
- I have updated the list of community video guides with the link to this new video.
- 9️⃣ Points for making a new video.
- 1️⃣ Point for adding a new Video Link to the Community List.
💚 mindsdb

New community video guide updated with a new video by Rutam 😎

---

docs/mindsdb-docs/docs/tutorials.md

added `Predicting the Rating of Cars using Mindsdb` tutorial blog
Fixes #
- Added tutorial article link
mindsdb

added tutorial blog

---

docs/mindsdb-docs/docs/contribute/techstack.md

Fixes #
- I have updated "Contributing Guide" section with skill set required to make code contributions to MindsDB.
- Have added the skill set based on my observations done on Github repository.
- The skill set requirement list is not exhaustive but listing few of the major skill set will help potential contributors, specially new open-source contributors who want to get started with MindsDB.
- This is my first contribution to MindsDB. Open to making any improvements if required :)

added skillset requirement for code contributions

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3290 
- I added a tutorial to tutorial.md for [Predicting & Visualizing Hourly Electricity Demand in the US with MindsDB and Tableau](https://teslimodus.medium.com/predicting-visualizing-hourly-electricity-demand-in-the-us-with-mindsdb-and-tableau-126d1c74d860)
mindsdb

Adding Tutorial for issue #3290

---

docs/mindsdb-docs/docs/hacktoberfest-facebook-post.md

Fixes #3385 
I wrote a Facebook post about my experience with MindsDB

Shared my MindsDB experience on Facebook

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

Fixes #3383 
Hacktoberfest Post on Linkedin

Update hacktoberfest-linkedin post

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Hacktoberfest Tweet

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Fixes #
- Added twitter thread link
mindsdb

added twitter thread link

---

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
mindsdb/interfaces/database/views.py

Changes:
- Try to run query of the view with 'limit 1' at the moment of creating view
#2827

Check query of the view

---

mindsdb/interfaces/database/integrations.py

Delete integration:
- not allow to delete permanent integration
- set data_integration_id and integration_id for deleted predictor

Fix for deleting integration:

---

mindsdb/integrations/handlers/dynamodb_handler/Manual_QA.md

Fixes #3322
- Done all the command steps required
- Used mindsdb online editor
- Uploaded dataset manually and created database
mindsdb

DynamoDB Handler Manually Tested

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3279 
-Predicting Logistics Quality using MindsDB
mindsdb

Predicting Logistics Quality using MindsDB

---

docs/mindsdb-docs/docs/tutorials.md

Refer #3485  
Video tutorial on setting up free cloud account.

Creating Free cloud account in just 2 minutes

---

docs/mindsdb-docs/docs/sql/create/databases.md

Fixes #3475 
- modified the syntax section
mindsdb

modified the syntax section

---

docs/mindsdb-docs/docs/connect/connect-mariadb-skysql.md

Added MVP for last step of connection on MariaDB SkySQL.

created and added last step video for MariaDB SkySQL

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- I have made a video tutorial which is published on youtube and I have explained it about. What is MindsDB? What does MindsDB do? and How to get started with MindsDB
-
mindsdb

Added mindsDb video tutorial with proper info.

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- created a video tutorial guide
mindsdb

created  added new tutorial link in docs

---

docs/mindsdb-docs/docs/tutorials.md

Fixes https://github.com/mindsdb/mindsdb/issues/3458
Video expalining about Mindsdb AI Tables with an example

Explains AI Tables with an example of predicting car prices

---

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
tests/unit/test_executor.py

Changes: 
- set __mindsdb_row_id of first horizon row if _mdb_forecast_offset > 0

Fix join with >latest

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3446 
- I have written a new Blog on **Creating Views with MindsDB**.
- I have updated the list of community tutorials with the links to this new article.
- I have also re-arranged and moved some of the Video Tutorials under the `Community Video Guides` section.
- Dataset has been updated to this [Uber Dataset](https://www.kaggle.com/datasets/yasserh/uber-fares-dataset?select=uber.csv).
- 5️⃣ Points for writing a new Tutorial
- 1️⃣ Point for adding a new Tutorial Link to the Community List
💚 mindsdb

Added new Blog by Rutam 😎

---

docs/mindsdb-docs/docs/tutorials.md

Fixes https://github.com/mindsdb/mindsdb/issues/3370
- add a video guide

chore(docs): add video guide to deploy on local

---

docs/mindsdb-docs/docs/tutorials.md

- Fixes #3486  
1) New **VIDEO TUTORIAL** that teaches viewers how to start MindsDB with Docker:
2) Updated `tutorials.md` file:
💚 mindsdb

[Video] Running MindsDB with Docker #3486 💚🐳

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- Added article link
mindsdb

added article link

---

docs/mindsdb-docs/docs/mongo/insert.md

Fixes #
- The "Checking the Predictor Status" section had a repeated code block containing error, select_data_query, and training_options. I removed it to make the docs consistent.
mindsdb

Removed Repeated Code Blocks.

---

mindsdb/integrations/handlers/cassandra_handler/Manual_QA.md
mindsdb/integrations/handlers/scylla_handler/Manual_QA.md

Contributes to #3246
- Completed the desired steps to manually check the Cassandra Handler as outlined in the issue.
- I also added to the Manual Check for Scylla while I was at it.
mindsdb

[Manual QA] Test Cassandra and Scylla Handlers Manually

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3485
- Video - Getting started with MindsDB
mindsdb

Video - Getting started with MindsDB

---

docs/mindsdb-docs/docs/setup/self-hosted/docker.md
docs/mindsdb-docs/docs/setup/self-hosted/pip/linux.md

This PR adds two video tutorials from @chandrevdw31 to the Pip and Docker sections

Add video tutorials

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

Fixes #3544 
- Added linked in post in linkedin md
mindsdb

chore: add linked in post in linkedin md

---

docs/mindsdb-docs/docs/hacktoberfest-facebook-post.md

Fixes #
- added facebook post stating my experience
mindsdb

added facebook post stating my experience

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Added my experience of MindsDB on twitter

A twitter thread by Haseeb Siddiqui

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Fixes #
- Started with my good first issue , and posted my experience on twitter
mindsdb

posted my experience on twitter

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3376 
Video on MindsDB Data Insights

MindsDB Data Insights Video

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- I have made a new tutorial on MindsDB cloud editor where I explaining how we can effectively use mindsDB to Analyse, Predict, & Train our ML model.
mindsdb

uploaded tutorial on Forecasting Quarterly House Sales with MindsDB 

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3381 
- I have written a new Blog on **Predict Tesla Stock Prices using MindsDB**.
- I have updated the list of community tutorials with the links to this new article.
- 5️⃣ Points for writing a new Tutorial
- 1️⃣ Point for adding a new Tutorial Link to the Community List
💚 mindsdb

Added a new Blog Article by Rutam 😎

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3485 
- I have uploaded a new video on the topic- **Signing Up with MindsDB Cloud**.
- I have updated the list of community video guides with the link to this new video.
- 9️⃣ Points for making a new video.
- 1️⃣ Point for adding a new Video Link to the Community List.
💚 mindsdb

Added a new video tutorial by Rutam 😎

---

docs/mindsdb-docs/docs/tutorials.md

Issue: https://github.com/mindsdb/mindsdb/issues/3374
A tutorial video for connecting from mongoshell.

Video on connecting from mongo shell

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3561 
- Video - Visualize prediction results in Tableau
- You can watch on youtube [here](https://youtu.be/4aio-8kNbOo)
mindsdb

Adding new video tutorial

---

docs/mindsdb-docs/docs/tutorials.md

In this Video I have explained
- what is mindDB?
- what are it's features.
- How does the MindsDB cloud editor works
- How to use MindsDB cloud Editor to predict the data.
Fixes #
-
mindsdb

Added My Tutorial Video About MindsDB

---

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py

Changes: 
- check if training dataframe contents column to predict and show error to user before run learn in subproccess.

Сheck target of predictor 

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3375 
Video tutorial on connecting and loading data from postgres.

 Connect Postgres Database to MindsDB

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3458 
- Created a YouTube video that answers the following questions:
- What is MindsDB?
- What problem does MindsDB solve?
- What are AI tables?
- Why should you use MindsDB?

Create Video - What is MindsDB?

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3668
- Added Video Tutorial For Honey Production Time Series Forecasting

Added Honey Production Video Tutorial

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3558 
- Updated `tutorials.md` with link to new video, ["Connecting MindsDB to Tableau"](https://www.youtube.com/watch?v=eUiBVrm85v4)
mindsdb

[Video] Connecting MindsDB to Tableau

---

docs/mindsdb-docs/docs/what-is-mindsdb.md

Fixes #3526 
- broken links update on what-is-mindsdb page
mindsdb

broken links update on what-is-mindsdb page

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
-
Added my video tutorial
mindsdb

Video tutorial by HellFire 😎 

---

docs/mindsdb-docs/docs/tutorials.md

Added tutorial for predicting genre of books

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3371 
- Update `tutorials.md` with link to newly created & published YouTube video, ["Deploy MindsDB on Google Cloud Platform"](https://www.youtube.com/watch?v=WLdb7UNi4bk)

[Video] Deploying MindsDB with Google Cloud

---

mindsdb/integrations/handlers/datastax_handler/Manual_QA.md

Fixes #
Not Fixed
Manual test results #3632 
mindsdb

Added results for manual test

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- added new tutorial on data sources
mindsdb

Added new tutorial

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

-Added new twitter thread to docs

added new twitter thread to docs

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

Fixes #
- uploaded LinkedIn post 
mindsdb

uploaded LinkedIn post by sharing my experience with mindsDB

---

docs/mindsdb-docs/docs/hacktoberfest-facebook-post.md

Create Post about MindsDB on Facebook

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #
- Added my article about what is mindsDB which I wrote on Medium
- you can read [here](https://medium.com/@hritikd3/what-is-mindsdb-how-to-get-started-2b3cf6d99707)
mindsdb

Wrote article on medium

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

- created a link to my post on linkedin for #3784

Add linkedin post

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Fixes # https://github.com/mindsdb/mindsdb/issues/3786
- -Added new Twitter Thread:  [Prakash Gatiyala](https://twitter.com/PrakashGatiyal1/status/1586822595676352512?s=20&t=Z6FlKNJTyfRvx2eLjW_2Dg)
mindsdb

Add twitter post link

---

docs/mindsdb-docs/docs/connect/connect-mariadb-skysql.md

Added sept 5 MariaDB SKYSQKL New video.

changed MariaDB SKYSQL video Step 5

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3874
-
An account of how I set up my MindsDB predictor to try and predict Microsoft Stock Prices using a Kaggle Dataset [here](https://dev.to/viveknshah/using-mindsdb-to-predict-microsoft-stock-prices-3l79)

Predicting Microsoft Stock Prices on Dev.To

---

docs/mindsdb-docs/docs/sql/native-queries.md
docs/mindsdb-docs/mkdocs.yml

Fixes #3738 
- added doc page on native queries
[Running Native Queries - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9902394/Running.Native.Queries.-.MindsDB.Documentation.pdf)
mindsdb

added doc page on native queries

---

mindsdb/integrations/handlers/access_handler/Manual_QA.md

Fixes #3734
- Test Microsoft Access Handler Manually, Report findings, and create bug
Drop a remark based on your observation.
- [] Works Great 💚 (This means that all the steps were executed successfuly and the expected outputs were returned.)
mindsdb

3734 Microsoft Access QA

---

mindsdb/integrations/handlers/mssql_handler/Manual_QA.md

- Performing Manual QA, attaching results, etc
Drop a remark based on your observation.
Works great! I thought Azure databases might cause issues (works better than DBeaver which threw errors I could not fix) aside from having to grant permission for the mindsdb cloud server. Not sure if it's a big deal but the api was able to expose the mindsdb IP address. (blurred in the following  ![screenshot](https://user-images.githubusercontent.com/241893/199147253-1e8aca4f-606c-48d1-8d6e-b77d821baec2.png))
mindsdb

Manual QA for SQL Server (Using Azure SQL Server)

---

docs/mindsdb-docs/docs/tutorials.md

Fixes #3803
Added two new tutorials using MindsDB and MongoDB + Mongo API

Added two tutorials on mongodb and mindsdb

---

docs/mindsdb-docs/docs/tutorials.md

In regards to issue #3953.
The links did not point to my tutorial correctly
Corrected the mixup of links for my tutorials in the tutorials.md file

Corrected the tutorial links

---

docs/mindsdb-docs/docs/sql/project.md
docs/mindsdb-docs/mkdocs.yml

Fixes #3890 
- first draft of docs on project (tested on alpha)
[PROJECTS - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9922506/PROJECTS.-.MindsDB.Documentation.pdf)
mindsdb

first draft of docs on project (tested on alpha)

---

docs/mindsdb-docs/docs/connect/connect-mariadb-skysql.md

Fixes #3980 
Changed the videos to iframes with the new Vimeo urls.
mindsdb

Changed MariaDB SkySQL doc video to Vimeo

---

docs/mindsdb-docs/docs/hacktoberfest-linkedin-post.md

Fixes #3867
- This PR adds a link to the LinkedIn post where I shared my Hacktoberfest experience.
💚 mindsdb

Added a LinkedIn Post by Rutam 😎

---

docs/mindsdb-docs/docs/hacktoberfest-twitter-post.md

Fixes #3865
- This PR adds a link to the Twitter post where I shared my Hacktoberfest experience.
💚 mindsdb

Added a Hacktoberfest Twitter Thread by Rutam 😎

---

docs/mindsdb-docs/docs/sql/create/ml_engine.md
docs/mindsdb-docs/mkdocs.yml

Fixes #4020 
- added sql api->create->ml_engine doc page
[ML_ENGINE - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/10003802/ML_ENGINE.-.MindsDB.Documentation.pdf)
mindsdb

started working on create ml_engine

---

mindsdb/integrations/handlers/file_handler/file_handler.py

get csv dialect from header

---

mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/functions.py
mindsdb/integrations/libs/ml_exec_base.py

del exception catching in LW learn to make it bubble up

Fix error msg if learn is failing

---

docs/mindsdb-docs/docs/rest/sql.md
docs/mindsdb-docs/mkdocs.yml

Fixes #3760 
Initial docs for the current `sql/query` endpoint.

Add rest docs

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/project_datanode.py
mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
mindsdb/integrations/libs/ml_exec_base.py
mindsdb/interfaces/database/projects.py
mindsdb/interfaces/model/functions.py
mindsdb/interfaces/model/model_controller.py
mindsdb/migrations/versions/2022-11-07_1e60096fc817_predictor_version.py
tests/unit/dummy_ml_handler/dummy_ml_handler.py
tests/unit/ml_handlers/test_lightwood.py
tests/unit/test_project_structure.py

Depended on #3988
Manage versions stage of SQL Syntax project
https://docs.google.com/document/d/15ndRacuJNpmsPp-OVNzq1E7FaIB1W8Yzo3abWAKpqbs/edit#
- List of models
```
Select * from project.models;
Show models <from | in> <project> where <expr>
```
*Manage versions*
- See all versions
`select * from project.models_versions `
- Set active selected version
```
update project.models_versions set active=1
where version=3 and name=’modelname’ 
```
- Delete specific version
`delete from project.models_versions where version=3 and name=’modelname’. `
Exception if version is active

Model versions: manage versions

---

mindsdb/migrations/versions/2022-11-07_1e60096fc817_predictor_version.py

Update versions for models was incorrect

Fix migration for model version

---

mindsdb/integrations/handlers/file_handler/file_handler.py

[#3312](https://github.com/mindsdb/mindsdb/issues/3312)

Fix csv reading

---

docs/mindsdb-docs/docs/custom-model/huggingface.md

Fixes #4079 
- updated queries to use database
mindsdb

updated HuggingFace docs

---

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py

Error message if model can not be retrained because of missed dataset

Error message if model can not be retrained

---

docs/contribute/docs.mdx

Fixes #4095 
- updated how to contribute to docs
mindsdb

updated how to contribute to docs

---

mindsdb/api/http/namespaces/analysis.py
mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py

Only merge once [lightwood#1049](https://github.com/mindsdb/lightwood/pull/1049/files) has been merged.

fix: use type_infer

---

docs/custom-model/huggingface.mdx

Fixes #4102
- updated huggingface.mdx
mindsdb

updated huggingface.mdx

---

mindsdb/integrations/libs/ml_exec_base.py

Fix for HF:
data_integration_ref can be None

HF fix: data integration can be none

---

docs/mint.json
docs/rest/sql.mdx

This PR adds the initial version of the REST API docs and a new page for the SQL endpoint.

Add Restapi docs

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py

Changes:
- show integration name in error from integration
- show error about unknown integration name
[#3496](https://github.com/mindsdb/mindsdb/issues/3496)

Error messages with native queries

---

mindsdb/integrations/libs/ml_exec_base.py
tests/unit/test_project_structure.py

Fix for HF: data_integration_ref can be None

Release 22.11.4.2

---

docs/sql/api/retrain.mdx

Fixes #4035 
- updated when to retrain a predictor
mindsdb

updated when to retrain a predictor

---

docs/sql/native-queries.mdx

Fixes #4141 
- updated native queries with new syntax
mindsdb

updated native queries with new syntax

---

docs/custom-model/huggingface.mdx

Fixes #4165 
- updated huggingface docs with prerequisite for local mindsdb
mindsdb

updated huggingface docs with prerequisite for local mindsdb

---

docs/contribute/install.mdx

Fixes #3966 
- updated commands
mindsdb

updated commands

---

docs/connect/connect-mariadb-skysql.mdx
docs/connect/dbt.mdx
docs/contribute/loanTutorial/loanTutorial.mdx
docs/contribute/tutorials.mdx
docs/docs-rules.mdx
docs/getting-started.mdx
docs/mongo/find.mdx
docs/mongo/insert.mdx
docs/mongo/mongo.mdx
docs/quickstart.mdx
docs/sql/api/describe.mdx
docs/sql/api/drop.mdx
docs/sql/api/insert.mdx
docs/sql/api/join.mdx
docs/sql/api/select-files.mdx
docs/sql/api/select.mdx
docs/sql/api/select2.mdx
docs/sql/create/databases.mdx
docs/sql/create/databases2.mdx
docs/sql/create/predictor.mdx
docs/sql/create/predictor2.mdx
docs/sql/create/table.mdx
docs/sql/create/view.mdx
docs/sql/feature-importance.mdx

Fixes #4178 
- updated query formatting throughout the docs
mindsdb

updated query formatting throughout the docs

---

docs/getting-started.mdx
docs/quickstart.mdx

Fixes #4182
- updated getting started guides
mindsdb

updated getting started guides

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/information_schema_datanode.py

Changes:
- [added ENGINE column to mindsdb.models and mindsdb.models_versions tables](https://github.com/mindsdb/mindsdb/commit/d327711a830400386749cc87178c8dbe4c9a1ef0)

ENGINE column in models and models_versions

---

mindsdb/api/http/namespaces/analysis.py
mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py

- Improved base error message if model fails post-download
- Fix imports for new ML module `dataprep_ml`

Hotfix: HF handler

---

.github/workflows/mindsdb.yml
mindsdb/__about__.py
mindsdb/api/mongo/responders/find.py
mindsdb/api/mongo/responders/insert.py
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
mindsdb/integrations/libs/ml_exec_base.py
requirements.txt
tests/unit/test_executor.py
tests/unit/test_predictor_params.py
tests/unit/test_project_structure.py

Changes:
- Fix: #4172
- #4195:
- create predictor from mongo: integration and query are optional 
- join model and table in mongo: query is optional
- check model metadata before creation
- pytorch has to be in tags
- metadata.pipeline_tag equal model task
- Improved base error message if model fails post-download
- Fix imports for new ML module dataprep_ml

Release 22.11.4.3

---

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py
mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py
mindsdb/integrations/libs/base.py
mindsdb/interfaces/model/model_controller.py
mindsdb/interfaces/storage/model_fs.py
tests/unit/executor_test_base.py
tests/unit/ml_handlers/test_lightwood.py

Changes:
- LW model describe moved to LW handler
- Added model description for HF

Describe HF model

---

mindsdb/__about__.py
mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
mindsdb/integrations/handlers/lightwood_handler/lightwood_handler/lightwood_handler.py

Merging changes from stable to avoid conflict with merging  from staging to stable

Staging from stable

---

mindsdb/integrations/handlers/trino_handler/trino_handler.py

- fix get_tables by rename the column name to expected value (TABLE_NAME)
- fix other query incorrect syntax (; insides)
- the result also fix #4203

fix trino handler

---

docs/mint.json
docs/nlp/nlp-extended-examples.mdx
docs/nlp/nlp-mindsdb-hf.mdx
docs/nlp/what-is-nlp.mdx

Fixes #4208 
- fixing some typos in nlp docs
mindsdb

fixing some typos in nlp docs

---

docs/sql/create/predictor.mdx
docs/sql/create/predictor2.mdx

Fixes #4180 
- restructured the create model page
[MODEL - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10218422/MODEL.-.MindsDB.pdf)
mindsdb

restructured the create model page

---

mindsdb/__about__.py

Release 22.12.4.2

---

docs/mint.json
docs/setup/environment-vars.mdx
docs/setup/self-hosted/docker.mdx

This PR documents the `env` variables used in MindsDB.
Fix #4238 
Warning for #4058
Added new Navigation menu for the MindsDB configuration and new docs for the environment variables.

Docs env vars

---

README.md

Updated path of Image In Readme File

---

mindsdb/integrations/handlers/openai_handler/__about__.py
mindsdb/integrations/handlers/openai_handler/__init__.py
mindsdb/integrations/handlers/openai_handler/openai_handler.py
mindsdb/integrations/handlers/openai_handler/requirements.txt
mindsdb/integrations/handlers/openai_handler/setup.py

ML handler for OpenAI API models.
**Fixes** #4235
The handler has roughly three main modes of operation, depending on the query that is used to create the model. All of them internally use the `completion` endpoint of the OpenAI API. The API token can be passed at model creation or directly read from the right environment variable if the value is not set or set to `env`. The model type is 'text-davinci-002' by default, but can be changed at creation time to other OpenAI completion models.
We specify a single input `question_column` to expect in the input dataset.
```sql
CREATE MODEL openai_test_a
PREDICT answer
USING
engine = 'openai',
question_column = 'question',
api_key = 'YOUR_OPENAI_API_KEY';  -- optional, if it's not passed (or "env") …
```

[ENH] OpenAI handler

---

mindsdb/integrations/handlers/openai_handler/openai_handler.py

[ENH] OpenAI handler - batched requests

---

docs/contribute/ml-handlers.mdx
docs/mindsdb-handlers.mdx
mindsdb_contest.md

**Fixes** #4261 
Updated file names in links wherever necessary.

updated links

---

mindsdb/integrations/handlers/openai_handler/openai_handler.py

Sequence to search api_key for openai:
1. provided at model creation
2. provided at engine creation
3. OPENAI_API_KEY env variable
4. openai.api_key setting in config.json

Openai: api_key from config

---

mindsdb/interfaces/model/model_controller.py

Case to repeat error:
- user is going to delete model
- user is already having deleted model with the same name
- deleted model is having different ml engine.
Result: 
- Model <name> does not exist

Fix drop model.

---

docs/mint.json
docs/sql/api/join-on.mdx
docs/sql/api/join.mdx

**Fixes** #4245 
- added join...on page
- corrections to the join page
- added the join...on page in navigation
As in Description.
[JOIN ... ON - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10338030/JOIN.ON.-.MindsDB.pdf)

added join...on page

---

docs/custom-model/openai.mdx

**Fixes** [#81](https://github.com/mindsdb/mindsdb_private/issues/81)
[OpenAI - MindsDB.pdf](https://github.com/mindsdb/mindsdb/files/10345593/OpenAI.-.MindsDB.pdf)
Updated the regular OpenAI doc page.

updated regular page on openai

---

docs/custom-model/openai.mdx
docs/nlp/nlp-mindsdb-hf.mdx
docs/nlp/nlp-mindsdb-openai.mdx

**Fixes** #4308 
- added openai mql example
- added tips with links to connect nlp docs with regular docs
As in Description.

added openai mql example, added tips with links to connect nlp docs with regular docs

---

docs/nlp/nlp-extended-examples.mdx
docs/nlp/nlp-mindsdb-openai.mdx
docs/nlp/what-is-nlp.mdx

**Boilerplate OpenAI**
---
**NLP Powered by HF and OpenAI** 
---
**Changed Accordion Example Names**
---
Added references to OpenAI on NLP docs, added OpenAI `CREATE MODEL` Boilerplate example.

[Docs] OpenAI disclaimer and templates on NLP

---

docs/connect/jupysql.mdx

This PR adds a connection guide from Jupyter notebooks to MindsDB via Jupysql.
Closes #4302

Jupysql docs integration guide

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/project_datanode.py

If model is obsolete, then we show proper error message if user try to use it

Error message if model is obsolete

---

docs/mint.json

Added the guide for jupyter notebooks to the index

Adding jupysql guide to mint.json

---

.github/pull_request_template.md
mindsdb/api/http/namespaces/configs/projects.py
mindsdb/api/http/namespaces/projects.py
mindsdb/api/http/start.py
mindsdb/api/mysql/mysql_proxy/classes/sql_query.py
mindsdb/api/mysql/mysql_proxy/datahub/datanodes/project_datanode.py
mindsdb/integrations/libs/ml_exec_base.py
mindsdb/interfaces/model/model_controller.py
tests/integration_tests/flows/test_http.py

#4290
New http api methods for using predictors without sql.
- **GET /api/projects/**
List of projects. 
Now returns only project names. Example of result:
```
[{'name': 'mindsdb'}]
```
- **GET /api/projects/<project_name>/models**
List of models in project. 
Returns information about models. Result is the same as 'show models from <project_name>':
```
[{'name': 'home_rentals_model',
'accuracy': 0.999,
...
'update': 'up_to_date',
'version': None}]
```
- **POST /api/projects/<project_name>/models/<model_name>[.<model_version>]/predict**
Make prediction.
model_version is optional
Input (in request payload):
```
{
'data': [
{'sqft': '1000'},
{'sqft': '500'},
],
'params': {
}
}
```
- data - input data for predictor
- can content several rows 
- can be input for timeseries predictor
- params - …

Http api, prediction

---

mindsdb/api/mysql/mysql_proxy/classes/sql_query.py

Allow join with model at left side

Allow join with model at left side

---

.github/pull_request_template.md
mindsdb/api/http/namespaces/projects.py
mindsdb/interfaces/model/model_controller.py

This PRs adds model version value to the `/models` endpoint payload.
#4329 

Return version for models API

---

docs/mint.json
docs/using-sql-api/classification.mdx
docs/using-sql-api/nlp.mdx
docs/using-sql-api/regression.mdx
docs/using-sql-api/timeseries.mdx

**Fixes** #4340
- added links to tutorial pages under Using MindsDB via SQL API -> Do Machine Learning

added links to tutorial pages under Using MindsDB via SQL API -> Do Machine Learning

---

docs/sql/create/databases.mdx

**Fixes** #4349 
- corrected the link

corrected the link

---

docs/connect/dbt.mdx
docs/connect/kafka.mdx
docs/mint.json
docs/using-dbt/classification.mdx
docs/using-dbt/nlp.mdx
docs/using-dbt/regression.mdx
docs/using-dbt/timeseries.mdx
docs/using-kafka/anomaly-detection.mdx
docs/using-kafka/classification.mdx
docs/using-kafka/nlp.mdx
docs/using-kafka/regression.mdx
docs/using-kafka/timeseries.mdx

**Fixes** #4351 
- updated navigation for dbt and kafka

updated navigation for dbt and kafka

---

docs/using-mongo-api/classification.mdx
docs/using-mongo-api/regression.mdx

**Fixes** #4353 
- added links to mongodb community tutorials under using mindsdb with mongo api
- **IDEA: ask community to create tutorials using MongoDB for NLP and Time Series**

added links to mongodb community tutorials under using mindsdb with mongo api

---

docs/custom-model/openai.mdx
docs/nlp/nlp-mindsdb-openai.mdx

**Fixes** #4347 
- added model_name parameter to openai docs

added model_name parameter to openai docs

---

docs/mint.json
docs/ml-types.mdx
docs/using-mongo-api/nlp.mdx

**Fixes** #4333 
- added an intro page for Machine Learning Examples section in SQL API and Mongo API
- linked NLP examples using MQL
- updates to navigation

updates to navigation

---

docs/mint.json
docs/sql/table-structure.mdx
docs/why-mindsdb.mdx

**Fixes** #4368 
- removed Why MindsDB
- renamed MindsDB Default Structure

navigation updates

---

mindsdb/__main__.py
mindsdb/api/http/initialize.py
mindsdb/api/http/namespaces/config.py
mindsdb/api/http/namespaces/configs/default.py
mindsdb/api/http/namespaces/default.py
mindsdb/api/http/start.py
mindsdb/api/mongo/classes/session.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/utilities/config.py
mindsdb/utilities/context.py
mindsdb/utilities/functions.py
tests/integration_tests/flows/config/config.json
tests/integration_tests/flows/test_http.py
tests/integration_tests/flows/test_mysql_api.py
tests/integration_tests/flows/test_mysql_bin_api.py

Simple auth for HTTP and routes to get and edit username/password

simple http auth

---

mindsdb/integrations/libs/ml_handler_proc.py

Don't lint ml_handler_proc.py docstring

Don't lint ml_handler_proc docstring

---

mindsdb/integrations/handlers/openai_handler/openai_handler.py

**Fixes** #4357
Replace `None` values with empty strings for the prompt templating mode.
- N/A I have updated the documentation, or created issues to update them.
- N/A I have shared a short loom video or screenshots demonstrating any new functionality.

[fix] OpenAI null values in prompt templating mode

---

mindsdb/api/http/namespaces/config.py
mindsdb/api/http/namespaces/default.py
mindsdb/api/http/start.py
mindsdb/utilities/config.py
tests/integration_tests/flows/test_http.py

fixed issue with re-reading config file
renamed field in config

fixes for config file reading

---

mindsdb/api/mysql/mysql_proxy/datahub/datanodes/integration_datanode.py
mindsdb/api/mysql/mysql_proxy/executor/executor_client.py
mindsdb/api/mysql/mysql_proxy/executor/executor_wrapper.py
mindsdb/integrations/handlers_client/db_client.py
mindsdb/integrations/handlers_wrapper/db_handler_wrapper.py

`use mindsdb` command didn't work properly for 'microservice` Mindsdb mode in mysql API + `show tables` returns error case operates with None object.

Fix 'use database' command
