mindsdb/mindsdb

mindsdb/integrations/handlers/twilio_handler/twilio_handler.py

Fixes:
- limit is moved to to client side because we need to filter by conditions with limit
- removed fetching media url in message list

Twilio fixes

---

docs/callbacks.mdx

Add description of new field in callback body.

[docs] add `project_name` to callbacks doc

---

mindsdb/integrations/handlers/sendinblue_handler/sendinblue_tables.py

fix syntax error

---

.github/workflows/mindsdb.yml
.pre-commit-config.yaml

update precommit and use in CI/CD

---

docs/sql/create/database.mdx
docs/sql/create/jobs.mdx
docs/sql/create/ml-engine.mdx
docs/sql/create/model.mdx
docs/sql/create/project.mdx
docs/sql/create/view.mdx
docs/sql/drop/database.mdx
docs/sql/drop/jobs.mdx
docs/sql/drop/ml-engine.mdx
docs/sql/drop/model.mdx
docs/sql/drop/project.mdx
docs/sql/drop/view.mdx

updated create and drop commands docs
Fixes #8354 

updated create and drop commands docs

---

docs/integrations/data-integrations/mongodb.mdx
docs/mongo/databases/insertOne.mdx

updated mongo docs

---

docker/release

This PR adds the dependencies for the LightFM handler to Docker image.
Fixes https://github.com/mindsdb/mindsdb/issues/8320

Added Dependencies for LightFM to Docker Image

---

mindsdb/integrations/handlers/anomaly_detection_handler/README.md

Add missing readme to anomaly detection handler
- [✅ ] ⚡ New feature (non-breaking change which adds functionality)
n/a
n/a
n/a

Add anomaly detection handler readme

---

mindsdb/integrations/handlers/confluence_handler/README.md

Adds a query to show how to select a single page from the pages table

doc(Confluence): Update Confluence Handler README

---

mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
requirements/requirements-grpc.txt
requirements/requirements.txt
setup.py
tests/scripts/check_requirements.py

Various requirements tweaks

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
mindsdb/integrations/handlers/chromadb_handler/settings.py
mindsdb/integrations/libs/vectordatabase_handler.py
tests/handler_tests/test_chromadb_handler.py

7270 chromadb support update syntax and upsert

---

Makefile

Update the `install_mindsdb` Makefile instruction to the new path to requirements files.

fix(makefile): Update install_mindsdb instruction

---

docs/agents/agent.mdx
docs/agents/chatbot.mdx
docs/mint.json

docs for agents and chatbots
Fixes #-

docs for agents and chatbots

---

docs/contribute/install.mdx
docs/setup/self-hosted/pip/linux.mdx
docs/setup/self-hosted/pip/macos.mdx
docs/setup/self-hosted/pip/source.mdx
docs/setup/self-hosted/pip/windows.mdx

updated mindsdb installation docs
Fixes #-

updated mindsdb installation docs

---

docs/integrations/ai-engines/langchain.mdx
docs/integrations/app-integrations/slack.mdx
docs/sql/tutorials/create-chatbot.mdx

docs updates: chatbots, langchain, slack

docs updates: chatbots, langchain, slack

---

docs/integrations/ai-engines/anthropic.mdx
docs/integrations/ai-engines/cohere.mdx
docs/integrations/ai-engines/langchain.mdx
docs/integrations/ai-engines/openai.mdx

updates to ai engines doc pages
Fixes #-

updates to ai engines doc pages

---

docs/integrations/ai-engines/anthropic.mdx
docs/integrations/ai-engines/rag.mdx
docs/integrations/ml-engines-overview.mdx
docs/mint.json

added docs for rag
Fixes #8284

added docs for rag

---

tests/scripts/check_requirements.py

Add map of requirement name `auto-ts` -> `auto_ts`

Fix CI: map `auto-ts` requirement name

---

mindsdb/integrations/handlers/shopify_handler/README.md
mindsdb/integrations/handlers/shopify_handler/shopify_tables.py

Fixes #7847
~~~~sql
CREATE DATABASE shopify_datasource
WITH ENGINE = 'shopify',
PARAMETERS = {
"shop_url": "your-shop-name.myshopify.com",
"access_token": "shppa_...",
"yotpo_app_key": "...",
"yotpo_access_token": "..."
};
~~~~
~~~~sql
DELETE FROM shopify_datasource.orders
WHERE id=5632672629053 AND contact_email='egnition_sample_47@egnition.com';
};
~~~~
https://github.com/mindsdb/mindsdb/assets/50673082/9d0a9078-f18f-4122-94e0-aa0b03a76081

Added delete function for order table

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py

Fixes Chromadb_handler http client

ChromaDB HTTP client doesn't work in cloud

---

mindsdb/integrations/handlers/shopify_handler/README.md

Updated the readme file of shopify inetgration

---

docs/integrations/app-integrations/shopify.mdx

Update the  shopify.mdx

---

docs/agents/agent.mdx

updated knowledge bases docs

---

mindsdb/integrations/handlers/clickhouse_handler/clickhouse_handler.py

Added URL escaping for host, username, password, and database fields while parsing the connection config for the CLickhouse handler.
Fixes #8385 

[FIX]: Clickhouse Config Parameter Escaping

---

docs/integrations/data-integrations/mariadb.mdx
docs/integrations/data-integrations/mysql.mdx
mindsdb/integrations/handlers/mariadb_handler/README.md
mindsdb/integrations/handlers/mysql_handler/README.md

updated connection docs for mysql and mariadb
Fixes #7981

updated connection docs for mysql and mariadb

---

docs/sdk_python/create_ml_engine.mdx

made create_ml_engine.mdx (py-sdk)  more clear

---

mindsdb/integrations/handlers/rag_handler/README.md
mindsdb/integrations/handlers/rag_handler/ingest.py
mindsdb/integrations/handlers/rag_handler/requirements.txt
mindsdb/integrations/handlers/rag_handler/settings.py
mindsdb/integrations/handlers/writer_handler/settings.py
requirements/requirements.txt
tests/unit/ml_handlers/test_rag.py

Reapply #8315

---

docs/sql/api/join.mdx

updated join docs

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
mindsdb/interfaces/knowledge_base/controller.py
tests/unit/test_knowledge_base.py

Fix of #8475 
https://github.com/mindsdb/mindsdb/pull/8475#discussion_r1420071200

Fix KB: _df_to_embeddings returns only embedings

---

mindsdb/api/http/namespaces/config.py

Fix: request.json raises exception without json content-type
Fixes: https://github.com/mindsdb/mindsdb-frontend/issues/2006

Fix for werkzeug 2.2.2

---

mindsdb/integrations/handlers/byom_handler/byom_handler.py

Create venv in temp folder and copy it to permanent after creation.
It needs to reduce time when `venv` appear in NFS.

BYOM: copy `venv` after creation

---

README.md

Update README.md to link to the latest hackhathon

Added Hashnode Hackathon link

---

docs/callbacks.mdx

Added `filter` and `attempt` keys to callback config

[doc] New fields in `callbacks` doc

---

mindsdb/integrations/handlers/palm_handler/README.md

Have added the readme for palm handler in mindsdb. 

Readme for PaLM Handler

---

mindsdb/integrations/handlers/Handlers_Manual_QA.md

Done Manual_QA.md for Apache Druid.

---

docs/integrations/data-integrations/amazon-redshift.mdx

Provides some minor grammar and clarity modifications to the Amazon Redshift documentation

Minor grammar and clarity modifications to amazon-redshift.mdx

---

mindsdb/integrations/handlers/byom_handler/byom_handler.py

If create byom-venv model with engine version > 1, then new venv will be created.

Fix unnecessary venv creation when create BYOM model

---

docs/integrations/app-integrations/microsoft-teams.mdx

This PR adds the documentation for the MS Teams integration.
Fixes https://github.com/mindsdb/mindsdb/issues/8504

Updated the Documentation for MS Teams

---

docs/integrations/data-sources-overview.mdx

Update GitLab icon in data sources overview

---

docs/integrations/app-integrations/gmail.mdx

fixed gmail docs

---

mindsdb/__main__.py

- add warning message if low memory. Because of mindsdb now can be used without heavy ML frameworks, warning will be show only if there is < 1Gb of memory
- make final process joining async-friendly
Close #5567

Add warning if low on memory

---

requirements/requirements.txt
tests/integration_tests/flows/test_ts_predictions.py

Update `mindsdb-sql` requirement

---

mindsdb/integrations/handlers/byom_handler/byom_handler.py

- convert to `pathlib.Path` storage path from config
- create storage dirs if not exists

Fix venvs storage creation

---

mindsdb/integrations/handlers/file_handler/requirements.txt
mindsdb/integrations/handlers/gmail_handler/requirements.txt
mindsdb/integrations/handlers/google_fit_handler/requirements.txt
mindsdb/integrations/handlers/google_search_handler/requirements.txt
mindsdb/integrations/handlers/langchain_embedding_handler/requirements.txt
mindsdb/integrations/handlers/langchain_handler/requirements.txt
mindsdb/integrations/handlers/llama_index_handler/requirements.txt
mindsdb/integrations/handlers/neuralforecast_handler/requirements_extra.txt
mindsdb/integrations/handlers/rag_handler/requirements.txt
mindsdb/integrations/handlers/statsforecast_handler/requirements_extra.txt
mindsdb/integrations/handlers/writer_handler/requirements.txt
mindsdb/integrations/handlers/youtube_handler/requirements.txt
requirements/requirements.txt
tests/scripts/check_requirements.py

added missing reqs to youtube handler
discussed here: https://mindsdbcommunity.slack.com/archives/C04EWFQEFEV/p1702899569784249

added missing reqs to youtube handler

---

docker/docker-bake.hcl

Added: timegpt,surrealdb,youtube,ignite,gmail,pgvector

Add handlers deps to dev

---

docs/integrations/data-sources-overview.mdx

Update PayPal icon in data sources overview

---

docs/finetune/anyscale.mdx
docs/sql/api/finetune.mdx

adding ref diagrams

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/README.md

Adds docs for AnyscaleEndpoints. Includes differences with OpenAI ML engine and an example.
ML Engine documentation.
Checked example works end to end.

[docs] Add README for AnyscaleEndpoints ML engine

---

.github/workflows/add_to_pr_review.yml

Fix `add_to_pr_review` action

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
mindsdb/integrations/handlers/openai_handler/helpers.py
mindsdb/integrations/handlers/openai_handler/openai_handler.py

Minor fixes for new API & improved JSONL checking

[fix] AnyscaleEndpoints: minor fixes for new API & improved jsonl checking

---

mindsdb/__about__.py

bump to 23.12.4.2 for release

---

docs/README.md
docs/ai-engines/overview.mdx
docs/connect/connect-mariadb-skysql.mdx
docs/connect/mongo-compass.mdx
docs/connect/tableau.mdx
docs/finetune/anyscale.mdx
docs/integrations/ai-engines/rag.mdx
docs/integrations/ai-engines/vertex.mdx
docs/integrations/app-integrations/twitter.mdx
docs/integrations/integrations.mdx
docs/manual-qa/template.mdx
docs/mint.json
docs/quickstart.mdx
docs/setup/aws.mdx
docs/setup/cloud.mdx
docs/setup/gcp.mdx
docs/setup/self-hosted/docker-desktop.mdx
docs/setup/self-hosted/docker.mdx
docs/setup/self-hosted/pip/linux.mdx
docs/sql/create/jobs.mdx
docs/what-is-mindsdb.mdx

Docs updates [fixes to broken links and some docs]

---

docs/mint.json
docs/sql/tutorials/rag.mdx

- fixed tab content in docs
- further docs updates coming soon

fixed tab content in docs

---

mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py

Update deps install log message

---

docs/finetune/anyscale.mdx
docs/integrations/ai-engines/replicate-audio.mdx
docs/integrations/ai-engines/replicate-img2text.mdx
docs/integrations/ai-engines/replicate-llm.mdx
docs/integrations/ai-engines/replicate-text2img.mdx
docs/integrations/ai-engines/replicate-text2video.mdx
mindsdb/integrations/handlers/replicate_handler/README.md

* Update Replicate docs to include setting up api key as env var using pip and Docker
* Fix formating issue on anyscale docs
* Update Replicate README
Related to https://github.com/mindsdb/mindsdb/issues/8588

Replicate docs update

---

mindsdb/integrations/handlers/file_handler/file_handler.py
mindsdb/integrations/handlers/file_handler/requirements.txt
requirements/requirements.txt

fix issue with pdf upload in cloud
loom video: https://www.loom.com/share/f1174519df794f9b8312a8cd5f5a81e9

fix issue with pdf upload in cloud

---

docs/integrations/ai-engines/openai.mdx

Update Openai docs to use the default `mindsdb` project

Update default project

---

docker/docker-bake.hcl

Cloud images currently don't have these

Fix neuralforecast and statsforecast in cloud image

---

docs/agents/chatbot.mdx
docs/integrations/app-integrations/slack.mdx

added info about which slack connection method to use with the chatbot syntax

added info about which slack connection method to use with the chatbot syntax

---

docs/finetune/anyscale.mdx

linked mistral 7b finetuning blog post

linked finetuning blog post

---

mindsdb/integrations/handlers/vertex_handler/requirements.txt
tests/scripts/check_requirements.py

Added vertex dependency ([was removed](https://github.com/mindsdb/mindsdb/pull/8134/files#diff-9e507b7f5f4cb315e928474987c387b57ead2a36ebd08a2936319ba75a3bf24fL1) before)

Fix vertex dependency 

---

docs/sql/api/describe.mdx
docs/sql/api/finetune.mdx
docs/sql/api/retrain.mdx

updated syntax of describe, retrain, finetune
Fixes #[issue](https://github.com/mindsdb/mindsdb_sql/issues/303)

updated syntax of describe, retrain, finetune

---

mindsdb/integrations/handlers/vertex_handler/README.md

Fix vertex install instructions

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
mindsdb/integrations/handlers/chromadb_handler/tests/test_chromadb_handler.py
mindsdb/integrations/libs/vectordatabase_handler.py

fix issuess with drop table with `chromadb_handler`

fix drop table for vectordatabase_handler.py and specifically chroma

---

docs/sql/tutorials/create-chatbot.mdx

updated agent/chatbot tutorial

updated agent/chatbot tutorial

---

docs/integrations/ai-engines/timegpt.mdx

updated timegpt docs with more info about WINDOW param

updated timegpt docs with more info

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/__init__.py

Marks AnyscaleEndpoints integration as permanent.

[fix] Mark anyscale endpoints integration as permanent

---

mindsdb/api/http/namespaces/handlers.py
mindsdb/integrations/handlers/byom_handler/byom_handler.py

- fix empty file uploading (may be required for `requirements.txt`)
- fix BYOM venv paths on windows
Fixes #8608

Fix BYOM venv paths on windows

---

docs/mindsdb_sql/agents/agent.mdx
docs/mindsdb_sql/agents/chatbot.mdx
docs/mindsdb_sql/agents/knowledge-bases.mdx
docs/mint.json
docs/rest/agents/agent.mdx
docs/rest/agents/chatbot.mdx
docs/sql/tutorials/create-chatbot-kb.mdx

updated docs re agents/chatbots/kb
waiting for info whether knowledge bases require embedding model - to be updated in docs

updated docs re agents/chatbots/kb

---

mindsdb/integrations/handlers/sendinblue_handler/sendinblue_tables.py

Added import for Text in sendinblue_tables.py

updated sendinblue_tables.py

---

mindsdb/__main__.py
mindsdb/interfaces/storage/db.py
mindsdb/migrations/migrate.py
mindsdb/migrations/versions/2023-12-25_4b3c9d63e89c_predictor_index.py

- The differences between the models and current DB state have been removed.
- Improved console output when applying migrations 

Update internal db

---

mindsdb/__about__.py

Bump mindsdb version

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py

Get `anyscale_endpoints` api key from env

Proper get `anyscale_endpoints` api key

---

docs/mindsdb_sql/syntax.mdx
docs/mint.json
mindsdb/integrations/handlers/ms_teams_handler/requirements.txt

sql syntax document page

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
mindsdb/integrations/libs/ml_exec_base.py

This is a hotfix while #8245 (#7496) is merged.

[fix] Anyscale key getter

---

README.md

Fix: Typo in documentation

---

mindsdb/api/mongo/utilities/mongodb_parser.py
tests/unit/test_mongodb_handler.py

Accept name in
``` mql: db.tbl.find({_id: 1}) ```
Fixes #8272

Fix mongodb parsing

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
mindsdb/integrations/handlers/openai_handler/openai_handler.py
requirements/requirements-test.txt

Fixes issue introduced in #8693 when exiting the context handler.

[fix] Key error when exiting context handler

---

docs/contribute/install.mdx
docs/integrations/integrations.mdx
docs/mindsdb_sql/sql/create/jobs.mdx
docs/mint.json
docs/setup/self-hosted/docker.mdx

- installation docs (updated docker, removed pip)
- integrations overview (added info about 'show handlers' and dependencies)
- updated titles in SQL API

installation docs updates

---

tests/unit/test_project_structure.py

Returned tests with last to #8662

Return tests with last to #8662

---

mindsdb/integrations/handlers/rag_handler/ingest.py
mindsdb/integrations/handlers/rag_handler/rag.py
mindsdb/integrations/handlers/rag_handler/requirements.txt
mindsdb/integrations/handlers/rag_handler/settings.py

`rag_handler`
- adjustment to core settings
- update requirements.txt, seems langchain as added more optional requirements in later version. So they are required to be installed manually
- Chroma seems to support batching under the hood now, I have removed batching

Fix RAG post openai changes

---

mindsdb/integrations/handlers/whatsapp_handler/whatsapp_handler.py

Imports the updated `logger`, fixes error messages
Fixes #8716
```sql
INSERT INTO my_twilio_test.messages (body, from_number, to_number)
VALUES('woww, such a cool integration', 'whatsapp:+14155238886', 'whatsapp:+15519990863');
```

Fixed: Whatsapp logger issue

---

mindsdb/integrations/handlers/google_analytics_handler/__init__.py

Changes:
- remove Google_analytics handler from permanent handlers
To remove it from user:
```sql
drop database google_analytics
```

Google_analytics is not permanent

---

mindsdb/integrations/handlers/autogluon_handler/__init__.py
mindsdb/integrations/handlers/autokeras_handler/__init__.py
mindsdb/integrations/handlers/clipdrop_handler/__init__.py
mindsdb/integrations/handlers/flaml_handler/__init__.py
mindsdb/integrations/handlers/leonardoai_handler/__init__.py
mindsdb/integrations/handlers/monkeylearn_handler/__init__.py
mindsdb/integrations/handlers/pycaret_handler/__init__.py
mindsdb/integrations/handlers/stabilityai_handler/__init__.py
mindsdb/integrations/handlers/tpot_handler/__init__.py

Removed permanent flag for:
- autogluon
- autokeras
- clipdrop
- FLAML
- leonardo_ai
- monkeylearn
- pycaret
- stabilityai
- TPOT

Remove permanent for some ml handlers

---

docs/integrations/data-integrations/postgresql.mdx

updates to postgres docs

---

docs/integrations/app-integrations/youtube.mdx

added two connection options to yt docs

youtube docs

---

mindsdb/integrations/handlers/anomaly_detection_handler/anomaly_detection_handler.py

Sync files of anomaly detection handler
Fixes #8708

Save anomaly_detection files to storage

---

docs/integrations/app-integrations/youtube.mdx

youtube docs for connecting

---

.github/workflows/deploy-dev.yml
docker/docker-bake.hcl

Add snowflake and clickhouse to cloud images

---

docs/finetune/openai.mdx
docs/integrations/ai-engines/openai.mdx
docs/nlp/nlp-mindsdb-openai.mdx

updated deprecated openai models
Fixes #8753

updated deprecated openai models

---

docs/integrations/ai-engines/twelvelabs.mdx
mindsdb/integrations/handlers/twelve_labs_handler/twelve_labs_api_client.py

This PR fixes #8747 by providing the raw binary file when using local files to create an index.

Fix Twelve Labs indexing local file

---

docs/integrations/ai-engines/neuralforecast.mdx

updated neuralforecast parameters in docs
*** this can be merged after [this bug](https://github.com/mindsdb/mindsdb/issues/7321) is resolved

updated neuralforecast parameters in docs

---

README.md

Update README.md with the new messaging

---

mindsdb/integrations/handlers/libsql_handler/libsql_handler.py

This PR fixes the incorrect use of the logger in the LibSQL handler.

Corrected Use of Logger in LibSQL Handler

---

docs/what-is-mindsdb.mdx

updated mindsdb intro

---

docker/docker-bake.hcl

Add couchbase to cloud docker image

---

docs/sql/tutorials/twitter-chatbot.mdx

Update twitter-chatbot.mdx to use LAST

---

docs/sql/tutorials/slack-chatbot.mdx

updated slack chatbot tutorial
Fixes #8771

updated slack chatbot tutorial

---

docs/mint.json
docs/what-is-mindsdb.mdx

updated intro docs

---

docs/mindsdb_sql/sql/create/jobs.mdx

updated last keyword docs

---

mindsdb/__about__.py

bump version

---

docs/integrations/ai-engines/anyscale.mdx
docs/mint.json
docs/sdks/javascript/overview.mdx
docs/sdks/mongo/mindsdb-mongo-ql-overview.mdx
docs/sdks/python/overview.mdx

- added anyscale docs
- fixed links in sdks

added anyscale docs

---

docs/integrations/ai-engines/rag.mdx

rag param update in docs

---

mindsdb/integrations/utilities/handler_utils.py

Fix getting api key

---

docs/setup/community-deploys-mindsdb.mdx

A link to the tutorial on deploying MindsDB on Linode has been added.

Update Other Clouds Deployment Page

---

tests/integration_tests/flows/test_predict_text_sentiment_openai_tutorial.py

Args for openai handler was changed in one of previous pr. This PR fixing it in test

Fix args in `test_predict_text_sentiment_openai_tutorial` 

---

docs/setup/self-hosted/docker.mdx

Assuming it was meant to be mdb for mindsdb

Typo "mbd" vs "mdb"

---

docker/docker-bake.hcl

Add 12labs handler to cloud

---

docs/finetune/openai.mdx
docs/integrations/ai-engines/huggingface_inference_api.mdx
docs/integrations/ai-engines/timegpt.mdx
docs/integrations/ai-engines/twelvelabs.mdx
docs/mindsdb_sql/agents/agent.mdx
docs/mindsdb_sql/agents/knowledge-bases.mdx
docs/sdks/python/create_ml_engine.mdx
docs/sql/tutorials/create-chatbot-kb.mdx
docs/sql/tutorials/create-chatbot.mdx
docs/sql/tutorials/twitter-chatbot.mdx

fixed api_key param names throughout docs

fixed api_key param names

---

docs/finetune/anyscale.mdx
docs/finetune/classification.mdx
docs/finetune/openai.mdx
docs/finetune/regression.mdx
docs/mindsdb_sql/sql/api/finetune.mdx

added info to finetune commands
Fixes -- https://github.com/mindsdb/mindsdb/issues/8757#issuecomment-1934690267

added info to finetune commands

---

mindsdb/integrations/handlers/sendinblue_handler/sendinblue_tables.py

Added insert method for email campaigns table
Fixes #8115 
content and subject:
Name:

Added insert method for email campaigns table

---

docs/mint.json
docs/rest/models/query-model-joined-with-data.mdx

update to rest api docs

---

mindsdb/integrations/handlers/openai_handler/openai_handler.py

Fix: If try to `describe` broken openai model, then error is appear.
Close #8828

Fix `describe` of broken openai model

---

docs/mindsdb_sql/sql/create/table.mdx

added a note that create table needs database with write access

added a note that create table needs database with write access

---

docs/integrations/ai-engines/anomaly.mdx

This PR adds link to the dataset used in the anomaly detection docs.

Update Anomaly detection docs

---

docs/sql/tutorials/eeg-forecasting.mdx

added eeg forecast tutorial

---

docs/finetune/anyscale.mdx

fixed query in tutorial

---

docs/mint.json
docs/sql/tutorials/expenditures-statsforecast.mdx
docs/sql/tutorials/home-rentals.mdx
docs/sql/tutorials/house-sales-forecasting.mdx
docs/sql/tutorials/text-sentiment-hf.mdx
docs/sql/tutorials/twitter-chatbot.mdx

updated tutorials for learning hub
/sql/tutorials/real-time-trading-forecasts
/sql/tutorials/twitter-chatbot
/sql/tutorials/house-sales-forecasting
/sql/tutorials/expenditures-statsforecast
/sql/tutorials/home-rentals
/sql/tutorials/text-sentiment-hf

updated tutorials for learning hub

---

docs/finetune/anyscale.mdx
mindsdb/api/executor/command_executor.py
mindsdb/api/executor/datahub/datanodes/information_schema_datanode.py
mindsdb/interfaces/model/model_controller.py
tests/unit/test_executor.py
tests/unit/test_project_structure.py

Fixes:
- create model, if database doesn't exist show clear error instead of 'key error'
- fix anyscale tutorial query
- show support 
-  "agents", "jobs", "skills", "chatbots"

PR for small fixes on hachaton 

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py
mindsdb/integrations/handlers/openai_handler/openai_handler.py

If api key provided during mk_engine creation (OpenAI or Anyscale-endpoints), then do check the key. If not - do nothing. 
Close #8846

Validate api key during OpenAI or Anyscale-endpoints ml_engine creation

---

mindsdb/integrations/handlers/timegpt_handler/timegpt_handler.py

This PR adds a token validate step when using the TimeGPT

Validate the timegpt token

---

.github/workflows/deploy-staging.yml

Add multi-eploy steps to all staging and development-related environments.

Add multi environment deploy step

---

.github/workflows/deploy-staging.yml

add deploy to staging when mergeing to staging branch

---

docs/integrations/ai-engines/anomaly.mdx
mindsdb/api/executor/command_executor.py

Fix show command

---

docs/finetune/openai.mdx

update file link

---

mindsdb/api/http/namespaces/handlers.py

This PR removes non-integrations (`dummy_data` and `utilities`) from the `GET /handlers` API endpoint.

Removed Non-integrations from the /handlers Endpoint

---

mindsdb/integrations/handlers/cloud_spanner_handler/cloud_spanner_handler.py
mindsdb/integrations/handlers/cloud_spanner_handler/requirements.txt
mindsdb/integrations/handlers/datastax_handler/__init__.py
mindsdb/integrations/handlers/sharepoint_handler/sharepoint_tables.py
tests/scripts/check_requirements.py

This PR fixes a few handlers that have become unusable due to slight errors in the code. The handlers fixed and their respective fix applied have been stated below,
- SharePoint: fixed a few incorrect type hints.
- Google Cloud Spanner: fixed a couple of incorrect imports and added the relevant dependencies required.
- Astra DB (DataStax): removed incorrect import of `connection_args`, which has not been defined.

Fixed Several Unusable Handlers

---

docs/sql/tutorials/slack-chatbot.mdx

fixed slack chatbot tutorial (column name in channels table)
Fixes #8813

fixed slack chatbot tutorial

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/README.md

Remove duplicated block in handler readme and mindsdb docs

Less redundant doc example

---

docs/integrations/app-integrations/github.mdx

fixed github docs

---

mindsdb/api/http/namespaces/file.py
mindsdb/integrations/handlers/file_handler/file_handler.py

- make `langchain_community` dependency optional for mindsdb
- improve files deletion if upload is failure
Fixes #8874

Make `langchain_community` dependency optional

---

mindsdb/integrations/handlers/github_handler/github_tables.py

Fix filtering by some columns
Fixes #8876

fix `github_tables` filtering 

---

mindsdb/integrations/handlers/web_handler/__init__.py

This PR makes the web handler optional to avoid bugs as #8818 
Fixes #8818

Make web handler optional

---

docs/integrations/ai-engines/twelvelabs.mdx
mindsdb/integrations/handlers/twelve_labs_handler/README.md
mindsdb/integrations/handlers/twelve_labs_handler/twelve_labs_api_client.py
mindsdb/integrations/handlers/twelve_labs_handler/twelve_labs_handler.py

This PR:
1. Updates the README and Docs for the  summarization task
2. Fixes #8882 by sending the endpoint query path in the requests
3. To avoid the GUI bug https://github.com/mindsdb/mindsdb-frontend/issues/2380 with parsing NaN values, we `fillna` the df NaN's with 0
4. Return response.content when error happen instead of response message which was resulting in invalid key in a case of error.

Twelvelabs Integration fixes

---

mindsdb/integrations/handlers/d0lt_handler/d0lt_handler.py

This PR fixes an import statement in the D0lt handler that makes it unusable.

Fixed the Import of MatrixOneHandler in D0lt Handler

---

mindsdb/api/executor/sql_query/steps/subselect_step.py
mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
mindsdb/integrations/libs/vectordatabase_handler.py
mindsdb/interfaces/query_context/context_controller.py
tests/unit/test_project_structure.py

Fixes: 
- fix bug when 'table join model' has no other conditions except last  
- fix saving metadata in pgvector

Fix last: one condition in view

---

mindsdb/integrations/handlers/anomaly_detection_handler/anomaly_detection_handler.py

This PR solves #8893 by using sklearn.preprocesing StandardScaler to standardize the data and avoid divisons by zero and getting NaN values.
Fixes #8893 

Anomaly detection process data bug

---

docs/what-is-mindsdb.mdx

updated middleware to platform

updated middleware to platform

---

.github/workflows/mindsdb.yml

This PR solves an issue with running coveralls through GitHub Actions

Fix failing coveralls action

---

mindsdb/api/executor/command_executor.py
mindsdb/api/mysql/mysql_proxy/executor/mysql_executor.py

Fixed connection ID selection.
Fixes #8919

Fix `select connection_id()`

---

setup.py

fix setup limits

---

mindsdb/__about__.py

Bump mindsdb version to 24.3.4.0

Bump mindsdb version to 24.3.4.0

---

mindsdb/api/executor/command_executor.py
mindsdb/api/executor/datahub/datanodes/integration_datanode.py
mindsdb/api/executor/datahub/datanodes/project_datanode.py
mindsdb/api/executor/sql_query/steps/__init__.py
mindsdb/api/executor/sql_query/steps/insert_step.py

Create empty table
```sql
CREATE or replace table my_pg.aaa1 (
id int8,
data varchar
) 
```
Depend on [mindsdb_sql PR](https://github.com/mindsdb/mindsdb_sql/pull/363)

Create empty table

---

requirements/requirements.txt

Empty PR for update mindsdb_sql requirement

Bump mindsdb sql version

---

mindsdb/integrations/handlers/lightwood_handler/requirements.txt

Bump lightwood requirements to v24.3.3.1

Bump lightwood requirements

---

docs/integrations/ai-engines/twelvelabs.mdx
mindsdb/integrations/handlers/twelve_labs_handler/README.md
mindsdb/integrations/handlers/twelve_labs_handler/settings.py
mindsdb/integrations/handlers/twelve_labs_handler/twelve_labs_api_client.py
mindsdb/integrations/handlers/twelve_labs_handler/twelve_labs_handler.py

This PR adds the `prompt` parameter for the TwelveLabs `summarization` tasks.
Fixes #8922 
- [] 📄 This change requires a documentation update

Prompt parameter for TwelveLabs

---

mindsdb/api/http/namespaces/tree.py

Set `system view` type for log tables in `GET /tree/log` response

Set type for log tables in `GET /tree/log` response

---

mindsdb/integrations/handlers/timegpt_handler/timegpt_handler.py

[fix] Fix TimeGPT token retrieval

---

.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

fix staging/prod tests

---

mindsdb/integrations/handlers/huggingface_handler/requirements.txt
mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt

Set correct dependency version

Fix huggingface's `transformers` dependency

---

.github/workflows/build_deploy_dev.yml
.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

Change CI build branch

---

.github/workflows/matrix_includes.json

Del py 3.11 from tests matrix

---

mindsdb/integrations/handlers/github_handler/github_tables.py
mindsdb/integrations/handlers/slack_handler/slack_handler.py
mindsdb/integrations/libs/api_handler.py

Changes:
- created APIResource base class for api table
- all github handler tables converted to APIResource
Overview
https://www.loom.com/share/551ae5b9330b4751a990b5e5b3694115

Github handler: all tables converted to APIResource

---

.github/actions/docker-bake/action.yml

Fix image tags

---

mindsdb/__about__.py

Bump version to v24.3.4.2

---

docs/mindsdb_sql/agents/agent.mdx
docs/mindsdb_sql/agents/chatbot.mdx
docs/mindsdb_sql/sql/create/jobs.mdx
docs/mindsdb_sql/sql/create/table.mdx
docs/mindsdb_sql/sql/query-jobs.mdx
docs/sql/project.mdx
docs/sql/tutorials/customer-reviews-notifications.mdx
docs/sql/tutorials/slack-chatbot.mdx
docs/sql/tutorials/twilio-chatbot.mdx
docs/sql/tutorials/twitter-chatbot.mdx
mindsdb/interfaces/jobs/README.md

mindsdb sql docs updates (in progress):
* updated jobs_history - https://github.com/mindsdb/mindsdb/pull/8793
* updated SHOW commands
* updated CREATE TABLE

mindsdb sql updates for docs

---

.github/workflows/test_on_push.yml
MANIFEST.in

add default handlers to manifest and fix pip install test

---

mindsdb/__about__.py

Bump version to 24.3.5.0

---

mindsdb/utilities/fs.py

Fix tarfile safe extract

---

docs/quickstart-tutorial.mdx

Minor update to query formatting. 
- [n/a] I have attached a brief loom video or screenshots showcasing the new functionality or change.

Update query format in quickstart-tutorial.mdx

---

docs/integrations/ai-engines/huggingface_inference_api.mdx

[404] fix url in  huggingface_inference_api.mdx

---

mindsdb/integrations/handlers/openai_handler/helpers.py
mindsdb/integrations/handlers/openai_handler/openai_handler.py

This PR removes the hardcoded base URL for openai and also provides an option to read the base URL from connection args created with CREATE ML Engine
Fixes #9013

Fix hardcoded API base 

---

docs/callbacks.mdx
docs/finetune/anyscale.mdx
docs/finetune/data.csv
docs/finetune/regression.mdx
docs/getting-started.mdx
docs/integrations/ai-engines/openai.mdx
docs/mindsdb_sql/agents/agent.mdx
docs/mindsdb_sql/connect/metabase.mdx
docs/mindsdb_sql/sql/native-queries.mdx
docs/nlp/nlp-mindsdb-openai.mdx
docs/quickstart.mdx
docs/sql/feature-eng.mdx
docs/sql/tutorials/customer-churn.mdx
docs/sql/tutorials/eeg-forecasting.mdx
docs/sql/tutorials/home-rentals.mdx
docs/sql/tutorials/house-sales-forecasting.mdx
docs/sql/tutorials/text-sentiment-hf.mdx
mindsdb/README.md
mindsdb/integrations/handlers/hsqldb_handler/README.md

updated hostname of sample dbs

updated hostname of sample dbs

---

docs/integrations/app-integrations/email.mdx

updated email integration docs
Fixes [#issue_number](https://github.com/mindsdb/mindsdb_private/issues/480)

updated email integration docs

---

mindsdb/__about__.py

Bump version for release

---

docs/integrations/ai-engines/lightfm.mdx

This PR adds a tip about the need to install a couple of Linux development package in the Docker container before installing the dependencies for the LightFM integration.
Fixes https://github.com/mindsdb/mindsdb/issues/9040

Updated LightFM Integration Docs with Tip to Install Linux Dev Pakcages

---

docs/callbacks.mdx
docs/finetune/anyscale.mdx
docs/finetune/data.csv
docs/finetune/regression.mdx
docs/getting-started.mdx
docs/integrations/ai-engines/openai.mdx
docs/mindsdb_sql/agents/agent.mdx
docs/mindsdb_sql/connect/metabase.mdx
docs/mindsdb_sql/sql/native-queries.mdx
docs/nlp/nlp-mindsdb-openai.mdx
docs/quickstart.mdx
docs/sql/feature-eng.mdx
docs/sql/tutorials/customer-churn.mdx
docs/sql/tutorials/eeg-forecasting.mdx
docs/sql/tutorials/home-rentals.mdx
docs/sql/tutorials/house-sales-forecasting.mdx
docs/sql/tutorials/text-sentiment-hf.mdx
mindsdb/README.md
mindsdb/integrations/handlers/hsqldb_handler/README.md
mindsdb/integrations/utilities/test_utils.py
tests/api/http/agents_test.py
tests/api/http/chatbots_test.py
tests/api/http/models_test.py
tests/api/http/tables_test.py
tests/integration_tests/flows/test_forecast_quaterly_house_tutorial.py
tests/integration_tests/flows/test_home_rental_prices_tutorial.py
tests/integration_tests/flows/test_predict_text_sentiment_huggingface_tutorial.py
tests/integration_tests/flows/test_ts_predictions.py

Updates demo database references to the new K8s service.

update sampledatabases to new k8s server

---

mindsdb/integrations/handlers/mongodb_handler/mongodb_handler.py

The "database" field in the form is changed to not required.
Fixes https://github.com/mindsdb/mindsdb-frontend/issues/2474

The "database" field in the form is changed to not required.

---

docs/integrations/data-integrations/mongodb.mdx

updated broken links in mongo docs

updated broken links in mongo docs

---

mindsdb/__about__.py

Bump version to 24.4.3.0

---

mindsdb/api/executor/datahub/datanodes/information_schema_datanode.py
mindsdb/interfaces/knowledge_base/controller.py

Changes:
- show 'params' in list of KBs (required by python sdk)
- readable exception if vectordb is deleted
Fix:
- fix insertion to KB bug (made in #9005)

Kb updates 04.2024

---

docs/mindsdb_sql/agents/agent.mdx
docs/sql/tutorials/create-chatbot.mdx

updated agent skills in docs

---

.github/workflows/build_deploy_dev.yml
.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

Use the new auto-scaling github runners

Switch to new GHA runners

---

tests/README.md
tests/load/tasks.py
tests/load/test_postgresql.py
tests/load/tests_start.py

This PR fixes the load tests that were previously broken and updates the documentation (README) for running all tests with accurate information.

Fixed Load Tests and Test Docs (README)

---

docs/integrations/data-integrations/mysql.mdx
docs/integrations/data-integrations/postgresql.mdx
mindsdb/integrations/handlers/mysql_handler/README.md
mindsdb/integrations/handlers/postgres_handler/README.md

updated mysql docs + readme according to the template
updated postgres docs + readme according to the template

mysql and postgres docs + readme updates

---

docker/docker-bake.hcl

add bigquery to cloud image

---

docs/mindsdb_sql/sql/create/trigger.mdx
docs/mindsdb_sql/sql/drop/trigger.mdx
docs/mindsdb_sql/sql/query-triggers.mdx

updated triggers docs - added available data sources

updated triggers docs

---

mindsdb/integrations/handlers/byom_handler/byom_handler.py

Fixes a small bug that leads to failure when describing BYOM-produced models because the dataframe is not correctly decoded.

[fix] dataframe encode in byom describe

---

mindsdb/integrations/handlers/anomaly_detection_handler/README.md

Replace dead links, and bring over information from private document, explaining reasoning behind learning paradigm dispatch.

[docs] Improved readme for anomaly detection handler

---

mindsdb/integrations/handlers/web_handler/README.md

Minor changes will be made to the README until we verify it. The important change was changing the comments in the query to make it executable in GUI and changing the Python website to correct URL + minor typos.

Update Web Handler README

---

docs/integrations/ai-engines/anthropic.mdx
docs/integrations/ai-engines/anyscale.mdx
docs/integrations/ai-engines/cohere.mdx
docs/integrations/ai-engines/huggingface.mdx
docs/integrations/ai-engines/huggingface_inference_api.mdx
docs/integrations/ai-engines/langchain.mdx
docs/integrations/ai-engines/mindsdb_inference.mdx
docs/integrations/ai-engines/ollama.mdx
docs/integrations/ai-engines/rag.mdx
docs/integrations/data-integrations/mysql.mdx
docs/integrations/data-integrations/postgresql.mdx
mindsdb/integrations/handlers/anthropic_handler/README.md
mindsdb/integrations/handlers/anyscale_endpoints_handler/README.md
mindsdb/integrations/handlers/cohere_handler/README.md
mindsdb/integrations/handlers/huggingface_api_handler/README.md
mindsdb/integrations/handlers/huggingface_handler/README.md
mindsdb/integrations/handlers/langchain_handler/README.md
mindsdb/integrations/handlers/mindsdb_inference/README.md
mindsdb/integrations/handlers/mysql_handler/README.md
mindsdb/integrations/handlers/ollama_handler/README.md
mindsdb/integrations/handlers/postgres_handler/README.md
mindsdb/integrations/handlers/rag_handler/README.md

updated docs links in completed readmes&docs for integrations

updated docs links in completed readmes&docs for integrations

---

docs/use-cases/automated_finetuning/openai.mdx

updated a link in openai finetuning tutorial

updated a link in openai finetuning tutorial

---

docs/integrations/data-integrations/clickhouse.mdx
docs/integrations/data-integrations/mysql.mdx
docs/mindsdb_sql/sql/create/trigger.mdx
docs/mindsdb_sql/sql/drop/trigger.mdx
docs/mindsdb_sql/sql/query-triggers.mdx
docs/use-cases/ai-powered_data_retrieval/semantic_search.mdx
mindsdb/integrations/handlers/clickhouse_handler/README.md
mindsdb/integrations/handlers/mysql_handler/README.md

Update doc links for branch rename

---

mindsdb/api/executor/command_executor.py

Fix for https://github.com/mindsdb/mindsdb/pull/9128
Fix using DropMLEngine command
- it is used if handler dependencies are not installed  

Fix drop ml-engine

---

docs/integrations/ai-engines/byom.mdx
docs/mindsdb-gui.mdx
docs/sdks/javascript/connect.mdx
docs/sdks/mongo/connect/mongo-compass.mdx
docs/sdks/mongo/connect/mongo-shell.mdx
docs/sdks/python/connect.mdx

removed ref to mindsdb (cloud) pro

removed ref to mindsdb (cloud) pro

---

docs/integrations/ai-engines/anomaly.mdx
docs/mint.json
docs/use-cases/predictive_analytics/overview.mdx
mindsdb/integrations/handlers/anomaly_detection_handler/README.md

Anomaly detection docs

---

mindsdb/integrations/handlers/autogluon_handler/requirements.txt
mindsdb/integrations/handlers/autosklearn_handler/requirements.txt
mindsdb/integrations/handlers/flaml_handler/requirements.txt
mindsdb/integrations/handlers/lightwood_handler/requirements.txt
mindsdb/integrations/handlers/tpot_handler/requirements.txt

Bump type_infer to 0.0.20

---

.dockerignore
Makefile

add docker commands to makefile

---

docs/integrations/ai-engines/mindsdb_inference.mdx

updated handler link in mindsdb_inference docs

updated handler link

---

docs/integrations/ai-engines/mindsdb_inference.mdx
mindsdb/integrations/handlers/mindsdb_inference/README.md

This PR adds the troubleshooting guide for the MindsDB Inference handler as part of the steps for making it enterprise-ready.

Added the Troubleshooting Guide for the MindsDB Inference Handler

---

docs/mint.json

added feedback question to all docs

added feedback question to all docs

---

.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

Fix concurrency settings

---

docs/integrations/ai-engines/statsforecast.mdx
docs/use-cases/data_enrichment/question-answering-inside-mongodb-with-openai.mdx
docs/use-cases/data_enrichment/sentiment-analysis-inside-mongodb-with-openai.mdx
docs/use-cases/data_enrichment/text-summarization-inside-mongodb-with-openai.mdx

updated mongo syntax

---

docs/mint.json

removing agents from python sdk docs (as discussed with product team)

removing agents from python sdk docs

---

mindsdb/integrations/handlers/anyscale_endpoints_handler/anyscale_endpoints_handler.py

This PR fixes the authentication errors raised by the Anyscale handler even when passing valid API keys by correctly setting the base URL to point the Anyscale API. The code is also cleaned up slightly by removing unused functions and duplicate code.
Fixes https://github.com/mindsdb/mindsdb/issues/9189
Create:
Predict:

Fixed Authentication Errors Raised by Anyscale Handler

---

docs/mint.json

hidden rest api for agents from navigation (same reason as for for python sdk)

removed rest api for agents

---

docs/use-cases/automated_finetuning/anyscale.mdx
docs/use-cases/automated_finetuning/classification.mdx
docs/use-cases/automated_finetuning/openai.mdx
docs/use-cases/automated_finetuning/regression.mdx

updated automated finetuning tutorials with new syntax for fine-tuning job

updated automated finetuning tutorials

---

docs/features/ai-integrations.mdx
docs/features/data-integrations.mdx
docs/features/model-management.mdx
docs/integrations/ai-engines/replicate-audio.mdx
docs/integrations/ai-engines/replicate-img2text.mdx
docs/integrations/ai-engines/replicate-llm.mdx
docs/integrations/ai-engines/replicate-text2img.mdx
docs/integrations/ai-engines/replicate-text2video.mdx
docs/integrations/ai-engines/twelvelabs.mdx
docs/integrations/ai-overview.mdx
docs/integrations/data-overview.mdx
docs/integrations/integrations.mdx
docs/mindsdb_sql/overview.mdx
docs/mint.json
docs/rest/overview.mdx
docs/sdks/overview.mdx
docs/use-cases/ai-powered_data_retrieval/overview.mdx
docs/use-cases/ai_agents/overview.mdx
docs/use-cases/ai_workflow_automation/overview.mdx
docs/use-cases/automated_finetuning/overview.mdx
docs/use-cases/data_enrichment/overview.mdx
docs/use-cases/in-database_ml/overview.mdx
docs/use-cases/predictive_analytics/overview.mdx
docs/what-is-mindsdb.mdx

enhanced user journey through docs:
- improved the docs landing page
- improved linking of doc pages overall
- updated overview pages for dev envs to guide users step-by-step
preview here - https://www.loom.com/share/c8adf9f625a548af9b465dc5ecd11d01

enhanced user journey through docs

---

docs/use-cases/data_enrichment/question-answering-inside-mongodb-with-openai.mdx
docs/use-cases/data_enrichment/sentiment-analysis-inside-mongodb-with-openai.mdx
docs/use-cases/data_enrichment/text-summarization-inside-mongodb-with-openai.mdx

updated mql tutorials

---

mindsdb/integrations/handlers/lightwood_handler/requirements.txt
requirements/requirements-test.txt
requirements/requirements.txt

Use new release of lightwood, which fixes an installation issue on macos

bump lightwood version

---

docs/contribute/contribute.mdx

This PR removes the community writers' dashboard for contributors' docs.

Minor updates to contributors docs

---

docs/package-lock.json
docs/package.json
docs/yarn.lock

This PR solves https://github.com/mindsdb/mindsdb/security/dependabot/119 and https://github.com/mindsdb/mindsdb/security/dependabot/118

Upgrade mintlify in docs

---

docs/mindsdb_sql/sql/create/trigger.mdx

updated trigger docs

---

mindsdb/api/http/namespaces/config.py

fix wrong `sensitive_info` arg

---

mindsdb/__about__.py

Bump the version for the new release

New release

---

.github/workflows/test_on_deploy.yml
.github/workflows/test_on_push.yml
requirements/requirements.txt

Fix dependency installs for tests

---

docs/integrations/ai-engines/lightfm.mdx
docs/integrations/ai-engines/neuralforecast.mdx
docs/integrations/ai-engines/popularity-recommender.mdx
docs/integrations/ai-engines/rag.mdx
docs/integrations/ai-engines/statsforecast.mdx
docs/mindsdb_sql/connect/grafana.mdx
docs/quickstart-tutorial.mdx
docs/sdks/javascript/create_database.mdx
docs/sdks/python/create_database.mdx
docs/use-cases/ai-powered_data_retrieval/semantic_search.mdx
docs/use-cases/data_enrichment/question-answering-inside-mysql-with-openai.mdx
docs/use-cases/data_enrichment/sentiment-analysis-inside-mysql-with-openai.mdx
docs/use-cases/data_enrichment/text-summarization-inside-mysql-with-openai.mdx
docs/use-cases/predictive_analytics/expenditures-statsforecast.mdx
docs/use-cases/predictive_analytics/house-sales-statsforecast.mdx
docs/use-cases/predictive_analytics/house-sales-timegpt.mdx
docs/use-cases/predictive_analytics/monthly-expediture-timegpt.mdx
mindsdb/integrations/handlers/langchain_embedding_handler/README.md
mindsdb/integrations/handlers/rag_handler/README.md
mindsdb/integrations/handlers/spacy_handler/README.md
tests/integration_tests/flows/test_predict_text_sentiment_openai_tutorial.py

Update references from `db-demo-data.cwoyhfn6bzs0.us-east-1.rds.amazonaws.com` to `samples.mindsdb.com`.

Update references to sample databases

---

docs/mint.json
docs/openapi.yml
docs/rest/databases/create-databases.mdx
docs/rest/databases/delete-databases.mdx
docs/rest/databases/list-database.mdx
docs/rest/databases/list-databases.mdx
docs/rest/databases/update-databases.mdx
docs/rest/files/delete.mdx
docs/rest/files/list.mdx
docs/rest/files/upload.mdx
docs/rest/models/delete-model.mdx
docs/rest/models/describe-model.mdx
docs/rest/models/list-model.mdx
docs/rest/models/list-models.mdx
docs/rest/models/query-model.mdx
docs/rest/models/train-model.mdx
docs/rest/projects/get-project.mdx
docs/rest/projects/get-projects.mdx
docs/rest/tables/create-table.mdx
docs/rest/tables/delete-table.mdx
docs/rest/tables/list-table.mdx
docs/rest/tables/list-tables.mdx
docs/rest/views/create-view.mdx
docs/rest/views/delete-views.mdx
docs/rest/views/list-view.mdx
docs/rest/views/list-views.mdx
docs/rest/views/update-view.mdx

added docs for rest api for files
Fixes #9238

added docs for rest api for files

---

docs/mint.json

updated mongodb sdk to api

---

.github/workflows/test_on_push.yml

This PR adds the Anyscale unit tests to the GitHub workflow in order to run on push.

Added Anyscale Unit Tests to the Workflow

---

docs/integrations/data-integrations/mongodb.mdx
mindsdb/integrations/handlers/mongodb_handler/README.md
mindsdb/integrations/handlers/mongodb_handler/mongodb_handler.py

This PR updates the mongo handler README file and removes the unnecessary certificate generation.
Fixes #https://github.com/mindsdb/mindsdb/security/code-scanning/15
-

Mongo updates

---

.dockerignore
requirements/requirements.txt

This PR upgrades the `requests` version to solve #https://github.com/mindsdb/mindsdb/security/dependabot/129

Upgrade requests

---

mindsdb/integrations/handlers/rag_handler/settings.py

Issues with rag_handler compatibility with pydantic v2, this PR should fix the issues

migrate rag handler to pydantic v2

---

mindsdb/integrations/handlers/dremio_handler/dremio_handler.py

This PR fixes the `get_tables()` method of the Dremio handler along with some other minor fixes to the `get_columns()` method and its query process.
Fixes https://github.com/mindsdb/mindsdb/issues/9283
Also, requires https://github.com/mindsdb/mindsdb-frontend/pull/2745 to be in complete working order.

Fixed Dremo Get Methods and Query Process

---

docs/setup/self-hosted/docker.mdx
docs/setup/self-hosted/pip/linux.mdx
docs/setup/self-hosted/pip/macos.mdx
docs/setup/self-hosted/pip/source.mdx
docs/setup/self-hosted/pip/windows.mdx

updated commands to install deps

updated commands to install deps

---

mindsdb/api/http/namespaces/config.py
mindsdb/integrations/handlers/gmail_handler/__init__.py
mindsdb/interfaces/database/integrations.py

Create database via form 
- rollback removed blocks:
- export storage of handler and pass to client
- pass handler storage to temporal handler 
- fix gmail handler import

Fix add database via form

---

docs/integrations/ai-engines/openai.mdx

updated openai doc page

---

docs/mindsdb_sql/agents/agent.mdx

fixed agent docs

---

.github/workflows/test_on_deploy.yml
.github/workflows/test_on_push.yml

Allow running tests manually

---

mindsdb/integrations/utilities/rag/retrievers/multi_vector_retriever.py

There was few types description that don't work in python 3.8.

Fix typing for py3.8

---

docs/integrations/ai-engines/openai.mdx
mindsdb/integrations/handlers/openai_handler/README.md

This PR adds the troubleshooting guide and README for the OpenAI handler.
Fixes https://github.com/mindsdb/mindsdb/issues/9319

Added the Troubleshooting Guide and README for OpenAI

---

docs/integrations/ai-engines/minds_endpoint.mdx
docs/mint.json

updated naming for minds endpoint

updated naming for minds endpoint

---

docs/integrations/ai-engines/ludwig.mdx
docs/mindsdb_sql/sql/api/manage-models-versions.mdx
docs/mindsdb_sql/sql/api/retrain.mdx
docs/mindsdb_sql/sql/drop/model.mdx
docs/mindsdb_sql/sql/get-batch-predictions.mdx
docs/mint.json
docs/sql/project.mdx
docs/sql/table-structure.mdx
docs/use-cases/automated_finetuning/classification.mdx
docs/use-cases/automated_finetuning/regression.mdx

docs updates for mindsdb schema and projects

docs updates for mindsdb schema and projects

---

.github/workflows/test_on_push.yml

stop coveralls running for forks

---

.github/workflows/build_deploy_prod.yml

This PR updates the env name used to pass the MindsDB image tag to the workflow of the Docker extension.

Updated the Env Name Used to Trigger DD Extension Release

---

.github/workflows/test_on_push.yml

Fix coveralls conditional

---

docs/integrations/ai-engines/langchain.mdx

This PR fixes some minor issues found in the LangChain documentation.
Partially fixes https://github.com/mindsdb/mindsdb/issues/9343

Fixed Minor Issues in LangChain Documentation

---

docs/mindsdb_sql/agents/agent.mdx
docs/mindsdb_sql/agents/knowledge-bases.mdx

updated agents kb docs
preview: https://www.loom.com/share/cbbf9842b6894e6bb8db69d02c1e441e

updated agents kb docs

---

mindsdb/integrations/handlers/huggingface_api_handler/huggingface_api_handler.py

Fix: json var 'args' doesn't content 'using' key

Huggingface api handler: fix getting api key

---

docs/integrations/data-integrations/amazon-redshift.mdx
mindsdb/integrations/handlers/redshift_handler/README.md

This PR adds the troubleshooting guide for Redshift.
Fixes https://github.com/mindsdb/mindsdb/issues/9351

Added the Troubleshooting Guide for Redshift

---

mindsdb/__about__.py

Draft new version release

---

docs/use-cases/ai_workflow_automation/slack-chatbot.mdx

updated slack tutorial job

---

mindsdb/__about__.py

Patch release v24.6.3.1

---

mindsdb/integrations/handlers/langchain_handler/log_callback_handler.py
mindsdb/integrations/handlers/langchain_handler/mindsdb_database_agent.py
mindsdb/interfaces/skills/sql_agent.py

Improvements to validation of generated SQL by SQL agents
- Some of the logging call back handlers for langchain were failing for agents.
- Introduced [table_info property](https://github.com/langchain-ai/langchain/blob/401d469a92223d5b028ea86af09e12ada056d700/libs/community/langchain_community/utilities/sql_database.py#L294), as per the langchain base class for SQLAgent
Tested locally with python sdk text2sql example
Part of RAG-89

Improve Agent logging to make debugging easier

---

docs/integrations/ai-engines/openai.mdx

docs note for overriding prompt template at prediction time
Fixes #5610

docs note for overriding prompt template

---

mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
tests/unit/handlers/test_postgres.py

The handler now fetches the 'schema' from connection arguments, defaulting to 'public' if not provided. The schema is then used in the table query, allowing for more accurate query execution in PostgreSQL.

Update Postgres handler to include schema in table query

---

.github/workflows/build_deploy_prod.yml
requirements/requirements-dev.txt

Add importlib_metadata in dev requirements to fix the Twine bug.

Fix twine bug

---

docker/mindsdb.Dockerfile

Add curl to docker containers (for healthchecks)

---

mindsdb/integrations/handlers/openai_handler/README.md

update links in openai readme

---

docs/integrations/ai-engines/langchain.mdx

added ollama to langchain providers docs

added ollama to langchain providers docs

---

docs/contribute/app-handlers.mdx
docs/contribute/data-handlers.mdx
docs/contribute/ml-handlers.mdx

updated docs for building handlers
Fixes #9209

updated docs for building handlers

---

docs/package-lock.json
docs/package.json
docs/yarn.lock

This PR upgrades Mintlify to latest version and solves:
- https://github.com/mindsdb/mindsdb/security/dependabot/136
- https://github.com/mindsdb/mindsdb/security/dependabot/139
- https://github.com/mindsdb/mindsdb/security/dependabot/138
- https://github.com/mindsdb/mindsdb/security/dependabot/137

Upgrade mintlify

---

mindsdb/integrations/handlers/ludwig_handler/requirements.txt
mindsdb/integrations/handlers/neuralforecast_handler/requirements.txt

Bumped RAY version to 2.8.1
Ludwig won't work on new version [info](https://docs.google.com/document/d/1eQtFJnQD2mqBc-0r6-UrlrhuiRxfP-xO-njU3z_A5hM/edit)
Fixes: https://linear.app/mindsdb/issue/PRI-214
Fixes: https://linear.app/mindsdb/issue/PRI-215

Updated ray version

---

mindsdb/api/executor/sql_query/result_set.py
mindsdb/integrations/handlers/byom_handler/byom_handler.py
mindsdb/integrations/handlers/byom_handler/requirements.txt
mindsdb/integrations/handlers/lancedb_handler/lancedb_handler.py
mindsdb/integrations/handlers/lancedb_handler/requirements.txt
mindsdb/integrations/handlers/mysql_handler/mysql_handler.py
mindsdb/integrations/libs/vectordatabase_handler.py

Updates:
- updated pyarrow version in byom and lancedb  handler 
- Fixed error 'connection is not defined' for mysql handler (in case database is not accesible)
- Fixed returning nan in json (it was in metadata of lancedb result)
- lancedb handler updated and adapted to VectorStoreHandler interface. Tested with knowledge base
- KB controller: if vector db doesn't support update do it with delete and then insert
Queries for testing lancedb:
```sql
-- create db
CREATE DATABASE lancedb
WITH ENGINE = "lancedb",
PARAMETERS = {
"persist_directory" : "/tmp/db"
};
-- connect to KB
CREATE KNOWLEDGE BASE my_kb1
USING
MODEL=openai_emb,
storage=lancedb.aaaa;
-- load it
insert into my_kb1 (content )
values ('aaa'), ('bbb')
-- check content
select * from my_kb1
```
Fixes …

Update Pyarrow version

---

mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py
mindsdb/integrations/handlers/vertex_handler/vertex_client.py
tests/unit/handlers/test_bigquery.py

This PR re-organizes the `google.cloud` imports used in the BigQuery and Vertex AI handlers to allow installation of dependencies via the GUI.
Fixes https://github.com/mindsdb/mindsdb/issues/9403

Re-organized Imports for BigQuery and Vertex to Allow Installation via GUI

---

requirements/requirements.txt

Updated werkzeug version of mindsdb dependency 
Fixes https://linear.app/mindsdb/issue/PRI-220

Update werkzeug version

---

docker/mindsdb.Dockerfile

Fix docker build cache collisions

---

mindsdb/integrations/handlers/slack_handler/requirements.txt
mindsdb/integrations/handlers/slack_handler/slack_handler.py

New features/changes:
- list of users table
- added columns to use them in triggers: channel and created_at
- chatbots and triggers can handle not only direct messages
- updated slack_sdk dependency
Fixes:
- avoiding duplicated messages from slack api
Demo
https://www.loom.com/share/0703bd31d610485a92eaf986021a6f6b
Used queries
```sql
CREATE CHATBOT cb1 USING
database = "mindsdb_slack",
agent = "openai_sqk_agent";
CREATE TRIGGER tr_slack ON mindsdb_slack.channels
(
INSERT INTO mindsdb_slack.channels(channel, text)
( 
SELECT c.channel as channel, a.answer as text 
FROM TABLE_DELTA as c              
JOIN openai_sqk_agent as a
ON a.question = c.text
WHERE c.channel = 'C05HRK6613Q' --AND c.user !='U05JB2G1PLH'
)
);
create trigger tr_slack on mindsdb_slack.channels
(
INSERT INTO …
```

Slack handler fixes

---

docker/db_images/mariadb/sql-scripts/prepare.sql
mindsdb/integrations/handlers/mysql_handler/requirements.txt

Bound `mysql-connector-python < 9.0.0`

Fix mysql driver version

---

mindsdb/__about__.py

bump version to 24.7.1.0

---

mindsdb/integrations/handlers/sqlite_handler/sqlite_handler.py

The current behavior of the SQLite handler is to create a file if the provided path does not exist in the given machine. This PR will now check for the existence of the file before establishing the connection.
Fixes https://github.com/mindsdb/mindsdb/issues/9431

Added a Check for Provided File Path in SQLite Handler

---

mindsdb/api/http/namespaces/handlers.py
mindsdb/integrations/utilities/install.py

This PR improves the error handling and messaging when running the installation of dependencies for integrations.
This is part of the requirement for this: https://github.com/mindsdb/mindsdb-frontend/issues/2803

Improved Error Handling and Messaging in Installation of Dependencies

---

default_handlers.txt

This PR corrects the name of the Minds Endpoint handler in the default list.
Fixes https://github.com/mindsdb/mindsdb/issues/9462

Corrected Minds Endpoint Name in Default List

---

docs/integrations/ai-engines/ollama.mdx

ollama docs update example to use llama3 instead of llama2

ollama docs update example

---

docs/rest/models/query-model-joined-with-data.mdx

rest api for batch pred

---

docs/rest/models/query-model.mdx

updates docs for rest api for querying models

updates docs for rest api for querying models

---

docs/integrations/support.mdx
docs/mint.json

docs for supported integrations

docs for supported integrations

---

tests/unit/ml_handlers/test_langchain.py

We haven't updated these tests in awhile. Now all of them pass if you:
1. Set `OPENAI_API_KEY`, `ANTHROPIC_API_KEY`, `ANYSCALE_API_KEY` environment variables
2. Run `ollama serve` and then `ollama pull mistral` in a different shell to make sure you have a local model
3. Run tests with `python -m pytest ./tests/unit/ml_handlers/test_langchain.py`
This PR fixes our tests for `langchain_handler`:
- Remove test that creates agent & skills using SQL since we don't officially support that
- Remove test that uses `mdb_read` tool since we don't officially support it anymore (use SQL skills instead)

Fix Langchain Tests

---

mindsdb/integrations/handlers/litellm_handler/README.md
mindsdb/integrations/handlers/litellm_handler/requirements.txt
mindsdb/integrations/handlers/litellm_handler/settings.py

This PR fixes #9472 , https://github.com/mindsdb/mindsdb/security/dependabot/142 and https://github.com/mindsdb/mindsdb/security/dependabot/143 and also updates the README to follow up to the new structure.

Updates to LiteLLM integration

---

docs/integrations/ai-engines/lightwood.mdx

added lightwood docker image to lightwood docs

added lightwood docker image to lightwood docs

---

docs/use-cases/ai-powered_data_retrieval/semantic_search.mdx

Engine is "rag_engine" not "rag"

fix: semantic_search.mdx from file example

---

mindsdb/integrations/libs/process_cache.py

Pre-warmed ml-processes was added by handler name, not be engine name

Fix pre-warming of ml-processes

---

mindsdb/migrations/versions/2024-07-09_bfc6f44f5bc9_agent_model_optional.py

Fix migration sequence

---

mindsdb/api/http/namespaces/handlers.py
mindsdb/integrations/libs/process_cache.py

This PR removes warm processes for a handler that have been instantiated before the installation of dependencies for that handler.
The need for this fix has been outlined in detail in issue linked below.
Fixes https://github.com/mindsdb/mindsdb_private/issues/612

Removed Warm Processes for Handler After Installation of Dependecies

---

mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
mindsdb/interfaces/database/integrations.py

This PR adds a thread safe option for retrieving handlers from the handler cache.

Added a Thread Safe Option for Retrieving from the Handler Cache

---

mindsdb/interfaces/model/model_controller.py

Fix integration tests

---

mindsdb/api/executor/controllers/session_controller.py
mindsdb/api/executor/datahub/datanodes/mindsdb_tables.py
mindsdb/api/http/namespaces/agents.py
mindsdb/api/http/namespaces/chatbots.py
mindsdb/interfaces/agents/agents_controller.py
mindsdb/interfaces/chatbot/chatbot_controller.py

Del `datahub` from `agents controller` to make it simpler.

Del `datahub` from `agents controller`

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
mindsdb/integrations/handlers/sharepoint_handler/sharepoint_api.py
mindsdb/integrations/handlers/weaviate_handler/weaviate_handler.py
mindsdb/integrations/libs/vectordatabase_handler.py

Changes:
`eval` is replaced with `ast.literal_eval` to prevent arbitrary code execution

Replace eval with literal_eval

---

docs/package-lock.json
docs/package.json
docs/yarn.lock

Upgrade to the latest mintlify version

Upgrade Minltify

---

mindsdb/integrations/handlers/dspy_handler/dspy_handler.py
mindsdb/integrations/handlers/dspy_handler/requirements.txt

DSPy depended on langchain handler so it wasn't working but fixed now

fixes to dspy handler

---

docs/integrations/ai-engines/openai.mdx

added json_struct to openai docs

added json_struct to openai docs

---

mindsdb/api/executor/command_executor.py
mindsdb/api/executor/sql_query/sql_query.py
mindsdb/api/http/namespaces/configs/projects.py
mindsdb/api/http/namespaces/databases.py
mindsdb/interfaces/database/projects.py

`database_controller.get_project` does not raise `NoResultFound`, therefore endpoint fail with code 500

Fix `GET /database/{name}` if project not exists

---

mindsdb/api/http/namespaces/agents.py
mindsdb/interfaces/agents/callback_handlers.py
mindsdb/interfaces/agents/constants.py
mindsdb/interfaces/agents/langchain_agent.py
mindsdb/interfaces/agents/tools.py
tests/unit/executor/test_agent.py

This PR adds the ability to return context for retrieval agents.
This will allow users to evaluate retrieval agents.
related PR to propagate changes to python_sdk -https://github.com/mindsdb/mindsdb_python_sdk/pull/139
see info on benchmarking of retrieval agents: https://github.com/mindsdb/minds-eval/pull/3
part of ML-99

add ability to return context in retriever agents

---

mindsdb/integrations/handlers/popularity_recommender_handler/popularity_recommender_handler.py

Fixes https://github.com/mindsdb/mindsdb/issues/9528

Fixed the Execution Logic for the Popularity Recommender Integration

---

mindsdb/integrations/handlers/openai_handler/helpers.py

This PR fixes the encoding issues in the Anyscale Endpoints integration by setting a default encoding model.
Fixes https://github.com/mindsdb/mindsdb/issues/9562

Fixed Encoding Error in Anyscale Endpoints Integration

---

docs/mindsdb_sql/sql/create/file.mdx
docs/rest/files/upload.mdx
docs/sdks/python/upload_file.mdx

Fixes - https://github.com/mindsdb/mindsdb/issues/8316

added a note about erased whitespaces upon uploading a file

---

mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_toolkit.py
mindsdb/interfaces/skills/skill_tool.py

Created skills:
```python
s1 = c.skills.create('skill1', 'sql', params={
'database':'example_db', 
'tables': ['car_info'],
'description': 'car info'})
s2 = c.skills.create('skill2', 'sql', params={
'database':'my_pg', 
'tables': ['home_rentals'],
'description': 'home rentals details'})
```
Generated prompt for tools
```
> sql_db_query10: Use this tool if you need data about car info. Use the conversation context to decide which table to query. These are the available tables: example_db.car_info.
ALWAYS consider these special cases:
- Not all SQL functions are supported. Do NOT use the following functions: INTERVAL. 
- For TIMESTAMP type columns, make sure you include the time portion in your query (e.g. WHERE date_column = "2020-01-01 12:00:00")Here are the rest of the instructions:
Input …
```

Agent, sql: multiple databases, option 1, unique names for tools

---

.github/workflows/deploy.yml

Fix prod deploy

---

requirements/requirements.txt

To be consistent with required `werkzeug==3.0.3` added requirement for `flask==3.0.3`

Update `flask` version

---

mindsdb/api/http/namespaces/agents.py
mindsdb/interfaces/agents/agents_controller.py
mindsdb/interfaces/agents/langchain_agent.py
tests/unit/executor/test_agent.py

Changes:
- Langchain usage was moved to langchain_agent
- added test for 'stream' mode

Langfuse moved to langchain_agent

---

.github/workflows/test_on_push.yml

Don't run tests on changes to .md files and docs/

Don't run tests

---

.flake8
.github/workflows/test_on_push.yml
docs/integrations/data-integrations/mariadb.mdx
mindsdb/integrations/handlers/mariadb_handler/README.md
tests/unit/handlers/test_mariadb.py

This PR, verifys the MariaDB Integration.

Verify mariadb

---

tests/unit/handlers/test_dynamodb.py

This PR refactors the tests for DynamoDB by using the new base classes for creating unit tests.

Refactored the DyanmoDB Unit Tests Using Base Classes

---

mindsdb/api/http/namespaces/databases.py

Add argument that allow to check connection before create or edit 'database'.

Check connection when create a database

---

docs/integrations/data-integrations/elasticsearch.mdx
mindsdb/integrations/handlers/elasticsearch_handler/README.md

updated elasticsearch docs

---

docs/mint.json

added docs redirect

---

docs/integrations/data-integrations/elasticsearch.mdx
mindsdb/integrations/handlers/elasticsearch_handler/README.md

elasticsearch conn params update

elasticsearch conn params update

---

requirements/requirements.txt

Bump mindsdb-sql version to https://github.com/mindsdb/mindsdb_sql/pull/397

Bump mindsdb-sql version

---

mindsdb/api/http/namespaces/file.py
mindsdb/integrations/handlers/llama_index_handler/llama_index_handler.py
mindsdb/integrations/handlers/web_handler/web_handler.py
mindsdb/utilities/security.py

This PR updates the checks for valid hosts and simplify the flow by using only one function to check for invalid hosts. By default, allows all
- Crawl allowed site
- Crawl forbidden site
- File upload from google drive:

Update check for valid hosts for file upload and web crawling

---

mindsdb/integrations/libs/llm/config.py
mindsdb/integrations/libs/llm/utils.py

llm_model_kwargs renamed to model_kwargs. This name is expected by ChatLiteLLM adapter

Fix litellm provider for langchain handler

---

docs/integrations/ai-engines/langchain.mdx

langchain provider litellm update

langchain provider litellm update

---

.flake8
.github/workflows/test_on_push.yml
docs/integrations/data-integrations/apache-hive.mdx
mindsdb/integrations/handlers/hive_handler/README.md
mindsdb/integrations/handlers/hive_handler/connection_args.py
mindsdb/integrations/handlers/hive_handler/hive_handler.py
mindsdb/integrations/handlers/hive_handler/requirements.txt
tests/scripts/check_requirements.py
tests/unit/handlers/test_hive.py

This PR improves the Apache Hive integration and makes it enterprise-ready.
Fixes https://github.com/mindsdb/mindsdb_private/issues/636

Apache Hive Integration Improvements

---

mindsdb/integrations/handlers/lancedb_handler/lancedb_handler.py
mindsdb/integrations/handlers/milvus_handler/milvus_handler.py
mindsdb/integrations/handlers/pinecone_handler/pinecone_handler.py
mindsdb/integrations/handlers/weaviate_handler/weaviate_handler.py
mindsdb/integrations/handlers/xata_handler/xata_handler.py

Updated handlers:
- milvus
- pinecone
- weaviate
- xata
- lancedb
Changes:
These methods don't return Response object and raise exceptions explicitly 
- select
- insert
- delete
- update
- create_table
- drop_table 

Fix: interfaces of vector handlers

---

mindsdb/api/executor/datahub/datanodes/integration_datanode.py
mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
mindsdb/integrations/handlers/qdrant_handler/qdrant_handler.py
mindsdb/interfaces/knowledge_base/controller.py

Changes:
- qdrant handler updated to actual vectorstore interface
- tested with ollama: mistral and nomic-embed-text models
- 'insert' of postgres handler doesn't return Response object (for compatibility with `insert` method of vector handlers)
- knowledge base controller looks for 'input_column' column to detect model input (in addition to question_column)
Fixes #9658
Demo
https://www.loom.com/share/efc51e63dd704effa7836021414178f7
Used queries:
```sql
CREATE MODEL ollama_model
PREDICT completion
USING
engine = 'ollama',   -- engine name as created via CREATE ML_ENGINE
model_name = 'mistral',  -- model run with 'ollama run model-name'
ollama_serve_url = 'http://localhost:11434';
;
CREATE MODEL embeddings_model
PREDICT embeddings
USING
engine = 'ollama',   -- engine name as created via …
```

Fix qdrant handler

---

.github/workflows/matrix_includes.json
setup.py

Test: add py3.11 to tests matrix

---

.flake8
.github/workflows/test_on_push.yml
docs/integrations/data-integrations/teradata.mdx
mindsdb/integrations/handlers/teradata_handler/README.md
mindsdb/integrations/handlers/teradata_handler/connection_args.py
mindsdb/integrations/handlers/teradata_handler/teradata_handler.py
tests/unit/handlers/test_teradata.py

This PR improves the Teradata integration and makes it enterprise-ready.
Fixes https://github.com/mindsdb/mindsdb_private/issues/638

Teradata Integration Improvements

---

mindsdb/integrations/handlers/byom_handler/byom_handler.py

fix BYOM model creation

---

docs/mint.json

fix docs mint.json by removing obsolete openapi line

fix docs mint.json

---

docs/integrations/app-integrations/microsoft-teams.mdx
mindsdb/integrations/handlers/ms_teams_handler/README.md
mindsdb/integrations/handlers/ms_teams_handler/settings.py

This PR updates the documentation for the MS Teams integration with the scopes (permissions) that need to be granted to access data and perform the relevant operations. A small update has also been made to the configuration for te

Updated the Permission Scopes for the MS Teams Integration

---

mindsdb/interfaces/skills/sql_agent.py

LLM could pass table name with new line, add these symbols to strip from table name

Fix: Error fetching table info: Table ...  not found in database

---

mindsdb/__about__.py
requirements/requirements.txt

Set pymongo requirement == 4.8.0

---

docs/package-lock.json
docs/package.json

This PR upgrades mintlify to latest versions

Upgrade mintlify to latest

---

mindsdb/api/executor/controllers/session_controller.py
mindsdb/interfaces/functions/controller.py
requirements/requirements.txt

Added LLM function
Usage
```sql
select LLM('2+1')
```
Requirements:
- LLM_FUNCTION_MODEL env variable to define openai model which have to be used
- OPENAI_API_KEY env variable
Dependent on
- https://github.com/mindsdb/mindsdb_sql/pull/401
- https://github.com/mindsdb/INTERNAL-mindsdb-build-deploy-to-kubernetes/pull/49

LLM function

---

docs/sql/table-structure.mdx

docs: typo correction

---

mindsdb/integrations/handlers/mongodb_handler/tests/test_mongodb_handler.py
mindsdb/integrations/handlers/ray_serve_handler/ray_serve_handler.py

Updated ray serve handler to return all column from ray service in 'predict' method 
Side fix: flake8 messages for test_mongodb_handler.py

Ray serve: return all columns from prediciton

---

.flake8
.github/workflows/test_on_push.yml
docs/integrations/data-integrations/sap-hana.mdx
mindsdb/integrations/handlers/hana_handler/README.md
mindsdb/integrations/handlers/hana_handler/connection_args.py
mindsdb/integrations/handlers/hana_handler/hana_handler.py
tests/unit/handlers/test_hana.py

This PR improves the SAP Hana integration and makes it enterprise-ready.
Fixes https://github.com/mindsdb/mindsdb_private/issues/639

SAP Hana Integration Improvements

---

docker-compose.yml
mindsdb/__main__.py
mindsdb/api/http/initialize.py
mindsdb/integrations/utilities/time_series_utils.py
mindsdb/interfaces/jobs/scheduler.py
mindsdb/utilities/ml_task_queue/consumer.py
mindsdb/utilities/ml_task_queue/producer.py
mindsdb/utilities/ml_task_queue/utils.py
mindsdb/utilities/sentry.py
requirements/requirements.txt

Adds an option to configure Sentry to monitor the performance of the application.

Feature: Add sentry monitoring

---

docs/integrations/ai-engines/ray-serve.mdx

updated rayserve docs

---

mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py

Updated HF handler: added catching ValueError exception to support transformers 4.45.1

Fix HF: new transformers version returns ValueError

---

.dockerignore

Fix typo in dockerignore to improve caching

---

docs/setup/custom-config.mdx

added info about mindsdb custom auth
Fixes #9670

docs: mindsdb custom auth

---

mindsdb/api/http/initialize.py

Use our custom JSON encoder when dump data for HTTP responses

Use our custom JSON encoder for HTTP responses

---

docs/integrations/data-integrations/ckan.mdx

CKAN Handler documentation update

Update the docs for CKAN handler

---

mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt

This PR upgrades the torch version for HF handler
Fixes https://github.com/mindsdb/mindsdb/security/dependabot/154 and https://github.com/mindsdb/mindsdb/security/dependabot/153

Upgrade torch version

---

.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

cache to main for staging and prod builds

---

mindsdb/integrations/handlers/databricks_handler/databricks_handler.py

[Bug Fix]: Databricks handler

---

mindsdb/integrations/handlers/databend_handler/databend_handler.py

Fixes #9949
[Screencast from 2024-10-19 16-55-29.webm](https://github.com/user-attachments/assets/6277e15e-bb17-4e3e-af45-77729ab7ad71)

[Bug Fix]: Databend handler

---

docs/mindsdb_sql/functions/llm_function.mdx
docs/mint.json

docs for the llm() function

---

docs/sdks/javascript/finetune.mdx

updated js sdk docs: adjust --> finetune

updated js sdk docs

---

docs/sdks/javascript/drop_view.mdx

docs for js sdk remove a view

---

mindsdb/integrations/handlers/couchbasevector_handler/README.md
mindsdb/integrations/handlers/couchbasevector_handler/couchbasevector_handler.py

this PR fixes the engine name in the readme.md file
Fixes #9909

Updated README.md  file couchbasevector  handler

---

docs/integrations/app-integrations/salesforce.mdx
docs/integrations/data-overview.mdx
docs/mint.json
mindsdb/integrations/handlers/salesforce_handler/README.md

This PR adds the documentation for the Salesforce integration.  Depends on https://github.com/mindsdb/mindsdb/pull/9880

Added the Documentation for the Salesforce Integration

---

mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py

This PR adds a few more resource tables to the Salesforce integration by making use of a utility function to create table classes.
Fixes https://linear.app/mindsdb/issue/BE-305/add-resource-tables-to-the-salesforce-integration

Added Resource Tables to the Salesforce Integration

---

docs/integrations/app-integrations/slack.mdx
docs/sdks/javascript/list_views.mdx

docs updates

---

docs/mindsdb_sql/agents/knowledge-bases.mdx

docs for knowledge bases with usage examples 
https://github.com/user-attachments/assets/cd016773-1daa-48c9-a739-efc41bbac48d

docs for knowledge bases with usage examples

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py

Fixes #9992 
[Screencast from 2024-10-23 10-43-33.webm](https://github.com/user-attachments/assets/38b4cd2c-0f02-4ab3-b42a-b29664ad19c1)

Refactor ChromaDBHandler to convert embeddings to list before storing

---

mindsdb/integrations/handlers/crate_handler/crate_handler.py

Updated crate_handler to be able to connect with crate database hosted on cloud
Fixes #9937

Updated crate_handler to be able to connect with crate database hosted on cloud

---

docs/features/model-management.mdx

This PR fixes a typo in the [Model Management](https://docs.mindsdb.com/features/model-management) page.
- Locate the [Model Management](https://docs.mindsdb.com/features/model-management) page and ensure the typo is fixed in the above section after merge and deployment.

DOCS: Fix Typo on Model Management Page

---

docs/use-cases/ai_workflow_automation/twilio-chatbot.mdx

This PR fixes a typo in the [Build a Twilio Chatbot with MindsDB and OpenAI](https://docs.mindsdb.com/use-cases/ai_workflow_automation/twilio-chatbot) page.
- Locate the [Build a Twilio Chatbot with MindsDB and OpenAI](https://docs.mindsdb.com/use-cases/ai_workflow_automation/twilio-chatbot) page and ensure the typo is fixed in the above section after merge and deployment.

DOCS: Fix Typo on Build a Twilio Chatbot with MindsDB and OpenAI Page

---

docs/use-cases/ai_workflow_automation/slack-chatbot.mdx

This PR fixes 2 Typos in the [Build a Slack Chatbot with MindsDB and OpenAI](https://docs.mindsdb.com/use-cases/ai_workflow_automation/slack-chatbot#build-a-slack-chatbot-with-mindsdb-and-openai) page.
- Locate the [Build a Slack Chatbot with MindsDB and OpenAI](https://docs.mindsdb.com/use-cases/ai_workflow_automation/slack-chatbot#build-a-slack-chatbot-with-mindsdb-and-openai) page and ensure the typos are fixed in the above sections after merge and deployment.

DOCS: Fix Typos on Build a Slack Chatbot with MindsDB and OpenAI Page

---

docs/use-cases/ai_workflow_automation/customer-reviews-notifications.mdx

This PR fixes 4 typos in the [Automate notifications about incoming customer reviews](https://docs.mindsdb.com/use-cases/ai_workflow_automation/customer-reviews-notifications#predictions-from-model-2) page.
- Locate the [Automate notifications about incoming customer reviews](https://docs.mindsdb.com/use-cases/ai_workflow_automation/customer-reviews-notifications#predictions-from-model-2) page and ensure the typos are fixed in the above sections after merge and deployment.

DOCS: Fix Typos on Automate notifications about incoming customer reviews

---

requirements/requirements.txt

This PR pins a stable version of the python-multipart package to prevent installation of yanked releases.

Pinned Stable Version of python-multipart

---

mindsdb/__about__.py

Bump version for patch release 24.10.4.2.

Patch Release 24.10.4.2

---

docs/integrations/ai-engines/cohere.mdx
mindsdb/integrations/handlers/cohere_handler/README.md
mindsdb/integrations/handlers/cohere_handler/cohere_handler.py

[Bug Fix]: Cohere handler

---

mindsdb/interfaces/database/projects.py
mindsdb/interfaces/database/views.py
tests/unit/executor/test_base_queires.py

Fix error if view is created with mixed case:
Changes:
- store view in lower case
- query view case-independently
Fixes https://linear.app/mindsdb/issue/BE-420/error-if-view-is-created-with-mixed-case
- [] I have appropriately commented on my code, especially in complex areas.

Fix view names

---

mindsdb/integrations/handlers/confluence_handler/README.md

Corrected markdown link syntax
Correction in document

fix: link format

---

docker-compose.yml
mindsdb/api/http/initialize.py
mindsdb/utilities/otel.py
requirements/requirements.txt
tests/scripts/check_requirements.py

Added Open Telemetry instrumentation to Flask.

Feature: Add Open Telemetry to MindsDB

---

docs/integrations/data-integrations/amazon-s3.mdx
mindsdb/integrations/handlers/s3_handler/README.md

This PR updates the documentation for S3 integration based on the recent improvements made by https://github.com/mindsdb/mindsdb/pull/9804 and https://github.com/mindsdb/mindsdb/pull/9879.
Fixes https://linear.app/mindsdb/issue/BE-364/update-the-documentation-for-the-s3-integration-based-on-recent

Updated the Documentation for S3 Integration Based on Recent Improvements

---

mindsdb/integrations/handlers/replicate_handler/replicate_handler.py

Fixed spelling in replicate_handler.py

---

mindsdb/utilities/otel.py

Fix an issue in the Open Telemetry setup

Fix batch processor added to trace in Open Telemetry

---

.github/workflows/build_deploy_dev.yml
.github/workflows/test_on_deploy.yml

Run integration tests on proper branch

---

docs/contribute/install.mdx

docs - removed 3.8 version of python

docs - removed 3.8 version of python

---

mindsdb/integrations/handlers/autokeras_handler/autokeras_handler.py

Fixes #9852
Training
```sql
CREATE MODEL 
mindsdb.autokeras_01
FROM files
(SELECT * FROM files.winequalityred)
PREDICT quality
USING
engine='autokeras',
train_time = 0.1;
```
Checking status
```sql
SELECT *
FROM mindsdb.models
WHERE name = 'autokeras_01';
```
Making single prediction
```sql
SELECT quality
FROM mindsdb.autokeras_01
WHERE fixed_acidity = 7.4
AND volatile_acidity = 0.7
AND citric_acid = 0
AND residual_sugar = 1.9
AND chlorides = 0.076
AND free_sulfur_dioxide = 11
AND total_sulfur_dioxide = 34
AND density = 0.9978
AND pH = 3.51
AND sulphates = 0.56
AND alcohol = 9.4;
```
Making batch prediction
```sql
SELECT t.quality as …
```

[Bug Fix]: AutoKeras handler

---

.github/workflows/test_on_push.yml

Fix GHA for 'only docs' changes

---

docker/mindsdb.Dockerfile

fix venvs in docker

---

docs/integrations/app-integrations/microsoft-onedrive.mdx
mindsdb/integrations/handlers/ms_one_drive_handler/README.md
mindsdb/integrations/utilities/handlers/auth_utilities/microsoft/ms_graph_api_auth_utilities.py

This makes a few quick improvements to the MS OneDrive integration including completely removing the depreciated `email` parameter from the docs, aligning the README with the docs and improving the documentation of the `MSGraphAPIDelegatedPermissionsManager`.

MS OneDrive Documentation Improvements

---

docker-compose.yml
scripts/init-dbs.sh

Add Langfuse for local development.

Feature: Add local langfuse

---

mindsdb/integrations/handlers/dspy_handler/requirements.txt
mindsdb/integrations/handlers/file_handler/file_handler.py
mindsdb/integrations/handlers/langchain_embedding_handler/langchain_embedding_handler.py
mindsdb/integrations/handlers/langchain_embedding_handler/requirements.txt
mindsdb/integrations/handlers/langchain_handler/langchain_handler.py
mindsdb/integrations/handlers/langchain_handler/requirements.txt
mindsdb/integrations/handlers/langchain_handler/tools.py
mindsdb/integrations/handlers/openai_handler/requirements.txt
mindsdb/integrations/handlers/rag_handler/ingest.py
mindsdb/integrations/handlers/rag_handler/requirements.txt
mindsdb/integrations/handlers/rag_handler/settings.py
mindsdb/integrations/handlers/writer_handler/settings.py
mindsdb/integrations/libs/llm/utils.py
mindsdb/integrations/utilities/rag/loaders/file_loader.py
mindsdb/integrations/utilities/rag/rag_pipeline_builder.py
mindsdb/integrations/utilities/rag/rerankers/reranker_compressor.py
mindsdb/integrations/utilities/rag/settings.py
mindsdb/interfaces/agents/callback_handlers.py
mindsdb/interfaces/agents/langchain_agent.py
mindsdb/interfaces/agents/mindsdb_chat_model.py
mindsdb/interfaces/agents/mindsdb_database_agent.py
mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_tool.py
mindsdb/interfaces/skills/retrieval_tool.py
mindsdb/interfaces/skills/skill_tool.py
requirements/requirements-test.txt
requirements/requirements.txt
tests/scripts/check_requirements.py

**Migration to LangChain 0.3.0**
This PR upgrades the codebase to use langchain version 0.3.0.
**Key Changes:**
•	Updated imports and code structure to be compatible with langchain 0.3.0.
•	Migrated core functionality 
**Outstanding Work:**
•	The migration of `initialize_agent` to `create_react_agent` is deferred for a follow-up PR, as there is ample time to address it before reaching langchain v1.0 when it is fully deprecated.
Fixes ML-195

Upgrade langchain 0.3.x

---

mindsdb/__main__.py

This PR updates the check for the 3.9 version since we deprecated python 3.8.x 

Supported Python version

---

mindsdb/interfaces/database/integrations.py

Handler module might be not imported. Check it before usage

Fix test connection: load handler module if it isn't loaded

---

docs/sdks/javascript/connect.mdx
docs/sdks/javascript/list_databases.mdx

docs: js sdk alternative syntax for es6 module
https://github.com/mindsdb/mindsdb/issues/10121
https://github.com/mindsdb/mindsdb/issues/10125

docs: js sdk alternative syntax for es6 module

---

docs/contribute/install.mdx
docs/mindsdb_sql/connect/mysql-client.mdx
docs/mindsdb_sql/connect/postgres-client.mdx
docs/setup/custom-config.mdx
docs/setup/self-hosted/pip/linux.mdx
docs/setup/self-hosted/pip/macos.mdx
docs/setup/self-hosted/pip/source.mdx
docs/setup/self-hosted/pip/windows.mdx

docs: added the no-studio flag
[resolves this ticket](https://linear.app/mindsdb/issue/BE-465/[docs]-mindsdb-start-without-gui)

docs: added the no-studio flag

---

mindsdb/integrations/handlers/druid_handler/druid_handler.py

Added connection validation in Druid Handler

---

mindsdb/api/http/namespaces/knowledge_bases.py
mindsdb/interfaces/knowledge_base/controller.py
mindsdb/interfaces/knowledge_base/preprocessing/document_loader.py
mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
mindsdb/interfaces/knowledge_base/preprocessing/models.py
tests/api/http/knowledge_bases_test.py

Implemented a new `TextChunkingPreprocessor` to handle text chunking preprocessing. Introduced necessary configurations, validations, and tests for the new preprocessor, ensuring default settings when preprocessing is not specified. 
Made improvements to the document loader to handle SQL queries and file types effectively.
Fixes ML-211

Add text chunking preprocessors and document handling 

---

mindsdb/integrations/handlers/langchain_handler/requirements.txt
requirements/requirements.txt

This PR addresses Dependabot issues related to the `litellm` package.
The only remaining issue is with `sklearn`. Upgrading `sklearn` will require updates to the `lightwood `repository, followed by a new release.

fix dependabot issues

---

docs/integrations/app-integrations/microsoft-onedrive.mdx
mindsdb/api/http/namespaces/databases.py
mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_handler.py

The endpoint will return `redirect_url` if required. Return structure:
```json
{
"status": "redirect_required",
"redirect_url": "https://my_service/auth",
"detail": "redirect is required for auth"
}
```

Improve `POST /databases` endpoint

---

mindsdb/api/http/namespaces/databases.py

`redirect_required` should be returned only if connection check status is `False`

Fix `redirect_required` response

---

docker/docker-bake.hcl

Spacebars are not allowed there

Fix `docker_bake`

---

mindsdb/interfaces/knowledge_base/controller.py

I  was testing out data to kb v2 from DB table and noticed issues, this resolves this.

fix kb v2 adding from database table

---

README.md

Update README.md /fix grammar)

---

mindsdb/api/http/initialize.py

This PR adds a check for directory path traversal when accessing resources from the server.
Fixes https://linear.app/mindsdb/issue/BE-526/uncontrolled-data-used-in-path-expression

Added a Check for Directory Path Traversal

---

mindsdb/__main__.py
mindsdb/api/executor/datahub/datanodes/integration_datanode.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
mindsdb/interfaces/database/integrations.py
mindsdb/utilities/config.py
tests/integration_tests/flows/test_mysql_api.py

- `get_table_packets` - convert and return data by piece. Consume about x10 less memory.
- Snowflake `native_query` - added check for available memory. Changed `.fetchall` to `.fetch_pandas_batches` - consume about x10 less memory and works faster. Results of tests for 500k rows query:
```
classic_fetch memory usage is 700.24219MB; Peak is 1628.396154MB
fetch_to_df_parts memory usage is 88.176669MB; Peak is 140.355725MB
timeit classic_fetch= 34.06174719200135
timeit fetch_to_df_parts= 19.37571559799835
```
- Allow to restart mysql and http api on failure (for linux and mac only). If process go to OOM, then OS kill it with code 9. In this case the process may be restarted. This can be controlled with config.json:
```json
{
...
"api": {
"http": {
"host": "127.0.0.1",
"port": "47334", …
```

MySQL API memory optimisation

---

mindsdb/interfaces/functions/controller.py

Update of[ LLM function](https://github.com/mindsdb/mindsdb/pull/9731) config:
Any env variable with prefix 'LLM_FUNCTION_' will be converted to setting for LLM function
- it uses [create_chat_model](https://github.com/mindsdb/mindsdb/blob/a32817546ec50161d9660a636f2e024c83f97c17/mindsdb/interfaces/agents/langchain_agent.py#L139) and supports several providers (anyscale, ollama, litellm and others) with own set of settings
- LLM_FUNCTION_MODEL is converted to 'model' setting
For example settings for ollama
```
LLM_FUNCTION_PROVIDER = ollama
LLM_FUNCTION_BASE_URL = http://localhost:11434
LLM_FUNCTION_MODEL = mistral
```
Fixes https://linear.app/mindsdb/issue/ML-214/use-ollama-model-with-llm-function
To ensure the changes are working as …

LLM function: arbitrary settings for provider

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
mindsdb/interfaces/knowledge_base/controller.py
mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
tests/unit/handlers/test_chromadb_handler.py
tests/unit/test_document_preprocessor.py

bug:
1. metadata is failing to be added as json.loads fails due to single quotes
2. when iterating thru df rows it tries to reference original column names but this fails as columns have been nested into metadata array column already
3. upsert fails as non-deterministic ids are created during preprocessing step
https://www.loom.com/share/36ce5203b2954fd19812279c418af126
```
CREATE KNOWLEDGE_BASE kb11 USING 
model = openai_emb, 
metadata_columns=['sqft', 'number_of_rooms'],
content_columns=['location', 'neighborhood'];
insert into kb11 (SELECT 1 as id, * FROM example_db.home_rentals LIMIT 1);
```

fix bug with kb

---

mindsdb/__about__.py

Version bump

---

docs/mindsdb_sql/agents/knowledge-bases.mdx

docs: knowledge base sql docs updates
some issues and questions here
https://www.loom.com/share/c43353d127cc48838a2a0ad607ebb7d3

docs: knowledge base sql docs updates

---

mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
mindsdb/interfaces/knowledge_base/preprocessing/models.py

Adds summarization capability for retrieval
- [ x] ⚡ New feature (non-breaking change which adds functionality)
Needs Testing
- [x ] I have appropriately commented on my code, especially in complex areas.

Summary preprocessor

---

docs/integrations/ai-engines/langchain.mdx

docs: langchain provider setup
Fixes #[issue_number](https://github.com/mindsdb/mindsdb/issues/10237)

docs: langchain provider setup

---

mindsdb/integrations/utilities/rag/chains/map_reduce_summarizer_chain.py
mindsdb/interfaces/knowledge_base/controller.py
mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
tests/unit/test_document_preprocessor.py

Refactored the document preprocessor to improve clarity and modularity by separating methods for splitting, metadata handling, and ID generation.
Introduced logging in the knowledge base controller to enhance traceability of preprocessing configuration and query execution, which aids in debugging by providing detailed runtime insights. 
Updated unit tests to validate the new structure and logging logic, ensuring consistent behavior and proper metadata handling across different preprocessing scenarios.
Improved handling in map reduce summarizer, especially handling of edge cases such as None metadata

Refactor document preprocessor and enhance logging for debug

---

mindsdb/api/http/namespaces/config.py
mindsdb/integrations/libs/process_cache.py
mindsdb/interfaces/database/integrations.py
mindsdb/interfaces/database/projects.py

Raise an exception in `create_tmp_handler`

Raise an exception in `create_tmp_handler`

---

mindsdb/integrations/utilities/rag/splitters/file_splitter.py
mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
tests/unit/test_document_preprocessor.py

Modifies contextual document processor to use asyncio.
- [x ] ⚡ New feature (non-breaking change which adds functionality)
unit tests
- [x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [x ] I have appropriately commented on my code, especially in complex areas.
- [x ] Necessary documentation updates are either made or tracked in issues.
- [x ] Relevant unit and integration tests are updated or added.

Text chunk model

---

mindsdb/interfaces/database/integrations.py
tests/unit/executor_test_base.py

Changes:
- don't import handler for getting connection args and type of a handler
Demo
https://www.loom.com/share/bd0387be08fb460faedc5ea182e10ab8
Fixes https://linear.app/mindsdb/issue/BE-537/time-to-first-query

Speed up of first query time

---

mindsdb/interfaces/agents/langchain_agent.py
tests/unit/test_langchain_agent.py

This PR adds proper support for VLLM embeddings via OpenAI interface and improves embedding configuration handling.
1. Added support for explicit VLLM embedding configuration:
- Users can now specify `embedding_model_provider: 'vllm'` 
- Requires `embedding_base_url` for VLLM endpoint
- Supports separate base URLs for LLM and embeddings
2. Improved model name handling:
- Added `embedding_model_name` parameter
- Clear fallback chain: embedding_model_name → model_name → default
- Default model remains 'text-embedding-ada-002'
3. Enhanced error messages and validation:
- More descriptive error messages with examples
- Explicit validation for required VLLM configuration
- Better logging for debugging configuration issues
Using VLLM for both LLM and embeddings with separate endpoints
```python …
```

Add VLLM embedding tests and improve configuration logic

---

mindsdb/integrations/handlers/lightwood_handler/requirements.txt
requirements/requirements.txt

This PR bumps the version of `scikit-learn` to 1.5.0 to resolve the issues listed below: 
Fixes https://github.com/mindsdb/mindsdb/issues/9877
Fixes https://linear.app/mindsdb/issue/BE-545/scikit-learn-sensitive-data-leakage-vulnerability

Bumped `scikit-learn` to 1.5.0

---

mindsdb/integrations/handlers/file_handler/file_handler.py

```sql
select * from files.file_name -- shows list of sheets (if it has several of them)
select * from files.file_name.sheet_name -- shows content from chosen sheet
```
Fixes #10092 
https://www.loom.com/share/3b3751cffd0c44fa864f32f5e21b4b7e?sid=8484b91f-eee5-4983-82c3-fc86c1812ef6

added list sheets and select sheets for Excel files

---

docs/setup/custom-config.mdx

docs: custom config - restart
Fixes #10215

docs: custom config - restart

---

docs/integrations/app-integrations/slack.mdx
mindsdb/integrations/handlers/slack_handler/README.md

This PR improves the documentation for the Slack integration by structuring the section on supported tables and the types of queries that can be executed.
This was raised as part of https://github.com/mindsdb/mindsdb/pull/10227 and therefore, let's avoid merging this until it is reviewed.

Slack Documentation Improvements

---

.github/workflows/test_on_push.yml
tests/unit/render/test_from_parser.py

Migrate renders tests from mindsdb_sql module: https://github.com/mindsdb/mindsdb_sql/tree/staging/tests/test_render

Test render using parser

---

docs/setup/custom-config.mdx

[Please include a summary of the change and the issue it solves. ](docs: http auth lifetime param)
Fixes #10260

docs: http auth lifetime param

---

docs/integrations/sample-database.mdx
docs/mint.json

Sample db docs

---

docs/integrations/data-integrations/amazon-dynamodb.mdx
docs/integrations/data-integrations/amazon-s3.mdx
docs/integrations/data-integrations/databricks.mdx
docs/integrations/data-integrations/postgresql.mdx

docs: added thread_safe info to data integrations
Fixes - https://linear.app/mindsdb/issue/BE-447/documentation-which-data-sources-support-connection-pooling

docs: added thread_safe info to data integrations

---

docs/setup/custom-config.mdx

docs for custom config - http auth
Fixes #10266

docs for custom config - http auth

---

docs/openapi.yml

docs - rest api for chatbots update
Fixes #10111

docs - rest api for chatbots update

---

mindsdb/integrations/handlers/langchain_embedding_handler/vllm_embeddings.py

Introduce logic to prepend appropriate prefixes for Nomic models, enhancing compatibility with their task-specific input requirements. Refactor text formatting to handle different input contexts for queries and documents.

Add support for Nomic embedding text formatting

---

.github/workflows/release_notes.yml

___
enhancement, configuration changes
___
- Introduced a new GitHub Actions workflow to automate the enhancement of release notes using OpenAI's GPT-4.
- The workflow triggers on release publication and generates a "TL;DR" summary section for the release notes.
- Utilized OpenAI API to process and enhance the release notes in Markdown format.
- Implemented error handling to ensure the workflow exits gracefully if the enhancement fails.
- Updated the release notes directly on GitHub using the GitHub CLI.
___
<table><thead><tr><th></th><th align="left">Relevant …

Add smart release notes

---

mindsdb/integrations/utilities/handlers/auth_utilities/microsoft/ms_graph_api_auth_utilities.py

This PR updates the logic handling Microsoft's authentication flow to set the redirect URI by using the request's origin.

Added the Redirect URI in Executing the MS Authentication Flow

---

mindsdb/integrations/utilities/handlers/auth_utilities/microsoft/ms_graph_api_auth_utilities.py

This PR makes the process of extracting the redirect URI for the MS authentication flow more reliable.

Added a More Reliable Means of Generating Redirect URI for MS Authentication Flow

---

.github/workflows/deploy.yml

stop deploys being cancelled when one in the list fails

---

mindsdb/integrations/handlers/langchain_embedding_handler/vllm_embeddings.py

- [x ] ⚡ New feature (non-breaking change which adds functionality)
This needs testing!
- [ x] I have appropriately commented on my code, especially in complex areas.
- [ x] Necessary documentation updates are either made or tracked in issues.

added asyncio support for embeddings

---

mindsdb/integrations/handlers/langchain_embedding_handler/vllm_embeddings.py

- [ x] 🐛 Bug fix (non-breaking change which fixes an issue)
Tested locally
- [ x]   Test Location: Specify the URL or path for testing.
- [ x] I have appropriately commented on my code, especially in complex areas.
- [ x] Necessary documentation updates are either made or tracked in issues.
- [ x] Relevant unit and integration tests are updated or added.

Async embeddings

---

mindsdb/interfaces/knowledge_base/preprocessing/document_preprocessor.py
tests/unit/test_document_preprocessor.py

Contextual chunking was broken by some changes, this should fix it to work properly with async
unit tests added to verify

fix async usage in contextual chunking

---

mindsdb/__main__.py
mindsdb/api/executor/controllers/session_controller.py
mindsdb/api/executor/datahub/datahub.py
mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py
mindsdb/utilities/render/sqlalchemy_render.py
tests/scripts/check_requirements.py

- disabled telemetry in snowflake handler
- deleted one of the most [frequent memory allocation](https://github.com/mindsdb/mindsdb/pull/10303/files#diff-a854f5e79c3e168ff928e9c44bcde7f27b1bc635769cc69e9c1586793182c6c6R84)
- changed default pyarrow memory pool to 'jemalloc'. It is slower than default 'mimalloc', but use less memory. On the chart below the amount of rss memory consumed by script that makes 500 call in cycle to snowflake with 50k rows in response.

Memory optimizations

---

mindsdb/__about__.py

Bump version for weekly release 25.1.2.0.
Fixes https://linear.app/mindsdb/issue/BE-601/deploy-new-mindsdb-version-on-070125

Release 25.1.2.0

---

mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
mindsdb/interfaces/knowledge_base/controller.py

Adds support for sparse vectors in pgvector
- [ x] ⚡ New feature (non-breaking change which adds functionality)
Create a knowledge base with the following parameters, passing the using argument:
```
embedding_config = EmbeddingConfig(
provider=...,
model=...,
params={
...,
'sparse': True
}
)
knowledge_base_config = KnowledgeBaseConfig(
name=...,
description=...,
vector_store_config=...,
embedding_config=embedding_config,
params=...
)
```
- [x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [x ] I have appropriately commented on my code, especially in complex areas.
- [x ] Necessary documentation updates are either made or tracked in issues.
- [x ] Relevant unit and integration tests are updated or added.

Sparse vector supp

---

mindsdb/__about__.py

Bumped version for patch release 25.1.2.1.

Patch Release 25.1.2.1

---

docker-compose.yml
mindsdb/utilities/otel.py

Add sample rate to Otel

---

mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
mindsdb/interfaces/knowledge_base/controller.py

Remove redundant sparse vector logic from knowledge base controller and streamline sparse vector checks in pgvector handler. Ensure `vector_size` is encapsulated correctly and simplify table creation for dense and sparse vectors.

Refactor sparse vector handling in knowledge base and pgvector handler

---

docs/setup/open_telemetry.mdx
mindsdb/utilities/otel/__init__.py

fix: disable otel logs and metrics by default

---

mindsdb/__about__.py

Bump version for weekly release 25.1.3.0.

Release 25.1.3.0

---

mindsdb/integrations/utilities/rag/loaders/vector_store_loader/pgvector.py

Hotfix for incorrect sorting order on retrieval

HOTFIX: fixing sort direction

---

docs/integrations/vector-db-integrations/pinecone.mdx
mindsdb/integrations/handlers/pinecone_handler/README.md
mindsdb/integrations/handlers/pinecone_handler/pinecone_handler.py
mindsdb/integrations/handlers/pinecone_handler/requirements.txt

This PR refactors the Pinecone integration based on the breaking changes made to the SDK and makes it usable again.
Fixes https://linear.app/mindsdb/issue/BE-600/refactor-the-pinecone-integration-with-new-sdk

Refactored Pinecone Integration Based on Updates Made to the SDK

---

docs/integrations/data-integrations/mongodb.mdx

docs - mongodb connection params updated

docs - mongodb connection params updated

---

docs/mindsdb_sql/sql/api/join-on.mdx

updates to the join-on doc page

docs: join-on updates

---

mindsdb/integrations/handlers/file_handler/tests/test_file_handler.py
tests/integration_tests/flows/test_http.py

In addition to the issue addressed [here](https://github.com/mindsdb/mindsdb/pull/10361), this PR fixes several other broken integration tests that are causing our deployments to fail.

Fixed Several Broken Integration Tests

---

docs/integrations/data-overview.mdx

docs - data overview logo for symbl

docs - data overview logo

---

mindsdb/interfaces/chatbot/chatbot_controller.py

Checks if agent exists before accessing it's attributes.

fix "Nonetype has no attribute model_name" error when CREATE CHATBOT

---

mindsdb/integrations/handlers/slack_handler/slack_handler.py
mindsdb/integrations/handlers/slack_handler/slack_tables.py
mindsdb/interfaces/chatbot/chatbot_task.py
mindsdb/interfaces/chatbot/memory.py

This PR enables the use of real-time chat-bots with handler memory instead of always defaulting to DB memory.
Fixes https://linear.app/mindsdb/issue/BE-566/chatbot-handler-memory

Enabled Real-time Chat-bots (Slack) with Handler Memory

---

mindsdb/integrations/utilities/rag/retrievers/sql_retriever.py

Added an SQL checker chain after the SQL re-generation to guard against long format prompt returns that fail to output in the correct structure. 

added gaurdrail SQL checking to sql re-formulation.

---

docs/integrations/ai-engines/portkey.mdx
docs/integrations/app-integrations/email.mdx

1. Replaced `yourmail@gmail.com` with `yourmail@outlook.com` for the Outlook section under Mail in documentation.
2. Added an Usage section to Portkey documentation under AI Engine documentation.
-  Added 4 different examples :
- Creating a Summarization Model
- Generating Sentiment Analysis
- Translating Text
- Extracting Key Information
Fixes #10329 and #10328

Fixed outlook.com and added Usage section to Portkey documentation

---

mindsdb/integrations/utilities/rag/chains/map_reduce_summarizer_chain.py

- [ x] ⚡ New feature (non-breaking change which adds functionality)
- [x ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.
tested on dev server
- [ x] I have appropriately commented on my code, especially in complex areas.
- [ x] Necessary documentation updates are either made or tracked in issues.
- [ x] Relevant unit and integration tests are updated or added.

Revert to ReduceDocumentsChain for efficiency

---

mindsdb/integrations/handlers/ray_serve_handler/ray_serve_handler.py

Propagate predict parameters from MindsDB query to the Ray BYOM.

RayServeHandler propagates predict params

---

docs/package-lock.json
docs/package.json

Upgrade mintlify to latest version.
Fixes https://github.com/mindsdb/mindsdb/security/dependabot/178, https://github.com/mindsdb/mindsdb/security/dependabot/177

Upgrade mintlify  to latest

---

mindsdb/interfaces/knowledge_base/preprocessing/document_loader.py

There is a bug in kb insert from db table:
we split on query load instead of in document processor, this fixes that

Fix insert kb from db table

---

mindsdb/interfaces/agents/agents_controller.py
mindsdb/interfaces/database/integrations.py
mindsdb/interfaces/skills/skills_controller.py
tests/unit/executor/test_agent.py

If integration, skill or agent has property is_demo=True, then it should not be deletable.

Prohibition on delete and edit for object with `is_demo=True`

---

mindsdb/api/http/namespaces/knowledge_bases.py
mindsdb/interfaces/knowledge_base/controller.py

Previously, a missing alias in the embedding model was not handled, potentially leading to issues when creating a default model. This change adds a condition to verify that the alias is not None, improving robustness.

Ensure embedding model has a valid alias during creation

---

mindsdb/__about__.py

New patch release

---

mindsdb/interfaces/skills/sql_agent.py

there was an error in template

Fix template for 'get_sample'

---

mindsdb/interfaces/skills/sql_agent.py

checking table permissions in same way as in `resolve_table_names`

Fix checking table permissions in agent

---

tests/unit/render/test_from_parser.py

Skip test where query can't be rendered to original form

Skip test for sqlalchemy render

---

mindsdb/interfaces/agents/langchain_agent.py

context was missed in threads created in agent streaming 
https://github.com/mindsdb/mindsdb/pull/10413

Fix agent streaming

---

mindsdb/integrations/handlers/ray_serve_handler/ray_serve_handler.py

Updated handling errors in `create` and `predict` methos of ray serve handler.
- create method:
- if response is not parsed as json: error
- if status != 'ok' in json response: error
- predict method:
- if response is not parsed as json: error
- if no 'prediction' key in json response: error
In ray serve service there are two options to return errors:
- raise exception
- or: return error message:
- in 'status' (for `create` method)
- in any key of response (for `create` method)
How it works in examples:
**Training**
Ray serve raised exception (to show traceback `app.exception_handler` decorator was used in fastapi)
Ray serve returned error message
**Prediction**
Ray serve raised exception
Ray serve returned error message
Ray serve script used for these examples:
```python
from fastapi …
```

Handling error in rayserve handler

---

mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_tool.py

there was missed clearing from $START$ and $STOP$

fix query parsing tool

---

mindsdb/integrations/handlers/file_handler/file_handler.py
mindsdb/integrations/handlers/file_handler/tests/test_file_handler.py
mindsdb/integrations/handlers/ms_one_drive_handler/ms_one_drive_tables.py
mindsdb/integrations/utilities/files/file_reader.py
mindsdb/integrations/utilities/handlers/api_utilities/microsoft/ms_graph_api_utilities.py
mindsdb/interfaces/file/file_controller.py

Function responsible for file format detecting and parsing are moved to utilities. 
File handler and ms one drive handler are switched to this utility function
Fixes https://linear.app/mindsdb/issue/BE-635/ms-onedrive-support-for-pdf-docdocx-and-txt-files

File handling in utilities

---

mindsdb/interfaces/agents/langfuse_callback_handler.py

Introduce tracking mechanisms to log usage, timing, and errors for tools and chains. Added methods to collect metrics, including execution count, total and average duration, error rates, and last error details. Updated callback methods to populate these metrics and ensure consistent tracking of tool and chain events.
**Tool Metrics Collection:**
1. Count of tool usage
2. Total execution time
3. Average duration per tool
4. Error counts and rates
5. Last error message
6. Input tracking
**Chain Metrics Collection:**
1. Chain execution counts
2. Total and average execution times
3. Error tracking
4. Performance metrics
**Detailed Timing Information:**
1. Start and end timestamps
2. Duration calculations
3. Input/output sizes
**Error Tracking:**
1. Error counts per tool/chain
2. Error types …

Add metrics tracking for tools and chains in Langfuse handler

---

README.md
docs/minds-demo.mdx
docs/mint.json

added link to minds

---

mindsdb/integrations/handlers/byom_handler/byom_handler.py
mindsdb/integrations/handlers/byom_handler/requirements.txt
mindsdb/integrations/handlers/lancedb_handler/requirements.txt
mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py

This PR updates the pyarrow version currently in use by our integrations to resolve a reported security vulnerability.
Fixes https://linear.app/mindsdb/issue/BE-695/[urgent]-pyarrow-cve-2024-52338

Bumped PyArrow Version

---

docs/mindsdb_sql/sql/get-batch-predictions.mdx
docs/sdks/python/agents_knowledge_bases.mdx
docs/sdks/python/get-batch-predictions.mdx

this PR updates the KB docs via Python SDK, and it adds info about the partitions_size param as defined in [this PR](https://github.com/mindsdb/mindsdb/pull/10326)

docs for partition_size support

---

mindsdb/api/executor/command_executor.py
mindsdb/api/executor/datahub/datanodes/system_tables.py
tests/unit/executor/test_schema.py

Fixed 'SHOW FULL COLUMNS' 
- it worded the same as without 'FULL'
Speed-up getting metadata. If database and table specified don't iterate over all connected databases:
- `SHOW FULL COLUMNS FROM amazon_reviews` (Database is in the connection)
- `SHOW FULL TABLES FROM example_db`

Fix getting column list

---

README.md
requirements/requirements.txt

Fix an issue with pymupdf. Set it to 1.25.2

---

mindsdb/__about__.py

bump version 25.2.2.2

---

docs/integrations/data-integrations/airtable.mdx
docs/integrations/data-integrations/google-sheets.mdx
docs/mindsdb_sql/sql/create/model.mdx
docs/sql/feature-eng.mdx
docs/use-cases/in-database_ml/byom.mdx
docs/use-cases/in-database_ml/mindsdb-superset-snowflake.mdx

docs: changed predictor to model

docs: changed predictor to model

---

mindsdb/integrations/handlers/youtube_handler/__init__.py
mindsdb/integrations/handlers/youtube_handler/connection_args.py

This PR adds the connection arguments for the YouTube integration in order to allow the form editor to be opened successfully.
Fixes https://github.com/mindsdb/mindsdb/issues/10500

Added the Connection Arguments for the YouTube Integration

---

mindsdb/__main__.py
mindsdb/api/http/initialize.py
mindsdb/integrations/libs/process_cache.py
mindsdb/interfaces/agents/langchain_agent.py
mindsdb/interfaces/database/integrations.py
mindsdb/interfaces/jobs/scheduler.py
mindsdb/utilities/ml_task_queue/consumer.py

- added names for started threads
- start `ProcessCache.clean` thread only if ProcessCache is in use

Do not start `ProcessCache.clean` thread if it is not used

---

mindsdb/interfaces/skills/custom/text2sql/mindsdb_sql_toolkit.py

Different output description for cloud and local versions

---

mindsdb/__about__.py
mindsdb/migrations/versions/2025-02-14_4521dafe89ab_added_encrypted_content_to_json_storage.py

Bump version and fix migrations order

Bump version and fix migrations order

---

mindsdb/integrations/utilities/pydantic_utils.py
mindsdb/integrations/utilities/rag/pipelines/rag.py
mindsdb/integrations/utilities/rag/retrievers/sql_retriever.py
mindsdb/integrations/utilities/rag/settings.py

Co-authored-by: Ty <124617566+tmichaeldb@users.noreply.github.com>
An advanced system for constructing metadata filters with granular database schemas.

Metadata v3 (#10463)

---

docs/mint.json

added try demo button

---

mindsdb/integrations/handlers/jira_handler/__init__.py
mindsdb/integrations/handlers/jira_handler/jira_handler.py
mindsdb/integrations/libs/api_handler_generator.py

Generate tables from api

---

.github/workflows/build_deploy_dev.yml

only build cloud image for dev builds

---

docs/what-is-mindsdb.mdx

docs (agi to ai)

---

mindsdb/__main__.py
mindsdb/api/http/initialize.py
mindsdb/utilities/config.py

`distutils` is deleted in python 3.12, so need to use alternative

Delete usage of `distutils`

---

.github/workflows/build_deploy_dev.yml

build only amd images in dev

---

docs/integrations/app-integrations/salesforce.mdx
mindsdb/integrations/handlers/salesforce_handler/README.md
mindsdb/integrations/handlers/salesforce_handler/requirements.txt
mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
mindsdb/integrations/handlers/salesforce_handler/salesforce_tables.py

This PR maps all the resources from the Salesforce API to the integration.

Mapped All Salesforce Resources to Integration

---

.github/workflows/test_on_push.yml

Remove changed-files action

---

docs/integrations/data-integrations/timescaledb.mdx
mindsdb/integrations/handlers/timescaledb_handler/README.md

This PR updates the documentation and README  of the Timescale integration.
Fixes https://linear.app/mindsdb/issue/BE-794/improve-timescale-docs

Update docs and readme for Timescale

---

docs/integrations/app-integrations/jira.mdx
docs/integrations/data-overview.mdx
docs/mint.json
mindsdb/integrations/handlers/jira_handler/README.md

This PR adds the documentation for the Jira integration.
Fixes https://linear.app/mindsdb/issue/BE-774/jira-handler-docs

Added the Documentation for the Jira Integration

---

mindsdb/integrations/handlers/redshift_handler/redshift_handler.py
tests/unit/handlers/test_redshift.py

This PR fixes the unit tests for the Redshift integration.

Fixed the Unit Tests for Redshift

---

mindsdb/__about__.py

Bump version for weekly release 25.3.3.0.

Release 25.3.3.0

---

docs/integrations/app-integrations/microsoft-teams.mdx
mindsdb/integrations/handlers/ms_teams_handler/README.md

This PR adds the documentation for using Microsoft Teams as a data source.

Added the Documentation for Microsoft Teams as a Data Source

---

docs/integrations/app-integrations/salesforce.mdx
mindsdb/integrations/handlers/salesforce_handler/README.md

This PR adds the documentation for using Microsoft Teams as a data source.

Updated the Documentation for Configuring a Connected App for the Salesforce Integration

---

docker/mindsdb.Dockerfile

This PR fixes the broken MindsDB Docker build.
Fixes https://linear.app/mindsdb/issue/OSS-521/fix-broken-docker-build

Fixed Broken Docker Build

---

mindsdb/__about__.py

Bump version for weekly release 25.3.4.0.

Release 25.3.4.0

---

docs/integrations/app-integrations/youtube.mdx

This PR standardizes the information, especially on the OAuth process across the Google-based integrations (YouTube, Gmail and Google Calendar).

Updated the Steps for Generating Credentials for YouTube Integration

---

.github/workflows/test_on_push.yml
tests/unit/handlers/test_mysql.py

This PR adds more unit tests for MySQL Handler.
Fixes https://linear.app/mindsdb/issue/BE-805/add-unit-tests-for-mysql

Mysql tests

---

.github/workflows/test_on_push.yml
tests/unit/handlers/test_mssql.py

Covered more scenarios with unittests for MS SQL integration.

Mssql unit tests

---

.github/workflows/test_on_push.yml
tests/unit/handlers/test_redshift.py

This PR adds more tests to Redshift INSERT functionality

Redshift tests

---

docs/integrations/app-integrations/confluence.mdx
mindsdb/integrations/handlers/confluence_handler/README.md

This PR updated the documentation for the Confluence integration based on the recent improvements.

Updated the Documentation for the Confluence Integration

---

mindsdb/integrations/handlers/ms_teams_handler/ms_graph_api_teams_client.py
mindsdb/integrations/handlers/ms_teams_handler/ms_teams_handler.py
mindsdb/integrations/handlers/ms_teams_handler/ms_teams_tables.py
mindsdb/integrations/utilities/handlers/auth_utilities/__init__.py
mindsdb/integrations/utilities/handlers/auth_utilities/microsoft/__init__.py
mindsdb/integrations/utilities/handlers/auth_utilities/microsoft/ms_graph_api_auth_utilities.py

This PR enables the use of the Microsoft Teams integration with application permissions in order to avoid user sign-ins. The code has also been refactored for better readability/maintainability.
Fixes https://linear.app/mindsdb/issue/BE-848/enable-the-use-of-the-ms-teams-integration-with-application

Enabled the Use of Microsoft Teams Integration with Application Permissions

---

docs/integrations/data-overview.mdx
docs/integrations/vector-db-integrations/couchbase.mdx
docs/integrations/vector-db-integrations/milvus.mdx
docs/mint.json

added milvus to docs

---

mindsdb/integrations/handlers/oracle_handler/oracle_handler.py
mindsdb/utilities/render/sqlalchemy_render.py
requirements/requirements.txt

Updates to pass TPC DS/H benchmarks for oracle:
- render outer mark (+), example:
```sql
SELECT *
FROM A, B
WHERE A.column(+) = B.column
```
- add oracle session variables in connection, example:
```sql 
CREATE DATABASE my_oracle WITH ENGINE = 'oracle',  
PARAMETERS = {
...
"session_variables": {
"NLS_DATE_FORMAT": "YYYY-MM-DD HH24:MI:SS"
}  
};
NLS_DATE_FORMAT is used by CAST operator, to convert string to time/data
```
- convert plural interval timescale names to singular (DAYS -> DAY)
- prevent using duplicated aliases for functions
- DEC is alias to DECIMAL type
- don't replace INT to BIGINT
Dependent on https://github.com/mindsdb/mindsdb_sql_parser/pull/13

TPC oracle updates

---

docs/integrations/app-integrations/microsoft-teams.mdx
mindsdb/integrations/handlers/ms_teams_handler/README.md

This PR updates the documentation for the MS Teams integration with newly supported permission types based on the changes made [here](https://github.com/mindsdb/mindsdb/pull/10616).

Updated the Documentation for MS Teams Integration with Supported Permission Types

---

mindsdb/interfaces/database/projects.py

Knownlege bases are added to tree/<project> api method
Content of element:
```json
{
"name": "kb3",
"schema": null,
"class": "table",
"type": "knowledge_base",
"engine": null,
"deletable": true
},
```

Add KB to the projects tree list

---

docs/mcp/cursor_usage.mdx

docs mcp video

---

README.md

added info about mcp api to github readme

added info about mcp api to github readme

---

docs/mcp/overview.mdx

mcp api docs -- docker command

mcp api docs -- docker command

---

.github/workflows/build_deploy_dev.yml
.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml
docker/docker-bake.hcl

Make pushing docker cache a separate step

---

docs/mcp/overview.mdx

docs mcp ports fix

---

mindsdb/api/executor/command_executor.py

If it is native query view - don't try to parser it

Fix: don't parse native query view

---

README.md
docs/what-is-mindsdb.mdx

updated messaging in readme and docs

updated messaging in readme and docs

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py
mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py
mindsdb/integrations/libs/vectordatabase_handler.py
mindsdb/interfaces/knowledge_base/controller.py
tests/integration_tests/knowledge_bases/test_kb_sql.py

Added tests:
**1. Test base syntax**
Function: `test_base_syntax`
- create / drop KB
- insert from table / insert individual records
- select 
- targets: all, by columns
- with/without limit
- filter by: content, id (=, !=, in, not in, like, not like)
- join with source table
- delete by id (=, in)
- update
The test shows sql requests and responses during execution
**2. Test ingestion**
Function: `test_ingestion`
Run insert with batch_size (in separated thread) and check status using `describe knowledge base`
Do it with different combination of batch_size/thread
The test shows sql requests and responses during execution. In the end it shows comparison table of options, example:
```
========= Tests summary ==========
batch_size threads  seconds
0          10   false       62
1          10 …
```

KB integration tests

---

mindsdb/interfaces/knowledge_base/controller.py

Added filtering_threshold to the query conditions, and it can be tested using this query:
```
SELECT *
FROM kb_custom_model_ada
WHERE content = "Kindle Voyage" AND reranking_threshold =0.6 LIMIT 5;
```

Reranking threshold

---

mindsdb/interfaces/knowledge_base/controller.py

Added filtering_threshold in the query (#10653)

---

mindsdb/interfaces/knowledge_base/controller.py

merging main into kb-staging

---

mindsdb/api/mysql/mysql_proxy/libs/constants/mysql.py
mindsdb/api/mysql/mysql_proxy/mysql_proxy.py
tests/integration_tests/flows/test_mysql_api.py

Fix MySQL bin API test

---

README.md
docs/what-is-mindsdb.mdx

docs - fixed variable name
Fixes #10635

docs - fixed variable name

---

README.md
docs/what-is-mindsdb.mdx

updated mindsdb messaging

---

docs/sdks/python/list_ml_engines.mdx

Corrected a typo in `list_ml_engines.mdx`

Corrected typo in list_ml_engines.mdx

---

.github/workflows/matrix_includes.json
.github/workflows/test_on_push.yml

This PR adds two new environments for running the unit tests as used by some of our customers with Python 3.11 (Windows and Mac)

Add env to matrix

---

docs/mindsdb_sql/agents/knowledge-bases.mdx

kb docs updates

---

mindsdb/integrations/utilities/rag/rerankers/reranker_compressor.py

Changed the reranking_threshold default to 0

---

docs/integrations/files/json.mdx

docs for json file

---

mindsdb/interfaces/knowledge_base/controller.py

Fix update KB by chunk_id

---

mindsdb/integrations/handlers/chromadb_handler/chromadb_handler.py

fixed querying embeddings from chromadb
```
SELECT * FROM <kb_name>_chromadb.default_collection;
```

fixed querying embeddings from chromadb

---

mindsdb/integrations/handlers/snowflake_handler/requirements.txt

This PR installs extras needed for `python snowflake connector` as pandas and pyarrow.

Install additional dep with snowflake

---

docs/mindsdb_sql/knowledge-bases.mdx

hotfix: documentation knowledge-bases.mdx

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs - provider update to lower case

kb docs - provider update

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs - reranking methods
Fixes #10706

kb docs - reranking methods

---

docs/mindsdb_sql/knowledge-bases.mdx
mindsdb/interfaces/skills/skill_tool.py

Fixed the issue of Agent using KB skill.
Query to test it:
```
CREATE KNOWLEDGE_BASE my_knowledge_base
USING
embedding_model = {
"provider": "openai",
"model_name" : "text-embedding-ada-002",
"api_key": "sk-proj-...},
reranking_model = {
"provider": "openai",
"model_name": "gpt-4o",
"method": "multi-class",
"api_key": "sk-proj-...},
storage = pvec.storage_table, 
content_columns = ['review', 'product_name'],
id_column = "index";
INSERT INTO my_knowledge_base (
SELECT *
FROM example_db.amazon_reviews
);
CREATE SKILL kb_skill
USING
type = 'knowledge_base',
source = 'my_knowledge_base', -- this must be created with CREATE KNOWLEDGE BASE
description = 'My data';
CREATE AGENT my_agent
USING 
skills=['kb_skill'], 
provider='openai', 
model='gpt-4',
prompt_template='Answer the user input in a …
```

fix the issue for query Agent using KB skill

---

mindsdb/__about__.py
mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
tests/unit/handlers/test_postgres.py

Fixed `insert` method in Postgres handler

fix `insert` in postgres handler

---

mindsdb/integrations/handlers/oracle_handler/oracle_handler.py
tests/unit/handlers/test_oracle.py

This PR includes more tests for the Oracle integration.

Add more tests for Oracle

---

mindsdb/integrations/utilities/rag/rerankers/reranker_compressor.py
mindsdb/interfaces/knowledge_base/controller.py

This PR updates the use of re-rankers with Knowledge Bases by allowing the `provider` to be passed in any case.

Updated Provider Validation for the Re-ranker in Knowledge Bases

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs - id column

---

mindsdb/interfaces/knowledge_base/controller.py

This PR fixes a small issue that incorrectly uses the default model for re-ranking.

Fixed the Use of Default Model for Re-ranking

---

mindsdb/interfaces/knowledge_base/controller.py

copy config to prevent config mutation

KB fix: copy config to prevent mutation

---

.github/workflows/build_deploy_staging.yml

Add slack notification if testing fails in main

---

mindsdb/integrations/handlers/openai_handler/helpers.py
mindsdb/integrations/handlers/openai_handler/openai_handler.py
mindsdb/interfaces/knowledge_base/controller.py
tests/integration_tests/knowledge_bases/test_kb_sql.py
tests/unit/ml_handlers/test_openai.py

Disable using langchain for embedings in knowledge base
1. Changes in handling 'embedding_model' parameter of KB:
- if model is passed as string - use it as mindsdb model 
- if it is dict: create mindsdb model for it using provided parameters, tested providers:
- openai
- azure_openai (will create openai model with provider='azure')
2. Updated openai handler in order to support azure
Example query:
```sql
CREATE MODEL kb_emb
PREDICT embeddings 
USING engine="openai", 
openai_api_key='---',
api_version="2024-02-01",
provider='azure',
question_column='content',
model_name="text-embedding-3-large",
mode='embedding',
api_base = "https://ai-fedor2249ai742481026689.openai.azure.com/"
```
To ensure the changes are working as …

KB: use mindsdb model for embedding_model

---

docs/mint.json

docs fix - to markdown function

docs fix - to markdown function

---

mindsdb/api/http/namespaces/config.py

added parameters to GET /config:
- 'default_llm', 'default_embedding_model'

Fix: return KB llm parameter in rest api config endpoint

---

mindsdb/__main__.py

Fix the wrong object reference when logging the error.

Use logger object

---

mindsdb/utilities/config.py

There was a call of unexciting function after update of auto-config.

Fix update of auto config

---

.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

fix staging workflow

---

docs/mindsdb_sql/knowledge-bases.mdx
mindsdb/interfaces/knowledge_base/controller.py
tests/unit/executor/test_agent.py

kb id_column mandatory

---

.github/workflows/build_deploy_dev.yml
.github/workflows/test_on_deploy.yml

Allow workflow_dispatch on integration tests

---

.github/workflows/build_deploy_dev.yml

missing runs-on in build-on-dev

---

.github/workflows/test_on_deploy.yml
.github/workflows/test_on_push.yml

dont use github cache on self hosted runners

---

mindsdb/api/executor/datahub/datanodes/information_schema_datanode.py
mindsdb/api/http/namespaces/tree.py

Fixed funciton of getting list tables from information_schema (broken in #10777)

Fix getting tree for information_schema

---

mindsdb/__main__.py

This PR removes the import of integration_controller in the main and adds a function that creates the permanent integration (for now hardcoded to files)

Don't import integration_controller in main

---

.github/workflows/add_to_pr_review.yml
.github/workflows/cla.yml

Fix CLA workflow

---

.github/workflows/build_deploy_staging.yml

remove deploy to hackathon

---

.github/workflows/build_deploy_dev.yml
.github/workflows/test_on_deploy.yml

dont run tests on docs changes

---

docker/docker-bake.hcl
mindsdb/integrations/handlers/jira_handler/jira_handler.archived.py
mindsdb/integrations/handlers/jira_handler/jira_handler.py
mindsdb/integrations/handlers/jira_handler/jira_tables.py
mindsdb/integrations/handlers/jira_handler/requirements.txt
mindsdb/interfaces/knowledge_base/controller.py

This PR overhauls the Jira integration and maps resources to tables manually.
Fixes https://linear.app/mindsdb/issue/BE-982/overhaul-jira-intergation-to-work-with-minds

Overhauled the Jira Integration

---

.github/workflows/test_on_deploy.yml

Fix testing on release

---

.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

Fix staging test fail msg, and add release msg

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs example update

---

docs/mindsdb_sql/agents/agent.mdx
docs/mindsdb_sql/agents/chatbot.mdx

docs for agents and chatbots updates

docs for agents and chatbots updates

---

docs/docs.json

added copy button to doc pages

added copy to doc pages

---

docs/docs.json
docs/mindsdb-connect.mdx
docs/mindsdb-respond.mdx
docs/mindsdb-unify.mdx
docs/mindsdb.mdx
docs/overview_sdks_apis.mdx
docs/rest/overview.mdx
docs/sdks/javascript/overview.mdx
docs/sdks/mongo/mindsdb-mongo-ql-overview.mdx
docs/sdks/python/overview.mdx

docs restructured into connect/unify/respond sections
related PR -- https://github.com/mindsdb/mindsdb/pull/10849
demo -- https://www.loom.com/share/68aabddbe7c94b28b4e0254c8b50e6ba

docs into connect/unify/respond sections

---

mindsdb/migrations/README.md
mindsdb/migrations/migrate.py
mindsdb/migrations/versions/2025-05-21_9f150e4f9a05_checkpoint_1.py

During the development of the app, more and more migrations are added (58 at the moment). When running the app in a new environment, significant time is required to apply all migrations one-by-one.
This PR add new migration that:
- executes only in new environment
- completely creates the current state of the DB
- migrations starts to apply from that 'checkpoint' migration in new environment

Add 'checkpoint' migration

---

docs/integrations/ai-engines/langchain.mdx

docs langchain updates: example, supported models

docs langchain updates

---

docs/docs.json
docs/mindsdb-respond.mdx

temp hide agents docs

---

mindsdb/api/executor/sql_query/steps/insert_step.py
tests/unit/executor/test_executor.py

Allow to run `INSERT` without columns list:
```sql
INSERT INTO table (a, b, c) VALUES (1, 2, 3);
INSERT INTO table VALUES (1, 2, 3);
```

Allow `INSERT` without columns list

---

docs/docs.json

docs shortcut to mcp docs

---

mindsdb/__about__.py
mindsdb/api/a2a/run_a2a.py
mindsdb/utilities/starters.py

fix getting a2a config

---

mindsdb/interfaces/knowledge_base/controller.py

adding empty reranking for kb controller

---

.github/workflows/build_deploy_prod.yml

infra: remove prod deploy

---

mindsdb/interfaces/agents/agents_controller.py
mindsdb/interfaces/skills/skills_controller.py

Use `sql` type instead of `text2sql` skill when starting data catalogue loader.

Update skill for Data catalogue

---

mindsdb/api/executor/utilities/sql.py

This PR enables to show InvalidInputException text of from query_df. This type of exception is raised when UDF is failed
Examples:

Show exception of LLM function

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs - create index on kb

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs -- update for metadata

kb docs -- update for metadata

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs - provider name fix

---

.github/workflows/build_deploy_prod.yml
.github/workflows/build_deploy_staging.yml

remove github-actions pull secret

---

mindsdb/utilities/config.py
mindsdb/utilities/ml_task_queue/task.py
tests/integration/flows/test_mysql_api.py
tests/unit/render/test_from_parser.py

Testing fixes

---

mindsdb/interfaces/agents/constants.py

add more openai models for agents

---

mindsdb/integrations/handlers/snowflake_handler/snowflake_handler.py

This PR updates the queries used to load Snowflake metadata into the data catalog.
Fixes https://linear.app/mindsdb/issue/BE-1056/fix-snowflake-queries-for-loading-data-catalog

Fixed Metadata Queries for Snowflake (Data Catalog)

---

docs/package-lock.json
mindsdb/api/a2a/agent.py

Added conversation history support to the A2A agent's stream method, allowing it to maintain context across multiple interactions by accepting and processing previous messages in the conversation. 

a2a: add conversation history support to agent stream method

---

mindsdb/utilities/config.py

fix auto config not existing

---

mindsdb/utilities/render/sqlalchemy_render.py

Fixed rendering of  CAST function: 
- add own unique alias
Also it is done for other functions
Befor the fix the query `select CAST(col AS DATE) ` 
was rendered as
```sql
CAST(`col` AS DATE) AS `_`col``
```

Fix render of Cast function in select targets for BigQuery

---

mindsdb/interfaces/knowledge_base/evaluate.py

Removed duplicated parameter:
`retrieved_in_top_k` is the same as `total_found`

Fix Evaluate output: remove retrieved_in_top_k

---

mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py
mindsdb/integrations/libs/api_handler.py
mindsdb/interfaces/data_catalog/data_catalog_reader.py

Incorporated Handler Information to Data Catalog

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs -- added links to ai integrations

kb docs -- added links to ai integrations

---

mindsdb/api/executor/utilities/sql.py

It looks like `locals()` has some platform or interpreter version features, so better to register tables using `connection.register`

Replace `locals()` to `connection.register` when register duckdb tables

---

mindsdb/interfaces/agents/constants.py

This PR adds the stable Gemini 2.5 models to the list of supported LLMs.
Fixes #11116 

Add Support for Stable Gemini 2.5 Models

---

mindsdb/interfaces/skills/custom/text2sql/mindsdb_kb_tools.py

Continue of https://github.com/mindsdb/mindsdb/pull/11115
Strip input of kb_query_tool

Fix agent with KB:  strip input of kb_query_tool

---

docs/mindsdb_sql/knowledge-bases.mdx

kb docs -- changed relevance_threshold into relevance

kb docs -- changed relevance_threshold into relevance

---

docs/mindsdb_sql/knowledge-bases.mdx

docs for kbs -- removed ollama support

docs for kbs -- removed ollama support

---

mindsdb/interfaces/knowledge_base/controller.py

This PR fixes handling of default model configuration parameters.
Depends on https://github.com/mindsdb/mindsdb-frontend/pull/3150

Fixed Handling of Default Model Configuration Parameters

---

docker/docker-bake.hcl
mindsdb/integrations/handlers/huggingface_handler/__init__.py
mindsdb/integrations/handlers/huggingface_handler/finetune.py
mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
mindsdb/integrations/handlers/huggingface_handler/requirements.txt
mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
mindsdb/integrations/handlers/huggingface_handler/settings.py
requirements/requirements.txt
tests/integration/tutorials/test_predict_text_sentiment_huggingface_tutorial.py

Changes:
- `huggingface_handler` temporary disabled due to security vulnerability in its dependency.
- `transformers` dependency moved from main requirements.txt to docker-bake

Temporary disable `huggingface_handler`

---

.github/workflows/test_on_push.yml

Get current version of mindsdb_sql_parser (it is defined by requirements file of current branch) and get the same version of parser's tests to run tnem

Use parser tests with the same version as installed version

---

mindsdb/api/mcp/start.py

Improved descriptions of MCP tools so that agents can use them more correctly.
Fixes #11122

Improve MCP tools description

---

docs/docs.json
docs/rest/knowledge_bases/create.mdx
docs/rest/knowledge_bases/delete.mdx
docs/rest/knowledge_bases/get.mdx
docs/rest/knowledge_bases/insert.mdx
docs/rest/knowledge_bases/list.mdx
docs/rest/knowledge_bases/query.mdx

- added api endpoints for KBs (https://github.com/mindsdb/mindsdb/blob/main/mindsdb/api/http/namespaces/knowledge_bases.py)
- fixed docs.json structure for MCP API

docs -- kb via rest api

---

docs/mindsdb_sql/sql/create/file.mdx
docs/setup/custom-config.mdx
docs/setup/my_config.json

docs -- url_file_upload into config.json
Fixes #11181

docs -- url_file_upload into config.json

---

docs/mindsdb_sql/knowledge-bases.mdx

docs -- evaluate kb updates to from_sql info

docs -- evaluate kb updates to from_sql info

---

docs/setup/custom-config.mdx

docs -- logging config
Fixes #10491

docs -- logging config

---

mindsdb/integrations/handlers/salesforce_handler/constants.py
mindsdb/integrations/handlers/salesforce_handler/salesforce_handler.py

See https://docs.google.com/document/d/1sUZwbCNP4XwiOuHWOZ_1-nDrYlOOxTadMfmJTb6fUdU/edit?tab=t.0 for an exhaustive list of SOQL differences.

Add SOQL Instructions to Data Catalog Meta Prompts

---

docs/mindsdb_sql/knowledge_bases/create.mdx

docs -- kb models usage

---

docs/docs.json
docs/integrations/ai-engines/litellm.mdx

docs -- added litellm docs
waiting for these issues to be resolved -- https://linear.app/mindsdb/issue/UNI-156/litellm-handler-issues

docs -- added litellm docs

---

docs/mindsdb_sql/agents/agent_syntax.mdx

docs -- added * syntax for adding data to agents

docs -- added * syntax for adding data to agents

---

.github/workflows/matrix_includes.json
.github/workflows/test_on_push.yml

Downgrade UV

---

mindsdb/integrations/handlers/openai_handler/openai_handler.py
mindsdb/integrations/utilities/handler_utils.py
mindsdb/interfaces/knowledge_base/controller.py

- Adds support for 'preprocessing config'
- fixes issue with empty string for api key

add preprocessing field to KnowledgeBase controller

---

mindsdb/integrations/handlers/pgvector_handler/pgvector_handler.py

[[bug] hybrid_search = true causes failure when query includes escaped single quotes ](https://linear.app/mindsdb/issue/CONN-797/bug-hybrid-search-=-true-causes-failure-when-query-includes-escaped)

adding escaping for double quotes in the code

---

.github/workflows/test_on_deploy.yml

Fix staging integration tests

---

mindsdb/api/http/initialize.py
mindsdb/integrations/handlers/bigquery_handler/bigquery_handler.py

Improvements:
- set timeout for initial connection query (default timeout is 10 mins)
- return correct error message if dataset not exists, instead of 500 error
- There is a issues 'private_key' in connection parameters: users encountered error on parsing `\` char.  Some clients may escape new line char `\n`. Added replace `\\n` to `\n`. Also replaced windows-style new lines.
Fixes CONN-598

Improve bigquery connection method

---

mindsdb/interfaces/knowledge_base/controller.py

adding alpha blending

---

docs/mindsdb_sql/functions/to_markdown_function.mdx

docs -- to_markdown updates
* added s3 support
* added google support updates
https://github.com/user-attachments/assets/6b23eef6-7466-40f9-b2ea-5f7024471bb1
https://linear.app/mindsdb/issue/CONN-597/update-the-documentation-to-indicate-to-markdown-can-be-called-over

docs -- to_markdown updates

---

docs/mindsdb_sql/knowledge_bases/query.mdx

docs - kb docs fix

---

mindsdb/api/mysql/mysql_proxy/utilities/dump.py

This PR fixes truth value handling for NumPy arrays when converting to MySQL types.
Fixes https://linear.app/mindsdb/issue/CONN-648/sema4-slack-api-issues

Fixed Truth Value Evaluation for NumPy Arrays

---

docs/quickstart-tutorial.mdx

docs -- updated quickstart tutorial
https://github.com/user-attachments/assets/a633374a-f8ff-4d82-a267-18890e332be3

docs -- updated quickstart tutorial

---

docs/mindsdb_sql/knowledge_bases/overview.mdx

docs -- kb intro update

---

mindsdb/integrations/handlers/huggingface_handler/__init__.py

The import error message was not correctly processed and showed because of wrong type.

Fix `huggingface` handler import error message

---

mindsdb/interfaces/knowledge_base/controller.py

fixes https://linear.app/mindsdb/issue/CONN-1358/improve-error-message-when-postgres-handler-isnt-installed
🐛 Bug fix (non-breaking change which fixes an issue)

fix error message in knowledge base on non existing database

---

mindsdb/integrations/handlers/huggingface_handler/__init__.py
mindsdb/integrations/handlers/huggingface_handler/finetune.py
mindsdb/integrations/handlers/huggingface_handler/huggingface_handler.py
mindsdb/integrations/handlers/huggingface_handler/requirements.txt
mindsdb/integrations/handlers/huggingface_handler/requirements_cpu.txt
mindsdb/integrations/handlers/huggingface_handler/settings.py
tests/integration/tutorials/test_predict_text_sentiment_huggingface_tutorial.py

The `huggingface` handler was temporary disabled because of issue in torch=2.7.1. New pytorch was released recently, so return `huggingface` handler back.

Return `huggingface` handler

---

docs/mindsdb_sql/agents/agent_syntax.mdx

docs -- alter agent command

---

docs/mindsdb_sql/knowledge_bases/create.mdx

docs -- kb with snowflake, api key gen

docs -- kb with snowflake, api key gen

---

docs/docs.json
docs/rest/authentication.mdx

docs -- rest api for login

---

docker/mindsdb.Dockerfile

dont compile bytecode in docker

---

docs/contribute/data-handlers.mdx

docs -- updated page for building db handlers

docs -- updated page for building db handlers

---

.github/workflows/deploy.yml
.github/workflows/test_on_deploy.yml

fix env secrets

---

docs/integrations/app-integrations/twitter.mdx
docs/integrations/data-integrations/snowflake.mdx
docs/mindsdb_sql/connect/connect-mariadb-skysql.mdx
docs/mindsdb_sql/connect/tableau.mdx
docs/model-context-protocol/cursor_usage.mdx
docs/sdks/mongo/connect/mongo-compass.mdx
docs/setup/self-hosted/pip/linux.mdx
docs/use-cases/mcp_api/cursor.mdx

docs -- updated yt embedded videos

docs -- updated yt embedded videos

---

docs/setup/environment-vars.mdx

docs -- added env var for pid file

docs -- added env var for pid file

---

mindsdb/__about__.py

bump release

---

mindsdb/api/http/initialize.py

Due to a change in the way GUI versions are numbered, a bug occurred that caused GUI to be updated every time the application was started.
Fixes CONN-1480

fix GUI autoupdate

---

mindsdb/integrations/handlers/autogluon_handler/requirements.txt
mindsdb/integrations/handlers/autosklearn_handler/requirements.txt
mindsdb/integrations/handlers/flaml_handler/requirements.txt
mindsdb/integrations/handlers/lightfm_handler/requirements.txt
mindsdb/integrations/handlers/lightwood_handler/requirements.txt
mindsdb/integrations/handlers/tpot_handler/requirements.txt
requirements/requirements-test.txt
requirements/requirements.txt
setup.py

Bump python dependency and related modules

Python 3.13 support

---

mindsdb/__about__.py

Bump version to 25.9.1.1

---

docs/docs.json
docs/mindsdb-objects.mdx

docs -- mindsdb objects naming

docs -- mindsdb objects naming

---

docs/package-lock.json
docs/package.json

Update `mintlify`  to  remove indirect the "tmp" dependency.
Fixes CONN-1452

Update `mintlify` docs dependency

---

.github/workflows/test_on_push.yml

Fix main unit tests

---

.github/workflows/release_notes.yml

Test PR plz ignore

---

.github/workflows/deploy.yml

fix db uri

---

.github/workflows/build_deploy_dev.yml

remove unused manual approval for forks

---

.github/workflows/build_deploy_dev.yml
.github/workflows/build_deploy_staging.yml

run tests on develop, fix pr concurrency

---

.github/workflows/build_deploy_dev.yml
.github/workflows/deploy.yml
.github/workflows/tests_integration.yml
.github/workflows/tests_unit.yml

update github actions

---

.github/workflows/build_deploy_staging.yml

fix sending fail msg on closed PRs

---

.github/workflows/build_deploy_dev.yml
.github/workflows/build_deploy_staging.yml
.github/workflows/deploy.yml
.github/workflows/tests_integration.yml
.github/workflows/tests_unit.yml

Merge gha changes from main

---

mindsdb hacktoberfest/use-cases/README.md

Added the use-cases folder for hacktoberfest

Create use cases folder for Hacktoberfest

---

.github/workflows/build_deploy_dev.yml
.github/workflows/tests_unit.yml

Dont run integration tests on forks

---

mindsdb/api/executor/datahub/datanodes/integration_datanode.py
mindsdb/api/http/namespaces/sql.py
mindsdb/integrations/handlers/postgres_handler/postgres_handler.py
mindsdb/integrations/libs/response.py
mindsdb/utilities/exception.py

Rename attr `is_acceptable` to `is_expected` for consistent

Rename `is_acceptable` to `is_expected`

---

mindsdb/integrations/handlers/zendesk_handler/README.md
mindsdb/integrations/handlers/zendesk_handler/zendesk_tables.py

Fixes https://github.com/mindsdb/mindsdb/issues/11665
Zendesk integration was failing due to below reasons
`mindsdb/integrations/utilities/sql_utils.py:197` was expecting `op, arg1, arg2` on unpacking `conditions` which was passed through `subset_where_conditions` in `mindsdb/integrations/handlers/zendesk_handler/zendesk_tables.py` 
But  subset_where_conditions was passed as a dictionary in the current implemention, so to fix this issue following changes were done in this PR
- introduce new var `api_filters` which will be a dict as previously `subset_where_conditions` used to be that will be passed to the Zendesk api calls
- Make `subset_where_conditions` in the expected format
When the number of records where more 
```
if isinstance(result, zenpy.lib.generator.BaseResultGenerator):
while …
```

Fix zendesk integration issues
